/* Single-owner workspace policy and two-mode, standby-only assembly design. */
'use strict';
const assemblyDesign={mode:'wizard',step:0,storyId:'',channelId:'',workflowId:'',workflowQuery:'',seedEnabled:false,seed:1,presets:new Set(),title:'',stories:[],visuals:[],edges:[],requestId:'',busy:false,drag:null,overrides:{model:'',loras:[]},overrideDefaults:{model:null,loras:[]},overrideUI:{modelQuery:'',loraQuery:''}};
function designerChannel(){return ensureImageProviders().profiles.find(p=>p.id===assemblyDesign.channelId)}
function designerWorkflow(){return state.settings.comfy.presets.find(p=>p.id===assemblyDesign.workflowId)}
/* C1: mirrors backend/production/api.py seed_binding_ready — a `random` source or a scene-parameter mapping of `seed` (what「添加分镜参数映射」and the shipped workflow create) both drive the per-frame seed. */
function isSeedBinding(b){return !!b&&b.enabled!==false&&(b.source==='random'||(b.source==='sceneParameter'&&String(b.value||'').trim()==='seed'))}
function designerSeedReady(){const w=designerWorkflow();return !!w?.bindings?.some(b=>{if(!b.enabled||!isSeedBinding(b))return false;try{let v=w.workflow[String(b.nodeId)].inputs;for(const part of (b.path.startsWith('/')?b.path.slice(1).split('/'):b.path.split('.')))v=v[part.replace(/~1/g,'/').replace(/~0/g,'~')];return typeof v==='number'&&Number.isFinite(v)}catch{return false}})}
function designerChannelNotice(){const d=assemblyDesign,current=designerChannel(),previous=ensureImageProviders().profiles.find(p=>p.id===d.previousChannelId);if(!current||!previous||previous.id===current.id||current.id!==ensureImageProviders().active)return '';return `<p class="notice designer-channel-notice" role="status">已按设置中当前启用的渠道预选「${esc(current.title)}」；上次装配使用的是「${esc(previous.title)}」。请确认后再入队，避免发送到非预期的付费渠道。</p>`}
function designerEnvironment(){const d=assemblyDesign,comfy=designerChannel()?.provider==='comfyui',ready=designerSeedReady();return `<div class="designer-environment">${designerChannelNotice()}${field('图像生成渠道',`<select id="designer-channel">${ensureImageProviders().profiles.map(p=>opt(p.id,p.title,d.channelId)).join('')}</select>`)}${comfy?`<div class="designer-workflow">${designerWorkflowPickerHTML()}${designerOverridesPanel()}<div class="seed-setting"><label class="row"><span class="switch"><input id="designer-seed-enable" type="checkbox" role="switch" aria-label="启用可复现种子" ${d.seedEnabled&&ready?'checked':''} ${ready?'':'disabled'}><span class="switch-track"></span></span><span>可复现种子</span></label><input id="designer-seed" type="number" min="0" max="4294967295" value="${d.seed}" ${d.seedEnabled&&ready?'':'disabled'} aria-label="可复现种子"><p class="help">${ready?'已找到有效种子映射。关闭时每幕、每次重跑都使用新的随机种子；开启后按固定种子 + 幕序号生成，可复现。':'未找到种子映射：所有分幕会沿用工作流中的固定种子，画面可能雷同。请在「工作流与 API 配置」中点击「添加分镜参数映射」，或手动把采样器的 seed 映射为分镜参数 seed / 每次生成新种子。'}</p></div></div>`:''}</div>`}
/* Workflow picker: a search box that filters a multi-row list box. The list only ever contains matches; the current selection is
   explained by a status line instead of being pinned into the results, and the query survives wizard re-renders. */
function designerWorkflowChoices(){return filterChoices(state.settings.comfy.presets,assemblyDesign.workflowQuery,assemblyDesign.workflowId)}
function designerWorkflowListSize(total){return Math.min(8,Math.max(3,total))}
function designerWorkflowOptionsHTML(result){return result.empty?`<option value="" disabled>${esc(localeString(result.total?'没有匹配「{query}」的工作流':'还没有保存的工作流',{query:result.query}))}</option>`:result.options.map(o=>opt(o.id,o.label,assemblyDesign.workflowId)).join('')}
function designerWorkflowStatusHTML(result){
 const text=!result.total?localeString('还没有保存的工作流；请先在「工作流与 API 配置」中保存。'):!result.query?localeString('共 {total} 个工作流',{total:result.total}):result.empty?localeString('没有匹配「{query}」的工作流',{query:result.query}):localeString('匹配 {matched} / {total} 个工作流',{matched:result.matched,total:result.total});
 const selection=result.query&&result.selectedLabel&&!result.selectedVisible?` <span class="choice-selection">${esc(localeString('当前选择「{title}」不在筛选结果中，仍然有效。',{title:result.selectedLabel}))}</span>`:'';
 const clear=result.query?` <button type="button" class="link-button" data-act="designer-workflow-clear">${esc(localeString('清除搜索'))}</button>`:'';
 return `<span>${esc(text)}</span>${selection}${clear}`;
}
function designerWorkflowPickerHTML(){const d=assemblyDesign,result=designerWorkflowChoices();return `${field('搜索已保存的工作流',searchInput({id:'designer-workflow-search',value:d.workflowQuery||'',placeholder:'输入工作流名称',label:'搜索已保存的工作流',controls:'designer-workflow'}))}${field('工作流',`<select id="designer-workflow" class="choice-list" size="${designerWorkflowListSize(result.total)}">${designerWorkflowOptionsHTML(result)}</select>`)}<p class="help choice-status" id="designer-workflow-status" role="status" aria-live="polite">${designerWorkflowStatusHTML(result)}</p>`}
function refreshDesignerWorkflowPicker(){const list=$('#designer-workflow'),status=$('#designer-workflow-status');if(!list)return;const result=designerWorkflowChoices();list.size=designerWorkflowListSize(result.total);list.innerHTML=designerWorkflowOptionsHTML(result);if(!result.selectedVisible)list.selectedIndex=-1;if(status)status.innerHTML=designerWorkflowStatusHTML(result);if(typeof localizeWorkspace==='function')localizeWorkspace(list.closest('.designer-workflow')||list.parentElement)}
/* ---- task-level model / LoRA overrides -------------------------------------------------------------------
   The chosen workflow's semantic slots decide what can be overridden; the pickers are built from the catalog that
   「同步模型列表」reads through the backend. Untouched selections send nothing, so the blueprint stays authoritative. */
function designerSlots(){const w=designerWorkflow();if(!w)return null;return comfySlotsResolved({slots:w.slots||{},workflow:w.workflow||{},bindings:w.bindings||[],objectInfo:state.settings.comfy.objectInfo||{}})}
function designerLoraKey(name){return WorkflowSlots.loraStem(name).toLowerCase()}
function designerRememberedOverrides(id){const remembered=state.settings.productionAssembly?.overrides?.[id];if(!remembered||typeof remembered!=='object')return null;return {model:typeof remembered.model==='string'?remembered.model:'',loras:Array.isArray(remembered.loras)?remembered.loras.filter(l=>l&&typeof l.name==='string').map(l=>({name:l.name,strength:clamp(Number(l.strength)||1,0.1,1.5)})):null}}
function initDesignerOverrides(){const d=assemblyDesign,w=designerWorkflow(),slots=w?designerSlots():null;d.overrideUI={modelQuery:'',loraQuery:''};
 if(!w||!slots){d.overrideDefaults={model:null,loras:[]};d.overrides={model:'',loras:[]};return}
 const defaults={model:WorkflowSlots.currentModel(w.workflow,slots),loras:WorkflowSlots.currentLoras(w.workflow,slots).map(l=>({name:l.name,strength:clamp(Number(l.strength)||1,0.1,1.5)}))};
 const remembered=designerRememberedOverrides(w.id);d.overrideDefaults=defaults;d.overrides={model:remembered?.model||'',loras:remembered?.loras?clone(remembered.loras):clone(defaults.loras)}}
function designerOverrides(){const d=assemblyDesign,slots=designerSlots();if(!slots||designerChannel()?.provider!=='comfyui')return undefined;const out={};
 const model=String(d.overrides.model||'').trim();if(slots.model.enabled&&model&&model!==d.overrideDefaults.model)out.model=model;
 if(slots.lora.mode!=='off'){const chosen=d.overrides.loras.map(l=>({name:l.name,strength:Math.round(l.strength*100)/100})),base=d.overrideDefaults.loras.map(l=>({name:l.name,strength:Math.round(l.strength*100)/100}));if(JSON.stringify(chosen)!==JSON.stringify(base))out.loras=chosen}
 return Object.keys(out).length?out:undefined}
function designerModelChoices(slots){const catalog=comfyModelCatalog(),kind=slots.model.kind,list=kind==='checkpoint'?catalog.checkpoints:kind==='unet'?catalog.unets:[...catalog.checkpoints,...catalog.unets],query=assemblyDesign.overrideUI.modelQuery.trim().toLowerCase();return {total:list.length,options:(query?list.filter(m=>m.toLowerCase().includes(query)):list).slice(0,80)}}
function designerModelOptionsHTML(slots){const d=assemblyDesign,{options,total}=designerModelChoices(slots),current=String(d.overrides.model||''),fallback=d.overrideDefaults.model,query=d.overrideUI.modelQuery.trim();let html=opt('',fallback?`蓝图默认 · ${WorkflowSlots.loraStem(fallback)}`:'蓝图默认（未填模型）',current);
 for(const m of options)if(m!==fallback||current===m)html+=`<option value="${esc(m)}" ${current===m?'selected':''} title="${esc(m)}">${esc(m)}</option>`;
 if(current&&!options.includes(current)&&current!==fallback)html+=`<option value="${esc(current)}" selected>${esc(current)} · 手动输入</option>`;
 if(query&&!options.some(m=>m.toLowerCase()===query.toLowerCase())&&query!==current)html+=`<option value="${esc(query)}">使用「${esc(query)}」作为文件名${total?'':' · 未同步模型列表'}</option>`;
 return html}
function designerLoraResultsHTML(slots){const d=assemblyDesign,catalog=comfyModelCatalog(),query=d.overrideUI.loraQuery.trim().toLowerCase(),picked=new Set(d.overrides.loras.map(l=>designerLoraKey(l.name)));
 const list=(query?catalog.loras.filter(m=>m.toLowerCase().includes(query)):catalog.loras).slice(0,200);
 const rows=list.map(m=>{const on=picked.has(designerLoraKey(m));return `<label class="designer-lora-option ${on?'is-on':''}"><input type="checkbox" data-designer-lora-toggle="${esc(m)}" ${on?'checked':''}><span data-user-content title="${esc(m)}">${esc(WorkflowSlots.loraStem(m))}</span><small>${esc(m.includes('/')||m.includes('\\')?m.replace(/\\/g,'/').split('/').slice(0,-1).join('/'):'')}</small></label>`}).join('');
 const free=query&&!list.some(m=>designerLoraKey(m)===designerLoraKey(query))&&!picked.has(designerLoraKey(query))?`<button type="button" class="designer-lora-free" data-act="designer-lora-add-free" data-name="${esc(d.overrideUI.loraQuery.trim())}">${icon('plus','sm')}<span>添加「${esc(d.overrideUI.loraQuery.trim())}」${catalog.loras.length?'（不在列表中）':'（未同步列表，按文件名写入）'}</span></button>`:'';
 const empty=!rows&&!free?`<p class="designer-lora-empty">${catalog.loras.length?'没有匹配的 LoRA。':'还没有同步 LoRA 列表；点右上角「同步模型列表」，或直接输入文件名添加。'}</p>`:'';
 return rows+free+empty}
function designerLoraChipsHTML(){const d=assemblyDesign;if(!d.overrides.loras.length)return '<p class="designer-lora-none">不叠加 LoRA</p>';
 return d.overrides.loras.map((l,i)=>`<div class="designer-lora-chip" data-designer-lora-chip="${i}"><span class="designer-lora-name" data-user-content title="${esc(l.name)}">${esc(WorkflowSlots.loraStem(l.name))}</span><input type="range" min="0.1" max="1.5" step="0.05" value="${l.strength}" data-designer-lora-strength="${i}" aria-label="${esc(WorkflowSlots.loraStem(l.name))} 强度"><output class="mono" data-designer-lora-output="${i}">${WorkflowSlots.numberText(l.strength)}</output>${ibtn('close','designer-lora-remove','移除此 LoRA',`data-index="${i}"`)}</div>`).join('')}
function designerOverridesPanel(){const d=assemblyDesign,w=designerWorkflow(),slots=w?designerSlots():null;if(!w||!slots)return '';const catalog=comfyModelCatalog(),modelOn=slots.model.enabled,loraOn=slots.lora.mode!=='off',synced=catalog.fetchedAt?`已同步 ${catalog.checkpoints.length+catalog.unets.length} 个模型 · ${catalog.loras.length} 个 LoRA`:'尚未同步模型列表';
 if(!modelOn&&!loraOn)return `<section class="designer-slots is-inert" aria-label="模型与 LoRA"><header><h4>模型与 LoRA</h4><span class="help">此工作流未识别出模型或 LoRA 槽，将按蓝图原样提交；可在「工作流与 API 配置」里手动指定。</span></header></section>`;
 const modelBody=modelOn?`<div class="designer-slot-field"><label class="designer-slot-label" for="designer-model-search">基础模型 <small>写入 #${esc(slots.model.nodeId)} · ${esc(slots.model.path)}</small></label>${searchInput({id:'designer-model-search',value:d.overrideUI.modelQuery,placeholder:catalog.fetchedAt?`搜索 ${designerModelChoices(slots).total} 个模型，或输入文件名`:'未同步列表：输入模型文件名',label:'搜索模型',controls:'designer-model-list'})}<select id="designer-model-list" class="choice-list" size="4" aria-label="基础模型">${designerModelOptionsHTML(slots)}</select></div>`:`<p class="designer-slot-off">模型槽未启用，沿用蓝图模型。</p>`;
 const loraBody=loraOn?`<div class="designer-slot-field"><label class="designer-slot-label" for="designer-lora-search">LoRA 叠加 <small>${esc(({syntax:'语法注入',chain:'节点链',stack:'堆栈'})[slots.lora.mode])} · #${esc(slots.lora.nodeId)}${d.overrideDefaults.loras.length?` · 蓝图自带 ${d.overrideDefaults.loras.length} 个`:''}</small></label><div class="designer-lora-chips" id="designer-lora-chips">${designerLoraChipsHTML()}</div>${searchInput({id:'designer-lora-search',value:d.overrideUI.loraQuery,placeholder:catalog.loras.length?`搜索 ${catalog.loras.length} 个 LoRA`:'未同步列表：输入 LoRA 文件名后添加',label:'搜索 LoRA',controls:'designer-lora-results'})}<div id="designer-lora-results" class="designer-lora-results" role="group" aria-label="可选 LoRA">${designerLoraResultsHTML(slots)}</div></div>`:`<p class="designer-slot-off">LoRA 槽未启用，沿用蓝图 LoRA。</p>`;
 return `<section class="designer-slots" aria-label="模型与 LoRA"><header><h4>模型与 LoRA</h4><span class="help">${esc(synced)} · 只影响本次任务</span>${btn('同步模型列表','refresh','designer-sync-catalog','','ghost small')}</header>${modelBody}${loraBody}</section>`}
function refreshDesignerOverrides(part){const slots=designerSlots();if(!slots)return;if(part!=='lora'){const list=$('#designer-model-list');if(list)list.innerHTML=designerModelOptionsHTML(slots)}if(part!=='model'){const chips=$('#designer-lora-chips'),results=$('#designer-lora-results');if(chips)chips.innerHTML=designerLoraChipsHTML();if(results)results.innerHTML=designerLoraResultsHTML(slots)}}
function designerAddLora(name){const d=assemblyDesign,key=designerLoraKey(name);if(!name||d.overrides.loras.some(l=>designerLoraKey(l.name)===key))return;if(d.overrides.loras.length>=WorkflowSlots.MAX_LORAS)throw Error('一次最多叠加 '+WorkflowSlots.MAX_LORAS+' 个 LoRA');d.overrides.loras.push({name,strength:1})}
function openAssemblyDesigner(){
 const d=assemblyDesign,prefs=state.settings.productionAssembly||{},providers=ensureImageProviders(),lastUsed=providers.profiles.find(p=>p.id===prefs.channelId)?.id||'';
 /* B10: the wizard follows the channel enabled in Settings, never silently the last one billed; a differing history is only a notice. */
 Object.assign(d,{mode:'wizard',step:0,storyId:workshopStory()?.id||'',channelId:providers.active||lastUsed,previousChannelId:lastUsed&&lastUsed!==providers.active?lastUsed:'',workflowId:(prefs.channelId===providers.active?prefs.workflowId:'')||state.settings.comfy.activeWorkflowId,workflowQuery:'',seedEnabled:false,seed:1,presets:new Set(),title:'',stories:[],visuals:[],edges:[],requestId:uid('assembly'),busy:false,drag:null});
 if(!designerChannel())d.channelId=ensureImageProviders().profiles[0]?.id||'';if(!designerWorkflow())d.workflowId=state.settings.comfy.presets[0]?.id||'';
 initDesignerOverrides();
 renderAssemblyDesigner();
}
function designerPresets(){return `<div class="designer-presets">${projectVariableSets().map(p=>`<label class="designer-preset ${assemblyDesign.presets.has(p.id)?'selected':''}"><input type="checkbox" data-designer-preset="${esc(p.id)}" ${assemblyDesign.presets.has(p.id)?'checked':''}><span>${icon('box')}<strong>${esc(p.title)}</strong><small>${p.entries.length} 个视觉变量</small></span></label>`).join('')||'<p class="help">可以不使用预设，直接生成不含变量的分镜。</p>'}</div>`}
function designerCanvas(){const d=assemblyDesign,height=Math.max(700,Math.max(d.stories.length,d.visuals.length)*180+70);return `<div class="canvas-toolbar"><label>分镜资产<select id="canvas-story-choice">${projectTemplates().map(t=>opt(t.id,t.title,'')).join('')}</select></label>${btn('调入分镜','plus','designer-add-story')}<label>视觉预设<select id="canvas-preset-choice">${projectVariableSets().map(p=>opt(p.id,p.title,'')).join('')}</select></label>${btn('调入预设','plus','designer-add-preset')}</div><p class="help">拖动卡片标题调整位置；从分镜的右侧圆点拖到预设的左侧圆点建立连线。也可点击两个端口，或使用下方的键盘关联选项。点击连线可删除。</p><div class="link-board"><div class="link-world" style="height:${height}px"><svg class="link-lines" width="1180" height="${height}" aria-label="分镜与预设关联"></svg>${d.stories.map(n=>`<section class="link-node story-node" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px"><header data-drag-node="${n.id}">${icon('story')}<strong>${esc(templateBy(n.assetId)?.title||'分镜')}</strong>${ibtn('close','designer-remove-node','移除分镜节点',`data-id="${n.id}"`)}</header><label>输出画册名称<input data-node-title="${n.id}" value="${esc(n.title)}" maxlength="150"></label><button class="node-port output" data-port-story="${n.id}" aria-label="连接 ${esc(n.title)} 的预设"></button></section>`).join('')}${d.visuals.map(n=>`<section class="link-node preset-node" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px"><header data-drag-node="${n.id}">${icon('box')}<strong>${esc(setBy(n.assetId)?.title||'预设')}</strong>${ibtn('close','designer-remove-node','移除预设节点',`data-id="${n.id}"`)}</header><p>${setBy(n.assetId)?.entries.length||0} 个视觉变量 · 可连接多个分镜</p><button class="node-port input" data-port-preset="${n.id}" aria-label="使用 ${esc(setBy(n.assetId)?.title)}"></button></section>`).join('')}</div></div><details class="canvas-accessible"><summary>关联清单 · 键盘操作与核对</summary>${d.stories.map(s=>`<fieldset><legend>${esc(s.title)}</legend>${d.visuals.map(p=>`<label><input type="checkbox" data-edge-story="${s.id}" data-edge-preset="${p.id}" ${d.edges.some(e=>e.story===s.id&&e.preset===p.id)?'checked':''}>${esc(setBy(p.assetId)?.title)}</label>`).join('')}</fieldset>`).join('')}</details><p class="help">${d.stories.length} 个分镜任务节点 · ${d.edges.length} 条关联。每个分镜节点产生一张任务卡，合并它连接的全部预设；不展开为笛卡尔积。同名变量按预设卡片调入顺序覆盖。</p>`}
function renderAssemblyDesigner(){const d=assemblyDesign;const steps=['分镜与渠道','视觉预设','命名与入队'];let content;
 if(d.mode==='canvas')content=`<div class="canvas-environment">${designerEnvironment()}</div>${designerCanvas()}`;
 else content=`<nav class="assembly-stepper" aria-label="装配步骤">${steps.map((s,i)=>`<span class="${d.step===i?'active':d.step>i?'done':''}"><b>${i+1}</b>${s}</span>`).join('')}</nav><section class="designer-step"><h3>${['选择故事与生成环境','为故事搭配视觉资产','让这次创作有自己的名字'][d.step]}</h3><p>${['选择渠道；使用 ComfyUI 时，再选择工作流。','选择角色、服装和画风预设。','填写名称，添加生成任务。'][d.step]}</p>${d.step===0?`${field('分镜资产',`<select id="designer-story">${projectTemplates().map(t=>opt(t.id,t.title+' · '+t.frames.length+' 幕',d.storyId)).join('')}</select>`)}${designerEnvironment()}`:d.step===1?designerPresets():`${assemblyPreflightHTML()}${field('画册名称',input('title',d.title,'text','id="designer-title" maxlength="150" placeholder="例如：雨夜里的第二次相遇"'))}<div class="assembly-review"><p>分镜：${esc(templateBy(d.storyId)?.title)}</p><p>渠道：${esc(designerChannel()?.title)}</p><p>预设：${esc([...d.presets].map(id=>setBy(id)?.title).join(' + ')||'不使用预设')}</p></div>`}</section>`;
 modal('新建生成任务',`<div class="designer-modes" role="group" aria-label="装配模式">${[['wizard','分步向导'],['canvas','画布连线']].map(([id,label])=>btn(label,id==='wizard'?'list':'nodes','designer-mode',`data-mode="${id}" aria-pressed="${d.mode===id}"`,d.mode===id?'active':'ghost')).join('')}</div>${content}<div class="modal-footer designer-footer"><span class="grow"></span>${btn('取消','','close-modal','','ghost')}${d.mode==='wizard'&&d.step>0?btn('上一步','arrow-back','designer-back'):''}${d.mode==='wizard'&&d.step<2?btn('下一步','arrow','designer-next','','primary'):btn(d.mode==='canvas'?'批量生成 · 加入待命':'添加待命任务','plus','designer-submit',d.busy?'disabled':'','primary')}</div>`,'',true);
 $('#modal').classList.add('assembly-designer');if(d.mode==='canvas')updateDesignerLines();
}
function updateDesignerLines(point=null){const svg=$('.link-lines');if(!svg)return;const d=assemblyDesign;
 const curve=(a,b)=>`M ${a.x} ${a.y} C ${a.x+110} ${a.y}, ${b.x-110} ${b.y}, ${b.x} ${b.y}`;
 svg.innerHTML=d.edges.map((e,i)=>{const a=d.stories.find(n=>n.id===e.story),b=d.visuals.find(n=>n.id===e.preset);return a&&b?`<path tabindex="0" role="button" aria-label="删除关联 ${i+1}" data-edge-delete="${i}" d="${curve({x:a.x+244,y:a.y+64},{x:b.x,y:b.y+64})}"/>`:''}).join('');
 if(point&&d.drag?.kind==='link'){const a=d.stories.find(n=>n.id===d.drag.id);if(a)svg.insertAdjacentHTML('beforeend',`<path class="pending" d="${curve({x:a.x+244,y:a.y+64},point)}"/>`)}
}
function linkDesigner(story,preset){const d=assemblyDesign;if(!d.edges.some(e=>e.story===story&&e.preset===preset))d.edges.push({story,preset});d.drag=null;renderAssemblyDesigner()}
function designerItem(storyId,presetIds,title,index){const d=assemblyDesign;return {storyId,presets:presetIds.map(id=>({id,kind:setBy(id)?.category==='scenes'?'scenes':'characters'})),title:title.trim(),projectId:state.activeProjectId,channelId:d.channelId,workflowId:designerChannel()?.provider==='comfyui'?d.workflowId:undefined,seedEnabled:designerChannel()?.provider==='comfyui'&&d.seedEnabled&&designerSeedReady(),seed:d.seed,overrides:designerOverrides(),requestId:d.requestId+'-'+index}}
function validateDesignerEnvironment(){if(!designerChannel())throw Error('请选择图像渠道');const issues=providerSetupIssues(designerChannel());if(issues.length)throw Error(issues[0]);if(designerChannel().provider==='comfyui'&&!designerWorkflow())throw Error('请先保存并选择工作流');if(assemblyDesign.seedEnabled&&(!designerSeedReady()||!Number.isInteger(assemblyDesign.seed)||assemblyDesign.seed<0||assemblyDesign.seed>4294967295))throw Error('请配置有效种子映射并填写 uint32 种子')}
async function submitAssemblyDesigner(){const d=assemblyDesign;if(d.busy)return;validateDesignerEnvironment();let items;
 if(d.mode==='wizard')items=[designerItem(d.storyId,[...d.presets],d.title,0)];
 else {if(!d.stories.length)throw Error('请至少调入一个分镜');items=d.stories.map((s,i)=>{const ids=d.visuals.filter(p=>d.edges.some(e=>e.story===s.id&&e.preset===p.id)).map(p=>p.assetId);if(!ids.length)throw Error('请连接「'+s.title+'」的视觉预设，或移除该节点');return designerItem(s.assetId,ids,s.title,i)})}
 const inputIssues=items.flatMap(i=>assemblyInputIssues(i.storyId,i.presets.map(p=>p.id),designerChannel()));if(inputIssues.length)throw Error(inputIssues[0]);
 if(items.some(i=>!i.title||!templateBy(i.storyId)?.frames.length))throw Error('每张任务都需要名称和非空分镜');
 if(d.mode==='canvas'&&!await confirmAction('确认批量装配？',`将创建 ${items.length} 张待命任务卡。`,'添加待命'))return;
 d.busy=true;const button=$('[data-act="designer-submit"]');if(button)button.disabled=true;
 try{const remembered={...(state.settings.productionAssembly?.overrides||{})};if(d.workflowId&&designerChannel()?.provider==='comfyui'){remembered[d.workflowId]={model:String(d.overrides.model||''),loras:d.overrides.loras.map(l=>({name:l.name,strength:l.strength}))};for(const key of Object.keys(remembered).slice(0,-24))delete remembered[key]}state.settings.productionAssembly={channelId:d.channelId,workflowId:d.workflowId,overrides:remembered};save();if(!await savePythonWorkspace())throw Error('资产尚未保存，未入队');await productionRequest('assemble-batch',{items});closeModal();ui.workspace=1;workshop.view='production';await refreshProduction();toast(`已添加 ${items.length} 张待命任务卡`)}finally{d.busy=false;if(button?.isConnected)button.disabled=false}
}
function optionalModulesHTML(){const p=state.settings.studio,on=p.visibility.extensions!==false;return `<section class="settings-section"><h2>只留下你需要的功能</h2><p>核心创作始终保留，其余工作区由你选择。</p>${settingsRow('画册集与创作工坊','管理作品、独立分镜、预设与生产任务。','<span class="tiny muted">核心功能</span>','book')}${settingsRow('模板与扩展市场','独立全屏资源工作区。',switchControl('visibility.marketplace','显示模板与扩展市场',p.visibility.marketplace===true),'box')}${settingsRow('运行日志','查看运行记录与错误。',switchControl('visibility.logs','显示运行日志',p.visibility.logs),'terminal')}${settingsRow('AI 写故事','按需启用故事辅助工作区。',switchControl('visibility.llm','启用 AI 写故事',p.visibility.llm),'spark')}</section><section class="settings-section optional-settings"><header><div><h2>可选功能</h2></div><label class="switch"><input id="ws-extensions" role="switch" type="checkbox" aria-label="启用可选功能" ${on?'checked':''}><span class="switch-track"></span></label></header>${on?`<div class="optional-children">${laboratoryExtensions().map(x=>settingsRow(x.title,x.description,`<label class="switch"><input role="switch" type="checkbox" data-art-extension="${x.key}" aria-label="启用${x.title}" ${x.enabled?'checked':''}><span class="switch-track"></span></label>`,x.icon)).join('')}</div>`:''}</section>`}
function installArchitecture(){
 paths['arrow-back']='<path d="M19 12H5m6-6-6 6 6 6"/>';
 studioDefaults.visibility.extensions=true;studioDefaults.visibility.marketplace=false;studioDefaults.features.assistant??=true;
 renderV3Modules=optionalModulesHTML;
 const enabled=featureEnabled;featureEnabled=function(key){if(key==='marketplace')return state.settings.studio.visibility.marketplace===true;if(['assistant','visualCritic'].includes(key)&&state.settings.studio.visibility.extensions===false)return false;return enabled(key)};
 const visible=workspaceVisible;workspaceVisible=function(index){if(index===8)return featureEnabled('marketplace');if(index===7)return state.settings.studio.visibility.extensions!==false;return visible(index)};
 const assistant=showAssistant;showAssistant=function(...args){if(!featureEnabled('assistant'))return toast('请先在设置的可选功能中启用助手');return assistant(...args)};
 marketModal=function(){if(!featureEnabled('marketplace')){ui.workspace=5;studioUI.settingsTab='modules';render();toast('请先开启模板与扩展市场');return}closeModal();ui.workspace=8;render()};
 renderMarket=function(){if($('#market-content')){const raw=$('#raw-url')?.value;renderStudioMarket();if(raw!==undefined&&$('#raw-url'))$('#raw-url').value=raw;localizeWorkspace($('#market-content'))}};
 const renderPrevious=render;render=function(...args){if(ui.workspace===8){if(!featureEnabled('marketplace'))ui.workspace=0;else{ensureStudioState();renderShell();patchMain('<section class="market-workspace">'+heading('模板与扩展市场','探索可复用的分镜、视觉资源与扩展。','','')+'<div id="market-content"></div></section>');renderMarket();$('.breadcrumb strong').textContent='模板与扩展市场';return}}if(ui.workspace===5&&studioUI.settingsTab==='critic'){ui.workspace=7}const result=renderPrevious(...args);if(ui.workspace===3){const crumb=$('.breadcrumb strong');if(crumb)crumb.textContent='工作流与 API 配置'}if(state.settings.studio.visibility.extensions===false){if($('#assistant'))$('#assistant').hidden=true}return result};
 const navigatePrevious=navigate;navigate=function(index){if(Number(index)===8){marketModal();return}const result=navigatePrevious(index);if(Number(index)===7){const book=selectedLabBook();if(book?._lazy)globalThis.Mio.fileLibrary.hydrate(book.id).then(()=>{if(ui.workspace===7)render()}).catch(e=>toast(e.message,'error'))}return result};
 const actionPrevious=handleAction;handleAction=async function(action,d={},el){if(action.startsWith('art-lab-')&&state.settings.studio.visibility.extensions===false)throw Error('可选功能已关闭');return actionPrevious(action,d,el)};
 Object.assign(v3Actions,{
  'local-critic-api':()=>{if(ui.workspace!==7||state.settings.studio.visibility.extensions===false)throw Error('请在可选功能工作台配置');openCriticSettings()},
  'workshop-negative-all':async()=>{const s=workshopStory(),value=s.frames[workshop.frame]?.negative||'';if(await confirmAction('覆盖所有分幕的负向提示词？',`将更新「${s.title}」的 ${s.frames.length} 幕；已装配任务不受影响。`,'应用到所有分幕')){s.frames.forEach(f=>f.negative=value);save();render()}},
  'designer-mode':d=>{assemblyDesign.drag=null;assemblyDesign.mode=d.mode;renderAssemblyDesigner()},
  'designer-workflow-clear':()=>{assemblyDesign.workflowQuery='';const box=$('#designer-workflow-search');if(box){box.value='';box.focus()}refreshDesignerWorkflowPicker()},
  'designer-next':()=>{if(assemblyDesign.step===0){validateDesignerEnvironment();if(!templateBy(assemblyDesign.storyId)?.frames.length)throw Error('请选择非空分镜')}assemblyDesign.step++;renderAssemblyDesigner()},
  'designer-back':()=>{assemblyDesign.step--;renderAssemblyDesigner()},
  'designer-submit':submitAssemblyDesigner,
  'designer-add-story':()=>{const id=$('#canvas-story-choice').value,t=templateBy(id);if(!t)return;const d=assemblyDesign;d.stories.push({id:uid('node'),assetId:id,title:t.title+' · 新画册',x:35,y:30+d.stories.length*180});renderAssemblyDesigner()},
  'designer-add-preset':()=>{const id=$('#canvas-preset-choice').value;if(!id)return;const d=assemblyDesign;if(d.visuals.some(p=>p.assetId===id))return;d.visuals.push({id:uid('node'),assetId:id,x:760,y:30+d.visuals.length*180});renderAssemblyDesigner()},
  'designer-remove-node':d=>{const a=assemblyDesign;a.stories=a.stories.filter(n=>n.id!==d.id);a.visuals=a.visuals.filter(n=>n.id!==d.id);a.edges=a.edges.filter(e=>e.story!==d.id&&e.preset!==d.id);renderAssemblyDesigner()},
  'designer-lora-remove':d=>{assemblyDesign.overrides.loras.splice(Number(d.index),1);refreshDesignerOverrides('lora')},
  'designer-lora-add-free':d=>{designerAddLora(String(d.name||'').trim());assemblyDesign.overrideUI.loraQuery='';const search=$('#designer-lora-search');if(search)search.value='';refreshDesignerOverrides('lora')},
  'designer-sync-catalog':async()=>{await readComfyObjectInfo();const query=assemblyDesign.overrideUI;initDesignerOverrides();assemblyDesign.overrideUI=query;renderAssemblyDesigner()}
 });
 document.addEventListener('change',e=>{const el=e.target,d=assemblyDesign;if(el.id==='designer-story')d.storyId=el.value;if(el.dataset.designerPreset){el.checked?d.presets.add(el.dataset.designerPreset):d.presets.delete(el.dataset.designerPreset);el.closest('label').classList.toggle('selected',el.checked)}if(el.id==='designer-channel'||el.id==='designer-workflow'){if(el.id==='designer-channel')d.channelId=el.value;else d.workflowId=el.value;d.seedEnabled=false;state.settings.productionAssembly={...(state.settings.productionAssembly||{}),channelId:d.channelId,workflowId:d.workflowId};save();initDesignerOverrides();renderAssemblyDesigner()}if(el.id==='designer-model-list'){d.overrides.model=el.value;refreshDesignerOverrides('model')}if(el.dataset.designerLoraToggle!==undefined){try{if(el.checked)designerAddLora(el.dataset.designerLoraToggle);else{const key=designerLoraKey(el.dataset.designerLoraToggle);d.overrides.loras=d.overrides.loras.filter(l=>designerLoraKey(l.name)!==key)}}catch(error){el.checked=false;toast(error.message,'error')}refreshDesignerOverrides('lora')}if(el.id==='designer-seed-enable'){d.seedEnabled=el.checked;renderAssemblyDesigner()}if(el.dataset.edgeStory){const {edgeStory:story,edgePreset:preset}=el.dataset;if(el.checked)linkDesigner(story,preset);else{d.edges=d.edges.filter(e=>e.story!==story||e.preset!==preset);updateDesignerLines()}}if(el.dataset.studioPref==='visibility.marketplace')render()});
 document.addEventListener('input',e=>{const el=e.target,d=assemblyDesign;if(el.id==='designer-title')d.title=el.value;if(el.id==='designer-seed')d.seed=Number(el.value);if(el.dataset.nodeTitle){const n=d.stories.find(n=>n.id===el.dataset.nodeTitle);if(n)n.title=el.value}if(el.id==='designer-workflow-search'){d.workflowQuery=el.value;refreshDesignerWorkflowPicker()}if(el.id==='designer-model-search'){d.overrideUI.modelQuery=el.value;refreshDesignerOverrides('model')}if(el.id==='designer-lora-search'){d.overrideUI.loraQuery=el.value;const results=$('#designer-lora-results'),slots=designerSlots();if(results&&slots)results.innerHTML=designerLoraResultsHTML(slots)}if(el.dataset.designerLoraStrength!==undefined){const l=d.overrides.loras[Number(el.dataset.designerLoraStrength)];if(l){l.strength=clamp(Number(el.value)||1,0.1,1.5);const out=$(`[data-designer-lora-output="${el.dataset.designerLoraStrength}"]`);if(out)out.textContent=WorkflowSlots.numberText(l.strength)}}});
 document.addEventListener('pointerdown',e=>{const d=assemblyDesign,port=e.target.closest('[data-port-story]'),header=e.target.closest('[data-drag-node]');if(port){d.drag={kind:'link',id:port.dataset.portStory};e.preventDefault()}else if(header&&!e.target.closest('button')){const n=[...d.stories,...d.visuals].find(n=>n.id===header.dataset.dragNode);d.drag={kind:'move',id:n.id,x:e.clientX,y:e.clientY,ox:n.x,oy:n.y};e.preventDefault()}});
 document.addEventListener('pointermove',e=>{const d=assemblyDesign;if(!d.drag)return;const world=$('.link-world');if(!world)return;const r=world.getBoundingClientRect();if(d.drag.kind==='link')updateDesignerLines({x:e.clientX-r.left,y:e.clientY-r.top});else{const n=[...d.stories,...d.visuals].find(n=>n.id===d.drag.id);if(!n)return;n.x=clamp(d.drag.ox+e.clientX-d.drag.x,12,920);n.y=clamp(d.drag.oy+e.clientY-d.drag.y,12,world.offsetHeight-165);const node=$(`[data-node="${n.id}"]`);node.style.left=n.x+'px';node.style.top=n.y+'px';updateDesignerLines()}});
 document.addEventListener('pointerup',e=>{const d=assemblyDesign;if(!d.drag)return;if(d.drag.kind==='link'){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-port-preset]');if(target)linkDesigner(d.drag.id,target.dataset.portPreset)}else d.drag=null});
 document.addEventListener('click',e=>{const target=e.target.closest('[data-port-preset]'),line=e.target.closest('[data-edge-delete]');if(target&&assemblyDesign.drag?.kind==='link')linkDesigner(assemblyDesign.drag.id,target.dataset.portPreset);if(line){assemblyDesign.edges.splice(Number(line.dataset.edgeDelete),1);renderAssemblyDesigner()}});
 document.addEventListener('keydown',e=>{if(e.target.id==='designer-workflow-search'&&!e.isComposing){const list=$('#designer-workflow');if(e.key==='ArrowDown'&&list){e.preventDefault();list.focus();return}if(e.key==='Enter'){e.preventDefault();const result=designerWorkflowChoices();if(result.matched===1&&String(result.options[0].id)!==String(assemblyDesign.workflowId)&&list){list.value=result.options[0].id;list.dispatchEvent(new Event('change',{bubbles:true}))}return}}if(e.key==='Escape'){assemblyDesign.drag=null;updateDesignerLines()}if(['Enter','Delete','Backspace'].includes(e.key)&&e.target.matches('[data-edge-delete]')){e.preventDefault();assemblyDesign.edges.splice(Number(e.target.dataset.edgeDelete),1);renderAssemblyDesigner()}});
 $('#modal').addEventListener('close',()=>{$('#modal').classList.remove('assembly-designer');assemblyDesign.drag=null});
}
