/* Single-owner workspace policy and two-mode, standby-only assembly design. */
'use strict';
const assemblyDesign={mode:'wizard',step:0,storyId:'',channelId:'',workflowId:'',seedEnabled:false,seed:1,presets:new Set(),title:'',stories:[],visuals:[],edges:[],requestId:'',busy:false,drag:null};
function designerChannel(){return ensureImageProviders().profiles.find(p=>p.id===assemblyDesign.channelId)}
function designerWorkflow(){return state.settings.comfy.presets.find(p=>p.id===assemblyDesign.workflowId)}
function designerSeedReady(){const w=designerWorkflow();return !!w?.bindings?.some(b=>{if(!b.enabled||b.source!=='random')return false;try{let v=w.workflow[String(b.nodeId)].inputs;for(const part of (b.path.startsWith('/')?b.path.slice(1).split('/'):b.path.split('.')))v=v[part.replace(/~1/g,'/').replace(/~0/g,'~')];return typeof v==='number'&&Number.isFinite(v)}catch{return false}})}
function designerChannelNotice(){const d=assemblyDesign,current=designerChannel(),previous=ensureImageProviders().profiles.find(p=>p.id===d.previousChannelId);if(!current||!previous||previous.id===current.id||current.id!==ensureImageProviders().active)return '';return `<p class="notice designer-channel-notice" role="status">已按设置中当前启用的渠道预选「${esc(current.title)}」；上次装配使用的是「${esc(previous.title)}」。请确认后再入队，避免发送到非预期的付费渠道。</p>`}
function designerEnvironment(){const d=assemblyDesign,comfy=designerChannel()?.provider==='comfyui',ready=designerSeedReady();return `<div class="designer-environment">${designerChannelNotice()}${field('图像生成渠道',`<select id="designer-channel">${ensureImageProviders().profiles.map(p=>opt(p.id,p.title,d.channelId)).join('')}</select>`)}${comfy?`<div class="designer-workflow">${field('搜索已保存的工作流',input('search','','search','id="designer-workflow-search" placeholder="输入工作流名称"'))}${field('工作流',`<select id="designer-workflow">${state.settings.comfy.presets.map(w=>opt(w.id,w.title,d.workflowId)).join('')}</select>`)}<div class="seed-setting"><label class="row"><span class="switch"><input id="designer-seed-enable" type="checkbox" role="switch" aria-label="启用可复现种子" ${d.seedEnabled&&ready?'checked':''} ${ready?'':'disabled'}><span class="switch-track"></span></span><span>可复现种子</span></label><input id="designer-seed" type="number" min="0" max="4294967295" value="${d.seed}" ${d.seedEnabled&&ready?'':'disabled'} aria-label="可复现种子"><p class="help">${ready?'已找到有效种子映射。关闭时每幕、每次重跑都使用新的随机种子；开启后按固定种子 + 幕序号生成，可复现。':'未找到种子映射：所有分幕会沿用工作流中的固定种子，画面可能雷同。请在工作流映射中为采样器 seed 绑定「每次生成新种子」后再启用。'}</p></div></div>`:''}</div>`}
function openAssemblyDesigner(){
 const d=assemblyDesign,prefs=state.settings.productionAssembly||{},providers=ensureImageProviders(),lastUsed=providers.profiles.find(p=>p.id===prefs.channelId)?.id||'';
 /* B10: the wizard follows the channel enabled in Settings, never silently the last one billed; a differing history is only a notice. */
 Object.assign(d,{mode:'wizard',step:0,storyId:workshopStory()?.id||'',channelId:providers.active||lastUsed,previousChannelId:lastUsed&&lastUsed!==providers.active?lastUsed:'',workflowId:(prefs.channelId===providers.active?prefs.workflowId:'')||state.settings.comfy.activeWorkflowId,seedEnabled:false,seed:1,presets:new Set(),title:'',stories:[],visuals:[],edges:[],requestId:uid('assembly'),busy:false,drag:null});
 if(!designerChannel())d.channelId=ensureImageProviders().profiles[0]?.id||'';if(!designerWorkflow())d.workflowId=state.settings.comfy.presets[0]?.id||'';
 renderAssemblyDesigner();
}
function designerPresets(){return `<div class="designer-presets">${projectVariableSets().map(p=>`<label class="designer-preset ${assemblyDesign.presets.has(p.id)?'selected':''}"><input type="checkbox" data-designer-preset="${esc(p.id)}" ${assemblyDesign.presets.has(p.id)?'checked':''}><span>${icon('box')}<strong>${esc(p.title)}</strong><small>${p.entries.length} 个视觉变量</small></span></label>`).join('')||'<p class="help">可以不使用预设，直接生成不含变量的分镜。</p>'}</div>`}
function designerCanvas(){const d=assemblyDesign,height=Math.max(700,Math.max(d.stories.length,d.visuals.length)*180+70);return `<div class="canvas-toolbar"><label>分镜资产<select id="canvas-story-choice">${projectTemplates().map(t=>opt(t.id,t.title,'')).join('')}</select></label>${btn('调入分镜','plus','designer-add-story')}<label>视觉预设<select id="canvas-preset-choice">${projectVariableSets().map(p=>opt(p.id,p.title,'')).join('')}</select></label>${btn('调入预设','plus','designer-add-preset')}</div><p class="help">拖动卡片标题调整位置；从分镜的右侧圆点拖到预设的左侧圆点建立连线。也可点击两个端口，或使用下方的键盘关联选项。点击连线可删除。</p><div class="link-board"><div class="link-world" style="height:${height}px"><svg class="link-lines" width="1180" height="${height}" aria-label="分镜与预设关联"></svg>${d.stories.map(n=>`<section class="link-node story-node" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px"><header data-drag-node="${n.id}">${icon('story')}<strong>${esc(templateBy(n.assetId)?.title||'分镜')}</strong>${ibtn('close','designer-remove-node','移除分镜节点',`data-id="${n.id}"`)}</header><label>输出画册名称<input data-node-title="${n.id}" value="${esc(n.title)}" maxlength="150"></label><button class="node-port output" data-port-story="${n.id}" aria-label="连接 ${esc(n.title)} 的预设"></button></section>`).join('')}${d.visuals.map(n=>`<section class="link-node preset-node" data-node="${n.id}" style="left:${n.x}px;top:${n.y}px"><header data-drag-node="${n.id}">${icon('box')}<strong>${esc(setBy(n.assetId)?.title||'预设')}</strong>${ibtn('close','designer-remove-node','移除预设节点',`data-id="${n.id}"`)}</header><p>${setBy(n.assetId)?.entries.length||0} 个视觉变量 · 可连接多个分镜</p><button class="node-port input" data-port-preset="${n.id}" aria-label="使用 ${esc(setBy(n.assetId)?.title)}"></button></section>`).join('')}</div></div><details class="canvas-accessible"><summary>关联清单 · 键盘操作与核对</summary>${d.stories.map(s=>`<fieldset><legend>${esc(s.title)}</legend>${d.visuals.map(p=>`<label><input type="checkbox" data-edge-story="${s.id}" data-edge-preset="${p.id}" ${d.edges.some(e=>e.story===s.id&&e.preset===p.id)?'checked':''}>${esc(setBy(p.assetId)?.title)}</label>`).join('')}</fieldset>`).join('')}</details><p class="help">${d.stories.length} 个分镜任务节点 · ${d.edges.length} 条关联。每个分镜节点产生一张任务卡，合并它连接的全部预设；不展开为笛卡尔积。同名变量按预设卡片调入顺序覆盖。</p>`}
function renderAssemblyDesigner(){const d=assemblyDesign;const steps=['分镜与渠道','视觉预设','命名与入队'];let content;
 if(d.mode==='canvas')content=`<div class="canvas-environment">${designerEnvironment()}</div>${designerCanvas()}`;
 else content=`<nav class="assembly-stepper" aria-label="装配步骤">${steps.map((s,i)=>`<span class="${d.step===i?'active':d.step>i?'done':''}"><b>${i+1}</b>${s}</span>`).join('')}</nav><section class="designer-step"><h3>${['选择故事与生成环境','为故事搭配视觉资产','让这次创作有自己的名字'][d.step]}</h3><p>${['选择渠道；使用 ComfyUI 时，再选择工作流。','选择角色、服装和画风预设。','填写名称，添加生成任务。'][d.step]}</p>${d.step===0?`${field('分镜资产',`<select id="designer-story">${projectTemplates().map(t=>opt(t.id,t.title+' · '+t.frames.length+' 幕',d.storyId)).join('')}</select>`)}${designerEnvironment()}`:d.step===1?designerPresets():`${assemblyPreflightHTML()}${field('画册名称',input('title',d.title,'text','id="designer-title" maxlength="150" placeholder="例如：雨夜里的第二次相遇"'))}<div class="assembly-review"><p>分镜：${esc(templateBy(d.storyId)?.title)}</p><p>渠道：${esc(designerChannel()?.title)}</p><p>预设：${esc([...d.presets].map(id=>setBy(id)?.title).join(' + ')||'不使用预设')}</p></div>`}</section>`;
 modal('新建生成任务',`<div class="designer-modes" role="group" aria-label="装配模式">${[['wizard','分步向导'],['canvas','画布连线']].map(([id,label])=>btn(label,id==='wizard'?'list':'nodes','designer-mode',`data-mode="${id}" aria-pressed="${d.mode===id}"`,d.mode===id?'active':'ghost')).join('')}</div>${content}<div class="modal-footer designer-footer"><span class="grow"></span>${btn('取消','','close-modal','','ghost')}${d.mode==='wizard'&&d.step>0?btn('上一步','arrow-back','designer-back'):''}${d.mode==='wizard'&&d.step<2?btn('下一步','arrow','designer-next','','primary'):btn(d.mode==='canvas'?'批量生成 · 加入待命':'添加待命任务','plus','designer-submit',d.busy?'disabled':'','primary')}</div>`,'',true);
 $('#modal').classList.add('assembly-designer');if(d.mode==='canvas')updateDesignerLines();
}
function updateDesignerLines(point=null){const svg=$('.link-lines');if(!svg)return;const d=assemblyDesign;
 const curve=(a,b)=>`M ${a.x} ${a.y} C ${a.x+110} ${a.y}, ${b.x-110} ${b.y}, ${b.x} ${b.y}`;
 svg.innerHTML=d.edges.map((e,i)=>{const a=d.stories.find(n=>n.id===e.story),b=d.visuals.find(n=>n.id===e.preset);return a&&b?`<path tabindex="0" role="button" aria-label="删除关联 ${i+1}" data-edge-delete="${i}" d="${curve({x:a.x+244,y:a.y+64},{x:b.x,y:b.y+64})}"/>`:''}).join('');
 if(point&&d.drag?.kind==='link'){const a=d.stories.find(n=>n.id===d.drag.id);if(a)svg.insertAdjacentHTML('beforeend',`<path class="pending" d="${curve({x:a.x+244,y:a.y+64},point)}"/>`)}
}
function linkDesigner(story,preset){const d=assemblyDesign;if(!d.edges.some(e=>e.story===story&&e.preset===preset))d.edges.push({story,preset});d.drag=null;renderAssemblyDesigner()}
function designerItem(storyId,presetIds,title,index){const d=assemblyDesign;return {storyId,presets:presetIds.map(id=>({id,kind:setBy(id)?.category==='scenes'?'scenes':'characters'})),title:title.trim(),projectId:state.activeProjectId,channelId:d.channelId,workflowId:designerChannel()?.provider==='comfyui'?d.workflowId:undefined,seedEnabled:designerChannel()?.provider==='comfyui'&&d.seedEnabled&&designerSeedReady(),seed:d.seed,requestId:d.requestId+'-'+index}}
function validateDesignerEnvironment(){if(!designerChannel())throw Error('请选择图像渠道');const issues=providerSetupIssues(designerChannel());if(issues.length)throw Error(issues[0]);if(designerChannel().provider==='comfyui'&&!designerWorkflow())throw Error('请先保存并选择工作流');if(assemblyDesign.seedEnabled&&(!designerSeedReady()||!Number.isInteger(assemblyDesign.seed)||assemblyDesign.seed<0||assemblyDesign.seed>4294967295))throw Error('请配置有效种子映射并填写 uint32 种子')}
async function submitAssemblyDesigner(){const d=assemblyDesign;if(d.busy)return;validateDesignerEnvironment();let items;
 if(d.mode==='wizard')items=[designerItem(d.storyId,[...d.presets],d.title,0)];
 else {if(!d.stories.length)throw Error('请至少调入一个分镜');items=d.stories.map((s,i)=>{const ids=d.visuals.filter(p=>d.edges.some(e=>e.story===s.id&&e.preset===p.id)).map(p=>p.assetId);if(!ids.length)throw Error('请连接「'+s.title+'」的视觉预设，或移除该节点');return designerItem(s.assetId,ids,s.title,i)})}
 const inputIssues=items.flatMap(i=>assemblyInputIssues(i.storyId,i.presets.map(p=>p.id),designerChannel()));if(inputIssues.length)throw Error(inputIssues[0]);
 if(items.some(i=>!i.title||!templateBy(i.storyId)?.frames.length))throw Error('每张任务都需要名称和非空分镜');
 if(d.mode==='canvas'&&!await confirmAction('确认批量装配？',`将创建 ${items.length} 张待命任务卡。`,'添加待命'))return;
 d.busy=true;const button=$('[data-act="designer-submit"]');if(button)button.disabled=true;
 try{state.settings.productionAssembly={channelId:d.channelId,workflowId:d.workflowId};save();if(!await savePythonWorkspace())throw Error('资产尚未保存，未入队');await productionRequest('assemble-batch',{items});closeModal();ui.workspace=1;workshop.view='production';await refreshProduction();toast(`已添加 ${items.length} 张待命任务卡`)}finally{d.busy=false;if(button?.isConnected)button.disabled=false}
}
function optionalModulesHTML(){const p=state.settings.studio,on=p.visibility.extensions!==false;return `<section class="settings-section"><h2>只留下你需要的功能</h2><p>核心创作始终保留，其余工作区由你选择。</p>${settingsRow('画册集与创作工坊','管理作品、独立分镜、预设与生产任务。','<span class="tiny muted">核心功能</span>','book')}${settingsRow('模板与扩展市场','独立全屏资源工作区。',switchControl('visibility.marketplace','显示模板与扩展市场',p.visibility.marketplace===true),'box')}${settingsRow('运行日志','查看运行记录与错误。',switchControl('visibility.logs','显示运行日志',p.visibility.logs),'terminal')}${settingsRow('AI 写故事','按需启用故事辅助工作区。',switchControl('visibility.llm','启用 AI 写故事',p.visibility.llm),'spark')}</section><section class="settings-section optional-settings"><header><div><h2>可选功能</h2></div><label class="switch"><input id="ws-extensions" role="switch" type="checkbox" aria-label="启用可选功能" ${on?'checked':''}><span class="switch-track"></span></label></header>${on?`<div class="optional-children">${laboratoryExtensions().map(x=>settingsRow(x.title,x.description,`<label class="switch"><input role="switch" type="checkbox" data-art-extension="${x.key}" aria-label="启用${x.title}" ${x.enabled?'checked':''}><span class="switch-track"></span></label>`,x.icon)).join('')}</div>`:''}</section>`}
function installArchitecture(){
 paths['arrow-back']='<path d="M19 12H5m6-6-6 6 6 6"/>';
 studioDefaults.visibility.extensions=true;studioDefaults.visibility.marketplace=false;studioDefaults.features.assistant??=true;
 renderV3Modules=optionalModulesHTML;
 const enabled=featureEnabled;featureEnabled=function(key){if(key==='marketplace')return state.settings.studio.visibility.marketplace===true;if(['assistant','visualCritic'].includes(key)&&state.settings.studio.visibility.extensions===false)return false;return enabled(key)};
 const visible=workspaceVisible;workspaceVisible=function(index){if(index===8)return featureEnabled('marketplace');if(index===7)return state.settings.studio.visibility.extensions!==false;return visible(index)};
 const assistant=showAssistant;showAssistant=function(...args){if(!featureEnabled('assistant'))return toast('请先在设置的可选功能中启用助手');return assistant(...args)};
 marketModal=function(){if(!featureEnabled('marketplace')){ui.workspace=5;studioUI.settingsTab='modules';render();toast('请先开启模板与扩展市场');return}closeModal();ui.workspace=8;render()};
 renderMarket=function(){if($('#market-content')){const raw=$('#raw-url')?.value;renderStudioMarket();if(raw!==undefined&&$('#raw-url'))$('#raw-url').value=raw;localizeWorkspace($('#market-content'))}};
 const renderPrevious=render;render=function(...args){if(ui.workspace===8){if(!featureEnabled('marketplace'))ui.workspace=0;else{ensureStudioState();renderShell();patchMain('<section class="market-workspace">'+heading('模板与扩展市场','探索可复用的分镜、视觉资源与扩展。','','')+'<div id="market-content"></div></section>');renderMarket();$('.breadcrumb strong').textContent='模板与扩展市场';return}}if(ui.workspace===5&&studioUI.settingsTab==='critic'){ui.workspace=7}const result=renderPrevious(...args);if(ui.workspace===3){const crumb=$('.breadcrumb strong');if(crumb)crumb.textContent='工作流与 API 配置'}if(state.settings.studio.visibility.extensions===false){if($('#assistant'))$('#assistant').hidden=true}return result};
 const navigatePrevious=navigate;navigate=function(index){if(Number(index)===8){marketModal();return}const result=navigatePrevious(index);if(Number(index)===7){const book=selectedLabBook();if(book?._lazy)globalThis.Mio.fileLibrary.hydrate(book.id).then(()=>{if(ui.workspace===7)render()}).catch(e=>toast(e.message,'error'))}return result};
 const actionPrevious=handleAction;handleAction=async function(action,d={},el){if(action.startsWith('art-lab-')&&state.settings.studio.visibility.extensions===false)throw Error('可选功能已关闭');return actionPrevious(action,d,el)};
 Object.assign(v3Actions,{
  'local-critic-api':()=>{if(ui.workspace!==7||state.settings.studio.visibility.extensions===false)throw Error('请在可选功能工作台配置');openCriticSettings()},
  'workshop-negative-all':async()=>{const s=workshopStory(),value=s.frames[workshop.frame]?.negative||'';if(await confirmAction('覆盖所有分幕的负向提示词？',`将更新「${s.title}」的 ${s.frames.length} 幕；已装配任务不受影响。`,'应用到所有分幕')){s.frames.forEach(f=>f.negative=value);save();render()}},
  'designer-mode':d=>{assemblyDesign.drag=null;assemblyDesign.mode=d.mode;renderAssemblyDesigner()},
  'designer-next':()=>{if(assemblyDesign.step===0){validateDesignerEnvironment();if(!templateBy(assemblyDesign.storyId)?.frames.length)throw Error('请选择非空分镜')}assemblyDesign.step++;renderAssemblyDesigner()},
  'designer-back':()=>{assemblyDesign.step--;renderAssemblyDesigner()},
  'designer-submit':submitAssemblyDesigner,
  'designer-add-story':()=>{const id=$('#canvas-story-choice').value,t=templateBy(id);if(!t)return;const d=assemblyDesign;d.stories.push({id:uid('node'),assetId:id,title:t.title+' · 新画册',x:35,y:30+d.stories.length*180});renderAssemblyDesigner()},
  'designer-add-preset':()=>{const id=$('#canvas-preset-choice').value;if(!id)return;const d=assemblyDesign;if(d.visuals.some(p=>p.assetId===id))return;d.visuals.push({id:uid('node'),assetId:id,x:760,y:30+d.visuals.length*180});renderAssemblyDesigner()},
  'designer-remove-node':d=>{const a=assemblyDesign;a.stories=a.stories.filter(n=>n.id!==d.id);a.visuals=a.visuals.filter(n=>n.id!==d.id);a.edges=a.edges.filter(e=>e.story!==d.id&&e.preset!==d.id);renderAssemblyDesigner()}
 });
 document.addEventListener('change',e=>{const el=e.target,d=assemblyDesign;if(el.id==='designer-story')d.storyId=el.value;if(el.dataset.designerPreset){el.checked?d.presets.add(el.dataset.designerPreset):d.presets.delete(el.dataset.designerPreset);el.closest('label').classList.toggle('selected',el.checked)}if(el.id==='designer-channel'||el.id==='designer-workflow'){if(el.id==='designer-channel')d.channelId=el.value;else d.workflowId=el.value;d.seedEnabled=false;state.settings.productionAssembly={channelId:d.channelId,workflowId:d.workflowId};save();renderAssemblyDesigner()}if(el.id==='designer-seed-enable'){d.seedEnabled=el.checked;renderAssemblyDesigner()}if(el.dataset.edgeStory){const {edgeStory:story,edgePreset:preset}=el.dataset;if(el.checked)linkDesigner(story,preset);else{d.edges=d.edges.filter(e=>e.story!==story||e.preset!==preset);updateDesignerLines()}}if(el.dataset.studioPref==='visibility.marketplace')render()});
 document.addEventListener('input',e=>{const el=e.target,d=assemblyDesign;if(el.id==='designer-title')d.title=el.value;if(el.id==='designer-seed')d.seed=Number(el.value);if(el.dataset.nodeTitle){const n=d.stories.find(n=>n.id===el.dataset.nodeTitle);if(n)n.title=el.value}if(el.id==='designer-workflow-search')$('#designer-workflow').innerHTML=state.settings.comfy.presets.filter(w=>w.id===d.workflowId||w.title.toLowerCase().includes(el.value.toLowerCase())).map(w=>opt(w.id,(w.id===d.workflowId?'当前选择 · ':'')+w.title,d.workflowId)).join('')});
 document.addEventListener('pointerdown',e=>{const d=assemblyDesign,port=e.target.closest('[data-port-story]'),header=e.target.closest('[data-drag-node]');if(port){d.drag={kind:'link',id:port.dataset.portStory};e.preventDefault()}else if(header&&!e.target.closest('button')){const n=[...d.stories,...d.visuals].find(n=>n.id===header.dataset.dragNode);d.drag={kind:'move',id:n.id,x:e.clientX,y:e.clientY,ox:n.x,oy:n.y};e.preventDefault()}});
 document.addEventListener('pointermove',e=>{const d=assemblyDesign;if(!d.drag)return;const world=$('.link-world');if(!world)return;const r=world.getBoundingClientRect();if(d.drag.kind==='link')updateDesignerLines({x:e.clientX-r.left,y:e.clientY-r.top});else{const n=[...d.stories,...d.visuals].find(n=>n.id===d.drag.id);if(!n)return;n.x=clamp(d.drag.ox+e.clientX-d.drag.x,12,920);n.y=clamp(d.drag.oy+e.clientY-d.drag.y,12,world.offsetHeight-165);const node=$(`[data-node="${n.id}"]`);node.style.left=n.x+'px';node.style.top=n.y+'px';updateDesignerLines()}});
 document.addEventListener('pointerup',e=>{const d=assemblyDesign;if(!d.drag)return;if(d.drag.kind==='link'){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-port-preset]');if(target)linkDesigner(d.drag.id,target.dataset.portPreset)}else d.drag=null});
 document.addEventListener('click',e=>{const target=e.target.closest('[data-port-preset]'),line=e.target.closest('[data-edge-delete]');if(target&&assemblyDesign.drag?.kind==='link')linkDesigner(assemblyDesign.drag.id,target.dataset.portPreset);if(line){assemblyDesign.edges.splice(Number(line.dataset.edgeDelete),1);renderAssemblyDesigner()}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){assemblyDesign.drag=null;updateDesignerLines()}if(['Enter','Delete','Backspace'].includes(e.key)&&e.target.matches('[data-edge-delete]')){e.preventDefault();assemblyDesign.edges.splice(Number(e.target.dataset.edgeDelete),1);renderAssemblyDesigner()}});
 $('#modal').addEventListener('close',()=>{$('#modal').classList.remove('assembly-designer');assemblyDesign.drag=null});
}
