/* Mio gallery: feature declarations; initialization remains in app.js. */
'use strict';
function renderGallery(){const b=projectBooks(),scores=b.map(score).filter(Boolean),avg=scores.length?(scores.reduce((a,b)=>a+b)/scores.length).toFixed(1):'0.0';return heading('画廊展厅','让每一个灵感，成为值得珍藏的连续画面。',btn('导入工程','upload','import-project')+btn('新建画册','plus','new-book','','primary'),'YOUR STORIES, FRAME BY FRAME.')+`<section class="metrics" aria-label="项目统计">${[['folder','创作企划',state.projects.length,'个企划'],['book','连续画册',b.length,b.filter(b=>b.status==='complete').length+' 本已完成'],['image','已生成分镜',b.reduce((a,b)=>a+b.generatedSteps,0),'帧画面'],['shield','平均审校得分',avg,'/ 10 · 演示']].map(m=>`<div class="metric"><div class="metric-label">${icon(m[0])}${m[1]}</div><strong>${typeof m[2]==='number'?pad(m[2]):m[2]}</strong><small>${m[3]}</small></div>`).join('')}</section><div class="tabbar"><button class="tab ${ui.filter!=='starred'?'active':''}" data-act="gallery-tab" data-filter="all">全部画册 <b>${b.length}</b></button><button class="tab ${ui.filter==='starred'?'active':''}" data-act="gallery-tab" data-filter="starred">${icon('star','sm')}星标收藏 <b>${b.filter(b=>b.liked).length}</b></button><button class="tab" data-act="recent">最近编辑</button><div class="spacer"></div>${btn('批量管理','check','toggle-bulk','','ghost small')}</div><div class="gallery-controls"><div class="search-field">${icon('search')}<input id="gallery-search" value="${esc(ui.search)}" placeholder="搜索画册、角色、标签或故事内容..." aria-label="搜索画册"></div><div class="spacer"></div><select id="gallery-filter" aria-label="状态筛选">${[['all','全部状态'],['complete','已完成'],['generating','渲染中 / 排队'],['failed','失败 / 待补齐'],['starred','星标收藏']].map(x=>opt(...x,ui.filter)).join('')}</select><select id="gallery-sort" aria-label="画册排序">${[['createdAt','创建时间 ↓'],['updatedAt','最近更新 ↓'],['totalSteps','分镜数量 ↓'],['score','审校评分 ↓']].map(x=>opt(...x,ui.sort)).join('')}</select><div class="view-toggle"><button class="ibtn ${ui.layout==='grid'?'on':''}" data-act="layout" data-layout="grid" aria-label="网格视图">${icon('grid','sm')}</button><button class="ibtn ${ui.layout==='list'?'on':''}" data-act="layout" data-layout="list" aria-label="列表视图">${icon('list','sm')}</button></div></div><div id="gallery-results">${galleryResults()}</div><div class="gallery-note">每一帧，都是故事的一部分。</div>`}

function filteredBooks(){let b=projectBooks().filter(b=>ui.filter==='all'||ui.filter==='starred'&&b.liked||ui.filter==='failed'&&(b.status==='failed'||missingIndices(b).length)||b.status===ui.filter);const q=ui.search.trim().toLowerCase();if(q)b=b.filter(b=>[b.title,b.characterName,b.templateTitle,b.synopsis,...b.tags,...b.steps.map(s=>s.caption)].join(' ').toLowerCase().includes(q));return b.sort((a,b)=>ui.sort==='score'?score(b)-score(a):(b[ui.sort]||0)-(a[ui.sort]||0))}

function galleryResults(){const b=filteredBooks(),n=ui.selected.size;return`${n?`<div class="bulk-bar"><span>已选择 ${n} 本</span>${btn('全选','','select-all','','small')}${btn('星标','star','bulk-star','','small')}${btn('导出','download','bulk-export','','small')}${btn('补齐','refresh','bulk-resume','','small')}${btn('删除','trash','bulk-delete','','small danger')}<div class="spacer"></div>${ibtn('close','clear-selection','取消选择')}</div>`:''}<div class="result-count"><i class="dot" style="width:4px;height:4px;opacity:.55"></i>${b.length} 本画册<span style="margin-left:auto">${esc(project().title)} <span style="opacity:.4;margin-left:5px">/ PRIVATE COLLECTION</span></span></div><div class="gallery-grid ${ui.layout==='list'?'gallery-list':''} ${ui.bulk?'bulk-active':''}">${b.length?b.map(bookCard).join(''):`<div class="empty">${icon('book')}<h3>故事，等待第一帧</h3><p>${ui.search?'试试其他关键词，或清除筛选。':'从一个角色、一份剧本开始，创建你的第一本画册。'}</p>${btn('新建画册','plus','new-book','','primary')}</div>`}</div>`}

function bookCard(b,i){const missing=missingIndices(b),status=b.inProgress?'渲染中':b.status==='complete'&&!missing.length?'已完成':b.status==='generating'?'等待渲染':'待补齐';return`<article class="book-card ${ui.selected.has(b.id)?'selected':''}" style="--i:${i}"><div class="cover" role="button" tabindex="0" data-act="read" data-id="${b.id}" aria-label="阅读 ${esc(b.title)}">${imgTag(coverImage(b),b.title,`data-book="${b.id}" data-step="0" loading="${i<4?'eager':'lazy'}"`)}<div class="cover-top"><span class="cover-status"><i class="dot ${status==='已完成'?'':'amber'}"></i>${status}</span><button class="cover-star ${b.liked?'on':''}" data-act="star" data-id="${b.id}" aria-label="${b.liked?'取消星标':'星标收藏'}">${icon('star')}</button></div><label class="cover-check"><input type="checkbox" data-select-book="${b.id}" ${ui.selected.has(b.id)?'checked':''} aria-label="选择 ${esc(b.title)}"></label><div class="cover-foot"><span class="row" style="gap:4px">${icon('story')}${b.generatedSteps} / ${b.totalSteps} 幕</span><span class="chapter-label">${score(b)?'A / '+score(b).toFixed(1):'IN PROGRESS'}</span></div></div><div class="book-title"><h3>${esc(b.title)}</h3>${ibtn('more','book-menu','画册操作',`data-id="${b.id}"`)}</div><p class="book-desc">${esc(b.synopsis)}</p><div class="book-meta"><span class="character-dot">${esc(b.characterName[0])}</span><span>${esc(b.characterName)}</span><span style="opacity:.4">·</span><span>${esc(b.tags[0]||'原创')}</span><time>${dateFmt(b.createdAt)}</time></div>${missing.length?btn('断点补齐 · '+missing.length+' 帧','refresh','resume',`data-id="${b.id}"`,'resume'):''}</article>`}

function refreshGallery(){if(ui.workspace===0&&$('#gallery-results')){$('#gallery-results').innerHTML=galleryResults();applyArtworkRatios();const books=projectBooks(),scores=books.map(score).filter(Boolean),values=[pad(state.projects.length),pad(books.length),pad(books.reduce((n,b)=>n+b.generatedSteps,0)),scores.length?(scores.reduce((a,b)=>a+b)/scores.length).toFixed(1):'0.0'];$$('.metric strong').forEach((e,i)=>e.textContent=values[i]);const completed=$$('.metric small')[1];if(completed)completed.textContent=books.filter(b=>b.status==='complete').length+' 本已完成';const tabs=$$('.tabbar .tab b');if(tabs[0])tabs[0].textContent=books.length;if(tabs[1])tabs[1].textContent=books.filter(b=>b.liked).length}}

function newBookModal(){flushEditor();if(!projectRows().length||!projectTemplates().length){toast('先为企划创建角色和分镜模板。');navigate(projectTemplates().length?2:1);return}modal('让一个新故事开始',`${field('画册标题',input('title','未命名的夏天','text','id="new-book-title" required'))}${field('主演角色',`<select id="new-book-row">${projectRows().map(r=>opt(r.id,r.character,'')).join('')}</select>`)}${field('叙事模板',templateSelect('new-book-template',ui.templateId))}<div class="notice">角色变量与激活剧情将自动载入。没有专属台词时，使用模板默认旁白。</div><div class="modal-footer">${btn('仅加入队列','plus','create-book')}${btn('创建并开始渲染','play','create-book','data-start="true"','primary')}</div>`,'从一份剧本，到一本属于你的画册。')}

function bookMenu(id){const b=bookBy(id);modal(b.title,`<p class="soft small" style="line-height:1.9">${esc(b.synopsis)}</p><div class="grid2">${btn('进入沉浸阅读','book','read',`data-id="${id}"`)}${btn(b.liked?'取消星标':'星标收藏','star','star',`data-id="${id}"`)}${btn('复制画册概要','copy','copy-book',`data-id="${id}"`)}${btn('剧情版本对比','compare','compare-book',`data-id="${id}"`)}${btn('导出离线画册','download','export-book',`data-id="${id}"`)}${btn('增量补齐缺帧','refresh','resume',`data-id="${id}"`)}</div><div class="divider"></div><div class="row tiny muted"><span>${esc(b.templateTitle)} · ${esc(b.storyTitle||'默认剧情')}</span><span class="spacer"></span>${btn('删除画册','trash','delete-book',`data-id="${id}"`,'small danger')}</div>`,'仅保存在本地工程中，无公开社交功能')}

function compareBook(id){const b=bookBy(id),other=state.books.find(x=>x.id!==id&&x.rowId===b.rowId&&x.templateId===b.templateId);if(!other){toast('此角色与模板目前只有一个画册版本。请生成新的剧情版本再对比。');return}modal('多剧情版本对比',`<div class="compare-grid">${[b,other].map(x=>`<section>${imgTag(coverImage(x),x.title,`data-book="${x.id}" data-step="0"`)}<h3 style="font-size:14px;font-weight:500">${esc(x.storyTitle||x.title)}</h3>${x.steps.map(s=>`<p><span class="mono muted">${pad(s.stepIndex+1)}</span> ${esc(s.caption)}</p>`).join('')}${btn('阅读此版本','book','read',`data-id="${x.id}"`)}</section>`).join('')}</div>`,'同角色 × 同模板，独立剧情演进',true)}

function standardBookLoop(){return `{{#books}}
<article class="cc-book" data-cc-book>
  <header class="cc-cover">
    <p class="cc-eyebrow">MIO / {{layoutName}}</p>
    <h1>{{title}}</h1>
    <p class="cc-synopsis">{{synopsis}}</p>
    <span class="cc-byline">{{characterName}} · {{panelCount}} 幕</span>
  </header>
  <main class="cc-pages" data-cc-pages>
    {{#frames}}
    <figure class="cc-frame" data-cc-frame>
      <img class="cc-image" src="{{image}}" alt="{{name}}">
      <figcaption class="cc-caption" data-cc-caption>
        <span class="cc-scene">{{number}} / {{name}}</span>
        <p>{{caption}}</p>
        <pre class="cc-prompt" data-cc-prompt>{{prompt}}</pre>
        <small class="cc-image-note">{{imageNote}}</small>
        <div class="cc-palette"><i style="background:{{palette1}}"></i><i style="background:{{palette2}}"></i><i style="background:{{palette3}}"></i></div>
      </figcaption>
    </figure>
    {{/frames}}
  </main>
  <footer class="cc-colophon"><span>{{signature}}</span><span>{{date}} / MIO</span></footer>
</article>
{{/books}}`;}

function descriptiveBookMenu(id){
  const b=bookBy(id);if(!b)throw Error('画册不存在。');
  const rows=[['book','read','沉浸阅读','查看画面、台词与逐页精修工具。'],['star','star',b.liked?'取消星标':'加入星标','仅在本地收藏，方便之后快速找到。'],['copy','copy-book','复制画册概要','复制标题、角色、故事概要与标签。'],['compare','compare-book','对比剧情版本','并排查看同角色、同模板的不同剧情。'],['download','export-book','导出离线画册','选择精装版式，生成单文件 HTML。'],['refresh','resume','补齐缺失分镜',missingIndices(b).length?'检测到 '+missingIndices(b).length+' 个待补齐分镜，已完成图片不重跑。':'所有分镜已齐备，无需重复生成。']];
  modal('画册操作',`<div class="book-actions-heading">${imgTag(coverImage(b),b.title,`data-book="${b.id}" data-step="0"`)}<div class="grow"><h3>${esc(b.title)}</h3><p>${esc(b.characterName)} · ${b.generatedSteps} / ${b.totalSteps} 幕<br>${esc(b.synopsis)}</p></div></div>${rows.map(([ic,a,title,sub])=>`<div class="book-action-row"><button class="book-action" data-act="${a}" data-id="${b.id}" ${a==='resume'&&!missingIndices(b).length?'disabled':''}>${icon(ic)}<span class="grow"><strong>${title}</strong><small>${sub}</small></span>${icon('arrow','sm')}</button>${hint(actionHelp[a])}</div>`).join('')}<div class="row" style="padding-top:19px"><span class="tiny muted grow">悬停在 ? 上可查看更完整的操作说明。</span>${btn('移除画册','trash','delete-book',`data-id="${b.id}"`,'small danger')}${hint(actionHelp['delete-book'])}</div>`,'所有操作仅作用于你的私有工程。');
}

function bookDiskPathModal(id){const b=bookBy(id),path=disk.paths.books[id];if(!path||!disk.root){toast('此画册尚未写入目录，请先连接根目录并保存。');return}modal('画册文件位置',`<p class="soft small">${esc(b.title)}</p><div class="disk-path">${esc(disk.root.name)} / ${esc(path)} / 图片</div><p class="help">目录选择器不会向网页提供绝对磁盘路径。你可以在系统文件管理器中打开授权的根目录，再按此相对路径查找。</p><div class="modal-footer">${btn('复制相对路径','copy','copy-disk-path',`data-id="${id}"`,'primary')}</div>`)}

function guideBook(){const p=guidePreferences();return bookBy(p.practiceBookId)||projectBooks()[0]||state.books[0]}

function renderCollectionGallery(){const books=filteredBooks();return `<section class="art-fade"><div class="collection-heading"><div class="grow"><div class="overline">MIO / PRIVATE COLLECTION</div><h1 data-user-content>${esc(project().title)}</h1><p>把故事留在画面里，把时间留给创作。</p></div>${btn('创作新画册','plus','new-book','','primary')}</div><div class="collection-toolbar"><div class="search-field">${icon('search')}<input id="gallery-search" value="${esc(ui.search)}" placeholder="寻找一本画册..." aria-label="搜索画册"></div><span class="spacer"></span><button class="filter-link ${ui.filter==='starred'?'active':''}" data-act="art-star-filter">${icon('star','sm')}星标</button><select id="gallery-filter" aria-label="画册状态">${[['all','所有画册'],['complete','已完成'],['generating','生成中'],['failed','待补齐'],['starred','星标收藏']].map(x=>opt(...x,ui.filter)).join('')}</select><select id="gallery-sort" aria-label="画册排序">${[['manual','手动排序'],['createdAt','最近创建'],['updatedAt','最近修改'],['totalSteps','分镜数量']].map(x=>opt(...x,ui.sort)).join('')}</select>${ibtn('check','toggle-bulk','批量选择与管理')}</div><div id="gallery-results">${artGalleryResults()}</div><p class="collection-note">每一帧，都值得被好好收藏。</p></section>`}

function artGalleryResults(){const books=filteredBooks(),selected=ui.selected.size;const bulk=selected?`<div class="bulk-bar"><span>选中 ${selected} 本</span>${btn('星标','star','bulk-star','','small')}${btn('导出','download','bulk-export','','small')}${btn('删除','trash','bulk-delete','','small danger')}<span class="spacer"></span>${ibtn('close','clear-selection','退出选择')}</div>`:'';const index=`<div class="collection-index"><span>${pad(books.length)} BOOK${books.length===1?'':'S'} / 画册集</span><span>LOCAL FIRST · YOUR WORK, YOUR SPACE</span></div>`;if(!books.length)return bulk+index+`<div class="empty">${icon('book')}<h3>留一点空白，给新的故事。</h3><p>${ui.search?'没有找到匹配的画册，试试其他名字。':'这里还没有画册。可以开始创作，或载入一份十二幕示范。'}</p>${btn('开始创作','plus','new-book','','primary')}${!ui.search?btn('载入精选示范','image','art-import-demo','style="margin-left:10px"'):''}</div>`;
  if(books.length===1&&!ui.bulk&&!selected){const b=books[0];return bulk+index+`<article class="edition-showcase"><button class="edition-image" data-act="read" data-id="${b.id}" aria-label="打开 ${esc(b.title)}">${imgTag(coverImage(b),b.title,`data-book="${b.id}" data-step="0" loading="eager" decoding="async"`)}</button><div class="edition-info"><div class="edition-count">${b.curatedDemo?'THE FIRST EDITION':'A VISUAL STORY'} / ${pad(b.totalSteps)} FRAMES</div><h2 data-user-content>${esc(b.title)}</h2><p class="synopsis" data-user-content>${esc(b.synopsis)}</p><div class="edition-byline" data-user-content>${esc(b.characterName||'原创画册')}</div><div class="edition-entry"><button class="read-link" data-act="read" data-id="${b.id}">翻开这本画册 ${icon('arrow','sm')}</button><span class="spacer"></span><button class="ibtn ${b.liked?'on':''}" data-act="star" data-id="${b.id}" aria-label="${b.liked?'取消星标':'星标收藏'}">${icon('star')}</button>${ibtn('more','book-menu','导出与管理画册',`data-id="${b.id}"`)}</div>${missingIndices(b).length?btn('补齐 '+missingIndices(b).length+' 幕','refresh','resume',`data-id="${b.id}" style="margin-top:20px"`,'small'):''}<div class="edition-credit">MIO<br><span style="display:block;margin-top:9px;opacity:.55">${b.curatedDemo?'CURATED DEMO / PERSONAL PREVIEW':'PRIVATE ARTBOOK'}</span></div></div></article>`}
  return bulk+index+`<div class="collection-grid">${books.map(b=>`<article class="edition-tile"><button class="edition-image" data-act="read" data-id="${b.id}" aria-label="阅读 ${esc(b.title)}">${imgTag(coverImage(b),b.title,`data-book="${b.id}" data-step="0" loading="lazy" decoding="async"`)}</button><div class="edition-tile-footer"><h3 data-user-content>${esc(b.title)}</h3>${ibtn('more','book-menu','画册操作',`data-id="${b.id}"`)}</div><div class="edition-tile-meta">${b.totalSteps} 幕 · ${esc(b.characterName||'原创')}</div>${ui.bulk||selected?`<label class="edition-select"><input type="checkbox" data-select-book="${b.id}" ${ui.selected.has(b.id)?'checked':''}>选择这本画册</label>`:''}</article>`).join('')}</div>`;
}

function selectedLabBook(){return bookBy(artUI.labBookId)||projectBooks()[0]||null}

function renderCollectionSwitcher(){const menu=$('#project-popover'),trigger=$('#project-switch-button');if(!trigger)return;menu.innerHTML=`<div class="project-popover-label row">切换画册集<span class="spacer"></span>${ibtn('close','v3-project-close','关闭画册集菜单')}</div>${state.projects.map(p=>`<button class="project-choice" role="menuitem" data-act="project" data-id="${p.id}" aria-current="${p.id===state.activeProjectId}">${icon('folder','sm')}<span class="grow"><strong data-user-content>${esc(p.title)}</strong><small>${state.books.filter(b=>b.projectId===p.id).length} 本画册</small></span></button>`).join('')}<button class="project-new" role="menuitem" data-act="new-project">${icon('plus','sm')}新建画册集</button><button class="project-choice" role="menuitem" data-act="project-rename">${icon('edit','sm')}重命名当前画册集</button><button class="project-choice" role="menuitem" data-act="delete-collection" data-id="${state.activeProjectId}" style="color:var(--red);border-top:1px solid var(--line);border-radius:0;margin-top:5px">${icon('trash','sm')}删除当前画册集</button>`;const r=trigger.getBoundingClientRect();menu.style.left=clamp(r.left,12,Math.max(12,innerWidth-312))+'px';menu.style.top=(r.bottom+7)+'px';menu.hidden=false;trigger.setAttribute('aria-expanded','true');detailUI.projectOpen=true}

function createCollectionDisplayModel(){
  const validModes=new Set(['showcase','grid']);
  function mode(value){return validModes.has(value)?value:'showcase'}
  function page(total,requested=0,pageSize=24){const size=Math.max(1,Number(pageSize)||24),count=Math.max(0,Number(total)||0),pages=Math.max(1,Math.ceil(count/size)),index=Math.max(0,Math.min(pages-1,Math.floor(Number(requested)||0)));return{index,pages,start:index*size,end:Math.min(count,(index+1)*size),total:count}}
  function fit(width,height,maxWidth,maxHeight,upscale=true){if(![width,height,maxWidth,maxHeight].every(value=>Number.isFinite(value)&&value>0))return{width:0,height:0,scale:0};const scale=Math.min(maxWidth/width,maxHeight/height,upscale?Infinity:1);return{width:width*scale,height:height*scale,scale}}
  return Object.freeze({mode,page,fit});
}

function collectionCoverInfo(book){const frame=[...(book.steps||[])].sort((a,b)=>a.stepIndex-b.stepIndex).find(s=>s.image&&!s.offlineFallback&&!isFallbackImage(s.image));const src=frame?.image||'',dimensions=displayUI.dimensions.get(src);return{frame,src,ratio:dimensions?dimensions.width/dimensions.height:Number(frame?.width)>0&&Number(frame?.height)>0?frame.width/frame.height:4/5}}

function getShelfBooks(){const key=[state.activeProjectId,ui.search,ui.filter,ui.sort].join('|');if(displayUI.filterKey!==key){displayUI.filterKey=key;displayUI.featuredIndex=0;displayUI.page=0}const books=filteredBooks();displayUI.featuredIndex=clamp(displayUI.featuredIndex,0,Math.max(0,books.length-1));displayUI.page=displayModel.page(books.length,displayUI.page).index;return books}

function shelfBookCount(count){return localeString('{count} 本画册',{count})}

function renderResponsiveCollection(){return `<section class="art-fade" id="collection-home"><div class="collection-heading"><div class="grow"><div class="overline">MIO / PRIVATE COLLECTION</div><h1 data-user-content>${esc(project().title)}</h1><p>${localeString('把故事留在画面里，把时间留给创作。')}</p></div>${shelfButton('plus','new-book','创作新画册','','primary')}</div><a class="home-learning" href="/docs/index.html" target="_blank" rel="noopener">${icon('book')}<span><strong>使用教程 · 从这里开始</strong><small>首次生成、图片变量、手机访问与常见问题</small></span><b>打开教程 ↗</b></a><div class="collection-toolbar shelf-toolbar"><div class="search-field">${icon('search')}<input id="gallery-search" value="${esc(ui.search)}" placeholder="${esc(localeString('寻找一本画册...'))}" aria-label="${esc(localeString('搜索画册'))}"></div><span class="spacer"></span><button class="filter-link ${ui.filter==='starred'?'active':''}" data-act="art-star-filter">${icon('star','sm')}${localeString('星标')}</button><select id="gallery-filter" aria-label="${esc(localeString('画册状态'))}">${[['all','所有画册'],['complete','已完成'],['generating','生成中'],['failed','待补齐'],['starred','星标收藏']].map(([id,label])=>opt(id,localeString(label),ui.filter)).join('')}</select><select id="gallery-sort" aria-label="${esc(localeString('画册排序'))}">${[['manual','手动排序'],['createdAt','最近创建'],['updatedAt','最近修改'],['totalSteps','分镜数量']].map(([id,label])=>opt(id,localeString(label),ui.sort)).join('')}</select>${shelfViewSwitch()}${shelfIcon('check','toggle-bulk','批量选择与管理')}</div><div id="gallery-results">${responsiveCollectionResults()}</div><p class="collection-note">${localeString('每一帧，都值得被好好收藏。')}</p></section>`}

function shelfSelectionBar(books){if(!ui.bulk&&!ui.selected.size)return'';const selected=ui.selected.size,all=books.length>0&&books.every(b=>ui.selected.has(b.id));return `<div class="shelf-bulk"><label><input type="checkbox" id="shelf-select-all" ${all?'checked':''} aria-label="${esc(localeString('全部选择'))}">${localeString('全部选择')}</label><span class="grow">${localeString('已选 {count} 本',{count:selected})}</span>${shelfButton('star','bulk-star','星标',selected?'':'disabled','small')}${shelfButton('download','bulk-export','导出',selected?'':'disabled','small')}${shelfButton('trash','bulk-delete','删除',selected?'':'disabled','small danger')}${shelfIcon('close','clear-selection','退出选择')}<small class="selection-instructions">拖过画册批量选择 / 取消 · Esc 退出 · 手机点选复选框</small></div>`}

function responsiveCollectionResults(){
  const books=getShelfBooks(),mode=state.settings.presentation.homeLayout,b=books[displayUI.featuredIndex],paging=displayModel.page(books.length,displayUI.page),bulk=shelfSelectionBar(books),count=`<span>${shelfBookCount(books.length)}</span>`;
  if(!books.length)return `<div class="shelf-index">${count}</div><div class="empty">${icon('book')}<h3>${localeString('留一点空白，给新的故事。')}</h3><p>${localeString(ui.search?'没有找到匹配的画册，试试其他名字。':'这里还没有画册。可以开始创作，或载入一份封面示范。')}</p>${shelfButton('plus','new-book','开始创作','','primary')}${!ui.search?shelfButton('image','art-import-demo','载入精选示范','style="margin-left:10px"'):''}</div>`;
  const navigation=mode==='showcase'?`<div class="shelf-exhibit-nav">${shelfIcon('up','shelf-feature-prev','上一册',displayUI.featuredIndex===0?'disabled':'')}<span class="shelf-counter">${pad(displayUI.featuredIndex+1)} / ${pad(books.length)}</span>${shelfIcon('down','shelf-feature-next','下一册',displayUI.featuredIndex===books.length-1?'disabled':'')}</div>`:`<span class="shelf-context">${paging.start+1} - ${paging.end} / ${books.length}</span>`;
  const prefix=`${bulk}<div class="shelf-index">${count}${navigation}</div>`;
  if(mode==='showcase')return prefix+`<article class="edition-showcase shelf-exhibit ${ui.selected.has(b.id)?'is-selected':''}" data-sort-book="${esc(b.id)}" draggable="true" tabindex="0" aria-label="画册 ${esc(b.title)}，右键管理">${responsiveCover(b,'showcase')}<div class="edition-info"><div class="edition-count">${b.curatedDemo?'THE FIRST EDITION':'A VISUAL STORY'} / ${localeString('{count} 幕',{count:b.totalSteps})}</div><h2 data-user-content>${esc(b.title)}</h2><p class="synopsis" data-user-content>${esc(b.synopsis)}</p><div class="edition-byline" data-user-content>${esc(b.characterName||'')}</div><div class="edition-entry"><button class="read-link" data-act="read" data-id="${b.id}">${localeString('翻开这本画册')} ${icon('arrow','sm')}</button><span class="spacer"></span><button class="ibtn ${b.liked?'on':''}" data-act="star" data-id="${b.id}" aria-label="${esc(localeString(b.liked?'取消星标':'星标收藏'))}">${icon('star')}</button>${shelfIcon('more','book-menu','导出与管理画册',`data-id="${b.id}"`)}</div><div class="shelf-meta-line"><i class="dot ${missingIndices(b).length?'amber':''}"></i><span>${shelfStatus(b)}</span><span style="opacity:.4">/</span><time>${new Date(b.createdAt).toLocaleDateString(displayUI.locale.language==='en'?'en-US':'zh-CN',{year:'numeric',month:'short',day:'numeric'})}</time></div>${missingIndices(b).length?btn(localeString('补齐 {count} 幕',{count:missingIndices(b).length}),'refresh','resume',`data-id="${b.id}" style="margin-top:19px"`,'small'):''}${b.curatedDemo&&b.demoContentRevision===2?`<p class="shelf-import-note">${localeString('仅保留封面示例，十二幕分镜模板仍可用于创作。')}</p>`:''}${ui.bulk||ui.selected.size?`<label class="shelf-select"><input type="checkbox" data-select-book="${b.id}" ${ui.selected.has(b.id)?'checked':''}>${localeString('选择这本画册')}</label>`:''}<div class="edition-credit">MIO<br><span style="display:block;margin-top:8px;opacity:.55">PRIVATE ARTBOOK COLLECTION</span></div></div></article>`;
  const tiles=books.slice(paging.start,paging.end).map((book,i)=>`<article class="shelf-item ${ui.selected.has(book.id)?'is-selected':''}" data-sort-book="${esc(book.id)}" draggable="true" tabindex="0" aria-label="画册 ${esc(book.title)}，右键管理">${responsiveCover(book,'grid',i)}<div class="edition-tile-footer"><h3 data-user-content>${esc(book.title)}</h3><button class="ibtn ${book.liked?'on':''}" data-act="star" data-id="${book.id}" aria-label="${esc(localeString(book.liked?'取消星标':'星标收藏'))}">${icon('star','sm')}</button>${shelfIcon('more','book-menu','画册操作',`data-id="${book.id}"`)}</div><div class="edition-tile-meta"><span>${localeString('{count} 幕',{count:book.totalSteps})}</span><span class="status-label">${shelfStatus(book)}</span><time>${dateFmt(book.createdAt)}</time></div>${ui.bulk||ui.selected.size?`<label class="shelf-select"><input type="checkbox" data-select-book="${book.id}" ${ui.selected.has(book.id)?'checked':''}>${localeString('选择这本画册')}</label>`:''}</article>`).join('');
  return prefix+`<div class="shelf-grid">${tiles}</div>${paging.pages>1?`<nav class="shelf-pages" aria-label="${esc(localeString('第 {current} / {total} 页',{current:paging.index+1,total:paging.pages}))}">${shelfButton('up','shelf-page-prev','上一页',paging.index===0?'disabled':'','small')}<span class="shelf-page-number">${localeString('第 {current} / {total} 页',{current:paging.index+1,total:paging.pages})}</span>${shelfButton('down','shelf-page-next','下一页',paging.index===paging.pages-1?'disabled':'','small')}</nav>`:''}`;
}

function updateCollectionFontStatus(){const label=$('#collection-font-status');if(label)label.textContent=localeString(displayUI.fontStatus==='loaded'?'字体已就绪':displayUI.fontStatus==='loading'?'正在加载字体，当前使用系统字体。':'丰富字体按需下载；离线时自动使用系统字体。');if(label&&displayUI.fontStatus==='fallback')label.textContent=localeString('字体加载不可用，已使用系统字体。')}

function loadCollectionFonts(){if(state.settings.presentation.fonts===false)return;const existing=$('#collection-font-stylesheet');if(existing){void verifyDisplayTypeface();return}displayUI.fontStatus='loading';const link=document.createElement('link');link.id='collection-font-stylesheet';link.rel='stylesheet';link.href='https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,wght@0,400;0,500;1,400&family=DM+Serif+Display:ital@0;1&family=Ma+Shan+Zheng&display=swap';link.onload=()=>void verifyDisplayTypeface();link.onerror=()=>{displayUI.fontStatus='fallback';updateCollectionFontStatus()};$('#art-font-stylesheet')?.addEventListener('load',()=>void verifyDisplayTypeface(),{once:true});document.head.append(link)}

async function deleteCollection(collectionId=state.activeProjectId){
  if(activeJobs()||backendRuntime.loading||disk.busy||disk.connecting)throw Error(localeString('请先等待当前生成、审校、上传或保存任务结束，再删除画册集。'));
  flushEditor();saveStoryInputs();closeProjectPopover();
  const original=state,replacement={id:uid('collection'),title:localeString('未命名画册集'),createdAt:Date.now()},preview=planCollectionRemoval(state,collectionId,replacement),s=preview.summary;
  const description=[s.title,localeString('将移除 {books} 本画册、{plans} 份创作草稿、{templates} 套专属分镜和 {sets} 组设定。',{books:s.books,plans:s.plans,templates:s.templates,sets:s.variableSets}),localeString('关联的角色记录、对话与队列任务也会移除；全局工作流和导出模板保留。'),s.sharedAssets?localeString('另外 {count} 项被其他画册集使用的资产会保留。',{count:s.sharedAssets}):'',s.lastCollection?localeString('这是最后一个画册集，删除后会建立一个新的空白画册集。'):'',localeString('无法撤销，建议先导出备份。磁盘文件的清理由你的后端策略决定。')].filter(Boolean).join('\n\n');
  if(!await confirmAction(localeString('确定删除这个画册集？'),description,localeString('删除画册集')))return;
  if(state!==original||activeJobs()||backendRuntime.loading||disk.busy||disk.connecting)throw Error(localeString('工程在确认期间发生变化，请重新检查后删除。'));
  const deletion=planCollectionRemoval(state,collectionId,replacement);if(JSON.stringify(deletion.summary)!==JSON.stringify(s))throw Error(localeString('工程在确认期间发生变化，请重新检查后删除。'));
  validateState(deletion.next);
  await foundationCancelForBooks(state.books.filter(b=>b.projectId===collectionId).map(b=>b.id));
  if($('#reader').open)closeReader();if($('#modal').open)closeModal();$('#assistant').hidden=true;
  state=deletion.next;ensureStudioState();ui.workspace=0;ui.selected.clear();ui.bulk=false;ui.search='';ui.filter='all';ui.bookId=null;ui.step=0;ui.frameIndex=0;ui.templateId=projectTemplates()[0]?.id;ui.storyTemplateId=ui.templateId;ui.storyRowId=projectRows()[0]?.id;ui.exportIds=[];
  createUI.planId=projectPlans()[0]?.id||null;createUI.setId=projectVariableSets()[0]?.id||null;artUI.labBookId=null;artUI.labIndex=0;studioUI.assistantUndo=null;studioUI.assistantTargetId=null;studioUI.exportDraft=null;displayUI.featuredIndex=0;displayUI.page=0;
  save(true);render();toast(localeString(ComfyComic.sync?.runtime.loaded?'画册集已删除，正在等待后端保存确认。':'画册集已删除；当前尚未连接后端，请保存或导出备份。'));
}
