/* Mio reader: feature-owned UI functions. Loaded before ui.js; initialization remains in app.js. */
'use strict';

function openReader(id){flushEditor();const b=bookBy(id);if(!b)throw Error('画册不存在。');preserveFloating();ui.bookId=id;ui.step=0;renderReader();if(!$('#reader').open)$('#reader').showModal();if(!$('#assistant').hidden)$('#reader').append($('#assistant'))}

function closeReader(){rt.observer?.disconnect();if($('#assistant'))document.body.append($('#assistant'));if($('#toasts'))document.body.append($('#toasts'));$('#reader').close();ui.bookId=null;refreshGallery()}

function renderReader(){const b=bookBy(ui.bookId);if(!b)return;const variants=state.books.filter(x=>x.rowId===b.rowId&&x.templateId===b.templateId&&x.projectId===b.projectId);$('#reader').innerHTML=`<header class="reader-header">${ibtn('close','close-reader','关闭阅读器')}<div class="reader-title grow"><h2>${esc(b.title)}</h2><div class="tiny muted" style="margin-top:5px">${esc(b.characterName)} · ${b.totalSteps} 幕</div></div><select id="reader-version" aria-label="切换剧情画册">${variants.map(x=>opt(x.id,x.storyTitle||x.title,b.id)).join('')}</select><div class="reader-modes">${[['focus','单页'],['manga','Manga 双页'],['webtoon','Webtoon'],['flip','3D 翻页']].map(([v,l])=>btn(l,'','reader-mode',`data-mode="${v}"`,ui.mode===v?'on':'')).join('')}</div>${ibtn('list','toggle-inspector','显示分镜检查器')}${btn('导出画册','download','export-book',`data-id="${b.id}"`,'small reader-export')}</header><div class="reader-layout"><section class="reader-stage"><div class="reader-canvas" id="reader-canvas"></div><div class="reader-pagination">${ibtn('up','page-prev','上一页')}<span id="page-position"></span>${ibtn('down','page-next','下一页')}</div></section><aside class="reader-inspector"><div class="inspector-label row">${icon('story','sm')}分镜检查器 <span class="spacer"></span><span class="mono tiny">${pad(b.totalSteps)} PANELS</span></div>${slots(b).map((s,i)=>`<section class="inspector-step ${i===ui.step?'active':''}" data-inspector="${i}"><button class="inspector-step-head" data-act="reader-step" data-index="${i}">${imgTag(s.image,s.name,`data-page-img="${b.id}:${i}" data-book="${b.id}" data-step="${i}"`)}<span class="grow"><strong>${esc(s.name)}</strong><small>SCENE ${pad(i+1)} ${s.pending?' / PENDING':''}</small></span>${icon('down','sm')}</button><div class="inspector-content"><p class="caption">${esc(s.caption)}</p><div class="row">${btn('审校本页','shield','critique',`data-index="${i}" ${s.pending?'disabled':''}`,'small')}${btn('图片替换','upload','replace-page',`data-index="${i}"`,'small')}</div><div id="critique-${i}">${critiqueHTML(s.critique,i)}</div><div class="divider"></div><label class="label">精修提示词 / REFINEMENT</label><textarea id="refine-${i}" placeholder="描述希望调整的细节...">${esc(s.prompt)}</textarea><div class="row tiny soft" style="margin:12px 0">Denoise <input type="range" min="0" max="1" step=".05" value=".45" id="denoise-${i}" aria-label="重绘强度"><span id="denoise-value-${i}">0.45</span></div><div class="row">${btn('精修重绘','brush','redraw',`data-index="${i}"`,'small primary')}${btn('局部蒙版','edit','mask',`data-index="${i}"`,'small')}</div><div class="help">${state.settings.comfy.mode==='mock'?'离线矢量模拟：输出可复现的新画面。':'局部精修需要绑定图像输入与蒙版工作流。'}</div></div></section>`).join('')}</aside></div>`;renderReaderCanvas()}

function renderReaderCanvas(animate=false){const b=bookBy(ui.bookId);if(!b||!$('#reader-canvas'))return;rt.observer?.disconnect();const list=slots(b),canvas=$('#reader-canvas');ui.step=clamp(ui.step,0,list.length-1);if(ui.mode==='webtoon'){canvas.innerHTML=`<div class="webtoon">${list.map(s=>`<div data-scroll-step="${s.stepIndex}">${pageHTML(b,s)}<div class="page-caption">${esc(s.caption)}</div></div>`).join('')}</div>`;rt.observer=new IntersectionObserver(entries=>{if(Date.now()<(rt.anchorUntil||0))return;const best=entries.filter(x=>x.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(best){ui.step=Number(best.target.dataset.scrollStep);syncInspector()}},{root:canvas,threshold:[.1,.3,.6]});$$('[data-scroll-step]',canvas).forEach(el=>rt.observer.observe(el))}else if(ui.mode==='focus')canvas.innerHTML=`<div class="page-focus">${pageHTML(b,list[ui.step])}</div>`;else{const first=Math.floor(ui.step/2)*2;canvas.innerHTML=`<div class="spread ${ui.mode==='flip'&&animate?'flipping':''}">${pageHTML(b,list[first])}${pageHTML(b,list[first+1])}</div>`}syncInspector()}

function setReaderStep(i){const b=bookBy(ui.bookId);if(!b)return;ui.step=clamp(i,0,b.totalSteps-1);if(ui.mode==='webtoon'){rt.anchorUntil=Date.now()+800;$(`[data-scroll-step="${ui.step}"]`,$('#reader-canvas'))?.scrollIntoView({behavior:'smooth',block:'start'});syncInspector()}else renderReaderCanvas(ui.mode==='flip')}

function readerFrame(book,index){const step=book.steps.find(s=>s.stepIndex===index);if(!step)return{stepIndex:index,name:'尚未生成的分镜',caption:'',prompt:'',image:'',pending:true};const pending=!step.image||step.offlineFallback===true||isFallbackImage(step.image);return{...step,image:pending?'':step.image,pending}}

function readerSequence(book){const byIndex=new Map(book.steps.map(s=>[s.stepIndex,s])),valid=new Map();return Array.from({length:book.totalSteps||book.steps?.length||0},(_,i)=>{const step=byIndex.get(i);if(!step)return{stepIndex:i,name:'尚未生成的分镜',caption:'',prompt:'',image:'',pending:true};if(!valid.has(step.image))valid.set(step.image,!isFallbackImage(step.image));const pending=!step.image||step.offlineFallback===true||!valid.get(step.image);return{...step,image:pending?'':step.image,pending}})}

function readerSpreadIndices(index,total){const start=Math.floor(Math.max(0,index)/2)*2;return[start<total?start:null,start+1<total?start+1:null]}

function openArtReader(id){
  flushEditor();const book=bookBy(id);if(!book)throw Error('这本画册已经不存在。');if(!readerSequence(book).length){modal(book.title,'<div class="empty"><h3>这本画册还没有分镜。</h3><p>先生成或上传画面，再来翻阅。</p></div><div class="modal-footer">'+btn('关闭','','close-modal','','primary')+'</div>');return}
  preserveFloating();$('#assistant').hidden=true;ui.bookId=id;ui.step=0;artUI.showInfo=false;artUI.readerMode=state.settings.presentation.readerModeExplicit?(state.settings.presentation.defaultReaderMode||'gallery'):'gallery';artUI.filmstrip=false;ui.mode=artUI.readerMode==='spread'?'manga':artUI.readerMode==='webtoon'?'webtoon':'focus';
  const dialog=$('#reader');dialog.classList.add('art-reader');dialog.classList.remove('inspect-open');renderArtReader();if(!dialog.open)dialog.showModal();
}

function closeArtReader(){artUI.readerObserver?.disconnect();if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{});for(const id of ['#toasts','#ui-tooltip','#assistant']){const el=$(id);if(el&&$('#reader').contains(el))document.body.append(el)}$('#reader').close();ui.bookId=null;artUI.showInfo=false;refreshGallery()}

function renderArtReader(){
  const b=bookBy(ui.bookId);if(!b)return;artUI.readerObserver?.disconnect();preserveFloating();const versions=state.books.filter(x=>x.rowId===b.rowId&&x.templateId===b.templateId&&x.projectId===b.projectId),sequence=readerSequence(b);ui.step=clamp(ui.step,0,sequence.length-1);
  $('#reader').innerHTML=`<header class="room-head">${ibtn('close','close-reader','关闭画册')}<span class="room-brand">Mio.</span><span class="room-title grow" data-user-content>${esc(b.title)}</span>${versions.length>1?`<select id="reader-version" aria-label="切换此画册的剧情版本">${versions.map(v=>opt(v.id,v.storyTitle||v.title,b.id)).join('')}</select>`:''}<nav class="room-controls" aria-label="阅读模式">${[['spread','book','对开本'],['webtoon','list','卷轴'],['gallery','image','画廊']].map(([mode,ic,label])=>`<button class="${artUI.readerMode===mode?'active':''}" data-act="room-mode" data-mode="${mode}" aria-pressed="${artUI.readerMode===mode}">${label}</button>`).join('')}</nav>${ibtn('expand','room-fullscreen','网页全屏 · 电脑也可使用 F11')}${btn('导出','download','export-book',`data-id="${b.id}"`,'small room-export')}</header><section class="room-stage"><div class="room-canvas" id="reader-canvas"></div><button class="room-open-details" data-act="room-info">${icon('eye')}本幕文字</button><aside class="room-info" id="room-info" ${artUI.showInfo?'':'hidden'} aria-label="当前分镜信息"></aside></section><div class="room-filmstrip" id="room-filmstrip" ${artUI.readerMode==='gallery'||artUI.filmstrip?'':'hidden'} aria-label="分镜缩略图">${(artUI.filmstrip?sequence:[]).map(s=>`<button data-act="reader-step" data-index="${s.stepIndex}" class="${s.stepIndex===ui.step?'active':''}" aria-label="跳到第 ${s.stepIndex+1} 幕：${esc(s.name)}" ${s.stepIndex===ui.step?'aria-current="page"':''}>${imgTag(s.image,s.name,`data-book="${b.id}" data-step="${s.stepIndex}" data-page-img="${b.id}:${s.stepIndex}" loading="lazy" decoding="async"`)}<small>${pad(s.stepIndex+1)}</small></button>`).join('')}</div><footer class="room-footer"><span>PRIVATE READING ROOM</span><span class="spacer"></span><div class="room-pagination">${ibtn('up','page-prev','上一页')}<span class="page-label" id="page-position"></span>${ibtn('down','page-next','下一页')}</div><span class="spacer"></span><span class="room-scene-title" id="room-scene-title" data-user-content></span>${ibtn('story','room-thumbnails','显示或收起分镜胶卷')}${ibtn('eye','room-info','查看本幕文字')}${ibtn('nodes','room-laboratory','到实验室使用精修扩展')}</footer>`;
  const filmstrip=$('#room-filmstrip');if(filmstrip)filmstrip.hidden=!artUI.filmstrip;
  renderArtCanvas(false);
}

function renderArtCanvas(animate=false){
  const book=bookBy(ui.bookId),canvas=$('#reader-canvas');if(!book||!canvas)return;const frames=artUI.readerMode==='gallery'?{length:book.totalSteps||book.steps.length,[ui.step]:readerFrame(book,ui.step)}:readerSequence(book);ui.step=clamp(ui.step,0,frames.length-1);artUI.readerObserver?.disconnect();
  if(artUI.readerMode==='webtoon'){
    canvas.innerHTML=`<div class="room-scroll">${frames.map(s=>`<article data-scroll-step="${s.stepIndex}">${roomPage(book,s)}${artUI.showCaptions?`<div class="scroll-caption" data-user-content>${esc(s.caption)}</div>`:''}</article>`).join('')}</div>`;
    if(window.IntersectionObserver){const visible=new Map();artUI.readerObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting)visible.set(entry.target,entry.intersectionRatio);else visible.delete(entry.target)}if(Date.now()<artUI.readerAnchorUntil)return;const best=[...visible].sort((a,b)=>b[1]-a[1])[0];if(best){ui.step=Number(best[0].dataset.scrollStep);syncArtReader()}},{root:canvas,threshold:[0,.15,.35,.65]});$$('[data-scroll-step]',canvas).forEach(el=>artUI.readerObserver.observe(el))}
    requestAnimationFrame(()=>{if(ui.step>0)scrollRoomTo(ui.step,false)});
  }else if(artUI.readerMode==='gallery')canvas.innerHTML=`<div class="room-focus">${roomPage(book,frames[ui.step])}</div>`;
  else{const [a,b]=readerSpreadIndices(ui.step,frames.length);canvas.innerHTML=`<div class="room-spread ${animate?'turning':''}">${roomPage(book,a===null?null:frames[a])}${roomPage(book,b===null?null:frames[b])}</div>`}
  $$('img',canvas).forEach(img=>{img.addEventListener('load',()=>{if(artUI.showInfo)renderRoomInfo()},{once:true})});
  syncArtReader();
}

function setArtStep(index){const b=bookBy(ui.bookId);if(!b)return;ui.step=clamp(Number(index)||0,0,Math.max(0,b.totalSteps-1));if(artUI.readerMode==='webtoon'){scrollRoomTo(ui.step);syncArtReader()}else renderArtCanvas(true)}

function syncArtReader(){const book=bookBy(ui.bookId);if(!book)return;const [a,b]=readerSpreadIndices(ui.step,book.totalSteps);if($('#page-position'))$('#page-position').textContent=artUI.readerMode==='spread'?pad(a+1)+(b===null?'':' / '+pad(b+1))+' · '+pad(book.totalSteps):pad(ui.step+1)+' / '+pad(book.totalSteps);const frame=readerFrame(book,ui.step);if($('#room-scene-title'))$('#room-scene-title').textContent=frame?.name||'';for(const el of $$('[data-act="reader-step"]',$('#room-filmstrip')||document)){const active=Number(el.dataset.index)===ui.step;el.classList.toggle('active',active);active?el.setAttribute('aria-current','page'):el.removeAttribute('aria-current')}const strip=$('#room-filmstrip'),active=strip?.querySelector('.active');if(strip&&!strip.hidden&&active){const offset=active.offsetLeft-strip.offsetLeft-strip.clientWidth/2+active.clientWidth/2;strip.scrollTo({left:Math.max(0,offset),behavior:'smooth'})}if(artUI.showInfo)renderRoomInfo()}

function readerLabNavigation(){artUI.labBookId=ui.bookId;artUI.labIndex=ui.step;closeArtReader();navigate(7)}
