"""Generate ``mio_client.py`` from the ``/api/v2`` OpenAPI document (no server needs to run).

    python clients/python/generate.py          # rewrite mio_client.py and openapi-v2.json
    python clients/python/generate.py --check  # CI: fail if either is out of date

The client is a single stdlib-only file (urllib), so bots and scripts can vendor it.
"""

from __future__ import annotations

import json
import keyword
import re
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
CLIENT = HERE / "mio_client.py"
BOT_COPY = HERE.parent / "astrbot_mio" / "mio_client.py"  # plugins must be self-contained
SCHEMA = HERE.parent / "openapi-v2.json"
RUNTIME = HERE / "_runtime.py"


def load_schema() -> dict:
    sys.path.insert(0, str(ROOT / "server"))
    from fastapi.testclient import TestClient
    from mio_server.api import create_app
    from mio_server.context import AppContext

    with tempfile.TemporaryDirectory() as tmp:
        ctx = AppContext.create(tmp, memory=True, autostart=False, seed_instance=False)
        try:
            return TestClient(create_app(ctx, serve_web=False)).get("/api/v2/openapi.json").json()
        finally:
            ctx.close()


def py_name(name: str) -> str:
    name = re.sub(r"\W", "_", name)
    return name + "_" if keyword.iskeyword(name) else name


def py_type(schema: dict) -> str:
    kind = schema.get("type")
    return {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
    }.get(kind, "Any")


def method_source(path: str, verb: str, op: dict) -> str:
    params = [p for p in op.get("parameters", []) if p["in"] in ("path", "query")]
    path_params = [p for p in params if p["in"] == "path"]
    query = [p for p in params if p["in"] == "query"]
    body = op.get("requestBody")
    args = ["self"] + [f"{py_name(p['name'])}: {py_type(p.get('schema', {}))}" for p in path_params]
    if body:
        media = next(iter(body.get("content", {"application/json": {}})))
        binary = media != "application/json"
        args.append("body: bytes" if binary else "body: dict | list | None = None")
    if query:
        args.append("*")
        for p in query:
            default = "None" if not p.get("required") else ""
            hint = py_type(p.get("schema", {}))
            args.append(
                f"{py_name(p['name'])}: {hint}" + (f" | None = {default}" if default else "")
            )
    url = re.sub(r"\{(\w+)\}", lambda m: "{_q(" + py_name(m.group(1)) + ")}", path)
    url = f'f"{url}"' if path_params else f'"{path}"'
    doc = (op.get("summary") or op["operationId"]).strip()
    detail = (op.get("description") or "").strip().splitlines()
    lines = wrap(f"    def {op['operationId']}(", args, ") -> Any:", 4)
    lines.append(f'        """{verb.upper()} {path} — {doc}.')
    if detail:
        lines += ["", f"        {detail[0]}"]
    lines.append('        """')
    call = [f'"{verb.upper()}"', url]
    if query:
        pairs = ", ".join(f'"{p["name"]}": {py_name(p["name"])}' for p in query)
        call.append(f"params={{{pairs}}}")
    if body:
        call.append("content=body" if binary else "json=body")
    lines += wrap("        return self._request(", call, ")", 8)
    return "\n".join(lines)


def wrap(head: str, items: list[str], tail: str, indent: int) -> list[str]:
    """One line if it fits in 100 columns, else one item per line (ruff-format style)."""
    line = head + ", ".join(items) + tail
    if len(line) <= 100:
        return [line]
    pad = " " * (indent + 4)
    return [head, *[f"{pad}{item}," for item in items], " " * indent + tail]


def render_client(schema: dict) -> str:
    methods = [
        method_source(path, verb, op)
        for path, ops in schema["paths"].items()
        for verb, op in ops.items()
    ]
    runtime = RUNTIME.read_text(encoding="utf-8")
    header = (
        f'"""Mio API v{schema["info"]["version"]} client — generated by clients/python/generate.py,'
        " do not edit.\n\n"
        "Usage::\n\n"
        "    from mio_client import MioClient\n"
        '    mio = MioClient("http://127.0.0.1:8788", token="mio_tok_…")\n'
        '    series = mio.create_series({"title": "雨夜"})\n'
        '    ep = mio.generate_episode(series["id"], {"sentence": "雨夜的便利店"})\n'
        '    job = mio.render_episode(ep["id"], {"candidates": 1})\n'
        '    mio.wait_job(job["id"])\n'
        '"""\n'
    )
    return formatted(header + runtime + "\n\n" + "\n\n".join(methods) + "\n")


def formatted(source: str) -> str:
    """Canonical layout via ``ruff format`` (a dev dependency of the server)."""
    import subprocess

    args = [sys.executable, "-m", "ruff", "format", "--config", str(HERE.parent / "ruff.toml"), "-"]
    try:
        done = subprocess.run(args, input=source, capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError) as exc:
        raise SystemExit(f"ruff is required (pip install -r server/requirements-dev.txt): {exc}")
    return done.stdout


def main() -> int:
    schema = load_schema()
    outputs = {
        SCHEMA: json.dumps(schema, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        CLIENT: render_client(schema),
    }
    outputs[BOT_COPY] = outputs[CLIENT]
    if "--check" in sys.argv:
        stale = [
            p.name for p, text in outputs.items() if not p.exists() or p.read_text("utf-8") != text
        ]
        if stale:
            print(f"out of date: {', '.join(stale)} — run python clients/python/generate.py")
            return 1
        print("clients up to date")
        return 0
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
