// A single new template: real compiled preview, offline export, motion and accessibility.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,cpSync,readdirSync,readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-afterglow-')),evidence=process.env.MIO_AFTERGLOW_EVIDENCE||path.join(root,'docs/acceptance-2.2/afterglow'),base='http://127.0.0.1:8807';mkdirSync(evidence,{recursive:true});
for(const n of [...readdirSync(root).filter(n=>n.endsWith('.py')),'data','backend','index.html','styles.css','favicon.svg','vendor','js','docs'])cpSync(path.join(root,n),path.join(temp,n),{recursive:true,filter:src=>!['runtime','.cache','.write.lock','secrets.json'].includes(path.basename(src))});
let server,browser,count=0;const errors=[];const check=(label,value)=>{assert.ok(value,label);console.log('PASS '+label);count++};
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('condition timeout')}
try{server=spawn('python',['-u','server.py'],{cwd:temp,env:{...process.env,MIO_PORT:'8807'},stdio:['ignore','pipe','pipe']});let logs='';server.stderr.on('data',d=>logs+=d);await until(async()=>{try{return (await fetch(base+'/api/config')).ok}catch{return false}});
browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>errors.push(e.message));await page.route(/^https:\/\//,r=>r.abort());await page.goto(base);await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));await page.evaluate(()=>Mio.fileLibrary.hydrateAll());
check('exactly one AFTERGLOW is registered and the original presets remain',await page.evaluate(()=>state.exportTemplates.filter(t=>t.id==='export-afterglow').length===1&&['mio-fit','export-paper','export-ink','export-gallery','export-flip'].every(id=>state.exportTemplates.some(t=>t.id===id&&t.builtin))));
check('normalization keeps file-owned older layouts, copies and album choices untouched',await page.evaluate(()=>{const s=clone(state),old=s.exportTemplates.find(t=>t.id==='export-afterglow');old.designRevision=1;old.html=old.html.replace('data-mio-afterglow','data-mio-afterglow data-legacy-sentinel');const copy={...clone(old),id:'my-afterglow',builtin:false};s.exportTemplates.push(copy);s.books[0].presentationTemplateId='export-afterglow';const originalBooks=JSON.stringify(s.books);ensureStudioState(s);const updated=s.exportTemplates.find(t=>t.id==='export-afterglow');return updated.designRevision===1&&updated.html.includes('data-legacy-sentinel')&&s.exportTemplates.find(t=>t.id===copy.id).html===copy.html&&JSON.stringify(s.books)===originalBooks}));
const assets=['coast','cover','station','postcard'].map(n=>'data:image/webp;base64,'+readFileSync(path.join(root,'examples/afterglow',n+'.webp')).toString('base64'));
await page.evaluate(async assets=>{state.queue=[];const b=state.books[0];b.id='afterglow-demo';b.title='风经过的地方';b.synopsis='列车驶过海岸，夏天缓慢地退到身后。\n那些没有寄出的信，终于有了自己的去处。';b.characterName='夏帆 / KAHO';b.storyTitle='海岸线上的四个瞬间';b.curatedDemo=false;delete b.pictureEdits;delete b.nativeReaderMode;delete b.presentationTemplateId;b.coverPresentation={index:1,x:50,y:43,fit:'cover'};b.steps=[];const names=['海岸线以外','未寄出的信','时间停靠的站台','留一小片黄昏'],captions=['风从海上来，带着盐与远方的气息。\n她忽然觉得，告别也可以是一种温柔的开始。','有些话，在纸上待得比夏天更久。\n她把信折好，没有再写下收件人的名字。','列车还会经过这里。只是下一次，\n我们也许已经学会，把想念说得更轻一些。','不用带走整个夏天。\n留下这一点光，就够了。'];for(let i=0;i<assets.length;i++){const image=new Image();image.src=assets[i];await image.decode();b.steps.push({stepIndex:i,name:names[i],caption:captions[i],prompt:'受控演示图，不调用生成服务。',image:assets[i],width:image.naturalWidth,height:image.naturalHeight})}b.totalSteps=4;b.generatedSteps=4;b.status='complete';state.settings.signature='Mio Creative Studio';save(true);if(!await savePythonWorkspace())throw Error('fixture save: '+Mio.sync.runtime.error);openArtReader(b.id)},assets);
await page.locator('.presentation-trigger').click();await page.locator('[data-act="presentation-select"][data-id="export-afterglow"]').click();await page.frameLocator('#presentation-preview').locator('html.ag-enhanced').waitFor();
const frame=page.frameLocator('#presentation-preview');check('fixed enhancement initializes without arbitrary-script consent',!await page.locator('#confirm-dialog').isVisible()&&await frame.locator('body').evaluate(()=>MioAfterglow.frameCount===4));check('preview keeps the original opaque sandbox and network CSP',await page.locator('#presentation-preview').getAttribute('sandbox')==='allow-scripts'&&(await frame.locator('meta[http-equiv="Content-Security-Policy"]').getAttribute('content')).includes("connect-src 'none'"));
await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();await frame.locator('.ag-cover-img').evaluate(i=>i.decode());await page.waitForTimeout(800);await page.screenshot({path:path.join(evidence,'afterglow-reader-cover.png')});
check('new preset uses copper rather than inheriting the untouched previous preset accent',await frame.locator('html').evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--ag-accent').trim()==='#b66b48'));
check('default small text and scene labels meet 4.5:1 contrast on paper',await frame.locator('body').evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=1;const ctx=canvas.getContext('2d');const luminance=c=>{ctx.fillStyle=c;ctx.fillRect(0,0,1,1);const rgb=[...ctx.getImageData(0,0,1,1).data].slice(0,3).map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return rgb.reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0)};const bg=luminance(getComputedStyle(document.body).backgroundColor);return ['.ag-caption-text','.ag-frame-label'].every(sel=>(bg+.05)/(luminance(getComputedStyle(document.querySelector(sel)).color)+.05)>=4.5)}));
check('selected cover is used without reordering story frames',await frame.locator('.ag-cover-img').getAttribute('src')===assets[1]&&await frame.locator('.ag-image').first().getAttribute('src')===assets[0]);
await frame.locator('.ag-image').evaluateAll(a=>Promise.all(a.map(i=>{i.loading="eager";return i.decode()})));check('mixed source sizes receive specific uncropped layouts',await frame.locator('.ag-frame').evaluateAll(a=>a.map(f=>f.dataset.agShape).join(',')==='wide,portrait,square,small'));
// Actual export path, then inspect file:// with all HTTP requests blocked.
const downloadEvent=page.waitForEvent('download');await page.evaluate(()=>void handleAction('presentation-export',{}));const dl=await downloadEvent,dest=path.join(evidence,'余光_AFTERGLOW_演示画册.html');await dl.saveAs(dest);const offline=await browser.newPage({viewport:{width:1440,height:1000}});offline.on('pageerror',e=>errors.push(e.message));let networks=0;await offline.route(/^https?:/,r=>{networks++;return r.abort()});await offline.goto('file://'+dest);await offline.waitForFunction(()=>!!window.MioAfterglow);await offline.locator('.ag-image').evaluateAll(a=>Promise.all(a.map(i=>{i.loading="eager";return i.decode()})));await offline.waitForTimeout(850);check('offline export embeds all four original full-resolution images',await offline.locator('.ag-image').evaluateAll(a=>a.length===4&&a[0].naturalWidth===1376&&a[1].naturalWidth===928&&a[3].naturalWidth===240&&a.every(i=>i.src.startsWith('data:'))));
check('body is one centered image-first column with closely attached captions',await offline.locator('.ag-frame').evaluateAll(fs=>fs.slice(0,3).every(f=>{const img=f.querySelector('.ag-image').getBoundingClientRect(),cap=f.querySelector('.ag-caption').getBoundingClientRect();return Math.abs(img.x+img.width/2-innerWidth/2)<2&&cap.top>=img.bottom&&cap.top-img.bottom<20&&Math.abs(cap.left-img.left)<2&&Math.abs(cap.right-img.right)<2})));check('portrait and square sources no longer switch between tiny and oversized plates',await offline.locator('.ag-image').evaluateAll(a=>{const widths=a.slice(0,3).map(i=>i.getBoundingClientRect().width);return Math.min(...widths)>=760&&Math.max(...widths)/Math.min(...widths)<1.15}));check('body removes decorative ghost numbers, detached plate labels and generic prologue',await offline.locator('.ag-ghost-number,.ag-visual-meta,.ag-prologue').count()===0&&!await offline.locator('.ag-pages').textContent().then(t=>t.includes('A MOMENT IN TIME')));
await offline.screenshot({path:path.join(evidence,'afterglow-cover-desktop.png')});await offline.locator('.ag-frame').first().scrollIntoViewIfNeeded();await offline.waitForTimeout(800);await offline.screenshot({path:path.join(evidence,'afterglow-wide-desktop.png')});
await offline.locator('.ag-frame').nth(1).scrollIntoViewIfNeeded();await offline.waitForTimeout(800);await offline.screenshot({path:path.join(evidence,'afterglow-portrait-desktop.png')});
check('small image stays at or below natural dimensions',await offline.locator('.ag-image').nth(3).evaluate(i=>{const r=i.getBoundingClientRect();return r.width<=i.naturalWidth+1&&r.height<=i.naturalHeight+1}));
await offline.locator('.ag-dock button').filter({hasText:'目次'}).click();check('contents list is complete and does not duplicate content scenes',await offline.locator('.ag-contents-item').count()===4&&await offline.locator('.ag-frame').count()===4);await offline.locator('.ag-contents-item').nth(2).click();await offline.waitForTimeout(600);check('contents navigation closes dialog and seeks selected scene',!await offline.locator('.ag-contents').isVisible()&&await offline.locator('.ag-frame').nth(2).evaluate(e=>Math.abs(e.getBoundingClientRect().top)<100));
await offline.locator('.ag-view').nth(2).click();check('detail view opens with same original image',await offline.locator('.ag-lightbox').isVisible()&&await offline.locator('.ag-light-stage img').evaluate(i=>i.decode().then(()=>i.naturalWidth===768)));await offline.locator('.ag-light-controls button').filter({hasText:'实际尺寸'}).click();check('actual-size view uses native pixel size',await offline.locator('.ag-light-stage img').evaluate(i=>Math.abs(i.getBoundingClientRect().width-i.naturalWidth)<1));await offline.locator('.ag-light-controls button').filter({hasText:'下一帧'}).click();await offline.locator('.ag-light-stage img').evaluate(i=>i.decode());check('detail navigation respects boundaries and correct source',await offline.locator('.ag-light-stage img').evaluate(i=>i.naturalWidth===240)&&await offline.locator('.ag-light-controls button').filter({hasText:'下一帧'}).isDisabled());await offline.keyboard.press('Escape');check('Escape closes detail viewer and restores usable page',!await offline.locator('.ag-lightbox').isVisible());check('dialog has a readable name and returns focus to its trigger',await offline.locator('.ag-lightbox').getAttribute('aria-label')==='细看这一帧'&&await offline.locator('.ag-view').nth(2).evaluate(e=>document.activeElement===e));
await offline.locator('.ag-dock button').filter({hasText:'暗室'}).click();await offline.locator('.ag-frame').nth(1).scrollIntoViewIfNeeded();await offline.waitForTimeout(500);await offline.screenshot({path:path.join(evidence,'afterglow-night-desktop.png')});check('night mode is local and changes presentation palette',await offline.locator('html').getAttribute('data-ag-theme')==='night');await offline.locator('.ag-dock button').filter({hasText:'日光'}).click();
await offline.emulateMedia({reducedMotion:'reduce'});await offline.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await offline.waitForTimeout(200);check('reduced-motion preference cancels active animation and parallax',await offline.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').length===0&&getComputedStyle(document.querySelector('.ag-cover-img')).transform==='none'));
await offline.setViewportSize({width:390,height:844});await offline.screenshot({path:path.join(evidence,'afterglow-cover-mobile.png')});await offline.locator('.ag-frame').first().scrollIntoViewIfNeeded();await offline.screenshot({path:path.join(evidence,'afterglow-story-mobile.png')});check('mobile content has no horizontal overflow',await offline.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await offline.locator('.ag-view').first().click();check('mobile detail image fits visible stage',await offline.locator('.ag-light-stage img').evaluate(i=>{const a=i.getBoundingClientRect(),b=i.parentElement.getBoundingClientRect();return a.width<=b.width+1&&a.height<=b.height+1}));await offline.screenshot({path:path.join(evidence,'afterglow-lightbox-mobile.png')});await offline.keyboard.press('Escape');await offline.locator('.ag-dock button').filter({hasText:'暗室'}).click();await offline.screenshot({path:path.join(evidence,'afterglow-night-mobile.png')});await offline.locator('.ag-dock button').filter({hasText:'日光'}).click();await offline.locator('.ag-ending').scrollIntoViewIfNeeded();await offline.screenshot({path:path.join(evidence,'afterglow-ending-mobile.png')});check('project poem and link remain once at the end',await offline.locator('[data-mio-colophon]').count()===1&&await offline.locator('[data-mio-colophon] a').getAttribute('href')==='https://github.com/lumingya/comfy-comic-studio');check('offline document made no external requests',networks===0);
await offline.setViewportSize({width:1440,height:1000});await offline.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await offline.screenshot({path:path.join(evidence,'afterglow-full-desktop.png'),fullPage:true});
// No JS must still show all content, and mobile long titles cannot push page sideways.
const staticPage=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await staticPage.goto('file://'+dest);check('JavaScript-disabled export remains fully readable',await staticPage.locator('.ag-frame').count()===4&&await staticPage.locator('.ag-frame').last().isVisible()&&!await staticPage.locator('.ag-read').first().isVisible());await staticPage.close();
const variants=await page.evaluate(async()=>{const t=afterglowTemplate(),b=clone(bookBy(ui.bookId));b.title='这是一个非常长的中文画册标题，用来确认精心设计的版式不会在真实内容下被撑坏';b.storyTitle='很长的篇章名称'.repeat(25);b.characterName='很长的角色名称'.repeat(25);b.steps[0].caption='<img src=x onerror=alert(1)>\n'+('一段仍然需要认真排版的旁白。'.repeat(35));b.steps.push({stepIndex:4,name:'尚未生成',caption:'这一幕保留位置。',prompt:'',image:missingArtworkDataURL(),pending:true});b.totalSteps=5;for(const s of b.steps)if(s.image.startsWith('/images/'))s.image=await imageData(s.image);return compileTemplateDocument(t,[b,{...b,title:'第二册',id:'second'}],{showPrompts:true})});const variantFile=path.join(evidence,'afterglow-edge-cases.html');writeFileSync(variantFile,variants);const variant=await browser.newPage({viewport:{width:390,height:844}});await variant.goto('file://'+variantFile);await variant.waitForFunction(()=>!!window.MioAfterglow);check('long titles, escaped captions and multiple books remain safe',await variant.locator('.ag-book').count()===2&&await variant.locator('.ag-frame').count()===10&&await variant.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)&&await variant.locator('img[onerror]').count()===0);check('missing scenes retain explicit placeholders, not fake success',await variant.locator('[data-ag-shape="missing"]').count()===2&&await variant.locator('[data-ag-shape="missing"] .ag-image-note').first().textContent()==='这一幕尚未生成。');await variant.setViewportSize({width:320,height:720});check('narrow 320px layout also wraps long metadata',await variant.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await variant.locator('.ag-view').nth(3).click();await variant.locator('.ag-light-stage img').evaluate(i=>i.decode());await variant.locator('.ag-light-controls button').filter({hasText:'下一帧'}).click();await variant.locator('.ag-light-stage img').evaluate(i=>i.decode());check('detail navigation skips ungenerated scenes instead of treating them as images',(await variant.locator('.ag-zoom-label').textContent()).startsWith('06 / 10'));await variant.keyboard.press('Escape');await variant.close();
// Browser capabilities are progressively enhanced, never required to read the art.
const fallback=await browser.newPage();await fallback.addInitScript(()=>{HTMLDialogElement.prototype.showModal=undefined;window.IntersectionObserver=undefined});await fallback.goto('file://'+dest);await fallback.waitForFunction(()=>!!window.MioAfterglow);check('unsupported dialog/observer hides nonfunctional controls but retains reading',!await fallback.locator('.ag-index-open').first().isVisible()&&!await fallback.locator('.ag-view').first().isVisible()&&await fallback.locator('.ag-read').first().isVisible()&&await fallback.locator('.ag-frame').count()===4);await fallback.close();
await offline.locator('.ag-dock button').filter({hasText:'暗室'}).click();await offline.emulateMedia({media:'print'});check('printing from night mode uses light paper and hides floating controls',!await offline.locator('.ag-dock').isVisible()&&await offline.locator('html').evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--ag-paper').trim()==='#fff'));await offline.emulateMedia({media:'screen'});
check('edited copy may remove decorative nodes without breaking compilation',await page.evaluate(()=>{const t=afterglowTemplate();t.html=t.html.replace(/<span class="ag-art-number"[^>]*>.*?<\/span>/g,'').replace(/<small class="ag-image-note">.*?<\/small>/g,'');return compileTemplateDocument(t,[bookBy(ui.bookId)]).includes('function afterglowRuntime')}));
check('template package roundtrip retains fixed enhancement without custom script permission',await page.evaluate(()=>{const original=afterglowTemplate(),restored=parseExportTemplateFile(JSON.stringify({kind:templateKind,formatVersion:1,template:{...original,builtin:false,source:'import'}}));return restored.enhancement==='mio-afterglow-v1'&&!restored.runtimeScript&&compileTemplateDocument(restored,[bookBy(ui.bookId)]).includes('function afterglowRuntime')}));
await page.evaluate(()=>window.agKeptFrame=document.querySelector('#presentation-preview'));await page.locator('.presentation-trigger').click();await page.locator('.presentation-trigger').click();check('new template preserves prior no-reload drawer guarantee',await page.evaluate(()=>window.agKeptFrame===document.querySelector('#presentation-preview')));
// Dense comic fixtures reuse our generated art with rasterized test dialogue, not user imagery.
const denseAssets=['dense-portrait','dense-square'].map(n=>'data:image/webp;base64,'+readFileSync(path.join(root,'examples/afterglow',n+'.webp')).toString('base64'));
const denseHTML=await page.evaluate(async images=>{const b=clone(bookBy(ui.bookId));b.title='末班车之前';b.synopsis='图内对白与多格画面的阅读排版样例。';b.storyTitle='密集对白 · 连续阅读';b.coverPresentation={index:0,x:50,y:35};b.steps=Array.from({length:24},(_,i)=>({stepIndex:i,name:'第'+(i+1)+'幕：'+(i%2?'最后一班列车，还是没说完的故事':'在站台倒计时结束之前'),caption:i%2?'检票口的灯已经亮起。她收好车票，等一个迟来的回答。':'列车还有三分钟进站。有些话，终于不必再写进信里。',image:images[i%2],width:1024,height:i%2?1024:1408}));b.totalSteps=24;return compileTemplateDocument(afterglowTemplate(),[b])},denseAssets);
const denseFile=path.join(evidence,'余光_密集对白排版样例.html');writeFileSync(denseFile,denseHTML);const dense=await browser.newPage({viewport:{width:1440,height:1100},reducedMotion:'reduce'});dense.on('pageerror',e=>errors.push(e.message));await dense.goto('file://'+denseFile);await dense.waitForFunction(()=>!!window.MioAfterglow);await dense.locator('.ag-image').evaluateAll(a=>Promise.all(a.map(i=>{i.loading='eager';return i.decode()})));
check('24 mixed-ratio comic pages maintain equal readable widths and original proportions',await dense.locator('.ag-image').evaluateAll(a=>a.length===24&&a.every(i=>{const r=i.getBoundingClientRect();return Math.abs(r.width-840)<1&&Math.abs(r.width/r.height-i.naturalWidth/i.naturalHeight)<.001})));
check('dense comic captions stay under their own image with compact next-page spacing',await dense.locator('.ag-frame').evaluateAll(a=>a.slice(0,-1).every((f,i)=>{const c=f.querySelector('.ag-caption').getBoundingClientRect(),image=f.querySelector('.ag-image').getBoundingClientRect(),next=a[i+1].getBoundingClientRect();return c.top>=image.bottom&&c.top-image.bottom<=16&&next.top-c.bottom>=30&&next.top-c.bottom<=45})));
await dense.locator('.ag-frame').first().screenshot({path:path.join(evidence,'dense-portrait-desktop.png')});await dense.locator('.ag-frame').nth(1).screenshot({path:path.join(evidence,'dense-square-desktop.png')});await dense.locator('.ag-caption').first().evaluate(e=>scrollTo({top:scrollY+e.getBoundingClientRect().top-260,behavior:'instant'}));await dense.screenshot({path:path.join(evidence,'dense-transition-desktop.png')});await dense.locator('.ag-dock button').filter({hasText:'暗室'}).click();await dense.screenshot({path:path.join(evidence,'dense-transition-night.png')});await dense.locator('.ag-dock button').filter({hasText:'日光'}).click();
await dense.setViewportSize({width:390,height:844});await dense.locator('.ag-frame').first().evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await dense.screenshot({path:path.join(evidence,'dense-reading-mobile.png')});check('mobile dense pages use the available width without cropping or sideways scrolling',await dense.locator('.ag-image').evaluateAll(a=>document.documentElement.scrollWidth<=innerWidth+1&&a.every(i=>{const r=i.getBoundingClientRect();return r.width>=innerWidth-28&&r.left>=12&&r.right<=innerWidth-12&&Math.abs(r.width/r.height-i.naturalWidth/i.naturalHeight)<.001})));await dense.setViewportSize({width:320,height:720});check('narrow dense comic view also remains inside the page',await dense.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await dense.close();
const nojsDense=await browser.newPage({javaScriptEnabled:false,viewport:{width:1440,height:1000}});await nojsDense.goto('file://'+denseFile);check('equal-width comic layout also works without JavaScript',await nojsDense.locator('.ag-frame').evaluateAll(a=>a.length===24&&a.every(f=>Math.abs(f.getBoundingClientRect().width-840)<1)));await nojsDense.close();
check('no uncaught browser errors',errors.length===0);console.log(`${count} afterglow checks passed`);
}finally{await browser?.close();if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
