import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {chromium} from 'playwright';
const root=process.cwd(),dir=fs.mkdtempSync(path.join(os.tmpdir(),'mio-assembly-ui-')),port=18763,url=`http://127.0.0.1:${port}`;fs.cpSync('data',dir,{recursive:true});const log=fs.openSync('/tmp/mio-assembly-ui-server.log','w');const server=spawn('python',['tests/production_fixture_server.py'],{cwd:root,env:{...process.env,MIO_DATA_DIR:dir,MIO_PORT:String(port),MIO_HOST:'127.0.0.1',MIO_NO_BROWSER:'1'},stdio:['ignore',log,log]});let browser;let checks=0;const check=(x,text)=>{assert.ok(x,text);checks++;console.log('PASS',text)};
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/content')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>globalThis.Mio&&state.templates.length);
 await page.evaluate(async()=>{await connectPythonBackend();state.settings.imageGeneration.profiles.push({id:'controlled',title:'受控验收渠道',provider:'openai',model:'fixture',baseUrl:'https://controlled.invalid/v1',keyMode:'none',protocol:'images'});save();await savePythonWorkspace();navigate(1)});
 check(await page.locator('.assembly-workshop h1').innerText()==='分镜工坊','independent story workshop');check(await page.locator('[data-act="v3-generate-plan"]').count()===0,'no source-owned generate action');
 await page.screenshot({path:'docs/acceptance-assembly/story-desktop.png',fullPage:true,animations:'disabled'});
 const planBefore=await page.evaluate(()=>JSON.stringify(state.creation.plans));await page.getByRole('button',{name:'预设工坊',exact:true}).click();await page.waitForFunction(()=>workshop.view==='presets');check(await page.locator('.settings-group[open]').count()===0,'preset groups collapsed');
 await page.screenshot({path:'docs/acceptance-assembly/presets-desktop.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'新建预设',exact:true}).click();await page.locator('#text-value').fill('独立的蓝色');await page.locator('[data-act="text-submit"]').click();await page.waitForFunction(()=>workshopPreset()?.title==='独立的蓝色');await page.evaluate(async()=>{workshopDraft().variables.push(variableEntry('画风负向','oversaturated'));workshopDraft().dirty=true;await saveWorkshop()});check(await page.evaluate(before=>JSON.stringify(state.creation.plans)===before,planBefore),'preset creation and save never modify album plans');
 await page.getByRole('button',{name:'装配与队列',exact:true}).click();await page.waitForFunction(()=>workshop.view==='production');
 const ids=[];for(let n=0;n<3;n++){await page.getByRole('button',{name:'新建生成任务',exact:true}).click();await page.locator('#designer-channel').selectOption('controlled');await page.getByRole('button',{name:'下一步',exact:true}).click();await page.locator('[data-designer-preset]').first().check();if(n===0){check(await page.locator('[data-designer-preset]').first().getAttribute('role')!=='switch','multi-preset selection remains a checkbox');await page.screenshot({path:'docs/acceptance-assembly/assembly-desktop.png',fullPage:true,animations:'disabled'})}await page.getByRole('button',{name:'下一步',exact:true}).click();await page.locator('#designer-title').fill('独立装配 '+n);await page.getByRole('button',{name:'添加待命任务',exact:true}).click();await page.waitForFunction(n=>workshop.queue.tasks.length===n+1,n);ids.push(await page.evaluate(()=>workshop.queue.tasks.at(-1).id))}
 check(!fs.existsSync(path.join(dir,'controlled-calls.json')),'standby assembly calls no provider');check(!fs.existsSync(path.join(dir,'runtime/preparations'))||fs.readdirSync(path.join(dir,'runtime/preparations')).length===0,'standby assembly executes no Phase 0');
 const card=id=>page.locator(`[data-production-task="${id}"]`);await card(ids[1]).getByRole('button',{name:'开始生成',exact:true}).click();await page.locator('#confirm-yes').click();await page.waitForFunction(id=>workshop.queue.tasks.find(t=>t.id===id)?.status==='complete',ids[1],{timeout:30000});check(await page.evaluate(ids=>workshop.queue.tasks.filter(t=>[ids[0],ids[2]].includes(t.id)).every(t=>t.status==='standby'),ids),'single start leaves both neighbours standby');
 let calls=JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json')));check(calls.length===12,'single card generates exactly its twelve scenes');
 await card(ids[1]).locator('summary').click();await card(ids[1]).locator('[data-act="production-rerun"][data-index="4"]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(id=>workshop.queue.tasks.find(t=>t.id===id).pages[4].attemptCount===2&&workshop.queue.tasks.find(t=>t.id===id).status==='complete',ids[1]);calls=JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json')));check(calls.length===13,'one scene rerun costs exactly one provider call');
 await card(ids[1]).locator('[data-act="production-rerun-tail"][data-index="10"]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(id=>workshop.queue.tasks.find(t=>t.id===id).pages[11].attemptCount===2&&workshop.queue.tasks.find(t=>t.id===id).status==='complete',ids[1]);calls=JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json')));check(calls.length===15,'suffix replay preserves every earlier scene');
 check(await page.locator('[data-act="production-batch"],[data-act="production-reprepare"],[data-act="production-details"],[data-act="production-uncertain-filter"],[data-act="production-uncertain-export"]').count()===0,'retired queue buttons are gone from the cards and the toolbar');
 await card(ids[2]).locator('h2').click({button:'right'});await page.locator('#mio-context-menu').waitFor();check(await page.locator('#mio-context-menu [data-act="production-clone"]').count()===1&&await page.locator('#mio-context-menu [data-act="production-batch"]').count()===0,'task context menu offers clone and drops retired entries');await page.locator('#mio-context-menu [data-act="production-sequence"]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(id=>workshop.queue.tasks.find(t=>t.id===id)?.status==='complete',ids[2]);check(await page.evaluate(id=>workshop.queue.tasks.find(t=>t.id===id).status,ids[0])==='standby','queueing a later task in the lane does not wake the preceding task');
 await card(ids[1]).getByRole('button',{name:'克隆',exact:true}).click();await page.waitForFunction(()=>workshop.queue.tasks.length===4);const cloneId=await page.evaluate(id=>{const i=workshop.queue.tasks.findIndex(t=>t.id===id);return workshop.queue.tasks[i+1].id},ids[1]);check(await page.evaluate(id=>{const t=workshop.queue.tasks.find(t=>t.id===id);return t.status==='standby'&&t.title.endsWith('副本')&&t.pages.every(p=>p.state==='standby')},cloneId),'clone sits behind its source as a fresh standby copy');check(JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json'))).length===27,'cloning never calls the provider');
 await card(cloneId).locator('[data-production-concurrency]').fill('3');await card(cloneId).locator('[data-production-concurrency]').press('Enter');await card(cloneId).locator('[data-production-concurrency]').blur();await page.waitForFunction(id=>workshop.queue.tasks.find(t=>t.id===id)?.concurrency===3,cloneId);check(true,'per-task page concurrency persists');
 await card(cloneId).getByRole('button',{name:'移除',exact:true}).click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>workshop.queue.tasks.length===3);
 await card(ids[0]).locator('h2').click({modifiers:['Control']});await card(ids[1]).locator('h2').click({modifiers:['Control']});check(await page.evaluate(()=>workshop.pickedTasks.size===2),'Ctrl-click selects task cards');await card(ids[1]).locator('h2').click({button:'right'});await page.locator('#mio-context-menu').waitFor();check((await page.locator('#mio-context-menu').innerText()).includes('已选 2 个生成任务'),'multi-selection opens the batch menu');await page.keyboard.press('Escape');await page.keyboard.press('Escape');await page.waitForFunction(()=>workshop.pickedTasks.size===0);
 await card(ids[1]).locator('summary').click();await page.waitForFunction(id=>!workshop.openTasks.has(id),ids[1]);await page.evaluate(()=>{document.querySelector('.production-cards').scrollIntoView({block:'start'});window.scrollBy(0,-90)});const dragFrom=await card(ids[2]).locator('.production-meta').boundingBox(),dragTo=await card(ids[0]).boundingBox();check(dragFrom.y<1000&&dragTo.y>60,'both cards are on screen for the drag');await page.mouse.move(dragFrom.x+30,dragFrom.y+4);await page.mouse.down();await page.mouse.move(dragFrom.x+30,dragFrom.y-30,{steps:4});await page.mouse.move(dragTo.x+200,dragTo.y+16,{steps:10});await page.mouse.up();await page.waitForFunction(id=>workshop.queue.tasks[0].id===id,ids[2]);await page.evaluate(()=>refreshProduction());await page.waitForTimeout(300);check(await page.evaluate(id=>workshop.queue.tasks[0].id===id,ids[2]),'dragging a card reorders the queue and the order persists');
 await card(ids[1]).getByRole('button',{name:'查看画册',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#reader').open);check(await page.evaluate(()=>bookBy(ui.bookId).steps.length)===12,'native generated album opens in the real reader');await page.evaluate(()=>closeReader());
 await page.screenshot({path:'docs/acceptance-assembly/queue-desktop.png',fullPage:true,animations:'disabled'});
 await page.evaluate(()=>{ui.workspace=5;studioUI.settingsTab='appearance';render()});check(await page.locator('[data-preference-category]').count()===3,'general preferences in three groups');check(await page.locator('[data-preference-category="display"] #display-lettering').count()===1,'artistic font retained under display');check(await page.locator('[data-preference-category="reader"] #default-room-view').count()===1,'reader interaction retained');check(await page.locator('[data-preference-category="general"] #interface-language').count()===1,'language retained under general');await page.screenshot({path:'docs/acceptance-assembly/preferences-desktop.png',fullPage:true,animations:'disabled'});
 await page.locator('[data-act="v3-settings-tab"][data-tab="modules"]').click();check(await page.locator('#ws-extensions').getAttribute('role')==='switch','master optional feature is a switch');await page.locator('#ws-extensions').check();await page.waitForFunction(()=>state.settings.studio.visibility.extensions===true);check(await page.evaluate(()=>primaryNavItems().find(x=>x[0]===3)[1]!==primaryNavItems().find(x=>x[0]===7)[1]),'image engine and optional tools have distinct icons');check(await page.locator('#studio-settings-content input[type="checkbox"]:not([role="switch"])').count()===0,'all module enable controls use switches');
 await page.locator('[data-act="v3-settings-tab"][data-tab="themes"]').click();check(await page.locator('#studio-settings-content #interface-language,#studio-settings-content #display-lettering').count()===0,'custom themes contains no base language/font controls');check(await page.locator('#studio-settings-content').innerText().then(s=>s.includes('样式工坊')),'custom theme heading');
 check(await page.evaluate(()=>fileOperationIcon('native-import','upload')==='file-import'&&fileOperationIcon('workshop-export','download')==='file-export'&&paths['file-import']===paths.download&&paths['file-export']===paths.upload),'import inward/export outward without changing network icons');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{ui.workspace=1;workshop.view='production';render()});await page.screenshot({path:'docs/acceptance-assembly/queue-mobile.png',fullPage:true,animations:'disabled'});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile queue has no horizontal overflow');await page.getByRole('button',{name:'新建生成任务',exact:true}).click();await page.screenshot({path:'docs/acceptance-assembly/assembly-mobile.png',fullPage:true,animations:'disabled'});check(await page.evaluate(()=>document.querySelector('#modal').scrollWidth<=document.querySelector('#modal').clientWidth+1),'mobile assembly dialog has no horizontal overflow');await page.getByRole('button',{name:'取消',exact:true}).click();
 await page.reload();await page.waitForFunction(()=>globalThis.Mio&&state.templates.length);await page.evaluate(async()=>{ui.workspace=1;workshop.view='production';await refreshProduction()});check(await page.evaluate(()=>workshop.queue.tasks.length)===3,'tasks survive browser reload');check(errors.length===0,'no browser runtime errors: '+errors.join(';'));
 check(await page.evaluate(()=>state.creation.variableSets.find(p=>p.title==='独立的蓝色')?.entries.find(e=>e.key==='画风负向')?.value)==='oversaturated','generic negative variables survive native save and reload');
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{ui.workspace=1;workshop.view='presets';workshop.presetId=state.creation.variableSets.find(p=>p.title==='独立的蓝色').id;render()});
 await page.locator('details.quiet-advanced summary').click();await page.getByRole('button',{name:'添加节点绑定',exact:true}).click();await page.locator('#preset-binding-node').fill('9');await page.locator('#preset-binding-path').fill('strength_model');await page.locator('#preset-binding-type').selectOption('number');await page.locator('#preset-binding-value').fill('0.65');await page.getByRole('button',{name:'保存绑定',exact:true}).click();await page.getByRole('button',{name:'保存预设',exact:true}).click();await page.waitForFunction(()=>workshopPreset().bindings?.[0]?.type==='number');check(await page.evaluate(()=>workshopPreset().bindings[0].value)==='0.65','LoRA form stores typed numeric binding');
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出',exact:true}).click();const downloaded=await downloadPromise,zip=path.join(dir,'preset.mio.zip');await downloaded.saveAs(zip);check(fs.statSync(zip).size>100,'independent preset exports as a real ZIP');
 const beforePresets=await page.evaluate(()=>state.creation.variableSets.length);const chooserPromise=page.waitForEvent('filechooser');await page.getByRole('button',{name:'导入',exact:true}).click();await(await chooserPromise).setFiles(zip);await page.locator('#confirm-yes').click();await page.waitForFunction(n=>state.creation.variableSets.length===n+1,beforePresets);check(await page.evaluate(()=>workshopPreset().bindings?.[0]?.type)==='number','shared preset round trip preserves LoRA bindings');
 const beforeBooks=await page.evaluate(()=>state.books.length),beforeCalls=JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json'))).length;await page.getByRole('button',{name:'独立试绘',exact:true}).click();await page.locator('#preset-preview-prompt').fill('independent portrait preview');await page.locator('#preset-preview-channel').selectOption('controlled');await page.getByRole('button',{name:'添加待命试绘',exact:true}).click();await page.waitForFunction(()=>workshop.queue.tasks.some(t=>t.purpose==='preview'));check(JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json'))).length===beforeCalls,'preview is standby without model call');const previewId=await page.evaluate(()=>workshop.queue.tasks.find(t=>t.purpose==='preview').id);await card(previewId).getByRole('button',{name:'开始生成',exact:true}).click();await page.locator('#confirm-yes').click();await page.waitForFunction(id=>workshop.queue.tasks.find(t=>t.id===id).status==='complete',previewId);check(JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json'))).length===beforeCalls+1,'standalone preview calls provider exactly once');await card(previewId).getByRole('button',{name:'查看试绘',exact:true}).click();check(await page.locator('#modal-body img').count()===1,'standalone preview opens as image, not album');await page.evaluate(()=>closeModal());await page.evaluate(async()=>{await connectPythonBackend()});check(await page.evaluate(()=>state.books.length)===beforeBooks,'preview never creates an album');
 const albumId=await page.evaluate(id=>workshop.queue.tasks.find(t=>t.id===id).albumId,ids[2]);await page.evaluate(id=>{workshop.syncedAlbums.clear();ui.workspace=0;render()},albumId);await page.waitForFunction(()=>workshop.syncedAlbums.size>0);check(await page.evaluate(id=>!!bookBy(id),albumId),'gallery refresh discovers production albums');
 const count=JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json'))).length;await page.evaluate(()=>handleAction('v3-run-queue',{}));check(await page.evaluate(()=>workshop.view)==='production','old global start redirects to explicit queue');check(JSON.parse(fs.readFileSync(path.join(dir,'controlled-calls.json'))).length===count,'old global start dispatches no model request');check(errors.length===0,'extended flow has no browser errors');
 console.log(`ASSEMBLY ACCEPTANCE: ${checks} checks passed`);
}finally{await browser?.close();server.kill('SIGTERM');fs.closeSync(log);fs.rmSync(dir,{recursive:true,force:true})}
