import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import path from 'node:path';import {tmpdir} from 'node:os';import assert from 'node:assert/strict';
const root=process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-context-')),base='http://127.0.0.1:8856',evidence=path.join(root,'docs/acceptance-2.2');mkdirSync(evidence,{recursive:true});
let browser,p,count=0;const errors=[],check=(name,result)=>{assert.ok(result,name);console.log('PASS '+name);count++};
const server=spawn('python',['-u','server.py'],{cwd:root,env:{...process.env,MIO_PORT:'8856',MIO_DATA_DIR:path.join(temp,'data')},stdio:['ignore','pipe','pipe']});let logs='';server.stderr.on('data',v=>logs+=v);server.stdout.on('data',()=>{});
async function choose(page,selector,file){const [event]=await Promise.all([page.waitForEvent('filechooser'),page.locator(selector).click()]);await event.setFiles(file)}
async function saveDownload(page,selector,name){const [event]=await Promise.all([page.waitForEvent('download'),page.locator(selector).click()]);const file=path.join(temp,name);await event.saveAs(file);return file}
try{
 for(let i=0;i<200;i++){try{if((await fetch(base+'/api/config')).ok)break}catch{}await new Promise(r=>setTimeout(r,30))}
 browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.route(/^https:\/\//,r=>r.abort());await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);
 await p.evaluate(async()=>{createUI.welcomePending=false;state.settings.identity.onboarded=true;guidePreferences().seen=true;document.querySelectorAll('dialog[open]').forEach(x=>x.close());await Mio.fileLibrary.hydrateAll();save();await savePythonWorkspace();render()});
 check('album import appears beside creation on the gallery page',await p.locator('#collection-home [data-act="native-import"][data-kind="albums"]').isVisible());
 await p.evaluate(()=>handleAction('v3-settings-tab',{tab:'connections'}));check('settings keeps maintenance but no single-resource picker/import/export',await p.locator('[data-act="v3-connect-backend"]').count()>0&&await p.locator('#native-share-resource,[data-act="native-import"],[data-act="eco-export-story"]').count()===0);
 await p.evaluate(()=>navigate(1));check('storyboard import and export are in the source story header',await p.locator('.source-story-head [data-act="native-import"]').isVisible()&&await p.locator('.source-story-head [data-act="eco-export-story"]').isVisible());
 const story=await saveDownload(p,'.source-story-head [data-act="eco-export-story"]','story.zip');check('storyboard exports a native self-contained ZIP',readFileSync(story).subarray(0,2).toString()==='PK');
 const oldStoryCount=await p.evaluate(()=>state.templates.length);await choose(p,'.source-story-head [data-act="native-import"]',story);await p.locator('#resource-import-confirm').waitFor();
 check('import inspection does not write before confirmation',await p.evaluate(n=>state.templates.length===n,oldStoryCount));await p.locator('#modal .btn[data-act="close-modal"]').click();check('cancel leaves existing storyboards alone',await p.evaluate(n=>state.templates.length===n,oldStoryCount));
 await choose(p,'.source-story-head [data-act="native-import"]',story);await p.locator('#resource-import-confirm').click();await p.waitForFunction(n=>state.templates.length===n+1,oldStoryCount);check('storyboard import selects a fresh copy without replacing the old one',await p.evaluate(()=>selectedPlan().templateId===ui.templateId&&new Set(state.templates.map(t=>t.id)).size===state.templates.length));
 await p.evaluate(()=>{createUI.tab='settings';render()});const hasAlbumExport=await p.locator('#main [data-act="native-export-settings"]').isVisible();await p.locator('[data-act="preset-library-open"]').click();check('album settings export locally and the separate preset library provides import',hasAlbumExport&&await p.locator('#preset-library [data-act="native-import"]').isVisible());await p.evaluate(()=>closeModal());
 await p.evaluate(async()=>{selectedPlan().variables.push({id:uid('var'),key:'主角参考图',type:'image',value:await storeVariableAsset(defaultCuratedCover(),'参考')});save();render()});
 const variables=await saveDownload(p,'[data-act="native-export-settings"]','variables.zip');const varsInfo=await(await fetch(base+'/api/library/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({zip:readFileSync(variables).toString('base64'),expectedKind:'variables'})})).json();check('variables and Chinese-named image references export with actual owned image bytes',readFileSync(variables).subarray(0,2).toString()==='PK'&&varsInfo.images===1);
 const before=await p.evaluate(()=>({count:state.creation.variableSets.length,entries:JSON.stringify(mergedSettingEntries(selectedPlan()))}));await p.locator('[data-act="preset-library-open"]').click();await choose(p,'#preset-library [data-act="native-import"]',variables);await p.locator('#resource-import-confirm').click();await p.waitForFunction(n=>state.creation.variableSets.length===n+1,before.count);check('variable import creates a preset without applying or overwriting current values',await p.evaluate(s=>JSON.stringify(mergedSettingEntries(selectedPlan()))===s,before.entries));
 await p.evaluate(()=>{closeModal();navigate(0)});await p.locator('[data-act="book-menu"]').first().click();await p.locator('#book-context-menu').waitFor();check('album share export lives in that album’s menu',await p.locator('#book-context-menu [data-act="native-export"]').isVisible());await p.locator('#book-context-menu [data-act="native-export"]').click();const album=await saveDownload(p,'#native-share-download','album.zip');await p.evaluate(()=>closeModal());
 const oldBookCount=await p.evaluate(()=>state.books.length);await choose(p,'#collection-home [data-act="native-import"]',album);await p.locator('#resource-import-confirm').click();await p.waitForFunction(n=>state.books.length===n+1,oldBookCount);await p.locator('#collection-home').waitFor();check('album import is usable from the gallery and allocates a fresh ID',await p.evaluate(()=>new Set(state.books.map(x=>x.id)).size===state.books.length));
 await p.evaluate(()=>{createUI.tab='story';navigate(1)});await choose(p,'.source-story-head [data-act="native-import"]',variables);await p.waitForFunction(()=>[...document.querySelectorAll('.toast')].some(x=>x.innerText.includes('Wrong resource type')||x.innerText.includes('类型')));check('wrong resource kinds are rejected before import',await p.locator('#resource-import-confirm').count()===0||!await p.locator('#modal').evaluate(e=>e.open));
 await p.waitForFunction(()=>document.querySelectorAll('.toast').length===0);
 for(const [width,theme]of[[1440,'dark'],[390,'dark'],[390,'light']]){await p.setViewportSize({width,height:900});await p.evaluate(theme=>{state.settings.studio.appearance.theme=theme;createUI.tab='story';render()},theme);check(`${width} ${theme} storyboard actions fit the viewport`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,`sharing-story-${width}-${theme}.png`)});await p.evaluate(()=>{createUI.tab='settings';render()});check(`${width} ${theme} variable controls fit the viewport`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,`sharing-variables-${width}-${theme}.png`)})}
 check('no uncaught browser errors',errors.length===0);console.log(`\n${count} contextual sharing checks PASS`);
}catch(e){console.error('UI',await p?.evaluate(()=>({workspace:ui.workspace,dialogs:[...document.querySelectorAll('dialog[open]')].map(x=>x.id),toasts:document.querySelector('#toast-region')?.innerText||[...document.querySelectorAll('.toast')].map(x=>x.innerText),active:activeJobs(),body:document.body.innerText.slice(-2200)})));await p?.screenshot({path:'/tmp/mio-context-fail.png'});console.error(errors,logs.slice(-4000));throw e}finally{await browser?.close();if(server.exitCode===null&&server.signalCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
