// Use the actual delivered 2.2.3 archive, not a reconstructed old state.
import {chromium} from 'playwright';import {spawn,spawnSync} from 'node:child_process';import {mkdtempSync,mkdirSync,readFileSync,readdirSync,rmSync} from 'node:fs';import {createHash} from 'node:crypto';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),archive=process.argv[2];assert.ok(archive,'Pass the delivered mio-2.2.3-source.zip');const temp=mkdtempSync(path.join(tmpdir(),'mio-context-upgrade-')),data=path.join(temp,'data'),base='http://127.0.0.1:8884',evidence=path.join(process.cwd(),'docs/acceptance-2.3.0');mkdirSync(evidence,{recursive:true});let server,browser,p,n=0;const errors=[],check=(name,v)=>{assert.ok(v,name);console.log('PASS '+name);n++};
async function stop(){if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}}
async function boot(project){server=spawn('python',['-u',path.join(project,'server.py')],{cwd:project,env:{...process.env,MIO_PORT:'8884',MIO_DATA_DIR:data},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)return}catch{}await new Promise(r=>setTimeout(r,40))}throw Error('startup failed')}
async function page(){p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.settings.identity.onboarded=true;guidePreferences().seen=true})}
function entities(){const result={};for(const dir of ['albums','presets','layouts','storyboards','plans','records','collections','settings','workflows'])for(const file of readdirSync(path.join(data,dir),{recursive:true}))if(file.endsWith('.json'))result[dir+'/'+file]=createHash('sha256').update(readFileSync(path.join(data,dir,file))).digest('hex');return result}
try{
 const unpack=spawnSync('python',['-c',`import sys,zipfile,json,hashlib
with zipfile.ZipFile(sys.argv[1]) as z:
 root=z.namelist()[0].split('/')[0]
 m=json.loads(z.read(root+'/PACKAGE_MANIFEST.json'));assert m['version']=='2.2.3'
 z.extractall(sys.argv[2]);print(sys.argv[2]+'/'+root)`,archive,temp],{encoding:'utf8'});assert.equal(unpack.status,0,unpack.stderr);console.log('Actual baseline SHA256',createHash('sha256').update(readFileSync(archive)).digest('hex'));
 browser=await chromium.launch({args:['--no-sandbox']});await boot(unpack.stdout.trim());await page();
 const art='data:image/webp;base64,'+readFileSync(path.join(root,'examples/afterglow/cover.webp')).toString('base64');
 const fixture=await p.evaluate(async art=>{
  await Mio.fileLibrary.hydrateAll();const b=state.books[0];b.curatedDemo=false;b.totalSteps=1;b.steps=[{stepIndex:0,name:'原始竖图',image:art,width:928,height:1152,prompt:'',caption:''}];delete b.pictureEdits;delete b.nativeReaderMode;delete b.presentationTemplateId;openArtReader(b.id);return{readBook:b.id};
 },art);await p.locator('#reader-canvas img').evaluate(i=>i.decode());check('2.2.3 reproduced: a portrait is taller than the desktop reading viewport',await p.evaluate(()=>$('#reader-canvas img').getBoundingClientRect().height>$('#reader-canvas').clientHeight+200));await p.screenshot({path:path.join(evidence,'baseline-2.2.3-portrait.png')});
 const owned=await p.evaluate(async art=>{
  closeArtReader();const plan=selectedPlan(),t=templateBy(plan.templateId),set=state.creation.variableSets[0];set.title=plan.title='同名也必须区分归属';set.entries.push(variableEntry('private_value','不要覆盖'));
  const image=await storeVariableAsset(art,'原参考图');plan.storyVersionId='';plan.variableSetIds=[];plan.variables=[variableEntry('mood','queued-original'),{id:uid('var'),key:'male_lead',type:'image',value:image}];plan.sceneOverrides={};const f=clone(t.frames[0]);t.frames=[0,1].map(i=>({...clone(f),id:'upgrade-frame-'+i,prompt:'第'+i+'幕 {mood} {male_lead}',negative:'',caption:''}));plan.sceneOverrides[t.frames[1].id]={variables:[variableEntry('mood','scene-specific')]};const g=ensureImageProviders();g.profiles.push({id:'upgrade-only',title:'Never called',provider:'openai',protocol:'chat',model:'test',baseUrl:'http://127.0.0.1:1',keyMode:'none',sendSize:false,sendQuality:false});g.active='upgrade-only';state.settings.comfy.mode='real';
  const b=enqueuePlanSnapshot(plan),q=state.queue.at(-1);q.serverIndices=[0,1];q.serverMeta=q.frames.map((f,i)=>({stepIndex:i,name:f.name,prompt:f._resolvedImagePrompt,caption:''}));q.serverInput={hold:true,owner:q.id,albumId:b.id,label:b.title,frames:q.frames.map((f,i)=>foundationFrameInput(f,q.rowSnapshot,b.id,i))};const job=await foundationRequest('jobs',{idempotencyKey:'actual-223-upgrade-held',input:q.serverInput});q.serverId=job.id;q.status='paused';q.serverAwaitingRelease=false;
  selectSettingPreset(set.id);const draft=settingPresetDraft(set.id);updateUnifiedSetting(draft,'character','原版未应用的私有草稿');plan.variables.find(v=>v.key==='mood').value='plan-edited-after-enqueue';save();if(!await savePythonWorkspace())throw Error(Mio.sync.runtime.error);await pollFoundationJobs();save();if(!await savePythonWorkspace())throw Error(Mio.sync.runtime.error);createUI.tab='settings';navigate(1);
  return{book:b.id,task:q.id,job:job.id,preset:set.id,plan:plan.id};
 },art);
 check('2.2.3 reproduced: the main editor targets a public preset while the global album stays selected',await p.evaluate(()=>!!settingsEditorTarget()._presetEditorId&&$('#main #art-setting-preset')!==null));
 check('2.2.3 reproduced: changed plan variables do not replace queued frame scope',await p.evaluate(id=>selectedPlan().variables.find(v=>v.key==='mood').value==='plan-edited-after-enqueue'&&state.queue.find(q=>q.id===id).frames[0]._scope.mood==='queued-original',owned.task));
 const before=entities();await p.close();await stop();await boot(root);await page();check('upgrade preserves every native entity and settings file byte-for-byte before editing',JSON.stringify(entities())===JSON.stringify(before));
 await p.evaluate(()=>{createUI.tab='settings';navigate(1)});await p.waitForSelector('[data-art-setting="mood"]');check('upgraded main editor restores the selected queued album’s own settings, not the preset or newer plan',await p.locator('[data-art-setting="mood"]').inputValue()==='queued-original'&&await p.locator('#main #art-setting-preset').count()===0);
 await p.locator('[data-act="preset-library-open"]').click();await p.locator('#art-setting-preset').selectOption(owned.preset);check('the old unapplied public preset draft remains intact in the separate library',await p.locator('#preset-library [data-art-setting="character"]').inputValue()==='原版未应用的私有草稿');await p.evaluate(()=>closeModal());
 await p.locator('[data-art-setting="mood"]').fill('upgraded-live-value');await p.evaluate(()=>ComfyComic.sync.save());const result=await p.evaluate(id=>bookBy(id).sourceSnapshot,owned.book);check('an existing queued task gains live settings without rebuilding or abandoning it',result.liveInputs['0'].input.prompt.includes('upgraded-live-value')&&result.liveInputs['1'].input.prompt.includes('scene-specific'));
 check('updating the old album does not alter its source plan or public preset',await p.evaluate(o=>planBy(o.plan).variables.find(v=>v.key==='mood').value==='plan-edited-after-enqueue'&&setBy(o.preset).entries.find(v=>v.key==='private_value').value==='不要覆盖',owned));
 const job=await p.evaluate(id=>foundationRequest('jobs/'+id),owned.job);check('the original held task keeps its identity and zero request attempts',job.id===owned.job&&job.attempts===0&&job.state==='paused');
 await p.evaluate(id=>openArtReader(id),fixture.readBook);await p.waitForFunction(()=>artUI.readingStage?.active);check('the unchanged old portrait now fits completely through the new reader runtime',await p.locator('#reader-canvas img').evaluate(i=>i.getBoundingClientRect().height<=document.querySelector('#reader-canvas').clientHeight));
 check('no browser runtime errors',errors.length===0);console.log(n+' actual 2.2.3 upgrade checks PASS');
}finally{await browser?.close();await stop();rmSync(temp,{recursive:true,force:true})}
