import {chromium} from 'playwright';import {spawn,spawnSync} from 'node:child_process';import {mkdtempSync,existsSync,readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {isDeepStrictEqual} from 'node:util';
const root=process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-complete-')),base='http://127.0.0.1:8862',evidence=path.join(root,'docs/acceptance-2.2');mkdirSync(evidence,{recursive:true});let server,browser,count=0;const errors=[],check=(name,value)=>{assert.ok(value,name);console.log('PASS '+name);count++};
async function stop(){if(server?.exitCode===null&&server.signalCode===null){const d=new Promise(r=>server.once('exit',r));server.kill();await d}server=null}
async function boot(project,data){server=spawn('python',['-u',path.join(project,'server.py')],{cwd:temp,env:{...process.env,MIO_PORT:'8862',MIO_DATA_DIR:data},stdio:['ignore','pipe','pipe']});server.stderr.on('data',()=>{});server.stdout.on('data',()=>{});for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)return}catch{}await new Promise(r=>setTimeout(r,30))}throw Error('Startup failed')}
async function page(){const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>{errors.push(e.message);console.error('BROWSER',e.message)});await p.route(/^https:\/\//,r=>r.abort());await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{createUI.welcomePending=false;state.settings.identity.onboarded=true;guidePreferences().seen=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close())});return p}
async function json(url,body){const r=await fetch(base+url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const value=await r.json();assert.equal(r.status,200,JSON.stringify(value));return value}
try{
 browser=await chromium.launch({args:['--no-sandbox']});
 let p;const existing=path.join(temp,'existing'),oldZip=process.env.MIO_UPGRADE_BASELINE||path.join(root,'.work/upgrade-baseline/mio-2.1.0-source.zip');if(existsSync(oldZip)){const oldRoot=path.join(temp,'old');const extract=spawnSync('python',['-c',`import zipfile,sys\nz=zipfile.ZipFile(sys.argv[1]);z.extractall(sys.argv[2]);print(sys.argv[2]+'/'+z.namelist()[0].split('/')[0])`,oldZip,oldRoot],{encoding:'utf8'});assert.equal(extract.status,0);
 await boot(extract.stdout.trim(),existing);p=await page();const baseline=await p.evaluate(async()=>{state.exportTemplates.find(t=>t.id==='mio-fit').title='用户自定义的留白';state.settings.studio.export.templateId='export-ink';state.books[0].title='升级不能覆盖这本';state.books[0].presentationTemplateId='export-afterglow';save();if(!await savePythonWorkspace())throw Error('save old');return {layouts:clone(state.exportTemplates),id:state.books[0].id}});await p.close();await stop();await boot(root,existing);p=await page();
 await p.evaluate(()=>Mio.fileLibrary.hydrateAll());check('actual delivered 2.1 upgrade keeps edited layouts and choices',isDeepStrictEqual(await p.evaluate(()=>state.exportTemplates),baseline.layouts)&&await p.evaluate(b=>state.settings.studio.export.templateId==='export-ink'&&bookBy(b.id).title==='升级不能覆盖这本'&&bookBy(b.id).presentationTemplateId==='export-afterglow',baseline));
 }else{console.log('SKIP actual 2.1 upgrade: set MIO_UPGRADE_BASELINE to the original delivered ZIP');await boot(root,existing);p=await page()}
 const reg=JSON.parse(readFileSync(path.join(existing,'catalog/index.json')));check('existing workspaces receive data catalogs, not replacement albums',await p.evaluate(()=>state.books.length===1)&&reg.schema==='mio.content.v1');
 // Disk is authoritative: edit a native layout, then delete another. Neither operation is undone by startup.
 const changed=spawnSync('python',['-c',`import json,sys\nfrom pathlib import Path\np=Path(sys.argv[1]);files=list((p/'layouts').glob('*.json'))\nfor f in files:\n d=json.loads(f.read_text())\n if d['id']=='export-seamless': d['title']='来自独立文件';f.write_text(json.dumps(d,ensure_ascii=False))\n if d['id']=='export-gallery': f.unlink()`,existing],{encoding:'utf8'});assert.equal(changed.status,0);await p.reload();await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);check('edited disk template is loaded and deleted built-in is not resurrected',await p.evaluate(()=>{ensureStudioState();return exportTemplateBy('export-seamless').title==='来自独立文件'&&!exportTemplateBy('export-gallery')}));await p.close();await stop();
 const fresh=path.join(temp,'fresh');await boot(root,fresh);p=await page();await p.evaluate(()=>Mio.fileLibrary.hydrateAll());check('fresh installation has real native album, storyboard, preset and seven layouts',await p.evaluate(()=>state.books.length===1&&state.templates[0].frames.length===12&&state.creation.variableSets.length===1&&state.exportTemplates.length===7));
 await p.locator('#collection-home img').first().evaluate(i=>i.decode());check('fresh gallery displays the shipped owned cover',await p.locator('#collection-home img').first().getAttribute('src').then(s=>s.startsWith('/images/library/')));
 const fixture=await p.evaluate(async()=>{const b=state.books[0];b.curatedDemo=false;b.title='排版与源素材往返';const sizes=[[3840,2160],[2160,3840],[240,160]];b.steps=sizes.map(([w,h],i)=>{const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle=['#788f91','#d9b78e','#577a69'][i];x.fillRect(0,0,w,h);x.fillStyle='#eae4d5';x.fillRect(w*.1,h*.1,w*.8,h*.8);return {stepIndex:i,name:'测试'+i,caption:'可保留的配文'+i,prompt:'源提示词'+i,image:c.toDataURL('image/png'),width:999,height:999}});b.totalSteps=b.generatedSteps=3;b.status='complete';state.queue=[];const plan=state.creation.plans[0];plan.variables.push({id:uid('var'),key:'主角参考图',type:'image',value:await storeVariableAsset(defaultCuratedCover(),'参考人物')});save();if(!await savePythonWorkspace())throw Error('save');return {id:b.id,sizes}});
 await p.evaluate(async id=>{await openArtReader(id);presentationUI.templateId='mio-fit';beginExportPreview();renderArtReader()},fixture.id);let frame=p.frameLocator('#presentation-preview');await frame.locator('[data-cc-frame] img').last().waitFor().catch(async e=>{console.log((await p.locator('body').innerText()).slice(-2200));throw e});await frame.locator('img').evaluateAll(a=>Promise.all(a.map(i=>{i.loading='eager';return i.decode()})));
 const view=await frame.locator('body').evaluate(()=>({width:innerWidth,height:innerHeight}));const metrics=async ctx=>{await ctx.locator('body').evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));return ctx.locator('[data-cc-frame] img').evaluateAll(a=>a.map(i=>{const r=i.getBoundingClientRect();return [r.width,r.height]}))};const preview=await metrics(frame);
 await p.locator('summary').filter({hasText:'分享源素材'}).click();await p.locator('#export-embed-storyboard').check();await p.locator('#export-embed-variables').check();const [download]=await Promise.all([p.waitForEvent('download'),p.locator('[data-act="presentation-export"]').click()]);const htmlFile=path.join(temp,'album.html');await download.saveAs(htmlFile);const html=readFileSync(htmlFile,'utf8');
 check('actual UI export includes inert metadata and explicit optional assets',html.includes('mio-album-data')&&html.includes('主角参考图')&&!html.includes('providerConfig'));
 const offline=await browser.newPage({viewport:view});await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+htmlFile);await offline.locator('img').evaluateAll(a=>Promise.all(a.map(i=>{i.loading='eager';return i.decode()})));const exported=await metrics(offline);check('preview and offline original export match at the exact same viewport',preview.every((r,i)=>r.every((n,j)=>Math.abs(n-exported[i][j])<1)));
 check('export retains actual original dimensions, not requested render dimensions',await offline.locator('[data-cc-frame] img').evaluateAll((a,sizes)=>a.every((im,i)=>im.naturalWidth===sizes[i][0]&&im.naturalHeight===sizes[i][1]),fixture.sizes));check('adaptive export keeps each complete original ratio inside its viewport without enlarging small art',exported.every((r,i)=>r[0]<=view.width&&r[1]<=view.height&&Math.abs(r[0]/r[1]-fixture.sizes[i][0]/fixture.sizes[i][1])<.01)&&exported[2][0]<=240);
 await offline.locator('[data-reading-mode="continuous"]').click();await offline.waitForFunction(()=>!document.querySelector('.mio-reading-stage'));const continuous=await metrics(offline);check('explicit continuous mode keeps the shared column and the small-image size ceiling',Math.abs(continuous[0][0]-continuous[1][0])<1&&continuous[2][0]<=240);
 await offline.setViewportSize({width:1440,height:1000});await offline.screenshot({path:path.join(evidence,'original-export-desktop.png')});await offline.setViewportSize({width:390,height:844});await offline.screenshot({path:path.join(evidence,'original-export-mobile.png')});await offline.close();
 let nativeZip,variablesOnlyId;
 for(const [storyboards,variables]of[[false,false],[true,false],[false,true],[true,true]]){
   await p.evaluate(async id=>{await closeReader();exportContextResource('albums',id).catch(e=>console.error(e))},fixture.id);await p.locator('#native-share-download').waitFor();
   assert.equal(await p.locator('#export-embed-storyboard').isChecked(),false);assert.equal(await p.locator('#export-embed-variables').isChecked(),false);
   await p.locator('summary').filter({hasText:'分享源素材'}).click();if(storyboards)await p.locator('#export-embed-storyboard').check();if(variables)await p.locator('#export-embed-variables').check();
   const dl=p.waitForEvent('download');await p.locator('#native-share-download').click();const file=path.join(temp,'native-'+storyboards+'-'+variables+'.zip');await(await dl).saveAs(file);nativeZip=readFileSync(file).toString('base64');
   const info=await json('/api/library/inspect',{zip:nativeZip,expectedKind:'albums'});check(`actual native export independently includes storyboard=${storyboards} variables=${variables}`,info.storyboards===Number(storyboards)&&info.variables===Number(variables));
 }
 await p.close();await stop();
 await boot(root,path.join(temp,'recipient'));p=await page();const dest=await p.evaluate(()=>state.activeProjectId);const malicious=html+'<script>globalThis.ALLOWED_TO_RUN=true</script><iframe src="https://must-not-load.invalid"></iframe>';const info=await json('/api/library/inspect',{html:malicious,expectedKind:'albums'});check('recipient detects storyboard and variables without executing HTML',info.storyboards===1&&info.variables===1&&!(await p.evaluate(()=>globalThis.ALLOWED_TO_RUN)));
 const countResources=c=>[c.savedGalleries.length,c.templates.length,c.uiConfig.comfyStudio.creation.variableSets.length];let previous=countResources(await json('/api/config'));
 for(const [storyboards,variables]of[[false,false],[true,false],[false,true],[true,true]]){const result=await json('/api/library/import',{html,expectedKind:'albums',projectId:dest,include:{storyboards,variables}}),cfg=await json('/api/config'),now=countResources(cfg);check(`independent consent storyboards=${storyboards} variables=${variables}`,now[0]===previous[0]+1&&now[1]===previous[1]+Number(storyboards)&&now[2]===previous[2]+Number(variables));const album=cfg.savedGalleries.find(b=>b.id===result.id);check('imported image belongs to its fresh album '+result.id,album.steps[0].image.startsWith('/images/library/albums/'+result.id+'/images/'));if(storyboards){const plan=cfg.uiConfig.comfyStudio.creation.plans.find(v=>v.rowId===album.rowId);check('new plan references imported source and selected presets',plan.templateId===album.templateId&&plan.variableSetIds.length===Number(variables))}previous=now}
 for(const [storyboards,variables]of[[false,false],[true,false],[false,true],[true,true]]){const result=await json('/api/library/import',{zip:nativeZip,expectedKind:'albums',projectId:dest,include:{storyboards,variables}}),cfg=await json('/api/config'),now=countResources(cfg);check(`native ZIP import independently accepts storyboard=${storyboards} variables=${variables}`,now[0]===previous[0]+1&&now[1]===previous[1]+Number(storyboards)&&now[2]===previous[2]+Number(variables)&&cfg.savedGalleries.some(b=>b.id===result.id));if(variables&&!storyboards)variablesOnlyId=result.id;previous=now}
 await p.reload();await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));check('variables-only import can re-export its reference values without a storyboard',await p.evaluate(async id=>{await Mio.fileLibrary.hydrate(id);return albumSharedSources(bookBy(id),{embedVariables:true}).variables.entries.some(e=>e.key==='主角参考图'&&e.value.src.startsWith('/images/'))},variablesOnlyId));const chooser=p.waitForEvent('filechooser');await p.locator('#collection-home [data-act="native-import"]').click();await(await chooser).setFiles(htmlFile);await p.locator('#resource-import-confirm').waitFor();check('one real import dialog offers two independent default-off choices',await p.locator('#import-include-storyboards').count()===1&&await p.locator('#import-include-variables').count()===1&&!await p.locator('#import-include-storyboards').isChecked()&&!await p.locator('#import-include-variables').isChecked());await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,'import-consent.png')});await p.locator('#modal .btn[data-act="close-modal"]').click();check('cancelling confirmation writes no resource',isDeepStrictEqual(previous,countResources(await json('/api/config'))));
 const bad=html.replace('mio.album-html.v1','mio.album-html.v999');const response=await fetch(base+'/api/library/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({html:bad,expectedKind:'albums',projectId:dest,include:{storyboards:true,variables:true}})});check('unsupported metadata is rejected before writes',response.status===400&&isDeepStrictEqual(previous,countResources(await json('/api/config'))));check('no uncaught browser errors',errors.length===0);console.log(count+' complete-content checks PASS');
}finally{await browser?.close();await stop();rmSync(temp,{recursive:true,force:true})}
