import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const artifacts=process.env.MIO_ARTIFACT_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'mio-refresh-'));
fs.mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch({args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1050}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.MIO_TEST_URL||'http://127.0.0.1:8000');
await page.waitForFunction(()=>typeof openAssemblyDesigner==='function'&&typeof state!=='undefined'&&state.templates.length);
await page.evaluate(()=>{
  const base=projectVariableSets()[0];
  for(let i=0;i<5;i++)state.creation.variableSets.push({...clone(base),id:'selection-fixture-'+i,title:['夜行旅人','水彩电影感','雨夜街道','日光与微风','胶片颗粒'][i]});
  openAssemblyDesigner();
});
await page.screenshot({path:path.join(artifacts,'task-designer.png'),fullPage:true});
assert.equal(await page.locator('.designer-navigation').count(),1);
await page.evaluate(()=>{assemblyDesign.step=1;renderAssemblyDesigner()});
const cards=page.locator('.designer-preset');
console.log('presets',await cards.count());
await cards.nth(0).click();
assert.equal(await page.evaluate(()=>assemblyDesign.presets.size),1);
await cards.nth(1).click({modifiers:['Control']});
assert.equal(await page.evaluate(()=>assemblyDesign.presets.size),2);
// Preset picks are wizard form state: Esc keeps them and closes the wizard like its close button.
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>assemblyDesign.presets.size),2);
assert.equal(await page.evaluate(()=>document.querySelector('#modal').open),false);
await page.evaluate(()=>{openAssemblyDesigner();assemblyDesign.step=1;assemblyDesign.presets=new Set();renderAssemblyDesigner()});
const box=await page.locator('.designer-presets').boundingBox();
await page.mouse.move(box.x+3,box.y+3);await page.mouse.down();await page.mouse.move(box.x+box.width-4,box.y+box.height-4,{steps:15});
assert.equal(await page.locator('.desktop-marquee').count(),1);
await page.mouse.up();
assert.equal(await page.evaluate(()=>assemblyDesign.presets.size),await cards.count());
await page.evaluate(()=>{assemblyDesign.presets=new Set();renderAssemblyDesigner()});
await page.locator('.designer-preset').first().click({modifiers:['Control']});
await page.keyboard.press('Control+a');
assert.equal(await page.evaluate(()=>assemblyDesign.presets.size),await cards.count());
await page.screenshot({path:path.join(artifacts,'task-presets.png'),fullPage:true});
await page.evaluate(()=>{closeModal();navigate(1);workshop.view='stories';render()});
let rows=page.locator('.workshop-frames-list button[data-index]');
await rows.nth(0).click({modifiers:['Control']});
await rows.nth(3).click({modifiers:['Shift']});
assert.equal(await page.evaluate(()=>workshop.pickedFrames.size),4);
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>workshop.pickedFrames.size),0);
// Single click switches the frame and never starts a selection.
await rows.nth(2).click();
assert.equal(await page.evaluate(()=>workshop.frame),2);
assert.equal(await page.evaluate(()=>workshop.pickedFrames.size),0);
await page.evaluate(()=>{mapperUI.railPinned=true;navigate(3)});
const flows=page.locator('#wf-rail-list [data-workflow-id]');
await flows.nth(0).click({modifiers:['Control']});
assert.equal(await page.evaluate(()=>mapperUI.libSel.size),1);
await page.keyboard.press('Control+a');
assert.equal(await page.evaluate(()=>mapperUI.libSel.size),await flows.count());
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>mapperUI.libSel.size),0);
const mappings=page.locator('#wm-binding-rows [data-binding-row]');
if(await mappings.count()){
  await mappings.first().locator('.wf-row-main').click({modifiers:['Control']});
  assert.equal(await page.evaluate(()=>mapperUI.sel.size),1);
  await page.keyboard.press('Control+a');
  assert.equal(await page.evaluate(()=>mapperUI.sel.size),await mappings.count());
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>mapperUI.sel.size),0);
}
await page.evaluate(()=>{navigate(0)});
const books=page.locator('#gallery-results [data-sort-book]');
await books.first().click({modifiers:['Control']});
assert.equal(await page.evaluate(()=>ui.selected.size),1);
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>ui.selected.size),0);
// A single click opens the album.
await books.first().locator('.shelf-cover').click();
await page.waitForFunction(()=>document.querySelector('#reader').open);
await page.evaluate(()=>{document.querySelector('#reader').close();openAssemblyDesigner();assemblyDesign.step=1;renderAssemblyDesigner()});
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
assert.deepEqual(errors,[]);
console.log('PASS designer, presets, frames, workflows, bindings, gallery; single-click open/Ctrl/Shift/Escape/marquee/Ctrl+A; mobile overflow; no runtime errors');
await browser.close();
