import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,readFileSync,mkdtempSync,rmSync,writeFileSync} from 'node:fs';import {spawn,execFileSync} from 'node:child_process';import {tmpdir} from 'node:os';import path from 'node:path';
const temp=mkdtempSync(path.join(tmpdir(),'mio-ecosystem-')),base='http://127.0.0.1:8896',artifacts='docs/acceptance-ecosystem';mkdirSync(artifacts,{recursive:true});
// Avoid modifying the installed extensions directory of the developer workspace.
execFileSync('python',['-c',`import pathlib,shutil,sys\ns=pathlib.Path(sys.argv[1]);d=pathlib.Path(sys.argv[2]);d.mkdir()\nfor name in ['backend','js','vendor','data','docs']:\n shutil.copytree(s/name,d/name,ignore=shutil.ignore_patterns('__pycache__','acceptance*'))\nfor name in ['server.py','styles.css','index.html','favicon.svg']:shutil.copy2(s/name,d/name)`,process.cwd(),temp+'/app']);
const server=spawn('python',['server.py'],{cwd:temp+'/app',env:{...process.env,MIO_HOST:'127.0.0.1',MIO_PORT:'8896',MIO_DATA_DIR:temp+'/data'},stdio:'ignore'});
let browser,p,n=0;const errors=[];const check=(name,v)=>{assert.ok(v,name);console.log('PASS '+name);n++};
async function boot(suffix=''){await p.goto(base+suffix);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting&&typeof ecoState!=='undefined');await p.waitForFunction(()=>ecoState.status.sdkVersion===1);await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.settings.identity.onboarded=true;guidePreferences().seen=true})}
async function view(tab){await p.evaluate(tab=>{studioUI.settingsTab=tab;navigate(5)},tab)}
async function shot(name){await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:artifacts+'/'+name+'.png',fullPage:true})}
try{
 for(let i=0;i<150;i++){try{if((await fetch(base+'/api/content')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1500,height:1000}});p.on('pageerror',e=>errors.push(e.message));await boot();await view('themes');
 check('theme manager and drag target exist',await p.locator('[data-eco-drop="theme"]').count()===1);await shot('01-theme-center');
 const css=readFileSync('examples/themes/orbital-night.css','utf8');
 await p.evaluate(css=>{void importEcosystemFile(new File([css],'orbital.css',{type:'text/css'}),'theme')},css);await p.locator('#confirm-yes').click();await p.waitForFunction(()=>ecoState.status.themes.items.length===1);
 const themeId=await p.evaluate(()=>ecoState.status.themes.items[0].id);await p.locator(`[data-act="eco-theme-use"][data-id="${themeId}"]`).click();await p.waitForSelector('#mio-user-theme',{state:'attached'});
 check('theme hot-applies global horizontal layout',await p.evaluate(()=>document.querySelector('.sidebar').getBoundingClientRect().width>innerWidth*.9));await shot('02-global-theme');
 await boot('/?safe_mode=1');check('safe mode excludes CSS and offers recovery',await p.locator('#mio-user-theme').count()===0&&await p.locator('#mio-safe-recovery').count()===1);await p.evaluate(()=>ecoRequest('reset',{}));await boot();
 const zip=execFileSync('python',['-c',`import io,zipfile,pathlib,base64\nb=io.BytesIO()\nwith zipfile.ZipFile(b,'w') as z:\n for p in pathlib.Path('examples/extensions/scene-notebook').glob('*'):\n  if p.is_file():z.write(p,p.name)\nprint(base64.b64encode(b.getvalue()).decode())`],{encoding:'utf8'}).trim();
 await view('extensions');await p.evaluate(zip=>{const bytes=Uint8Array.from(atob(zip),c=>c.charCodeAt(0));void importEcosystemFile(new File([bytes],'notebook.zip'),'extension')},zip);check('extension import requires trust',await p.locator('#confirm-yes').isVisible());await p.locator('#confirm-yes').click();await p.waitForFunction(()=>ecoState.loaded.has('scene-notebook'));
 check('frontend setup registers namespaced type',await p.evaluate(()=>ecoState.types.has('plugin:scene-notebook:palette')));check('extension reports no startup error',await p.evaluate(()=>ecoState.errors.length===0));await shot('03-extension-center');
 await p.evaluate(()=>{createUI.tab='settings';navigate(1)});await p.locator('[data-act="eco-plugin-action"]').click();await p.locator('[data-act="eco-plugin-panel"]').click();await p.waitForFunction(()=>document.querySelector('#eco-plugin-panel')?.textContent.includes('一次新的创作记录'));check('toolbar calls real Python worker and panel reads persisted data',true);await p.evaluate(()=>closeModal());
 await p.evaluate(async()=>{const ctx=ecoContext('scene-notebook');ctx.on('beforePrepare',()=>{});await ctx.storage.set('ui-prefs',{a:1});window.testPrefs=await ctx.storage.get('ui-prefs')});check('frontend SDK storage and hook contract work',await p.evaluate(()=>testPrefs.a===1));
 await view('extensions');await p.locator('[data-act="eco-extension-toggle"]').click();await p.waitForFunction(()=>!ecoState.loaded.has('scene-notebook'));check('disable unregisters frontend type and backend',await p.evaluate(()=>!ecoState.types.has('plugin:scene-notebook:palette')&&!ecoState.status.extensions[0].enabled));
 await p.evaluate(()=>{createUI.tab='settings';navigate(1);const plan=selectedPlan();plan.variables=[...mergedSettingEntries(plan).filter(e=>e.key!=='macro_deck'),variableEntry('macro_deck','')];plan.variableSetIds=[];settingsChanged(plan);render();macroEditor(plan.id,'macro_deck')});
 await p.locator('#eco-macro-type').selectOption('text');await p.locator('#eco-macro-code').fill('const deck=["SUN","MOON","STAR"];return deck[Math.floor(ctx.random()*deck.length)];');await p.locator('#eco-macro-seed').fill('777');await p.locator('[data-act="eco-macro-save"]').click();check('editor saves computed metadata',await p.evaluate(()=>selectedPlan().variables.find(e=>e.key==='macro_deck').compute.script.includes('ctx.random')));
 await p.evaluate(async()=>{await savePythonWorkspace()});await boot();check('computed metadata survives native save and reload',await p.evaluate(()=>selectedPlan().macroSeed===777&&selectedPlan().variables.find(e=>e.key==='macro_deck').compute.script.includes('ctx.random')));
 await p.evaluate(()=>{window.preparationResult=null;void prepareComputedPlan(selectedPlan()).then(p=>window.preparationResult=p).catch(e=>window.preparationError=e.message)});await p.locator('#confirm-yes').click();await p.waitForFunction(()=>window.preparationResult||window.preparationError);check('real Node preparation completes',await p.evaluate(()=>!!window.preparationResult),await p.evaluate(()=>window.preparationError));
 const first=await p.evaluate(()=>preparationResult.variables.find(e=>e.key==='macro_deck').value);check('resolved clone contains result but no executable script',await p.evaluate(()=>!preparationResult.variables.some(e=>e.compute)));check('source retains script',await p.evaluate(()=>!!selectedPlan().variables.find(e=>e.key==='macro_deck').compute));
 await p.evaluate(()=>{window.preparationResult=null;void prepareComputedPlan(selectedPlan()).then(p=>window.preparationResult=p).catch(e=>window.preparationError=e.message)});await p.locator('#confirm-yes').click();await p.waitForFunction(()=>window.preparationResult);check('same seed returns same cached result',await p.evaluate(()=>preparationResult.variables.find(e=>e.key==='macro_deck').value)===first);
 check('backend marks cache hit',await p.evaluate(async()=>Object.values((await ecoRequest('preparations/'+preparationResult.preparationId)).nodes).some(n=>n.status==='cached')));
 await p.evaluate(()=>{createUI.tab='plans';navigate(1)});check('source toolbar has explicit import/export/new',await p.locator('.source-story-actions [data-act="eco-export-story"]').count()===1&&await p.locator('.source-story-actions [data-act="add-frame"]').count()===1);await shot('04-source-story');
 const sourceId=await p.evaluate(()=>selectedPlan().templateId);await p.evaluate(async()=>{await savePythonWorkspace()});await boot();await p.evaluate(()=>{createUI.tab='plans';navigate(1)});check('owned story ID stays stable after reload',await p.evaluate(()=>selectedPlan().templateId)===sourceId);
 await p.evaluate(()=>{const p=selectedPlan(),prepared=clone(p);prepared.variables=mergedSettingEntries(p).map(e=>({...e,value:e.key==='macro_deck'?'RESOLVED':e.value}));for(const e of prepared.variables)delete e.compute;prepared.variableSetIds=[];prepared._macroPrepared=true;prepared.preparationId='verified-preparation';window.queuedBookId=enqueuePlanSnapshot(prepared).id});
 check('Phase 1 snapshot retains evaluated values and no scripts',await p.evaluate(()=>{const ctx=bookBy(queuedBookId).sourceSnapshot.settingsContext;return ctx.variables.find(e=>e.key==='macro_deck').value==='RESOLVED'&&!ctx.variables.some(e=>e.compute)}));
 await p.evaluate(()=>{selectedPlan().variables.find(e=>e.key==='macro_deck').compute.script='return "CHANGED";';save();render()});
 check('editing source does not change queued computed snapshot',await p.evaluate(()=>bookBy(queuedBookId).sourceSnapshot.settingsContext.variables.find(e=>e.key==='macro_deck').value==='RESOLVED'));
 await p.evaluate(()=>{const p=selectedPlan();state.queue.push({id:'history-fixture',planId:p.id,bookId:'history-book',createdAt:Date.now(),frames:[],indices:[],done:0,status:'complete'});render()});check('global selector only includes source plans',await p.evaluate(()=>[...document.querySelector('#art-book-draft').options].every(o=>!!planBy(o.value))));check('source never binds to generated history',await p.evaluate(()=>creationTask()===null&&liveStoryboardTask(selectedPlan())===null));
 const downloadEvent=p.waitForEvent('download');await p.locator('[data-act="eco-export-story"]').click();const download=await downloadEvent;await download.saveAs(temp+'/export.zip');check('effective storyboard exports real ZIP',readFileSync(temp+'/export.zip').subarray(0,2).toString()==='PK');
 await p.setViewportSize({width:390,height:844});await view('extensions');await shot('05-mobile-extensions');check('mobile ecosystem has no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 await boot('/?safe_mode=1');await view('themes');check('safe recovery remains visible on mobile',await p.locator('#mio-safe-recovery').isVisible());await shot('06-safe-recovery');
 check('no uncaught browser errors',errors.length===0);console.log(`${n} ecosystem assertions PASS`);
}finally{if(browser)await browser.close();server.kill();await new Promise(resolve=>server.exitCode!==null?resolve():server.once('exit',resolve));rmSync(temp,{recursive:true,force:true})}
