/* Isolated end-to-end tests. No paid provider calls, no developer data modified. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {chromium} from 'playwright';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mio-sdk2-')),app=path.join(dir,'app'),base='http://127.0.0.1:18876',evidence='docs/acceptance-extensibility';
fs.mkdirSync(app);fs.mkdirSync(evidence,{recursive:true});
for(const name of ['backend','js','vendor','data'])fs.cpSync(name,path.join(app,name),{recursive:true,filter:p=>!p.includes('__pycache__')});
for(const name of ['server.py','index.html','styles.css','favicon.svg'])fs.copyFileSync(name,path.join(app,name));
const log=fs.openSync(path.join(dir,'server.log'),'w'),server=spawn('python',['server.py'],{cwd:app,env:{...process.env,MIO_HOST:'127.0.0.1',MIO_PORT:'18876',MIO_DATA_DIR:path.join(dir,'data')},stdio:['ignore',log,log]});
let browser,count=0;const errors=[];
const check=(value,label)=>{assert.ok(value,label);console.log('PASS '+label);count++};
const zip=folder=>execFileSync('python',['-c',`import io,zipfile,pathlib,base64,sys\nb=io.BytesIO()\nr=pathlib.Path(sys.argv[1])\nwith zipfile.ZipFile(b,'w') as z:\n for p in r.rglob('*'):\n  if p.is_file():z.write(p,p.relative_to(r))\nprint(base64.b64encode(b.getvalue()).decode())`,folder],{encoding:'utf8'}).trim();
try{
  let ready=false;for(let i=0;i<150;i++){try{if((await fetch(base+'/api/content')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}assert.ok(ready,'fixture ready');
  browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));
  await p.route(/^https?:\/\//,r=>new URL(r.request().url()).origin===base?r.continue():r.abort());
  const boot=async(suffix='')=>{await p.goto(base+suffix);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting&&typeof customization!=='undefined'&&customization.loaded);await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.settings.identity.onboarded=true;guidePreferences().seen=true})};
  await boot();check(await p.evaluate(()=>Mio.extensions.apiVersion===2),'SDK 2 public API');
  await p.evaluate(()=>{studioUI.settingsTab='themes';navigate(5)});await p.locator('[data-act="custom-open"]').click();
  await p.locator('[data-custom-token="--accent"]').fill('#123456');await p.locator('[data-act="custom-add"]').click();
  await p.locator('#custom-name').fill('测试自由 CSS');await p.locator('#custom-css').fill('body { --test-free-css: hello; }\n[data-mio-part="workspace"] { border-top: 3px solid rgb(18,52,86); }');
  check(await p.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--test-free-css').trim()===''),'draft does not execute CSS');
  await p.locator('[data-act="custom-preview"]').click();check(await p.evaluate(()=>customization.preview===null),'preview requires explicit trust');
  await p.locator('#custom-trust').check();await p.locator('[data-act="custom-preview"]').click();await p.waitForSelector('#mio-style-preview-recovery',{state:'attached'});
  check(await p.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--test-free-css').trim()==='hello'),'preview executes complete stylesheet');
  await p.evaluate(()=>customizationStopPreview());check(await p.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--test-free-css').trim()===''),'preview rollback removes CSS');
  await p.clock.install();await p.locator('[data-act="custom-preview"]').click();await p.waitForSelector('#mio-style-preview-recovery',{state:'attached'});await p.clock.fastForward(31000);check(await p.evaluate(()=>customization.preview===null),'30-second trial automatically rolls back');
  await p.locator('[data-act="custom-preview"]').click();await p.waitForSelector('#mio-style-preview-recovery',{state:'attached'});await p.keyboard.press('Escape');check(await p.evaluate(()=>customization.preview===null),'Escape immediately cancels preview');await p.evaluate(()=>customizationOpen());await p.locator('#custom-trust').check();
  await p.locator('#custom-enabled').check();await p.locator('[data-act="custom-save"]').click();await p.waitForFunction(()=>customization.record.revision===1);
  check(await p.evaluate(()=>getComputedStyle(document.documentElement).getPropertyValue('--accent').trim()==='#123456'),'CSSOM design tokens applied');
  await p.locator('.customization-heading').scrollIntoViewIfNeeded();await p.screenshot({path:evidence+'/style-workbench-desktop.png',animations:'disabled'});
  await p.evaluate(()=>closeModal());await boot();check(await p.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--test-free-css').trim()==='hello'),'styles survive reload');
  await p.evaluate(()=>customizationOpen());await p.locator('#custom-scope').selectOption('workspace:creation');await p.locator('#custom-trust').check();await p.locator('[data-act="custom-save"]').click();await p.waitForFunction(()=>customization.record.revision===2);await p.evaluate(()=>closeModal());
  check(await p.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--test-free-css').trim()===''),'workspace scope inactive outside creation');
  await p.evaluate(()=>navigate(1));check(await p.evaluate(()=>getComputedStyle(document.body).getPropertyValue('--test-free-css').trim()==='hello'),'workspace scope activates during navigation');
  await p.evaluate(()=>customizationOpen());await p.locator('details').filter({hasText:'历史版本（'}).locator('summary').click();await p.locator('[data-act="custom-history"][data-revision="1"]').click();
  check(await p.locator('#custom-scope').inputValue()==='global','history restores into draft only');
  const conflict=await p.evaluate(async()=>{const current=await ecoRequest('customization');await ecoRequest('customization',{revision:current.revision,document:{...current.document,enabled:false}});try{await ecoRequest('customization',{revision:current.revision,document:current.document,trusted:true})}catch(e){return e.message}});
  check(conflict.includes('another window'),'stale save detects multi-window conflict');
  await p.setViewportSize({width:390,height:844});await p.locator('.customization-heading').scrollIntoViewIfNeeded();await p.screenshot({path:evidence+'/style-workbench-mobile.png',animations:'disabled'});
  check(await p.evaluate(()=>document.querySelector('#modal').scrollWidth<=document.querySelector('#modal').clientWidth+1),'mobile editor has no horizontal overflow');
  await p.evaluate(()=>{customization.dirty=false;closeModal()});await p.setViewportSize({width:1440,height:1000});
  // Install through management API (same operation used by the trust-confirmed UI).
  const data=zip('examples/extensions/studio-toolkit');await p.evaluate(async zip=>{await ecoRequest('extensions/install',{zip,trusted:true});await refreshEcosystem();render()},data);
  check(await p.evaluate(()=>extensionRuntime().list('commands').length===2),'real SDK 2 package registers commands');
  await p.locator('[data-act="ext-workspace"]').click();await p.locator('button').filter({hasText:/^保存便签$/}).waitFor();await p.waitForFunction(()=>!document.querySelector('[data-extension-mount="studio-toolkit:desk"] button').disabled);
  await p.getByLabel('创作便签').fill('我的第一份持久笔记');await p.getByRole('button',{name:'保存便签',exact:true}).click();await p.getByText('已保存到本机。',{exact:true}).waitFor();
  await p.getByLabel('创作便签').fill('尚未保存的笔记');await p.evaluate(()=>render());check(await p.getByLabel('创作便签').inputValue()==='尚未保存的笔记','custom workspace preserves its DOM during host rerender');
  await p.screenshot({path:evidence+'/extension-workspace.png',animations:'disabled'});
  await p.evaluate(()=>navigate(9));await p.keyboard.press('Control+Shift+Y');await p.getByLabel('创作便签').waitFor();await p.waitForFunction(()=>document.querySelector('[aria-label="创作便签"]').value==='我的第一份持久笔记');check(true,'shortcut opens workspace and loads isolated storage');
  await p.evaluate(()=>navigate(1));check(await p.locator('[data-mio-slot="workspace.after"]').count()===1,'real UI slot mounts in creation');
  await p.evaluate(()=>render());check(await p.locator('[data-mio-slot="workspace.after"]').count()===1,'render does not duplicate slots');
  await p.evaluate(()=>{const ctx=ecoContext('studio-toolkit');ctx.on('production:beforeRequest',event=>{event.cancel=true})});
  let posted=false;p.on('request',r=>{if(r.url().includes('/api/production/assemble')&&r.method()==='POST')posted=true});
  const blocked=await p.evaluate(async()=>{try{await productionRequest('assemble',{title:'not submitted'})}catch(e){return e.message}});check(blocked.includes('取消')&&!posted,'production before-hook cancels before HTTP side effects');
  await p.evaluate(async()=>{await ecoRequest('extensions/enable',{id:'studio-toolkit',enabled:false});await refreshEcosystem();render()});
  check(await p.evaluate(()=>extensionRuntime().list('commands').length===0&&extensionRuntime().list('hooks').length===0&&document.querySelectorAll('[data-extension-owner], [data-extension-style]').length===0),'disable cleans registrations, mounts, styles and hooks');
  await p.evaluate(async()=>{await ecoRequest('extensions/enable',{id:'studio-toolkit',enabled:true,trusted:true});await refreshEcosystem();render()});
  check(await p.evaluate(()=>extensionRuntime().list('commands').length===2),'re-enable creates fresh registrations');
  await p.evaluate(async()=>{await v3Actions['ext-reload']({id:'studio-toolkit'})});check(await p.evaluate(()=>extensionRuntime().list('commands').length===2),'reload does not duplicate commands');
  await p.keyboard.press('Control+Shift+P');await p.locator('#extension-command-search').fill('统计');check(await p.locator('#extension-command-list .extension-command').count()===1,'command palette searches registered commands');await p.evaluate(()=>closeModal());
  await p.evaluate(()=>{window.panelCleaned=0;ecoContext('studio-toolkit').panels.register({id:'cleanup-check',title:'Cleanup',render(root){root.textContent='Mounted';return ()=>window.panelCleaned++}});v3Actions['ext-panel']({id:'studio-toolkit:cleanup-check'});});
  await p.waitForFunction(()=>document.querySelector('#eco-plugin-panel')?.textContent==='Mounted');await p.evaluate(()=>modal('Replacement','<p>replaced</p>'));await p.waitForFunction(()=>window.panelCleaned===1);check(true,'replacing a modal disposes its extension panel');await p.evaluate(()=>closeModal());
  const broken=path.join(dir,'broken');fs.mkdirSync(broken);fs.writeFileSync(path.join(broken,'mio.extension.json'),JSON.stringify({id:'broken-setup',name:'Broken fixture',version:'1',apiVersion:2}));fs.writeFileSync(path.join(broken,'index.js'),`export default function(ctx){ctx.commands.register({id:'partial',label:'Never retained',run(){}});ctx.styles.add('body{--broken:1}');throw Error('fixture setup failure');}`);
  await p.evaluate(async zip=>{await ecoRequest('extensions/install',{zip,trusted:true});await refreshEcosystem();render()},zip(broken));
  check(await p.evaluate(()=>ecoState.loaded.get('broken-setup')?.failed&&!extensionRuntime().owners.has('broken-setup')&&!extensionRuntime().list('commands').some(c=>c.owner==='broken-setup')&&!document.querySelector('[data-extension-style="broken-setup"]')),'failed setup rolls back partial registrations and CSS');
  check(await p.evaluate(()=>extensionRuntime().errors.some(e=>e.owner==='broken-setup'&&e.phase==='setup')),'failed setup is attributed in diagnostics');
  await p.evaluate(async()=>{await ecoRequest('extensions/enable',{id:'broken-setup',enabled:false});await refreshEcosystem();render()});
  const theme=zip('examples/themes/unrestricted-atelier');await p.evaluate(async data=>{await ecoRequest('themes/install',{data,filename:'atelier.zip',trusted:true});await ecoRequest('themes/select',{id:'unrestricted-atelier'});await refreshEcosystem();render()},theme);
  await p.waitForFunction(()=>getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()==='#f3f0e8');check(true,'trusted theme supports package-relative @import');
  check((await p.request.get(base+'/theme-assets/unrestricted-atelier/palette.css')).ok(),'theme asset route serves CSS');check(!(await p.request.get(base+'/theme-assets/unrestricted-atelier/mio.theme.json')).ok(),'theme route does not expose arbitrary files');
  await boot('/?safe_mode=1');check(await p.evaluate(()=>!document.querySelector('#mio-user-theme')&&!document.querySelector('[data-mio-custom-style]')&&extensionRuntime().owners.size===0),'safe mode blocks all custom CSS and frontend extensions');
  await p.evaluate(()=>ecoRequest('reset',{}));await boot();check(await p.evaluate(()=>!customization.record.document.enabled&&!ecoState.status.themes.active&&!ecoState.status.extensions.some(p=>p.enabled)),'safe reset disables theme, custom styles and plugins without deleting source');
  check(await p.evaluate(()=>customization.record.document.snippets.length===1),'safe reset preserves CSS source');
  check(errors.length===0,'zero browser exceptions: '+errors.join('; '));
  fs.writeFileSync(evidence+'/results.json',JSON.stringify({checks:count,status:'passed',browserErrors:errors},null,2));console.log('EXTENSIBILITY: '+count+' checks PASS');
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}fs.closeSync(log);fs.rmSync(dir,{recursive:true,force:true})}
