import assert from 'node:assert/strict';
import '../js/extension-runtime.js';
const runtime=globalThis.MioExtensionRuntime.create();
const a=runtime.context('alpha'),b=runtime.context('beta');
let cleaned=0,calls=[];
const off=a.commands.register({id:'hello',label:'Hello',run:()=>42,shortcut:'mod+shift+h'});
assert.equal(await b.commands.execute('alpha:hello'),42);
assert.throws(()=>a.commands.register({id:'hello',label:'Dup',run(){}}),/Duplicate/);
assert.throws(()=>b.commands.register({id:'other',label:'Dup shortcut',shortcut:'mod+shift+h',run(){}}),/Shortcut/);
a.on('pipeline',()=>calls.push('late'),{priority:10});
a.on('pipeline',()=>calls.push('early'),{priority:-10});
b.on('pipeline',()=>calls.push('middle'));
await runtime.emit('pipeline',{});assert.deepEqual(calls,['early','middle','late']);
a.on('failure',()=>{throw Error('expected')});b.on('failure',()=>calls.push('survived'));
await runtime.emit('failure',{});assert.equal(calls.at(-1),'survived');
await assert.rejects(runtime.emit('failure',{},{strict:true}),/expected/);
assert.equal(runtime.errors.length,2);
a.dispose(()=>cleaned++);
let eventCalls=0;const target=new EventTarget();a.dom.listen(target,'test',()=>eventCalls++);
target.dispatchEvent(new Event('test'));assert.equal(eventCalls,1);
a.variables.registerType('palette',{normalize:x=>x});
const abort=a.signal;runtime.dispose('alpha');assert.ok(abort.aborted);assert.equal(cleaned,1);
target.dispatchEvent(new Event('test'));assert.equal(eventCalls,1);
assert.equal(runtime.list('commands').length,0);assert.equal(runtime.list('types').length,0);
assert.throws(()=>a.commands.register({id:'late',label:'Late',run(){}}),/disposed/);
const fresh=runtime.context('alpha');assert.throws(()=>a.on('late',()=>{}),/disposed/);
fresh.commands.register({id:'hello',label:'Fresh',run:()=>7});off();assert.equal(await runtime.execute('alpha:hello'),7);
runtime.dispose('alpha');runtime.dispose('alpha');assert.equal(cleaned,1);
for(let i=0;i<150;i++)runtime.report('beta','test',Error('bounded'));
assert.equal(runtime.errors.length,100);
runtime.dispose('beta');assert.equal(runtime.owners.size,0);
console.log('SDK 2 kernel: ownership, ordering, namespace, failure isolation, disposal, stale contexts, diagnostics PASS');
let lateCleaned=0;
const fast=globalThis.MioExtensionRuntime.create({callbackTimeout:5});
fast.context('slow');
await fast.invoke({owner:'slow'},()=>new Promise(resolve=>setTimeout(()=>resolve(()=>lateCleaned++),15)));
await new Promise(resolve=>setTimeout(resolve,25));assert.equal(lateCleaned,1);assert.equal(fast.errors.length,1);
console.log('SDK 2 kernel: timed-out async render performs eventual cleanup PASS');
