// Real navigation in an isolated fixture. No provider generation or paid operations.
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import{spawn}from'node:child_process';import{chromium}from'playwright';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mio-home-')),base='http://127.0.0.1:18873',evidence='build/home-evidence';fs.mkdirSync(evidence,{recursive:true});const log=fs.openSync(path.join(dir,'server.log'),'w'),server=spawn('python',['tests/journey_fixture_server.py'],{env:{...process.env,MIO_HOST:'127.0.0.1',MIO_PORT:'18873',MIO_DATA_DIR:path.join(dir,'data'),MIO_JOURNEY_PROVIDER_PORT:'18973'},stdio:['ignore',log,log]});let browser,count=0;const check=(v,label)=>{assert.ok(v,label);console.log('PASS '+label);count++};
try{
 let ready=false;for(let i=0;i<150;i++){try{if((await fetch(base+'/api/content')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}assert.ok(ready,'home fixture startup');
 browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1568,height:1004},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route(/^https?:\/\//,r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);
 const nav=async route=>{await p.locator(`#sidebar [data-act="art-nav"][data-route="${route}"]`).click();await p.waitForFunction(n=>ui.workspace===n,route)};
 const shot=async name=>{await p.evaluate(()=>scrollTo(0,0));await p.waitForFunction(()=>!document.querySelector('#toasts .toast'));await p.screenshot({path:path.join(evidence,name+'.png'),fullPage:true,animations:'disabled'});if(name==='home-dark-zh'||name==='home-mobile-zh')await p.screenshot({path:path.join(evidence,name+'-viewport.png'),animations:'disabled'})};
 const noOverflow=async()=>p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1);
 check(await p.locator('#mio-home').isVisible(),'fresh startup opens the independent home');check(await p.locator('#sidebar [aria-current="page"]').getAttribute('data-route')==='9','Home has its own selected first-level route');check(await p.locator('#sidebar .nav-item').first().getAttribute('data-route')==='9','Home is the first navigation item');check(await p.locator('#topbar .breadcrumb').innerText()==='首页','home breadcrumb is correct');check(await p.locator('.first-run-path').count()===3,'three provider onboarding cards moved into Home');check(await p.locator('.home-learning').count()===1,'tutorial is present once on Home');
 check(await p.locator('.home-overview').count()===0,'home-overview statistics bar is cleanly omitted');
 const tutorial=await p.locator('.home-learning').getAttribute('href');check((await p.request.get(base+tutorial)).ok(),'tutorial URL resolves to a real local page');check(await noOverflow(),'desktop Home fits the viewport');await shot('home-dark-zh');await p.locator('#topbar [data-act="theme"]').click();check(await p.locator('html').getAttribute('data-theme')==='light','home respects the light theme');await shot('home-light-zh');await p.locator('#topbar [data-act="theme"]').click();
 await p.locator('.home-primary-grid [data-route="0"]').click();check(await p.locator('#collection-home').isVisible(),'album card opens the original collection');check(await p.locator('.first-run,.home-learning,#mio-home').count()===0,'collection is now focused on works, without duplicate onboarding');await p.locator('#sidebar .brand').click();check(await p.locator('#mio-home').isVisible(),'brand returns to Home');
 await p.locator('.home-hero-actions [data-route="1"]').focus();await p.keyboard.press('Enter');check(await p.locator('.assembly-workshop').isVisible()&&await p.evaluate(()=>workshop.view==='stories'),'keyboard activation opens the storyboard workspace without creating a task');await nav(9);await p.locator('.home-primary-grid [data-route="1"]').click();check(await p.evaluate(()=>ui.workspace===1),'creative workshop card navigates correctly');await nav(9);await p.locator('.home-primary-grid [data-route="3"]').click();check(await p.locator('#image-provider-select').isVisible(),'provider module card opens provider configuration');await p.keyboard.press('Alt+0');check(await p.locator('#mio-home').isVisible(),'Alt+0 opens Home');await p.keyboard.press('Alt+3');check(await p.evaluate(()=>ui.workspace===3),'Alt+3 agrees with the provider navigation label');await nav(9);
 for(const provider of ['comfyui','novelai','openai']){await p.locator(`.first-run-path[data-provider="${provider}"]`).click();check(await p.locator('#image-provider-select').inputValue()===provider,provider+' onboarding opens the intended provider');await nav(9)}
 await p.locator('[data-act="first-run-hide"]').click();check(await p.locator('.first-run-path').count()===0&&await p.locator('.home-learning').isVisible(),'dismissing channel guidance keeps the tutorial and other home modules');await p.waitForFunction(()=>rt.saved);await p.reload();await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);check(await p.locator('#mio-home').isVisible()&&await p.locator('[data-act="first-run-show"]').isVisible(),'dismissal persists but reload still lands on Home');await p.locator('[data-act="first-run-show"]').click();
 await p.locator('.home-secondary[data-route="4"]').click();check(await p.evaluate(()=>ui.workspace===5&&studioUI.settingsTab==='modules'),'disabled optional module leads to its feature settings');check(!await p.locator('[data-studio-pref="visibility.llm"]').isChecked(),'opening the optional entry does not silently enable it');await p.locator('[data-studio-pref="visibility.llm"]').check();await p.locator('[data-studio-pref="visibility.marketplace"]').check();await nav(9);
 for(const route of [4,8,7,6]){await p.locator(`.home-secondary[data-route="${route}"]`).click();check(await p.evaluate(n=>ui.workspace===n,route),'enabled optional module route '+route+' opens its actual workspace');await nav(9)}
 await p.locator('.home-settings').click();check(await p.evaluate(()=>ui.workspace===5&&studioUI.settingsTab==='appearance'),'studio settings banner opens appearance settings');await p.locator('#interface-language').selectOption('en');await nav(9);check(await p.locator('#home-title').innerText()==='Stories into frames.\nIdeas into albums.','new home has complete English hero copy');check(!/[\u3400-\u9fff]/.test(await p.locator('#mio-home').innerText()),'all visible home interface copy is English');check(await p.locator('#sidebar [data-route="9"]').getAttribute('aria-label')==='Home','Home navigation has an English accessible name');check(await p.locator('.home-learning').getAttribute('href')==='/docs/en/GUIDE.html','English home links to the English guide');check((await p.request.get(base+'/docs/en/GUIDE.html')).ok(),'English guide route resolves');await shot('home-dark-en');
 await nav(5);await p.locator('.settings-nav [data-tab="appearance"]').click();await p.locator('#interface-language').selectOption('zh-CN');await nav(9);check((await p.locator('#home-title').innerText()).includes('让故事成帧'),'language switches reversibly back to Chinese');
 for(const [width,height]of[[390,844],[320,740],[844,390]]){await p.setViewportSize({width,height});await nav(9);check(await noOverflow(),'home has no page overflow at '+width);check(await p.locator('#sidebar .nav-item').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44})),'all navigation targets stay at least 44px with every optional module enabled at '+width);check(await p.locator('.home-module,.home-secondary,.home-settings,.first-run-path,.home-hero-actions .btn').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)),'home card and action targets stay at least 44px at '+width);await nav(6);check(await p.locator('#sidebar [data-route="6"]').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth+1}),'active navigation scrolls into view at '+width);await nav(9);if(width===390)await shot('home-mobile-zh')}
 await p.setViewportSize({width:390,height:844});await nav(5);await p.locator('.settings-nav [data-tab="appearance"]').click();await p.locator('#interface-language').selectOption('en');await nav(9);check(await noOverflow(),'English mobile home has no page overflow');await shot('home-mobile-en');
 await p.setViewportSize({width:1568,height:1004});await p.locator('#project-switch-button').click();await p.locator('[data-act="new-project"]').click();await p.locator('#text-value').fill('首页空集合');await p.locator('#modal [data-act="text-submit"]').click();await nav(9);check(await p.locator('.home-overview').count()===0,'overview bar stays omitted on empty collection');check(await p.locator('#project-switch-button').innerText().then(x=>x.includes('首页空集合')),'authored collection name stays unchanged in English');
 check(await p.evaluate(()=>!workshop.queue?.tasks?.length),'browsing Home never creates generation tasks');const wirePath=path.join(dir,'data/journey-wire.json'),wire=fs.existsSync(wirePath)?JSON.parse(fs.readFileSync(wirePath)):[];check(wire.every(x=>x.method!=='POST'),'home navigation makes no upstream generation calls');check(errors.length===0,'no browser exceptions: '+errors.join(';'));console.log('HOME WORKSPACE: '+count+' checks PASS');
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}fs.closeSync(log);fs.rmSync(dir,{recursive:true,force:true})}
