// End-to-end regression: browser -> real local service -> controlled HTTP upstream.
// No real provider credentials, no paid requests. Includes downloaded-file reopen.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {createServer} from 'node:http';
import {mkdtempSync,cpSync,rmSync,mkdirSync,readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temp=mkdtempSync(path.join(tmpdir(),'mio-lifecycle-'));
const evidence=process.env.MIO_TEST_EVIDENCE||path.join(root,'test-results');mkdirSync(evidence,{recursive:true});
for(const name of [...readdirSync(root).filter(n=>n.endsWith('.py')),'data','mio_content.py','mio_album_html.py','mio_resource_sharing.py','providers','index.html','styles.css','favicon.svg','vendor','js','docs'])cpSync(path.join(root,name),path.join(temp,name),{recursive:true,filter:src=>!['runtime','.cache','.write.lock','secrets.json'].includes(path.basename(src))});
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
const wire=[],held=new Map(),counts=new Map();
const upstream=createServer(async(req,res)=>{
 let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw),prompt=body.prompt.split('\n')[0];
 wire.push({prompt,model:body.model});const n=(counts.get(prompt)||0)+1;counts.set(prompt,n);
 if(prompt.startsWith('disconnect')){res.destroy();return}
 if(prompt.startsWith('slow')){await new Promise(resolve=>{held.set(prompt,resolve);res.on('close',resolve)});held.delete(prompt);if(res.destroyed)return}
 if(prompt==='journey-1'&&n===1){res.statusCode=422;res.end('Controlled content rejection');return}
 if(prompt==='journey-2'&&n===1){res.statusCode=503;res.end('Controlled temporary unavailable');return}
 res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data:[{b64_json:png}]}));
});
await new Promise(resolve=>upstream.listen(0,'127.0.0.1',resolve));
const upstreamURL='http://127.0.0.1:'+upstream.address().port+'/v1',port=8801,base='http://127.0.0.1:'+port,token='l'.repeat(40);
let server,browser;const errors=[];let checks=0;
const check=(name,value)=>{assert.ok(value,name);checks++;console.log('PASS '+name)};
async function boot(){server=spawn('python',['-u','server.py'],{cwd:temp,env:{...process.env,MIO_PORT:String(port),MIO_API_TOKEN:token},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('server startup timeout')),10000);server.stdout.on('data',d=>{if(d.toString().includes('物理落盘')){clearTimeout(timer);resolve()}});server.stderr.on('data',d=>writeFileSync(path.join(evidence,'lifecycle-server-last.log'),d));server.on('error',reject)});await until(async()=>{try{return (await fetch(base+'/api/config')).ok}catch{return false}})}
async function stop(){if(!server||server.exitCode!==null)return;const exit=new Promise(resolve=>server.once('exit',resolve));server.kill('SIGKILL');await exit}
async function api(route,body){const response=await fetch(base+'/api/v1/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:response.status,...await response.json()}}
async function until(fn){for(let i=0;i<240;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('condition timeout')}
async function dismiss(page){await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()))}
try{
 await boot();browser=await chromium.launch({args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.on('response',async r=>{if(r.url().includes('/api/config')&&!r.ok())console.log('SAVE RESPONSE',await r.text().catch(()=>''))});page.on('pageerror',e=>errors.push(e.message));await page.route(/^https:\/\//,r=>r.abort());await page.goto(base);await dismiss(page);
 await api('albums/delete',{ids:['edition_letter']});await page.reload();await dismiss(page);check('deleting an unsaved first-run demo cannot recreate it on refresh',await page.evaluate(()=>!bookBy('edition_letter')&&state.templates.length>0));
 // Configure channel, create album, edit the ORIGINAL storyboard, save, then enqueue.
 await page.evaluate(url=>{state.settings.identity.onboarded=true;state.settings.comfy.mode='real';state.books=[];state.queue=[];const g=ensureImageProviders();g.profiles.push({id:'lifecycle',title:'Controlled channel',provider:'openai',protocol:'images',model:'flow-model',baseUrl:url,keyMode:'none',sendSize:false,sendQuality:false});g.active='lifecycle';const p=selectedPlan(),t=templateBy(p.templateId);p.storyVersionId='';p.title='完整流程验收';t.frames=Array.from({length:4},(_,i)=>({...clone(t.frames[0]),id:'journey-frame-'+i,prompt:'journey-'+i,negative:'',caption:'第 '+(i+1)+' 幕'}));createUI.sceneScope='template';createUI.tab='story';navigate(1);save(true)},upstreamURL);
 await page.evaluate(async()=>{flushEditor();if(!await savePythonWorkspace(true))throw Error('setup save failed')});
 await api('jobs/scheduler',{action:'policy',policy:{mode:'retry',maxRetries:1,delaySeconds:5,onExhausted:'continue'}});
 await page.evaluate(async()=>{await generateChosenPlans(true);await runQueue()});
 await until(async()=>{const r=await api('jobs');return r.data.jobs.some(j=>j.state==='failed'&&j.cursor===3)});
 await page.evaluate(()=>pollFoundationJobs());const journey=await page.evaluate(()=>({book:state.queue[0].bookId,id:state.queue[0].serverId,qid:state.queue[0].id}));
 check('422 skips one frame; 503 retries; later scenes complete in the same album',(await api('jobs/'+journey.id)).data.completedIndices.join(',')==='0,2,3'&&counts.get('journey-2')===2&&counts.get('journey-1')===1);
 await page.evaluate(()=>{createUI.tab='story';navigate(1)});await page.locator('#art-book-draft').selectOption('task:'+journey.qid);
 await page.evaluate(()=>{ui.frameIndex=1;render()});await page.locator('[data-v3-frame="prompt"]').fill('journey-1-edited');await page.evaluate(async()=>{flushEditor();if(!await savePythonWorkspace())throw Error('edit save failed: '+Mio.sync.runtime.error)});
 await page.evaluate(id=>{void retryQueueTask(id)},journey.qid);await page.locator('#confirm-dialog[open]').waitFor();await page.locator('#confirm-yes').click();
 await until(async()=>(await api('jobs/'+journey.id)).data.state==='complete');await page.evaluate(()=>pollFoundationJobs());
 check('manual continuation preserves completed frames and uses saved scene edit',counts.get('journey-0')===1&&counts.get('journey-2')===2&&counts.get('journey-3')===1&&counts.get('journey-1-edited')===1);
 await page.evaluate(async()=>{if(!await savePythonWorkspace())throw Error('completion save failed')});
 await page.reload();await dismiss(page);await page.evaluate(id=>openReader(id),journey.book);check('refresh opens original complete four-scene album',await page.evaluate(id=>bookBy(id).generatedSteps===4&&bookBy(id).totalSteps===4,journey.book));
 await page.locator('[data-act="presentation-open-export"]').click();const downloadPromise=page.waitForEvent('download');await page.locator('[data-act="presentation-export"]').click();const download=await downloadPromise;const html=readFileSync(await download.path(),'utf8');const exported=path.join(evidence,'journey-offline.html');writeFileSync(exported,html);
 const offline=await browser.newPage();await offline.goto('file://'+exported);await offline.locator('[data-cc-frame]').first().waitFor();check('actual downloaded file opens offline with all four images',await offline.locator('[data-cc-frame]').count()===4&&await offline.locator('[data-cc-frame] img').evaluateAll(async imgs=>{imgs.forEach(i=>i.loading="eager");await Promise.all(imgs.map(i=>i.decode()));return imgs.every(i=>i.naturalWidth===1)}));await offline.close();await page.evaluate(()=>closeReader());
 // Running deletion: one confirmation, no stop-page detour, duplicate clicks ignored.
 const running=await page.evaluate(async()=>{const p=selectedPlan(),t=templateBy(p.templateId);t.frames=[{...clone(t.frames[0]),id:'slow-frame',prompt:'slow-delete'}];const b=enqueuePlanSnapshot(p);b.title='生成中也能一次删除';save();await savePythonWorkspace();await runQueue();return{book:b.id,qid:state.queue.at(-1).id,id:state.queue.at(-1).serverId}});
 await until(()=>held.has('slow-delete'));
 const isolation=await page.evaluate(async()=>{const g=ensureImageProviders(),active=g.active,mode=state.settings.comfy.mode;g.active=g.profiles.find(p=>p.provider==='comfyui').id;state.settings.comfy.mode='mock';const isolated=!foundationIsMock();let count=0;const running=rt.running;rt.running=false;const previous=generateFrame;generateFrame=async()=>{count++;return{image:defaultCuratedCover()}};try{await runFlexibleQueue()}finally{generateFrame=previous;rt.running=running;g.active=active;state.settings.comfy.mode=mode}return isolated&&count===0});check('switching current channel to demo cannot replay a durable real task locally',isolation&&counts.get('slow-delete')===1);await page.evaluate(()=>{createUI.tab='queue';navigate(1)});await page.evaluate(()=>pollFoundationJobs());
 for(const [width,height,name] of [[1440,1000,'desktop'],[390,844,'mobile']])for(const theme of ['light','dark']){await page.setViewportSize({width,height});await page.evaluate(theme=>{state.settings.studio.appearance.theme=theme;render()},theme);await page.locator(`[data-sort-task="${running.qid}"]`).scrollIntoViewIfNeeded();await page.screenshot({path:path.join(evidence,'running-'+name+'-'+theme+'.png')})}
 await page.setViewportSize({width:1440,height:1000});
 await page.evaluate(()=>openFoundationJobs());check('service task list uses the same deletion instead of exposing archive or abandon',await page.locator('[data-operation="remove"]').count()>0&&await page.locator('[data-operation="archive"],[data-operation="abandon"]').count()===0);await page.evaluate(()=>closeModal());
 const stale=await context.newPage();await stale.goto(base);await dismiss(stale);await stale.evaluate(()=>foundationRuntime.enabled=false);
 await page.locator(`[data-act="org-task-delete"][data-id="${running.qid}"]`).click();await page.locator('#confirm-dialog[open]').waitFor();check('running album offers one stop-and-delete confirmation',(await page.locator('#confirm-dialog').innerText()).includes('停止并删除')&&!(await page.locator('#confirm-dialog').innerText()).includes('放弃跟踪'));
 await page.evaluate(id=>{void deleteBooks([id])},running.book);await page.locator('#confirm-yes').click();await page.waitForFunction(id=>!bookBy(id),running.book);
 check('running deletion removes all queue mappings without another request',(await api('jobs/'+running.id)).data.state==='archived'&&counts.get('slow-delete')===1&&!await page.locator('#confirm-dialog').isVisible());
 // A stale tab must not resurrect a deleted album, whether its save is accepted or conflicts.
 await stale.evaluate(async()=>{save(true);await savePythonWorkspace(true)});const config=await(await fetch(base+'/api/config')).json();check('stale-tab full-config save cannot resurrect the deleted album',!config.savedGalleries.some(b=>b.id===running.book)&&!config.batchRunState.queue.some(q=>q.bookId===running.book));
 await stale.evaluate(async()=>{foundationRuntime.enabled=true;await pollFoundationJobs()});check('other open tab learns deletion through normal polling',await stale.evaluate(id=>!bookBy(id),running.book));await stale.close();
 // Unknown outcome from a real broken socket, followed by local stop and normal deletion.
 await page.reload();await dismiss(page);
 const unknown=await page.evaluate(async()=>{const p=selectedPlan(),t=templateBy(p.templateId);t.frames=[{...clone(t.frames[0]),prompt:'disconnect-delete'}];const b=enqueuePlanSnapshot(p);save();await savePythonWorkspace();await runQueue();return{book:b.id,id:state.queue.at(-1).serverId}});
 await until(async()=>(await api('jobs/'+unknown.id)).data.state==='unknown');await api('jobs/'+unknown.id,{action:'cancel'});await page.evaluate(()=>pollFoundationJobs());
 const before=wire.length;await page.evaluate(ids=>{void deleteBooks(ids)},[unknown.book,journey.book]);await page.locator('#confirm-dialog[open]').waitFor();await page.locator('#confirm-yes').click();await page.waitForFunction(ids=>ids.every(id=>!bookBy(id)),[unknown.book,journey.book]);
 check('mixed completed and stopped-unknown batch deletes with one confirmation',wire.length===before&&(await api('jobs')).data.jobs.length===0);
 await page.evaluate(async()=>{if(!await savePythonWorkspace(true))throw Error('post delete save failed: '+Mio.sync.runtime.error)});await stop();await boot();await page.reload();await dismiss(page);
 check('hard service restart does not restore deleted albums or repeat submissions',await page.evaluate(()=>state.books.length===0&&state.queue.length===0)&&wire.length===before);
 // Full resolution is independent of reader-thumbnail downsampling. Controlled slow asset for cancel.
 const large=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=2048;canvas.height=3072;const ctx=canvas.getContext('2d');ctx.fillStyle='#7ba184';ctx.fillRect(0,0,2048,3072);ctx.fillStyle='#f5d392';ctx.fillRect(300,300,1000,1600);const a=await foundationRequest('assets/upload',{dataUrl:canvas.toDataURL('image/png')});const b={id:uid('book'),projectId:state.activeProjectId,title:'完整分辨率与取消验收',rowId:selectedPlan().rowId,templateId:selectedPlan().templateId,characterName:'验收',templateTitle:'原图测试',synopsis:'用于验收',tags:[],createdAt:Date.now(),updatedAt:Date.now(),totalSteps:8,generatedSteps:8,status:'complete',steps:Array.from({length:8},(_,i)=>({stepIndex:i,name:'原图 '+i,prompt:'safe',caption:'完整画面',image:a.url}))};state.books.push(b);save();if(!await savePythonWorkspace())throw Error('original-image fixture save failed');openReader(b.id);return{book:b.id,url:b.steps[0].image}});
 await page.locator('[data-act="presentation-open-export"]').click();let assetRelease;await page.route('**'+large.url,async route=>{await new Promise(resolve=>assetRelease=resolve);await route.continue().catch(()=>{})});
 const downloads=[];page.on('download',d=>downloads.push(d));await page.locator('[data-act="presentation-export"]').click();await page.waitForFunction(()=>studioUI.exportBusy);await page.locator('[data-act="export-cancel"]').click();await page.waitForFunction(()=>!studioUI.exportBusy);assetRelease?.();await page.unroute('**'+large.url);
 check('canceling slow original-image export releases busy state and downloads nothing',downloads.length===0&&(await page.locator('#export-status').innerText()).includes('取消'));
 const fullDownload=page.waitForEvent('download');await page.locator('[data-act="presentation-export"]').click();const fullFile=await fullDownload;const fullPath=path.join(evidence,'full-resolution-offline.html');writeFileSync(fullPath,readFileSync(await fullFile.path()));const full=await browser.newPage();await full.goto('file://'+fullPath);check('downloaded full-resolution images decode at original 2048 × 3072',await full.locator('[data-cc-frame] img').evaluateAll(async imgs=>{imgs.forEach(i=>i.loading="eager");await Promise.all(imgs.map(i=>i.decode()));return imgs.length===8&&imgs.every(i=>i.naturalWidth===2048&&i.naturalHeight===3072)}));await full.close();
 await page.evaluate(()=>{closeReader();const b=state.books.at(-1),t=exportTemplateCopy(fitPresentationTemplate());t.id='load-cancel-test';t.title='受控整册载入';state.exportTemplates.push(t);b.presentationTemplateId=t.id;presentationImageCache.clear()});
 const loadReleases=[];await page.route('**'+large.url,async route=>{await new Promise(resolve=>loadReleases.push(resolve));await route.continue().catch(()=>{})});await page.evaluate(id=>openReader(id),large.book);await page.locator('[data-act="presentation-load-cancel"]').click();await page.waitForFunction(()=>document.querySelector('#presentation-preview-status')?.textContent.includes('取消'));loadReleases.forEach(resolve=>resolve());await page.unroute('**'+large.url);check('whole-book loading has a working cancellation control',await page.locator('#presentation-preview').getAttribute('srcdoc')===null);await page.evaluate(()=>closeReader());
 check('retry wait wording follows actual HTTP policy, not nested error text',await page.evaluate(()=>queueErrorSummary({serverState:'pending',serverReadyAt:Date.now()/1000+5,error:'HTTP 503: [422] Content violates policy'}).includes('自动重试')));
 // Logs: reading position and the expanded attempt survive new evidence.
 await page.evaluate(()=>{navigate(6);rt.logs=Array.from({length:80},(_,i)=>({time:Date.now(),level:'info',message:'日志记录 '+i,eventId:i,attemptKey:'attempt-'+i,request:{prompt:'prompt-'+i}}));renderLogs();const el=document.querySelector('#log-body');el.scrollTop=90;window.testLogTop=el.scrollTop;rt.logs.push({time:Date.now(),level:'info',message:'新增日志'});renderLogs()});
 check('new logs do not steal history-reading scroll position',await page.evaluate(()=>Math.abs(document.querySelector('#log-body').scrollTop-window.testLogTop)<2));
 await page.evaluate(()=>{const el=document.querySelector('[data-log-event="attempt-1"]');el.open=true;rt.logs[1].eventId=999;rt.logs[1].request.requestParameters={model:'resolved'};renderLogs()});check('resolved-parameter update keeps same attempt details open',await page.locator('[data-log-event="attempt-1"]').evaluate(el=>el.open));
 // A disconnected browser is not permission to replay a provider request.
 await page.evaluate(()=>{createUI.tab='queue';navigate(1)});await page.route('**/api/foundation/jobs',route=>route.abort());await page.evaluate(()=>pollFoundationJobs());await page.waitForFunction(()=>foundationRuntime.connectionError);check('connection loss is visible without opening logs',await page.locator('#queue-service-status').isVisible());await page.unroute('**/api/foundation/jobs');await page.evaluate(()=>pollFoundationJobs());await page.waitForFunction(()=>!foundationRuntime.connectionError);check('connection recovery clears the warning without replaying requests',wire.length===before);
 // Actual screenshots at desktop/mobile sizes in both application themes.
 for(const [width,height,name] of [[1440,1000,'desktop'],[390,844,'mobile']])for(const theme of ['light','dark']){await page.setViewportSize({width,height});await page.evaluate(theme=>{state.settings.studio.appearance.theme=theme;createUI.tab='queue';navigate(1)},theme);check(name+' '+theme+' has no horizontal page overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(evidence,name+'-'+theme+'.png'),fullPage:true})}
 const revisionConfig=await(await fetch(base+'/api/config')).json();const entity=revisionConfig.templates[0];const stalePayload={format:'mio.delta.v2',changes:[{kind:'storyboards',id:entity.id,document:{...entity,title:entity.title+' · CAS'},expected:revisionConfig._fileRevisions['storyboards:'+entity.id]}]};const configPost=()=>fetch(base+'/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(stalePayload)});const revisionAck=await(await configPost()).json();check('server revision advances even if client timestamp is unchanged',revisionAck.revision>revisionConfig.updatedAt);check('a second stale write cannot overwrite the newer revision',(await configPost()).status===409);
 check('no uncaught browser errors',errors.length===0);console.log(`Lifecycle flow: ${checks} checks passed`);
}finally{for(const release of held.values())release();await browser?.close();await stop();await new Promise(resolve=>upstream.close(resolve));rmSync(temp,{recursive:true,force:true})}
