import {settingsField} from './helpers/settings.mjs';
// Real UI -> native album files -> Python dispatcher -> controlled Chat image provider.
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {createServer} from 'node:http';import {mkdtempSync,mkdirSync,readFileSync,readdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-live-settings-')),data=path.join(temp,'data'),base='http://127.0.0.1:8882',token='s'.repeat(40),evidence=path.join(process.cwd(),'docs/acceptance-2.3.0');mkdirSync(evidence,{recursive:true});
const calls=[],held=[],png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
const provider=createServer(async(req,res)=>{try{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw),content=body.messages[0].content;calls.push({prompt:content.find(x=>x.type==='text').text,images:content.filter(x=>x.type==='image_url').map(x=>x.image_url.url)});const finish=()=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:[{type:'image_url',image_url:{url:'data:image/png;base64,'+png}}]}}]}))};if(calls.length===1)held.push(finish);else finish()}catch(e){res.statusCode=500;res.end(String(e))}});await new Promise(r=>provider.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+provider.address().port+'/v1';
let server,browser,p,n=0;const errors=[],check=(name,v)=>{assert.ok(v,name);console.log('PASS '+name);n++};
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('condition timed out')}
async function start(){server=spawn('python',['-u',path.join(root,'server.py')],{cwd:root,env:{...process.env,MIO_PORT:'8882',MIO_DATA_DIR:data,MIO_API_TOKEN:token},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});await until(async()=>{try{return(await fetch(base+'/api/config')).ok}catch{return false}})}
async function stop(){if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}}
async function api(route,body){const r=await fetch(base+'/api/v1/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await r.json();assert.ok(r.ok,JSON.stringify(result));return result.data}
async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.settings.identity.onboarded=true;guidePreferences().seen=true;createUI.tab='settings';navigate(1)})}
async function saved(){assert.ok(await p.evaluate(()=>savePythonWorkspace()),'native save must be acknowledged')}
async function diskBook(id){return(await(await fetch(base+'/api/config')).json()).savedGalleries.find(b=>b.id===id)}
async function shot(name){await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,name)})}
try{
 await start();browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await load();
 const f=await p.evaluate(async url=>{
  await Mio.fileLibrary.hydrateAll();state.books=[];state.queue=[];state.settings.comfy.mode='real';const channel=ensureImageProviders();channel.profiles.push({id:'live-references',title:'受控参考图渠道',provider:'openai',protocol:'chat',model:'local-controlled',baseUrl:url,keyMode:'none',sendSize:false,sendQuality:false});channel.active='live-references';
  const images={};for(const [name,color] of [['red','#d26b65'],['blue','#42789e'],['green','#668c68']]){const c=document.createElement('canvas');c.width=32;c.height=48;c.getContext('2d').fillStyle=color;c.getContext('2d').fillRect(0,0,32,48);images[name]={data:c.toDataURL(),value:await storeVariableAsset(c.toDataURL(),name+'.png')}}
  const plan=selectedPlan(),t=ensureSourceStory(plan),first=clone(t.frames[0]);plan.title='夏日借阅室';plan.storyVersionId='';plan.variableSetIds=[];plan.variables=[variableEntry('mood','old-mood'),{id:uid('var'),key:'male_lead',type:'image',value:images.red.value}];plan.excludedSettingKeys=[];plan.sceneOverrides={};t.frames=Array.from({length:4},(_,i)=>({...clone(first),id:'live-frame-'+i,prompt:'A'+i+' {mood} 参考 {male_lead}',caption:'',negative:''}));plan.sceneOverrides[t.frames[2].id]={variables:[{id:uid('var'),key:'male_lead',type:'image',value:images.green.value}]};
  const a=enqueuePlanSnapshot(plan),qa=state.queue.at(-1),other={...clone(plan),id:uid('plan'),title:'另一本源画册',variables:[variableEntry('mood','other-book'),{id:uid('var'),key:'male_lead',type:'image',value:images.green.value}],sceneOverrides:{}};state.creation.plans.push(other);ensureSourceStory(other);const b=enqueuePlanSnapshot(other),qb=state.queue.at(-1);qb.status='paused';selectCreationContext(plan.id);save(true);if(!await savePythonWorkspace(true))throw Error(Mio.sync.runtime.error);return {a:a.id,b:b.id,qa:qa.id,qb:qb.id,plan:plan.id,other:other.id,images};
 },url);
 check('title selector edits source plans, not generated versions',await p.locator('#art-book-draft').inputValue()===f.plan&&await p.evaluate(()=>[...$('#art-book-draft').options].every(o=>!!planBy(o.value))));
 check('source editor has no competing preset selector',await p.locator('#main #art-setting-preset,#main [data-act="art-apply-preset"]').count()===0);
 await p.evaluate(async()=>{await runQueue()});await until(()=>held.length===1);check('first request submits its captured image and text',calls.length===1&&calls[0].images[0]===f.images.red.data&&calls[0].prompt.includes('old-mood'));
 await (await settingsField(p,'[data-art-setting="mood"]')).fill('latest-source');await (await settingsField(p,'[data-image-key="male_lead"] input')).setInputFiles({name:'blue.png',mimeType:'image/png',buffer:Buffer.from(f.images.blue.data.split(',')[1],'base64')});await p.waitForFunction(()=>currentBookSettings().variables.find(v=>v.key==='male_lead').value.name==='blue.png');
 await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'controlled saved-variable conflict'})}):r.continue());check('save conflict is explicit, not acknowledged',!await p.evaluate(()=>savePythonWorkspace()));check('conflict does not mutate queued execution input',(await diskBook(f.a)).sourceSnapshot.settingsContext.variables.find(v=>v.key==='mood').value==='old-mood');await p.unroute('**/api/config');await saved();
 check('source edit survives acknowledged save',await p.evaluate(()=>currentBookSettings().variables.find(v=>v.key==='mood').value==='latest-source'));
 const savedA=await diskBook(f.a);check('pending generation retains original resolved text and reference',savedA.sourceSnapshot.liveInputs['1'].input.prompt.includes('old-mood')&&savedA.sourceSnapshot.liveInputs['1'].input.images[0].includes(f.images.red.value.src.split('/').at(-1)));
 check('single-frame override remains part of the independent snapshot',savedA.sourceSnapshot.liveInputs['2'].input.images[0].includes(f.images.green.value.src.split('/').at(-1)));
 check('other generated album retains its own settings',(await diskBook(f.b)).sourceSnapshot.settingsContext.variables.find(e=>e.key==='mood').value==='other-book');
 check('optional album source sharing exports its captured settings',await p.evaluate(id=>albumSharedSources(bookBy(id),{embedVariables:true}).variables.entries.find(e=>e.key==='mood').value==='old-mood',f.a));
 await shot('source-settings-desktop.png');const id=await p.evaluate(qid=>state.queue.find(q=>q.id===qid).serverId,f.qa);await p.close();held.shift()();await until(async()=>(await api('jobs/'+id)).state==='complete');
 check('closed-browser generation uses frozen image inputs',calls.length===4&&calls[1].images[0]===f.images.red.data&&calls[2].images[0]===f.images.green.data&&calls[3].images[0]===f.images.red.data&&calls.every(c=>c.prompt.includes('old-mood')));
 const job=await api('jobs/'+id);check('exactly four attempts, no replay',job.attempts===4&&job.completedIndices.length===4);
 await stop();await start();p=await browser.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.message));await load();await p.locator('#art-book-draft').selectOption(f.plan);await settingsField(p,'[data-art-setting="mood"]');check('service restart restores source edits',await p.locator('[data-art-setting="mood"]').inputValue()==='latest-source');await shot('source-settings-mobile.png');
 await p.locator('#art-book-draft').selectOption(f.other);await settingsField(p,'[data-art-setting="mood"]');check('switching source album restores its separate values',await p.locator('[data-art-setting="mood"]').inputValue()==='other-book');
 await p.evaluate(()=>{const ctx=currentBookSettings(),t=ensureSourceStory(ctx);for(const frame of t.frames.slice(0,2))ctx.sceneOverrides[frame.id]={variables:[{id:'same-id-in-two-scenes',key:'male_lead',type:'image',value:clone(ctx.variables.find(e=>e.key==='male_lead').value)}]};createUI.tab='story';ui.frameIndex=0;render();$$('#main details').forEach(e=>e.open=true);window.__oldSceneUpload=storeVariableAsset;storeVariableAsset=async(...args)=>{const result=await window.__oldSceneUpload(...args);await new Promise(r=>window.__releaseSceneUpload=r);return result}});
 await p.locator('[data-image-group="scene"] [data-image-variable-upload]').setInputFiles({name:'delayed-scene.png',mimeType:'image/png',buffer:Buffer.from(f.images.blue.data.split(',')[1],'base64')});await p.waitForFunction(()=>typeof window.__releaseSceneUpload==='function');await p.locator('.quiet-scene[data-index="1"]').click();await p.evaluate(()=>{storeVariableAsset=window.__oldSceneUpload;window.__releaseSceneUpload()});await p.waitForFunction(()=>currentBookSettings().sceneOverrides[currentTemplate().frames[0].id].variables[0].value.name==='delayed-scene.png');
 check('late image upload stays with the original scene',await p.evaluate(()=>{const c=currentBookSettings(),t=currentTemplate();return c.sceneOverrides[t.frames[0].id].variables[0].value.name==='delayed-scene.png'&&c.sceneOverrides[t.frames[1].id].variables[0].value.src===c.variables.find(e=>e.key==='male_lead').value.src}));await saved();
 check('restart and browsing do not replay paid calls',calls.length===4&&(await api('jobs/'+id)).attempts===4);check('no uncaught browser errors',errors.length===0);console.log(n+' source/queue isolation UI checks PASS');
}finally{held.forEach(fn=>fn());await browser?.close();await stop();provider.closeAllConnections();await new Promise(r=>provider.close(r));rmSync(temp,{recursive:true,force:true})}
