// Real UI -> native album files -> Python dispatcher -> controlled Chat image provider.
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {createServer} from 'node:http';import {mkdtempSync,mkdirSync,readFileSync,readdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-live-settings-')),data=path.join(temp,'data'),base='http://127.0.0.1:8882',token='s'.repeat(40),evidence=path.join(process.cwd(),'docs/acceptance-2.3.0');mkdirSync(evidence,{recursive:true});
const calls=[],held=[],png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
const provider=createServer(async(req,res)=>{try{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw),content=body.messages[0].content;calls.push({prompt:content.find(x=>x.type==='text').text,images:content.filter(x=>x.type==='image_url').map(x=>x.image_url.url)});const finish=()=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:[{type:'image_url',image_url:{url:'data:image/png;base64,'+png}}]}}]}))};if(calls.length===1)held.push(finish);else finish()}catch(e){res.statusCode=500;res.end(String(e))}});await new Promise(r=>provider.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+provider.address().port+'/v1';
let server,browser,p,n=0;const errors=[],check=(name,v)=>{assert.ok(v,name);console.log('PASS '+name);n++};
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('condition timed out')}
async function start(){server=spawn('python',['-u',path.join(root,'server.py')],{cwd:root,env:{...process.env,MIO_PORT:'8882',MIO_DATA_DIR:data,MIO_API_TOKEN:token},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});await until(async()=>{try{return(await fetch(base+'/api/config')).ok}catch{return false}})}
async function stop(){if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}}
async function api(route,body){const r=await fetch(base+'/api/v1/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const result=await r.json();assert.ok(r.ok,JSON.stringify(result));return result.data}
async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.settings.identity.onboarded=true;guidePreferences().seen=true;createUI.tab='settings';navigate(1)})}
async function saved(){assert.ok(await p.evaluate(()=>savePythonWorkspace()),'native save must be acknowledged')}
async function diskBook(id){return(await(await fetch(base+'/api/config')).json()).savedGalleries.find(b=>b.id===id)}
async function shot(name){await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,name)})}
try{
 await start();browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await load();
 const f=await p.evaluate(async url=>{
  await Mio.fileLibrary.hydrateAll();state.books=[];state.queue=[];state.settings.comfy.mode='real';const channel=ensureImageProviders();channel.profiles.push({id:'live-references',title:'受控参考图渠道',provider:'openai',protocol:'chat',model:'local-controlled',baseUrl:url,keyMode:'none',sendSize:false,sendQuality:false});channel.active='live-references';
  const images={};for(const [name,color] of [['red','#d26b65'],['blue','#42789e'],['green','#668c68']]){const c=document.createElement('canvas');c.width=32;c.height=48;c.getContext('2d').fillStyle=color;c.getContext('2d').fillRect(0,0,32,48);images[name]={data:c.toDataURL(),value:await storeVariableAsset(c.toDataURL(),name+'.png')}}
  const plan=selectedPlan(),t=templateBy(plan.templateId),first=clone(t.frames[0]);plan.title='夏日借阅室';plan.storyVersionId='';plan.variableSetIds=[];plan.variables=[variableEntry('mood','old-mood'),{id:uid('var'),key:'male_lead',type:'image',value:images.red.value}];plan.excludedSettingKeys=[];plan.sceneOverrides={};t.frames=Array.from({length:4},(_,i)=>({...clone(first),id:'live-frame-'+i,prompt:'A'+i+' {mood} 参考 {male_lead}',caption:'',negative:''}));plan.sceneOverrides[t.frames[2].id]={variables:[{id:uid('var'),key:'male_lead',type:'image',value:images.green.value}]};
  const a=enqueuePlanSnapshot(plan),qa=state.queue.at(-1);plan.title='另一本画册';plan.variables=[variableEntry('mood','other-book'),{id:uid('var'),key:'male_lead',type:'image',value:images.green.value}];plan.sceneOverrides={};const b=enqueuePlanSnapshot(plan),qb=state.queue.at(-1);qb.status='paused';selectCreationContext('task:'+qa.id);save(true);if(!await savePythonWorkspace(true))throw Error(Mio.sync.runtime.error);return {a:a.id,b:b.id,qa:qa.id,qb:qb.id,plan:plan.id,images};
 },url);
 const otherBefore=JSON.stringify(await diskBook(f.b));
 check('the top selector and main editor identify the same actual album version',await p.locator('#art-book-draft').inputValue()==='task:'+f.qa&&await p.locator('.character-settings h2').innerText()==='夏日借阅室');
 check('the main album editor has no competing preset selector or Apply/Update action',await p.locator('#main #art-setting-preset,#main [data-act="art-apply-preset"],#main [data-act="ws-update-preset"]').count()===0);
 await p.locator('[data-act="preset-library-open"]').click();await p.locator('#art-setting-preset').selectOption(await p.evaluate(()=>projectVariableSets()[0].id));await p.locator('#preset-library [data-art-setting="character"]').fill('只属于公共预设的草稿');await saved();await p.evaluate(()=>closeModal());check('editing the public library never changes the current book settings',await p.locator('[data-art-setting="mood"]').inputValue()==='old-mood'&&await p.locator('[data-image-key="male_lead"] img').count()===1);
 await p.evaluate(async()=>{await runQueue()});await until(()=>held.length===1);check('the first real request has already submitted its original reference',calls.length===1&&calls[0].images[0]===f.images.red.data&&calls[0].prompt.includes('old-mood'));
 await p.locator('[data-art-setting="mood"]').fill('latest-mood');await p.locator('[data-image-key="male_lead"] input').setInputFiles({name:'blue.png',mimeType:'image/png',buffer:Buffer.from(f.images.blue.data.split(',')[1],'base64')});await p.waitForFunction(()=>currentBookSettings().variables.find(v=>v.key==='male_lead').value.name==='blue.png');
 await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'controlled saved-variable conflict'})}):r.continue());check('a rejected save is explicitly not acknowledged',!await p.evaluate(()=>savePythonWorkspace()));
 check('save failure retains the old disk inputs, rather than pretending new references took effect',(await diskBook(f.a)).sourceSnapshot.settingsContext.variables.find(v=>v.key==='mood').value==='old-mood'&&await p.locator('[data-settings-save-status]').innerText()==='保存未确认');
 await p.unroute('**/api/config');await saved();const savedA=await diskBook(f.a);check('one acknowledged save resolves text and image inputs together for pending scenes',savedA.sourceSnapshot.liveInputs['1'].input.prompt.includes('latest-mood')&&savedA.sourceSnapshot.liveInputs['1'].input.images[0].includes(f.images.blue.value.src.split('/').at(-1)));
 check('single-scene reference overrides survive global reference replacement',savedA.sourceSnapshot.liveInputs['2'].input.images[0].includes(f.images.green.value.src.split('/').at(-1)));
 check('updating one version leaves the other album document byte-equivalent',JSON.stringify(await diskBook(f.b))===otherBefore);
 await p.locator('[data-art-setting="mood"]').fill('auto-final');await p.waitForFunction(()=>!Mio.sync.runtime.dirty&&!Mio.sync.runtime.saving);check('ordinary debounced autosave refreshes pending inputs without a separate Apply or Save button',(await diskBook(f.a)).sourceSnapshot.liveInputs['1'].input.prompt.includes('auto-final'));
 check('optional source sharing uses this album’s latest values and explicit scene overrides',await p.evaluate(id=>{const b=bookBy(id),s=albumSharedSources(b,{embedVariables:true}).variables;return s.entries.find(e=>e.key==='mood').value==='auto-final'&&s.frames[2].find(e=>e.key==='male_lead').value.src!==s.frames[1].find(e=>e.key==='male_lead').value.src&&Object.keys(albumSharedSources(b,{})).length===0},f.a));
 await shot('live-settings-desktop.png');const id=await p.evaluate(qid=>state.queue.find(q=>q.id===qid).serverId,f.qa);
 await p.close();held.shift()();await until(async()=>(await api('jobs/'+id)).state==='complete');
 check('closed-browser execution reads the newly saved reference for subsequent frames',calls.length===4&&calls[1].images[0]===f.images.blue.data&&calls[3].images[0]===f.images.blue.data&&calls.slice(1).every(c=>c.prompt.includes('auto-final')));
 check('in-flight input remains original and the single-scene override remains independent',calls[0].images[0]===f.images.red.data&&calls[2].images[0]===f.images.green.data);
 const job=await api('jobs/'+id);check('completed requests were not replayed and the immutable request evidence retains distinct references',job.attempts===4&&job.completedIndices.length===4&&job.requestHistory.length===4);
 await stop();await start();p=await browser.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>errors.push(e.message));await load();await p.locator('#art-book-draft').selectOption('task:'+f.qa);await p.waitForSelector('[data-art-setting="mood"]');check('a real service restart restores this album’s own edited values',await p.locator('[data-art-setting="mood"]').inputValue()==='auto-final');await shot('live-settings-mobile.png');
 await p.locator('#art-book-draft').selectOption('task:'+f.qb);await p.waitForSelector('[data-art-setting="mood"]');check('switching global album changes the editor owner and restores the other album values',await p.locator('[data-art-setting="mood"]').inputValue()==='other-book'&&await p.locator('.character-settings h2').innerText()==='另一本画册');
 await p.evaluate(()=>{const ctx=currentBookSettings(),q=creationTask();for(const frame of q.frames.slice(0,2))ctx.sceneOverrides[frame.id]={variables:[{id:'same-id-in-two-scenes',key:'male_lead',type:'image',value:clone(ctx.variables.find(e=>e.key==='male_lead').value)}]};createUI.tab='story';ui.frameIndex=0;render();$$('#main details').forEach(e=>e.open=true);window.__oldSceneUpload=storeVariableAsset;storeVariableAsset=async(...args)=>{const result=await window.__oldSceneUpload(...args);await new Promise(r=>window.__releaseSceneUpload=r);return result}});
 await p.locator('[data-image-group="scene"] [data-image-variable-upload]').setInputFiles({name:'delayed-scene.png',mimeType:'image/png',buffer:Buffer.from(f.images.blue.data.split(',')[1],'base64')});await p.waitForFunction(()=>typeof window.__releaseSceneUpload==='function');await p.locator('.quiet-scene[data-index="1"]').click();await p.evaluate(()=>{storeVariableAsset=window.__oldSceneUpload;window.__releaseSceneUpload()});await p.waitForFunction(()=>currentBookSettings().sceneOverrides[creationTask().frames[0].id].variables[0].value.name==='delayed-scene.png');
 check('delayed scene image upload stays with its original album and scene after switching',await p.evaluate(()=>{const c=currentBookSettings(),q=creationTask();return c.sceneOverrides[q.frames[0].id].variables[0].value.name==='delayed-scene.png'&&c.sceneOverrides[q.frames[1].id].variables[0].value.src===c.variables.find(e=>e.key==='male_lead').value.src}));await saved();
 check('restart and browsing cause no paid replay',calls.length===4&&(await api('jobs/'+id)).attempts===4);check('no uncaught browser errors',errors.length===0);console.log(n+' live settings UI checks PASS');
}finally{held.forEach(fn=>fn());await browser?.close();await stop();provider.closeAllConnections();await new Promise(r=>provider.close(r));rmSync(temp,{recursive:true,force:true})}
