// Isolated UI audit; excludes authored content and never invokes generation.
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {chromium} from 'playwright';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mio-locale-')),base='http://127.0.0.1:18871',evidence=process.env.MIO_LOCALE_EVIDENCE||'build/locale-audit';fs.mkdirSync(evidence,{recursive:true});const fd=fs.openSync(path.join(dir,'server.log'),'w');const server=spawn('python',['tests/journey_fixture_server.py'],{env:{...process.env,MIO_PORT:'18871',MIO_HOST:'127.0.0.1',MIO_DATA_DIR:path.join(dir,'data'),MIO_JOURNEY_PROVIDER_PORT:'18971'},stdio:['ignore',fd,fd]});let b;const report={},errors=[];
try{for(let i=0;i<120;i++){try{if((await fetch(base+'/api/content')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}b=await chromium.launch({args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1568,height:1004},reducedMotion:'reduce'});p.on('pageerror',e=>errors.push(e.message));await p.route(/^https?:\/\//,r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{state.settings.studio.visibility.extensions=true;state.settings.studio.visibility.logs=true;render()});
const nav=async i=>p.locator(`#sidebar [data-act="art-nav"][data-route="${i}"]`).click();
async function scan(name){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));report[name]=await p.evaluate(()=>{const found=[],values=new Set();for(const item of [...state.projects,...state.books,...state.templates,...state.rows,...(state.creation?.plans||[]),...(state.creation?.variableSets||[])]){for(const k of ['title','character','characterName','synopsis','outline'])if(typeof item[k]==='string')values.add(item[k]);for(const f of item.frames||item.steps||[])for(const k of ['name','prompt','caption'])if(typeof f[k]==='string')values.add(f[k])}values.add(workspaceName());for(const w of state.settings.comfy.presets||[])values.add(w.title);for(const p of state.creation?.variableSets||[])for(const g of p.settingsGroups||[])values.add(g.title);for(const c of [...catalog,...state.exportTemplates])values.add(c.title);const isInterfaceText=t=>{for(const v of [...values].filter(v=>typeof v==='string'&&v.length>1).sort((a,b)=>b.length-a.length))t=t.split(v).join('');return /[\u3400-\u9fff]/.test(t)};const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode())){const el=n.parentElement,t=n.nodeValue.trim();if(!/[\u3400-\u9fff]/.test(t)||localeExcludedElement(el)||values.has(t))continue;if(el.tagName==='OPTION'?!el.parentElement.checkVisibility():!el.checkVisibility())continue;found.push({text:t,tag:el.tagName,act:el.closest('[data-act]')?.dataset.act||''})}for(const e of document.querySelectorAll('[aria-label],[title],[placeholder]'))if(e.checkVisibility()&&!e.closest('[data-user-content],[data-no-translate],pre,code'))for(const a of ['aria-label','title','placeholder']){const t=e.getAttribute(a);if(t&&/[\u3400-\u9fff]/.test(t)&&!values.has(t))found.push({text:t,tag:e.tagName,attr:a})}return found.filter(x=>isInterfaceText(x.text))});await p.screenshot({path:path.join(evidence,name+'.png'),animations:'disabled'});fs.writeFileSync(path.join(evidence,'untranslated.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(evidence,'strings.txt'),[...new Set(Object.values(report).flat().map(x=>x.text))].join('\n'));console.log(name,report[name].length)}
await nav(5);await p.locator('[data-act="v3-settings-tab"][data-tab="appearance"]').click();await p.locator('#interface-language').selectOption('en');await p.waitForFunction(()=>document.documentElement.lang==='en');
for(const tab of ['appearance','general','modules','themes','extensions','connections','resources']){await p.locator(`.settings-nav [data-act="v3-settings-tab"][data-tab="${tab}"]`).click();await scan('settings-'+tab)}
await nav(9);await scan('home');await nav(0);await scan('albums');await nav(3);
for(const provider of ['comfyui','novelai','openai']){await p.locator('#image-provider-select').selectOption(provider);await scan(provider);if(provider!=='comfyui'){await p.locator('[data-act="image-provider-keys"]').click();await p.waitForFunction(()=>document.querySelector('#modal').open);await scan(provider+'-keys');await p.locator('#modal [data-act="close-modal"]').first().click()}}
await p.locator('[data-act="image-provider-new"]').click();await scan('new-channel');await p.locator('#modal [data-act="close-modal"]').first().click();await nav(1);
for(const view of ['stories','presets','production']){await p.locator(`[data-act="workshop-tab"][data-view="${view}"]`).click();await scan(view)}
await p.locator('[data-act="assembly-new"]').click();await p.locator('#designer-channel').selectOption('comfyui');await scan('assembly-1');await p.locator('[data-act="designer-next"]').click();await scan('assembly-2');await p.locator('[data-designer-preset]').first().check();await p.locator('[data-act="designer-next"]').click();await scan('assembly-3');await p.locator('#modal [data-act="close-modal"]').first().click();await nav(7);await scan('optional-tools');
await p.locator('[data-act="local-critic-api"]').click();await scan('critic-api');await p.locator('[data-act="critic-close"]').first().click();
await nav(1);await p.locator('[data-act="workshop-tab"][data-view="stories"]').click();await p.locator('.quiet-advanced summary').first().click();await scan('scene-parameters');
await p.locator('[data-act="workshop-tab"][data-view="presets"]').click();while(await p.locator('.group-toggle[aria-expanded="false"]').count())await p.locator('.group-toggle[aria-expanded="false"]').first().click();await scan('preset-expanded');
await p.locator('[data-act="art-setting-add"]').first().click();await scan('preset-new-attribute');await p.locator('#modal [data-act="close-modal"]').first().click();
if(await p.locator('.group-toggle[aria-expanded="false"]').count())await p.locator('.group-toggle[aria-expanded="false"]').first().click();await p.locator('.character-setting').first().hover();await p.locator('[data-act="eco-macro-edit"]:visible').first().click();await scan('computed-variable');await p.locator('#modal [data-act="close-modal"]').first().click();
await p.locator('[data-act="workshop-tab"][data-view="production"]').click();await p.locator('[data-act="assembly-new"]').click();await p.locator('[data-act="designer-mode"][data-mode="canvas"]').click();await p.locator('[data-act="designer-add-story"]').click();await p.locator('[data-act="designer-add-preset"]').click();await scan('assembly-canvas');await p.locator('#modal [data-act="close-modal"]').first().click();
await nav(0);await p.locator('[data-act="read"]').first().click();await p.locator('#reader').waitFor();await scan('reader');await p.locator('#reader [data-act="picture-edit"]').click();await p.locator('#image-studio').waitFor();await p.waitForFunction(()=>!!ComfyComic.pictures.runtime.editor?.image);await p.locator('#image-studio details').last().locator('summary').click();await scan('image-editor');await p.locator('[data-pic="bubble"]').click();await scan('image-layer');await p.locator('[data-pic="close"]').click();await scan('image-discard');await p.locator('#confirm-yes').click();await p.locator('#reader [data-act="presentation-open-export"]').click();await p.locator('.presentation-options summary').click();await scan('export-book');await p.locator('#reader [data-act="close-reader"]').click();
await nav(5);await p.locator('.settings-nav [data-act="v3-settings-tab"][data-tab="resources"]').click();await p.locator('[data-act="guide-open"]').first().click();for(let i=0;i<7;i++){await p.locator(`[data-act="guide-step"][data-index="${i}"]`).click();await scan('guide-'+i)}await p.locator('[data-act="guide-close"]').click();await p.locator('[data-act="github-open"]').first().click();for(const tab of ['publish','manual','import']){await p.locator(`[data-act="github-tab"][data-tab="${tab}"]`).click();await scan('github-'+tab)}await p.locator('[data-act="github-close"]').first().click();
await p.locator('.settings-nav [data-act="v3-settings-tab"][data-tab="modules"]').click();await p.locator('[data-studio-pref="visibility.llm"]').check();await p.locator('[data-studio-pref="visibility.marketplace"]').check();await nav(4);await scan('ai-writing');await p.locator('[data-act="llm-settings"]').first().click();await scan('text-model-settings');await p.locator('#modal [data-act="close-modal"]').first().click();await nav(8);await scan('market');await nav(6);await scan('logs');

fs.writeFileSync(path.join(evidence,'untranslated.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(evidence,'strings.txt'),[...new Set(Object.values(report).flat().map(x=>x.text))].join('\n'));console.log('Browser errors',errors);if(errors.length)throw Error(errors.join(';'));const missing=Object.entries(report).filter(([,items])=>items.length);if(missing.length)throw Error('Untranslated UI: '+JSON.stringify(missing));console.log('LOCALE AUDIT: '+Object.keys(report).length+' UI surfaces, zero untranslated interface labels (authored content excluded)');
}finally{await b?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}fs.closeSync(fd);fs.rmSync(dir,{recursive:true,force:true})}
