// Validate the real ZIP, its launcher, asset paths and migration of a retained data/.
// Run: node tests/package_smoke.mjs /absolute/path/mio-1.2.2-source.zip
import {chromium} from 'playwright';
import {spawn,execFileSync} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync,rmSync,mkdirSync,readdirSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const zip=path.resolve(process.argv[2]||'releases/mio-1.2.2-source.zip');
const temp=mkdtempSync(path.join(tmpdir(),'Mio 中文 path '));
let server,browser;
const check=(label,value)=>{assert.ok(value,label);console.log('PASS '+label)};
try{
 execFileSync('python',['-m','zipfile','-e',zip,temp]);
 const name=readdirSync(temp).find(x=>x.startsWith('mio-')),root=path.join(temp,name);
 const manifest=JSON.parse(readFileSync(path.join(root,'PACKAGE_MANIFEST.json'),'utf8'));
 check('ZIP is a complete independent-JS/CSS project without user data',manifest.kind==='complete-source-runtime'&&!manifest.includesUserData&&!readdirSync(root).includes('data')&&readFileSync(path.join(root,'index.html'),'utf8').includes('/styles.css'));
 execFileSync('python',['-c',`import pathlib,json,hashlib; r=pathlib.Path('.'); m=json.loads((r/'PACKAGE_MANIFEST.json').read_text()); assert all(hashlib.sha256((r/p).read_bytes()).hexdigest()==h for p,h in m['files'].items()); print('PASS every ZIP entry matches its SHA-256 manifest')`],{cwd:root,stdio:'inherit'});
 // Simulate a real retained legacy data directory, not packaged test defaults.
 execFileSync('python',['-c',`from tools.build_release import get_v9_pure_default_data; import pathlib,json; d=pathlib.Path('data');d.mkdir(); data=get_v9_pure_default_data(); data[0]['savedGalleries'][0]['title']='保留用户画册'; [(d/(n+'.json')).write_text(json.dumps(v,ensure_ascii=False),encoding='utf-8') for n,v in zip(['content','ui','chat','comfy','llm','xml_template'],data)]; (d/'user-note.txt').write_text('keep this user file',encoding='utf-8')`],{cwd:root});
 const legacy=readFileSync(path.join(root,'data/content.json'));
 server=spawn('sh',['start.sh'],{cwd:root,env:{...process.env,MIO_PORT:'8803',PYTHONUNBUFFERED:'1'},stdio:['ignore','pipe','pipe']});let logs='';server.stderr.on('data',d=>logs+=d);
 await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('packaged launcher timeout: '+logs)),10000);server.stdout.on('data',d=>{logs+=d;if(d.toString().includes('物理落盘')){clearTimeout(t);resolve()}});server.on('exit',code=>{clearTimeout(t);reject(Error('packaged launcher exited '+code+': '+logs))})});
 const base='http://127.0.0.1:8803';let ready=false;for(let i=0;i<100;i++){try{ready=(await fetch(base+'/api/config')).ok}catch{}if(ready)break;await new Promise(resolve=>setTimeout(resolve,50))}assert.ok(ready,'packaged HTTP listener ready');const config=await(await fetch(base+'/api/config')).json();
 check('packaged launcher starts from a Unicode-and-space path',logs.includes('8803'));
 check('existing user album and legacy originals survive migration',config.savedGalleries[0].title==='保留用户画册'&&legacy.equals(readFileSync(path.join(root,'data/content.json')))&&readFileSync(path.join(root,'data/user-note.txt'),'utf8')==='keep this user file');
 browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage(),errors=[],badAssets=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)badAssets.push(r.url())});await page.route(/^https:\/\//,r=>r.abort());await page.goto(base);await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));
 check('packaged UI runs with all local JS/CSS/vendor assets',await page.evaluate(version=>MIO_VERSION===version&&state.books[0].title==='保留用户画册'&&!!ComfyComic.pictures,manifest.version)&&!errors.length&&!badAssets.length);
 await page.evaluate(()=>openReader(state.books[0].id));await page.locator('#reader-canvas img').evaluate(img=>img.decode());check('retained original image decodes in packaged reader',await page.locator('#reader-canvas img').evaluate(img=>img.naturalWidth>0));
 check('packaged default reader scrolls the album and includes the quiet colophon',await page.evaluate(()=>artUI.readerMode==='webtoon'&&!!$('#reader-canvas [data-mio-colophon]')));
 await page.locator('.presentation-trigger').click();await page.locator('[data-act="presentation-select"][data-id="export-paper"]').click();await page.frameLocator('#presentation-preview').locator('[data-cc-frame]').first().waitFor();await page.evaluate(()=>window.packageFrame=$('#presentation-preview'));await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();check('packaged template drawer closes without replacing loaded iframe',await page.evaluate(()=>window.packageFrame===$('#presentation-preview')));await page.locator('.presentation-trigger').click();await page.locator('[data-act="presentation-select"][data-id="export-afterglow"]').click();await page.frameLocator('#presentation-preview').locator('html.ag-enhanced').waitFor();await page.frameLocator('#presentation-preview').locator('.ag-cover-img').evaluate(i=>i.decode());await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();
 check('packaged AFTERGLOW module registers and enhances the retained album',await page.evaluate(()=>state.exportTemplates.filter(t=>t.id==='export-afterglow').length===1)&&await page.frameLocator('#presentation-preview').locator('body').evaluate(()=>MioAfterglow.frameCount>0)&&await page.locator('#presentation-preview').getAttribute('sandbox')==='allow-scripts');
 const download=page.waitForEvent('download');await page.evaluate(()=>void handleAction('presentation-export',{}));const exportPath=path.join(temp,'packaged-afterglow.html');await(await download).saveAs(exportPath);const offline=await browser.newPage();await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+exportPath);await offline.waitForFunction(()=>!!window.MioAfterglow);check('actual ZIP exports a self-contained working AFTERGLOW album',await offline.locator('.ag-image').evaluateAll(a=>a.length>0&&a.every(i=>i.src.startsWith('data:')))&&await offline.locator('[data-mio-colophon]').count()===1);await offline.close();
 const demo=await browser.newPage();await demo.goto('file://'+path.join(root,'examples/afterglow/余光_AFTERGLOW_演示画册.html'));await demo.waitForFunction(()=>!!window.MioAfterglow);check('packaged demonstration opens directly offline with all four scenes',await demo.locator('.ag-frame').count()===4&&await demo.locator('.ag-cover-img').evaluate(i=>i.decode().then(()=>i.naturalWidth===928)));await demo.close();if(await page.locator('#presentation-drawer').isVisible())await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();
 // Persist an old built-in and a user copy, then exercise a real boot migration.
 await page.evaluate(()=>savePythonWorkspace());await page.goto('about:blank');const retained=await(await fetch(base+'/api/config')).json();const oldTemplate=retained.uiConfig.comfyStudio.exportTemplates.find(t=>t.id==='export-afterglow');oldTemplate.designRevision=1;oldTemplate.version='1.0.0';oldTemplate.html=oldTemplate.html.replace('data-mio-afterglow','data-mio-afterglow data-old-design');retained.uiConfig.comfyStudio.exportTemplates.push({...oldTemplate,id:'retained-afterglow-copy',builtin:false,source:'import'});retained.savedGalleries[0].presentationTemplateId='export-afterglow';retained.expectedRevision=retained.updatedAt;assert.ok((await fetch(base+'/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(retained)})).ok);await page.goto(base);await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));
 check('real saved-template upgrade replaces only the built-in and preserves the chosen album and custom copy',await page.evaluate(()=>{const t=state.exportTemplates.find(t=>t.id==='export-afterglow'),copy=state.exportTemplates.find(t=>t.id==='retained-afterglow-copy');return t.designRevision===2&&!t.html.includes('data-old-design')&&copy.html.includes('data-old-design')&&state.books[0].presentationTemplateId==='export-afterglow'}));await page.evaluate(()=>openReader(state.books[0].id));await page.frameLocator('#presentation-preview').locator('html.ag-enhanced').waitFor();await page.frameLocator('#presentation-preview').locator('.ag-image').first().evaluate(i=>{i.loading='eager';return i.decode()});check('upgraded packaged reader puts the caption directly below its image',await page.frameLocator('#presentation-preview').locator('.ag-frame').first().evaluate(f=>{const image=f.querySelector('.ag-image').getBoundingClientRect(),caption=f.querySelector('.ag-caption').getBoundingClientRect();return caption.top>=image.bottom&&caption.top-image.bottom<24}));
 await page.locator('.presentation-trigger').click();await page.locator('[data-act="presentation-select"][data-id="mio-fit"]').click();await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();
 const docs=await fetch(base+'/docs/RELEASE_1_2_2.html');check('packaged upgrade documentation is served locally',docs.status===200&&(await docs.text()).includes(manifest.version));
 check('packaged editor guide and starter assets are available',(await fetch(base+'/docs/guide/IMAGE_STUDIO.html')).ok&&JSON.parse(readFileSync(path.join(root,'examples/image-assets/starter.json'),'utf8')).schema==='mio.image-assets.v1');
 await page.locator('.picture-reader-edit').click();await page.waitForFunction(()=>ComfyComic.pictures.runtime.editor?.image);await page.locator('[data-pic="bubble"]').click();await page.locator('[data-pic="save"]').click();await page.waitForSelector('#image-studio',{state:'detached'});await page.reload();await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);check('packaged editor saves durable original and editable layer through refresh',await page.evaluate(()=>{const r=state.books[0].pictureEdits[0];return r.recipe.layers.length===1&&r.originalImage&&r.image.startsWith('/images/')}));
 check('private data is not publicly served',(await fetch(base+'/data/user-note.txt')).status===404);
 const requests=[];page.on('request',r=>{if(r.url().includes('/generate'))requests.push(r.url())});await page.evaluate(()=>closeReader());const id=await page.evaluate(()=>state.books[0].id);await page.evaluate(id=>{void deleteBooks([id])},id);await page.locator('#confirm-yes').click();await page.waitForFunction(id=>!bookBy(id),id);await page.reload();await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);
 check('packaged deletion persists through refresh and never generates',await page.evaluate(id=>!bookBy(id),id)&&requests.length===0);
 check('unrelated user file remains byte-for-byte intact',readFileSync(path.join(root,'data/user-note.txt'),'utf8')==='keep this user file');
 console.log('Packaged project acceptance passed (Linux launcher and Chromium). Windows cmd.exe not executed.');
}finally{await browser?.close();if(server&&server.exitCode===null){const done=new Promise(resolve=>server.once('exit',resolve));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
