// Mixed-aspect, durable image editing and safe assets. Chromium + real local Python.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,cpSync,rmSync,mkdirSync,readdirSync,writeFileSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-pictures-')),evidence=process.env.MIO_PICTURE_EVIDENCE||path.join(root,'docs/acceptance-2.2/pictures');mkdirSync(evidence,{recursive:true});
for(const name of [...readdirSync(root).filter(n=>n.endsWith('.py')),'data','backend','index.html','styles.css','favicon.svg','vendor','js','docs'])cpSync(path.join(root,name),path.join(temp,name),{recursive:true,filter:src=>!['runtime','.cache','.write.lock','secrets.json'].includes(path.basename(src))});
const base='http://127.0.0.1:8804';let server,browser,checks=0;const errors=[];const check=(name,value)=>{assert.ok(value,name);console.log('PASS '+name);checks++};
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('wait timeout')}
async function boot(){server=spawn('python',['-u','server.py'],{cwd:temp,env:{...process.env,MIO_PORT:'8804'},stdio:['ignore','pipe','pipe']});server.stderr.on('data',d=>writeFileSync(path.join(evidence,'pictures-server.log'),d,{flag:'a'}));await until(async()=>{try{return (await fetch(base+'/api/config')).ok}catch{return false}})}
async function stop(){const promise=new Promise(r=>server.once('exit',r));server.kill('SIGKILL');await promise}
async function dismiss(p){await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()))}
async function ready(p){await p.waitForFunction(()=>ComfyComic.pictures.runtime.editor?.image&&document.querySelector('#image-studio [role=status]').textContent.includes('px'))}
try{await boot();browser=await chromium.launch({args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:960}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.route(/^https:\/\//,r=>r.abort());await page.goto(base);await dismiss(page);
const id=await page.evaluate(async()=>{state.queue=[];const b=clone(state.books[0]);b.id='picture-fixture';b.title='山海之间 · 混合尺寸画册';b.curatedDemo=false;b.demoContentRevision=0;b.inProgress=false;b.steps=[];delete b.pictureEdits;delete b.coverPresentation;const sizes=[[1600,900],[800,1200],[240,160],[800,800],[400,1400]];for(let i=0;i<sizes.length;i++){const [w,h]=sizes[i],c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,['#acc9ca','#dfb6a5','#f1d0a0','#abbca5','#bbb4cc'][i]);g.addColorStop(1,'#354f61');x.fillStyle=g;x.fillRect(0,0,w,h);x.fillStyle='#e7dab9';x.beginPath();x.arc(w*.72,h*.26,Math.min(w,h)*.12,0,Math.PI*2);x.fill();for(let j=0;j<3;j++){x.fillStyle=['#819b9b','#587377','#314f5b'][j];x.beginPath();x.moveTo(0,h);x.lineTo(0,h*(.5+j*.13));for(let k=0;k<=8;k++)x.lineTo(w*k/8,h*(.48+j*.14+Math.sin(k*1.4+i+j)*.12));x.lineTo(w,h);x.closePath();x.fill()}x.fillStyle='#ffffff';x.font=`${Math.max(12,w*.035)}px sans-serif`;x.fillText(`${w} × ${h}`,w*.06,h*.92);const url=(await foundationRequest('assets/upload',{dataUrl:c.toDataURL(),name:'landscape-'+i+'.png'})).url;b.steps.push({stepIndex:i,name:['横幅 · 海岸','竖幅 · 远山','小图 · 黄昏','方形 · 林间','长幅 · 山谷'][i],caption:'完整画面、安静留白，与不同尺寸的作品一起阅读。',prompt:'controlled fixture',image:url,width:w,height:h})}b.totalSteps=5;b.generatedSteps=5;b.status='complete';state.books=[b,...b.steps.slice(1).map((s,i)=>({...clone(b),id:'cover-'+i,title:['远山来信','小小的黄昏','森林日记','山谷回声'][i],steps:[{...s,stepIndex:0}],totalSteps:1,generatedSteps:1}))];state.settings.presentation.homeLayout='grid';render();save(true);if(!await savePythonWorkspace())throw Error('seed save failed');return b.id});
await page.waitForTimeout(1000);check('square cover grid is independent of source ratio',await page.evaluate(()=>Array.from(document.querySelectorAll('.shelf-grid .shelf-cover')).every(e=>{const r=e.getBoundingClientRect();return Math.abs(r.width-r.height)<2})));await page.screenshot({path:path.join(evidence,'pictures-grid-dark.png')});
await page.evaluate(id=>openArtReader(id),id);await page.locator('.picture-reader-edit').click();await ready(page);check('editor opens from reader without any provider job',await page.evaluate(()=>ComfyComic.pictures.runtime.editor.index===0&&state.queue.length===0));
await page.locator('[data-pic="bubble"]').click();await page.locator('#pic-text').fill('你好，山海。');await page.locator('#pic-text').blur();await page.locator('[data-layer="shape"]').selectOption('ellipse');await page.locator('[data-pic="rotate"]').click();await page.locator('[data-pic="flipX"]').click();await page.locator('#pic-ratio').selectOption('1');await page.locator('[data-tone="brightness"]').fill('1.12');await page.locator('[data-tone="brightness"]').dispatchEvent('change');check('crop and rotation keep native square output',await page.evaluate(()=>document.querySelector('#pic-canvas').width===900&&ComfyComic.pictures.runtime.editor.recipe.rotation===90));
await page.locator('[data-pic="undo"]').click();await page.locator('[data-pic="redo"]').click();check('undo and redo retain layer text',await page.evaluate(()=>ComfyComic.pictures.runtime.editor.recipe.layers[0].text==='你好，山海。'));
const h=page.locator('[data-layer-hit="0"]'),box=await h.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.5+25,box.y+box.height*.5+20);await page.mouse.up();check('pointer drag edits normalized layer coordinates',await page.evaluate(()=>ComfyComic.pictures.runtime.editor.recipe.layers[0].x>.1));
const safe='<svg xmlns="http://www.w3.org/2000/svg" width="140" height="140"><path d="M70 5 88 47 134 50 100 82 112 132 70 107 28 132 40 82 6 50 52 47Z" fill="#efcf71" stroke="#343434" stroke-width="3"/></svg>';
await page.locator('#pic-assets-file').setInputFiles({name:'star.svg',mimeType:'image/svg+xml',buffer:Buffer.from(safe)});await page.waitForFunction(()=>state.settings.imageAssets?.length===1);await page.locator('[data-pic="sticker"]').click();await page.locator('#pic-assets-file').setInputFiles(path.join(root,'examples/image-assets/starter.json'));await page.waitForFunction(()=>state.settings.imageAssets.length===4);check('JSON starter pack imports three safe extensible assets',await page.locator('#pic-library img').count()===4);check('safe SVG rasterizes to local PNG sticker',await page.evaluate(()=>ComfyComic.pictures.runtime.editor.recipe.layers[1].asset.endsWith('.png')));
check('executable/external SVG rejected before image load',await page.evaluate(async()=>{let rejected=0;for(const svg of ['<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>','<svg xmlns="http://www.w3.org/2000/svg" onload="alert(1)"></svg>','<svg xmlns="http://www.w3.org/2000/svg"><image href="https://evil.invalid/x"/></svg>','<!DOCTYPE svg [<!ENTITY a "x">]><svg xmlns="http://www.w3.org/2000/svg"/>'])try{await ComfyComic.pictures.safeSVG(svg)}catch{rejected++}return rejected===4}));
await page.locator('[data-position="x"]').fill('62');await page.locator('[data-position="x"]').blur();await page.locator('[data-position="y"]').fill('68');await page.locator('[data-position="y"]').blur();await page.locator('#image-studio').screenshot({path:path.join(evidence,'pictures-editor-desktop-dark.png')});await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.waitForTimeout(400);await page.locator('#image-studio').screenshot({path:path.join(evidence,'pictures-editor-desktop-light.png')});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.waitForTimeout(400);await page.locator('[data-pic="save"]').click();await page.waitForSelector('#image-studio',{state:'detached'});check('save commits edited raster plus editable source and layers',await page.evaluate(id=>{const r=bookBy(id).pictureEdits[0];return r.revision===1&&r.recipe.layers.length===2&&r.width===900&&r.height===900&&r.image!==r.originalImage&&r.sourceImage===r.originalImage},id));
await page.locator('.picture-reader-edit').click();await ready(page);check('reopen restores editable layers',await page.locator('#pic-layers button').count()===2);await page.locator('summary').filter({hasText:'封面缩略图'}).click();await page.locator('#pic-cover-fit').selectOption('contain');await page.locator('#pic-cover-x').fill('30');await page.locator('#pic-cover-x').blur();await page.locator('[data-pic="cover"]').click();check('cover focal settings do not crop reading image',await page.evaluate(id=>bookBy(id).coverPresentation.x===30&&bookBy(id).pictureEdits[0].width===900,id));await page.locator('[data-pic="close"]').click();
// Native small-image ceiling in both focus and continuous layouts.
await page.evaluate(()=>{bookBy(ui.bookId).nativeReaderMode='gallery';artUI.readerMode='gallery';setArtStep(2)});await page.locator('#reader-canvas img').evaluate(i=>i.decode());check('small image never silently upscales in focus',await page.locator('#reader-canvas img').evaluate(i=>i.getBoundingClientRect().width<=i.naturalWidth+1&&i.getBoundingClientRect().height<=i.naturalHeight+1));
await page.evaluate(()=>{artUI.readerMode='webtoon';renderArtReader()});await page.locator('#reader-canvas img').first().evaluate(i=>i.decode());check('continuous layout keeps complete ratios and small-image ceiling',await page.locator('#reader-canvas img').evaluateAll(images=>images.every(i=>{const r=i.getBoundingClientRect();return r.width<=i.naturalWidth+1&&Math.abs(r.width/r.height-i.naturalWidth/i.naturalHeight)<.02})));await page.locator('#reader').screenshot({path:path.join(evidence,'pictures-scroll-desktop-dark.png')});
await page.evaluate(()=>{artUI.readerMode='spread';ui.step=2;renderArtReader()});await page.waitForTimeout(100);check('wide pages switch spread to full-width stacked stage',await page.locator('.picture-wide-spread').count()===1);
// Mobile editor in both themes.
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{artUI.readerMode='gallery';ui.step=0;renderArtReader()});await page.locator('.picture-reader-edit').click();await ready(page);for(const theme of ['dark','light']){await page.evaluate(theme=>{state.settings.theme=theme;document.documentElement.dataset.theme=theme},theme);await page.waitForTimeout(400);await page.locator('#image-studio').screenshot({path:path.join(evidence,`pictures-editor-mobile-${theme}.png`)});check('mobile '+theme+' editor has no horizontal overflow',await page.locator('#image-studio').evaluate(e=>e.scrollWidth<=e.clientWidth+1))}await page.locator('[data-pic="close"]').click();
// Controlled HTTP error and dropped response keep draft; no automatic mutation retry.
await page.evaluate(()=>setArtStep(4));await page.locator('.picture-reader-edit').click();await ready(page);await page.locator('[data-pic="text"]').click();let attempts=0;await page.route('**/api/foundation/albums/page',async r=>{attempts++;await r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'controlled save unavailable'})})});await page.locator('[data-pic="save"]').click();await page.waitForFunction(()=>!ComfyComic.pictures.runtime.editor.busy&&document.querySelector('#image-studio [role=status]').textContent.includes('503'));check('HTTP 503 leaves editable draft without committing',await page.evaluate(id=>!bookBy(id).pictureEdits[4]&&ComfyComic.pictures.runtime.editor.dirty,id));await page.unroute('**/api/foundation/albums/page');await page.route('**/api/foundation/albums/page',async r=>{attempts++;await r.fetch();await r.abort('connectionfailed')});await page.locator('[data-pic="save"]').click();await page.waitForFunction(()=>!ComfyComic.pictures.runtime.editor.busy);await page.waitForTimeout(2000);check('lost response never auto-retries mutation',attempts===2);check('lost response after commit remains recoverable from server',await page.evaluate(async id=>{const c=await(await fetch('/api/config')).json();return c.savedGalleries.find(b=>b.id===id).pictureEdits[4].recipe.layers.length===1},id));await page.unroute('**/api/foundation/albums/page');await page.locator('[data-pic="close"]').click();await page.locator('#confirm-yes').click();
// Remove persists; initial restore and local replacement.
await page.evaluate(()=>setArtStep(1));await page.locator('.picture-reader-edit').click();await ready(page);await page.locator('[data-pic="remove"]').click();await page.locator('#confirm-yes').click();await page.waitForSelector('#image-studio',{state:'detached'});check('single image removal keeps storyboard and excludes automatic refill',await page.evaluate(id=>{const b=bookBy(id);return b.totalSteps===5&&b.steps[1].caption&&!b.steps[1].image&&!missingIndices(b).includes(1)&&b.pictureEdits[1].removed},id));
await page.reload();await dismiss(page);await page.evaluate(id=>Mio.fileLibrary.hydrate(id),id);check('refresh does not resurrect removed image',await page.evaluate(id=>bookBy(id).pictureEdits[1].removed&&!bookBy(id).steps[1].image,id));await stop();await boot();await page.reload();await dismiss(page);await page.evaluate(id=>Mio.fileLibrary.hydrate(id),id);check('hard service restart retains edits and removal',await page.evaluate(id=>bookBy(id).pictureEdits[0].recipe.layers.length===2&&!bookBy(id).steps[1].image,id));
await page.evaluate(id=>{openArtReader(id);setArtStep(1)},id);await page.locator('.picture-reader-edit').click();await ready(page);await page.locator('[data-pic="restore"]').click();await page.locator('#confirm-yes').click();await page.waitForSelector('#image-studio',{state:'detached'});check('restore returns exact original image reference',await page.evaluate(id=>{const r=bookBy(id).pictureEdits[1];return r.image===r.originalImage&&!r.removed},id));
await page.locator('.picture-reader-edit').click();await ready(page);const png=await page.evaluate(id=>imageData(bookBy(id).steps[2].image),id);await page.locator('#pic-replace-file').setInputFiles({name:'local.png',mimeType:'image/png',buffer:Buffer.from(png.split(',')[1],'base64')});await page.waitForFunction(()=>ComfyComic.pictures.runtime.editor.image.naturalWidth===240);await page.locator('[data-pic="save"]').click();await page.waitForSelector('#image-studio',{state:'detached'});check('replacement preserves initial original for later restoration',await page.evaluate(id=>{const r=bookBy(id).pictureEdits[1];return r.width===240&&r.image!==r.originalImage},id));
// A second tab edits while draft is open: no overwrite of the newer image.
const second=await context.newPage();await second.goto(base);await dismiss(second);await second.evaluate(id=>Mio.fileLibrary.hydrate(id),id);await page.evaluate(()=>setArtStep(0));await page.locator('.picture-reader-edit').click();await ready(page);await page.locator('[data-pic="bubble"]').click();const previous=await page.evaluate(()=>({revision:ComfyComic.pictures.runtime.editor.revision,image:ComfyComic.pictures.runtime.editor.expectedImage}));await second.evaluate(async id=>{const b=bookBy(id),r=b.pictureEdits[0];await foundationRequest('albums/page',{albumId:id,index:0,action:'remove',expectedRevision:r.revision,expectedImage:b.steps[0].image})},id);await page.locator('[data-pic="save"]').click();await page.waitForFunction(()=>!ComfyComic.pictures.runtime.editor.busy&&document.querySelector('#image-studio [role=status]').textContent.includes('更新'));check('stale draft receives conflict and retains editable layers',await page.evaluate(()=>ComfyComic.pictures.runtime.editor.recipe.layers.length===3));await page.locator('[data-pic="close"]').click();await page.locator('#confirm-yes').click();
// Stale config projection must not resurrect a removed image.
check('stale ordinary save cannot resurrect overridden image',await second.evaluate(async({id,previous})=>{const config=await(await fetch('/api/config')).json(),b=config.savedGalleries.find(b=>b.id===id);delete b.pictureEdits;b.steps[0].image=previous.image;b.generatedSteps=b.steps.filter(s=>s.image).length;config.expectedRevision=config.updatedAt;const result=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});const stored=await(await fetch('/api/config')).json();return result.status===409&&!stored.savedGalleries.find(b=>b.id===id).steps[0].image},{id,previous}));
// Restore edited page for offline export, verify full-resolution raster in downloaded HTML.
await page.reload();await dismiss(page);await page.evaluate(id=>Mio.fileLibrary.hydrate(id),id);await page.evaluate(async id=>{const b=bookBy(id),r=b.pictureEdits[0];const result=await foundationRequest('albums/page',{albumId:id,index:0,action:'save',expectedRevision:r.revision,expectedImage:'',image:r.previousImage,sourceImage:r.sourceImage,recipe:r.recipe});ComfyComic.pictures.apply(result.edit);openArtReader(id)},id);const download=page.waitForEvent('download');await page.evaluate(()=>{beginExportPreview();void compileCustomExport()});const file=await download;const dest=path.join(evidence,'pictures-offline.html');await file.saveAs(dest);const offline=await context.newPage();await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+dest);await offline.locator('img').first().evaluate(i=>i.decode());check('offline HTML embeds edited native-resolution raster',await offline.locator('img').first().evaluate(i=>i.src.startsWith('data:')&&i.naturalWidth===900&&i.naturalHeight===900));
// Existing refinement action must use the same authoritative image commit, not silently revert.
check('controlled refinement of edited page commits new source without losing initial original',await page.evaluate(async id=>{const b=bookBy(id),original=b.pictureEdits[0].originalImage,previous=generateFrame;try{generateFrame=async()=>({image:b.steps[2].image,offlineFallback:false});ui.bookId=id;await redrawStep(0);const c=await(await fetch('/api/config')).json(),r=c.savedGalleries.find(b=>b.id===id).pictureEdits[0];return r.image===b.steps[2].image&&r.originalImage===original&&r.recipe.layers.length===0}finally{generateFrame=previous}},id));
check('directory export hydrates untouched albums and includes editable originals and sticker assets',await page.evaluate(async()=>{const pack=await buildDiskPackage(state),json=await Promise.all([...pack.files].filter(([p])=>p.endsWith('.json')).map(async([,v])=>typeof v==='string'?v:await v.text()));return json.some(s=>s.includes('pictureEdits')&&s.includes('__cc_asset'))&&!json.some(s=>/"(?:sourceImage|originalImage|asset|url)":\s*"\/images\//.test(s))}));
check('no uncaught browser errors',errors.length===0);console.log(`${checks} picture checks passed`);
}finally{await browser?.close();if(server?.exitCode===null)await stop();rmSync(temp,{recursive:true,force:true})}
