// Actual preset selector deletion: native persistence, values, image ownership and failed saves.
import {chromium} from 'playwright';import {spawn} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync,readdirSync,mkdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-preset-delete-')),data=path.join(temp,'data'),base='http://127.0.0.1:8867',evidence=path.join(process.cwd(),'docs/acceptance-'+JSON.parse(readFileSync(path.join(root,'package.json'))).version);mkdirSync(evidence,{recursive:true});
let browser,p,count=0,paid=0;const errors=[],check=(n,v)=>{assert.ok(v,n);console.log('PASS '+n);count++};
const server=spawn('python',['-u',path.join(root,'server.py')],{cwd:root,env:{...process.env,MIO_PORT:'8867',MIO_DATA_DIR:data},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});
async function api(){return (await fetch(base+'/api/config')).json()}
async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{guidePreferences().seen=true;state.settings.identity.onboarded=true;createUI.welcomePending=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());createUI.tab='settings';navigate(1);openPresetLibrary()});await p.waitForFunction(()=>!rt.contextLoading&&(!creationTask()||!bookBy(creationTask().bookId)?._lazy))}
async function library(){if(!await p.locator('#modal[open] #preset-library').count())await p.evaluate(()=>openPresetLibrary())}
async function select(id){if(!id){await p.evaluate(()=>{closeModal();selectSettingPreset('');render()});return}await library();await p.locator('#art-setting-preset').selectOption(id)}
function edit(s){return '#modal[open] #preset-library '+s+',body:not(:has(#modal[open] #preset-library)) #main '+s}
async function remove(yes=true){await library();await p.locator('[data-act="ws-delete-preset"]').click();await p.locator('#confirm-dialog').waitFor();await p.locator(yes?'#confirm-yes':'#confirm-no').click()}
try{
 for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)break}catch{}await new Promise(r=>setTimeout(r,40))}
 browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST'&&/api\/image\/generate|api\/foundation\/jobs$/.test(r.url()))paid++});await load();
 check('preset delete is beside the selector and disabled without a selection',await p.locator('.preset-library-index [data-act="ws-delete-preset"]').isVisible()&&await p.locator('[data-act="ws-delete-preset"]').isDisabled());
 await p.locator('[data-act="ws-new-preset"]').click();await p.locator('#text-value').fill('可以删除的新预设');await p.locator('[data-act="text-submit"]').click();await p.waitForFunction(()=>settingPresetSelection()&&setBy(settingPresetSelection()).title==='可以删除的新预设');const blank=await p.evaluate(()=>settingPresetSelection());await p.evaluate(()=>savePythonWorkspace());
 check('new blank preset is selected and can immediately be deleted',!await p.locator('[data-act="ws-delete-preset"]').isDisabled());const untouchedPlan=await p.evaluate(()=>JSON.stringify(selectedPlan()));await remove(false);check('cancel retains the preset draft and leaves the album plan unchanged',await p.evaluate(({id,plan})=>!!setBy(id)&&settingPresetSelection()===id&&JSON.stringify(selectedPlan())===plan,{id:blank,plan:untouchedPlan}));await p.locator('[data-act="art-apply-preset"]').click();await p.locator('#confirm-yes').click();await p.waitForFunction(()=>selectedPlan().variables.length===5&&selectedPlan().variableSetIds.length===0);
 const beforeBlank=await p.evaluate(()=>JSON.stringify(effectivePlanScope(selectedPlan()).values));await remove();await p.waitForFunction(id=>!setBy(id),blank);await p.waitForFunction(()=>!Mio.sync.runtime.dirty&&!Mio.sync.runtime.saving);check('one confirmation deletes the file while keeping applied blank values',await p.evaluate(({id,before})=>!setBy(id)&&JSON.stringify(effectivePlanScope(selectedPlan()).values)===before,{id:blank,before:beforeBlank})&&!(await api()).uiConfig.comfyStudio.creation.variableSets.some(s=>s.id===blank));
 await load();check('deleted preset stays deleted after reload',await p.evaluate(id=>!setBy(id),blank));
 const fixture=await p.evaluate(async()=>{
   await Mio.fileLibrary.hydrateAll();const plan=selectedPlan(),frame=templateBy(plan.templateId).frames[0],projectId=state.activeProjectId;
   const entry=(key,value)=>({id:uid('var'),key,type:'text',value});const a={id:uid('set'),projectId,title:'被删除的共享预设',entries:[entry('shared','原值'),entry('later','被后面覆盖'),entry('local','被本册覆盖'),{id:uid('var'),key:'参考',type:'image',value:await storeVariableAsset(defaultCuratedCover(),'保留参考图')}]};
   const b={id:uid('set'),projectId,title:'仍然共享的其他预设',entries:[entry('later','后面的值')]};state.creation.variableSets.push(a,b);
   plan.variableSetIds=[a.id,b.id];plan.variables=[entry('local','本册值')];plan.editingPresetId=a.id;plan.sceneOverrides[frame.id]={variableSetIds:[a.id,b.id],variables:[entry('shared','单幕值')],caption:'单幕台词不变'};
   const second={...clone(plan),id:uid('plan'),title:'第二本计划',variableSetIds:[a.id],variables:[],sceneOverrides:{}};state.creation.plans.push(second);
   const source=state.books[0],book={...clone(source),id:uid('book'),title:'仅变量导入的画册',importedVariableSetIds:[a.id]};delete book.sourceSnapshot;book.rowId='unassigned';book.templateId='unassigned';delete book._lazy;state.books.push(book);
   // A frozen, unsubmitted snapshot exercises preservation without contacting a model.
   plan.storyVersionId='';for(const f of templateBy(plan.templateId).frames){f.prompt='受控静止快照 {shared}';f.negative='';f.caption='冻结台词'}const queued=enqueuePlanSnapshot(plan,null,[0]);state.queue.find(q=>q.bookId===queued.id).status='paused';
   save();if(!await savePythonWorkspace())throw Error(Mio.sync.runtime.error);return {id:a.id,other:b.id,plan:plan.id,frame:frame.id,book:book.id};
 });
 await load();check('lazy album summary exposes only preset IDs needed for safe deletion',await p.evaluate(f=>bookBy(f.book)._lazy&&bookBy(f.book).importedVariableSetIds.includes(f.id)&&bookBy(f.book).steps.length===0,fixture));
 const diskBefore=readdirSync(path.join(data,'albums'),{withFileTypes:true}).filter(f=>f.isDirectory()).map(f=>{const file=path.join(data,'albums',f.name,'album.json'),bytes=readFileSync(file,'utf8');return {file,bytes,id:JSON.parse(bytes).id}}).filter(b=>b.id!==fixture.book);
 const before=await p.evaluate(f=>{const p=state.creation.plans.find(x=>x.id===f.plan),shape=v=>JSON.stringify(Object.fromEntries(Object.entries(v).sort()),(k,x)=>k==='src'&&typeof x==='string'?x.split('/').at(-1):x);return {global:shape(effectivePlanScope(p).values),scene:shape(effectivePlanScope(p,{id:f.frame}).values),queue:JSON.stringify(state.queue),books:JSON.stringify(state.books.filter(b=>b.id!==f.book)),other:JSON.stringify(setBy(f.other))}},fixture);
 await select(fixture.id);
 for(const [width,theme]of[[1440,'light'],[390,'dark'],[320,'light']]){await p.setViewportSize({width,height:900});await p.evaluate(theme=>{state.settings.studio.appearance.theme=theme;render()},theme);await p.locator('.preset-library-index').scrollIntoViewIfNeeded();check(`${width} ${theme} selector actions fit the viewport`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.screenshot({path:path.join(evidence,`preset-controls-${width}-${theme}.png`)})}
 await p.locator('[data-act="ws-delete-preset"]').click();check('confirmation discloses references and retains used values, not a second abandonment prompt',await p.locator('#confirm-dialog').innerText().then(t=>t.includes('2 份')&&t.includes('正在使用的值和参考图')));await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,'preset-delete-confirm-mobile.png')});await p.locator('#confirm-yes').click();await p.waitForFunction(id=>!setBy(id),fixture.id);await p.waitForFunction(()=>!Mio.sync.runtime.dirty&&!Mio.sync.runtime.saving);
 check('global and per-scene precedence remains identical after detaching the deleted preset',await p.evaluate(({f,b})=>{const p=state.creation.plans.find(x=>x.id===f.plan),shape=v=>JSON.stringify(Object.fromEntries(Object.entries(v).sort()),(k,x)=>k==='src'&&typeof x==='string'?x.split('/').at(-1):x);return !setBy(f.id)&&shape(effectivePlanScope(p).values)===b.global&&shape(effectivePlanScope(p,{id:f.frame}).values)===b.scene&&p.variableSetIds.includes(f.other)&&!p.editingPresetId},{f:fixture,b:before}));
 check('other presets, queued snapshots and unrelated album summaries remain unchanged',await p.evaluate(({f,b})=>JSON.stringify(setBy(f.other))===b.other&&JSON.stringify(state.queue)===b.queue&&JSON.stringify(state.books.filter(x=>x.id!==f.book))===b.books,{f:fixture,b:before})&&diskBefore.every(({file,bytes})=>readFileSync(file,'utf8')===bytes));
 const urls=await p.evaluate(f=>{const p=state.creation.plans.find(x=>x.id===f.plan),b=bookBy(f.book);return [effectivePlanScope(p).values['参考'].src,albumSharedSources(b,{embedVariables:true}).variables.entries.find(e=>e.key==='参考').value.src]},fixture);
 check('used reference images belong to surviving owners, not the deleted preset',urls[0].includes('/plans/')&&urls[1].includes('/albums/')&&urls.every(u=>!u.includes(fixture.id)));
 for(const u of urls)check('retained reference image bytes are readable',Buffer.from(await(await fetch(base+u)).arrayBuffer()).length>1000);
 await load();await p.evaluate(f=>Mio.fileLibrary.hydrate(f.book),fixture);check('reload keeps the preset deleted and variables-only album exportable',await p.evaluate(f=>!setBy(f.id)&&albumSharedSources(bookBy(f.book),{embedVariables:true}).variables.entries.some(e=>e.key==='参考'),fixture));
 // Rejected deletion is atomic; the UI must not claim a confirmed disk deletion.
 const fail=await p.evaluate(async()=>{const s={id:uid('set'),projectId:state.activeProjectId,title:'保存失败不能假装删除',entries:[]};state.creation.variableSets.push(s);save();await savePythonWorkspace();render();return s.id});await select(fail);
 await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:'受控版本冲突'})}):r.continue());await remove();await p.waitForFunction(()=>Mio.sync.runtime.error.includes('冲突'));check('409 leaves original disk resource and an explicit unconfirmed local draft',(await api()).uiConfig.comfyStudio.creation.variableSets.some(s=>s.id===fail)&&await p.evaluate(()=>Mio.sync.runtime.dirty)&&await p.locator('.toast').allTextContents().then(a=>a.some(x=>x.includes('删除尚未确认'))));await p.unroute('**/api/config');await load();
 await select(fail);await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'受控服务错误'})}):r.continue());await remove();await p.waitForFunction(()=>Mio.sync.runtime.error.includes('500'));check('500 never claims a completed deletion or discards the local draft',(await api()).uiConfig.comfyStudio.creation.variableSets.some(s=>s.id===fail)&&await p.evaluate(()=>Mio.sync.runtime.dirty));await p.unroute('**/api/config');await load();
 const lost=await p.evaluate(async()=>{const p=selectedPlan(),s={id:uid('set'),projectId:state.activeProjectId,title:'响应丢失的删除',entries:[{id:uid('var'),key:'lostRef',type:'image',value:await storeVariableAsset(defaultCuratedCover(),'引用图')}]};state.creation.variableSets.push(s);p.variableSetIds.push(s.id);save();await savePythonWorkspace();render();return s.id});await select(lost);
 await p.route('**/api/config',async r=>{if(r.request().method()!=='POST')return r.continue();await r.fetch();await r.abort()});await remove();await p.waitForFunction(()=>Mio.sync.runtime.dirty&&!!Mio.sync.runtime.error);check('lost acknowledgement is shown as unconfirmed even if the server committed deletion',!(await api()).uiConfig.comfyStudio.creation.variableSets.some(s=>s.id===lost)&&await p.evaluate(()=>Mio.sync.runtime.dirty));await p.unroute('**/api/config');check('normal save retry is idempotent and retains the copied reference',await p.evaluate(async id=>await savePythonWorkspace()&&!setBy(id)&&effectivePlanScope(selectedPlan()).values.lostRef.src.includes('/plans/'),lost));await load();
 const folder=path.join(data,'presets/characters'),file=readdirSync(folder).find(n=>n.endsWith('.json')&&JSON.parse(readFileSync(path.join(folder,n))).id===fail),raw=JSON.parse(readFileSync(path.join(folder,file)));raw.id='copied_new_identity';raw.title='文件管理器追加的新预设';writeFileSync(path.join(folder,'追加的新文件.json'),JSON.stringify(raw));await load();check('a distinct native file and ID append a preset without overwriting the original',await p.evaluate(id=>!!setBy(id)&&!!setBy('copied_new_identity'),fail));
 const original=readFileSync(path.join(folder,file),'utf8');raw.id=fail;raw.title='同 ID 的冲突副本';writeFileSync(path.join(folder,'同ID副本.json'),JSON.stringify(raw));await load();check('same ID under another filename is diagnosed, not silently merged or treated as a new preset',(await api())._libraryProblems.length>0&&readFileSync(path.join(folder,file),'utf8')===original);
 check('no browser exceptions or generation submissions',errors.length===0&&paid===0);console.log(`${count} preset deletion checks PASS`);
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
