import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {mkdtempSync,mkdirSync,rmSync,readFileSync,readdirSync,writeFileSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-preset-isolation-')),base='http://127.0.0.1:8870',evidence=path.join(process.cwd(),'docs/acceptance-'+JSON.parse(readFileSync(path.join(root,'package.json'))).version);mkdirSync(evidence,{recursive:true});
let browser,p,n=0,paid=0;const errors=[],check=(name,v)=>{assert.ok(v,name);console.log('PASS '+name);n++};const server=spawn('python',['-u',path.join(root,'server.py')],{cwd:root,env:{...process.env,MIO_PORT:'8870',MIO_DATA_DIR:path.join(temp,'data')},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});
async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{guidePreferences().seen=true;state.settings.identity.onboarded=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close());createUI.tab='settings';navigate(1);openPresetLibrary()})}
async function library(){if(!await p.locator('#modal[open] #preset-library').count())await p.evaluate(()=>openPresetLibrary())}
async function select(id){if(!id){await p.evaluate(()=>{closeModal();selectSettingPreset('');render()});return}await library();await p.locator('#art-setting-preset').selectOption(id)}
function edit(s){return '#modal[open] #preset-library '+s+',body:not(:has(#modal[open] #preset-library)) #main '+s}
async function named(action,name){await library();await p.locator(edit('[data-act="'+action+'"]')).click();await p.locator('#text-value').fill(name);await p.locator('[data-act="text-submit"]').click()}
async function add(key,type='text'){await p.locator(edit('[data-act="art-setting-add"]')).click();await p.locator('#art-new-setting-key').fill(key);await p.locator('#art-new-setting-type').selectOption(type);await p.locator('#modal [data-act="art-setting-confirm"]').click()}
function presetFiles(){const folder=path.join(temp,'data/presets/characters');return Object.fromEntries(readdirSync(folder).filter(f=>f.endsWith('.json')).map(f=>[f,readFileSync(path.join(folder,f),'utf8')]))}
async function diskSet(id){return (await(await fetch(base+'/api/config')).json()).uiConfig.comfyStudio.creation.variableSets.find(s=>s.id===id)}
async function saved(){assert.ok(await p.evaluate(()=>savePythonWorkspace()))}
async function update(){await library();await p.locator('[data-act="ws-update-preset"]').click();await p.waitForFunction(()=>!Mio.sync.runtime.dirty&&!Mio.sync.runtime.saving)}
try{
 for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)break}catch{}await new Promise(r=>setTimeout(r,40))}
 browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST'&&/api\/image\/generate|api\/foundation\/jobs$/.test(r.url()))paid++});await p.route(/^https:\/\//,r=>r.abort());await load();
 const initial=await p.evaluate(async()=>{await Mio.fileLibrary.hydrateAll();save();await savePythonWorkspace();return {id:state.creation.variableSets[0].id,source:JSON.stringify(state.creation.variableSets[0]),plan:JSON.stringify(selectedPlan()),books:JSON.stringify(state.books),queue:JSON.stringify(state.queue)}});
 const diskBefore=presetFiles();
 await named('ws-new-preset','预设 B');const b=await p.evaluate(()=>settingPresetSelection());if(!process.argv.includes('--reproduce-221'))await p.locator(edit('[data-art-setting="character"]')).fill('B 的角色');await named('art-save-preset','预设 C');const c=await p.evaluate(()=>settingPresetSelection());await add('自定义变量');await p.locator(edit('[data-art-setting="自定义变量"]')).fill('111');await select(initial.id);
 if(process.argv.includes('--reproduce-221')){console.log('REPRODUCED',await p.evaluate(()=>({selected:settingPresetSelection(),updateTarget:selectedPlan().editingPresetId,displayedCharacter:document.querySelector('[data-art-setting="character"]').value,storedSelected:setBy(settingPresetSelection()).entries.find(e=>e.key==='character').value})));assert.notEqual(await p.locator(edit('[data-art-setting="character"]')).inputValue(),'nanami');console.log('PASS reproduced blank fields after switching to a populated preset in 2.2.1');await update();await saved();assert.ok((await diskSet(b)).entries.some(e=>e.key==='自定义变量'&&e.value==='111'));assert.equal((await diskSet(initial.id)).entries.find(e=>e.key==='character').value,'nanami');console.log('PASS reproduced actual wrong-target write: Update writes B while the selector names the original preset');process.exitCode=0;
 }else{
 check('exact reported flow returns to the original preset content, not the new blank editor',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='nanami');
 check('original preset, current album plan, books and queued snapshots remain unchanged',await p.evaluate(s=>JSON.stringify(setBy(s.id))===s.source&&JSON.stringify(selectedPlan())===s.plan&&JSON.stringify(state.books)===s.books&&JSON.stringify(state.queue)===s.queue,initial));
 await select(b);check('new preset B retains its own draft across switching',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='B 的角色'&&await p.locator(edit('[data-art-setting="自定义变量"]')).count()===0);
 await select(c);check('Save As creates a separate C draft and owns the subsequently added variable',await p.locator(edit('[data-art-setting="自定义变量"]')).inputValue()==='111'&&await p.locator(edit('[data-art-setting="character"]')).inputValue()==='B 的角色');
 const beforeB=await p.evaluate(id=>JSON.stringify(setBy(id)),b);await update();check('Update saves only the preset named in the selector',await p.evaluate(({b,c,initial})=>JSON.stringify(setBy(b))===initial.b&&JSON.stringify(setBy(initial.id))===initial.source&&setBy(c).entries.some(e=>e.key==='自定义变量'&&e.value==='111'),{b,c,initial:{...initial,b:beforeB}}));
 await p.locator(edit('[data-art-setting="character"]')).fill('C 的新草稿');await add('参考图','image');const upload=p.locator(edit('[data-image-key="参考图"] input'));let release,ready;const started=new Promise(r=>ready=r);
 await p.route('**/api/store-image',async r=>{await new Promise(resolve=>{release=resolve;ready()});await r.continue()});await upload.setInputFiles(path.join(root,'examples/afterglow/cover.webp'));await started;await select(b);release();await p.waitForFunction(id=>state.drafts.presetEdits[id].variables.find(e=>e.key==='参考图')?.value?.src,c);await p.unroute('**/api/store-image');
 check('a delayed image upload stays with C after switching to B',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='B 的角色'&&await p.locator(edit('[data-image-key="参考图"]')).count()===0);
 await select(c);check('C shows its own uploaded image and text draft',await p.locator(edit('[data-image-key="参考图"] img')).count()===1&&await p.locator(edit('[data-art-setting="character"]')).inputValue()==='C 的新草稿');await saved();await load();await p.evaluate(()=>Mio.fileLibrary.hydrateAll());await select(c);check('per-preset drafts survive a normal saved reload',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='C 的新草稿'&&await p.locator(edit('[data-image-key="参考图"] img')).count()===1);
 await p.locator('[data-act="art-apply-preset"]').click();await p.locator('#confirm-no').click();check('canceling Apply leaves the album plan alone',await p.evaluate(s=>JSON.stringify(selectedPlan())===s.plan,initial));
 await p.locator('[data-act="art-apply-preset"]').click();await p.locator('#confirm-yes').click();await saved();check('Apply copies the visible draft into this album without changing the preset or other albums',await p.evaluate(({c,s})=>mergedSettingEntries(selectedPlan()).some(e=>e.key==='character'&&e.value==='C 的新草稿')&&setBy(c).entries.find(e=>e.key==='character').value==='B 的角色'&&JSON.stringify(state.books)===s.books,{c,s:initial}));
 await update();await p.locator(edit('[data-art-setting="character"]')).fill('只更新 C');await update();check('later preset updates do not mutate already applied album values',await p.evaluate(()=>mergedSettingEntries(selectedPlan()).find(e=>e.key==='character').value==='C 的新草稿'));
 await select('');check('closing the library returns to actual album settings, without a preset update target',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='C 的新草稿'&&await p.locator('#main [data-act="ws-update-preset"]').count()===0&&await p.evaluate(()=>!settingsEditorTarget()._presetEditorId));
 await p.locator(edit('[data-art-setting="character"]')).fill('本册单独修改');await select(c);check('editing the album does not write back into C',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='只更新 C');
 await named('art-save-preset','新副本 D');const d=await p.evaluate(()=>settingPresetSelection());await p.locator(edit('[data-art-setting="character"]')).fill('D 独立');await update();check('Save As rebinds Update to D, never the source C',await p.evaluate(({c,d})=>setBy(c).entries.find(e=>e.key==='character').value==='只更新 C'&&setBy(d).entries.find(e=>e.key==='character').value==='D 独立',{c,d}));
 // Failure paths target the selected draft, not an old editingPresetId.
 await saved();check('all original preset files remain byte-identical after the entire reproduced edit/switch/save sequence',Object.entries(diskBefore).every(([name,bytes])=>presetFiles()[name]===bytes));
 for(const status of [409,500]){
   const before=JSON.stringify(await diskSet(d));await p.locator(edit('[data-art-setting="character"]')).fill('失败草稿 '+status);await saved();
   await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status,contentType:'application/json',body:JSON.stringify({error:'受控保存失败'})}):r.continue());await p.locator('[data-act="ws-update-preset"]').click();await p.waitForFunction(()=>Mio.sync.runtime.dirty&&!!Mio.sync.runtime.error);
   check(status+' leaves the preset file unchanged, retains its draft and never reports confirmed success',JSON.stringify(await diskSet(d))===before&&await p.locator(edit('[data-art-setting="character"]')).inputValue()==='失败草稿 '+status&&await p.locator('.toast').allTextContents().then(a=>a.some(t=>t.includes('更新尚未确认'))));
   await p.unroute('**/api/config');await update();check(status+' ordinary Update retry saves the same selected preset only',(await diskSet(d)).entries.find(e=>e.key==='character').value==='失败草稿 '+status&&(await diskSet(c)).entries.find(e=>e.key==='character').value==='只更新 C');
 }
 await p.locator(edit('[data-art-setting="character"]')).fill('响应丢失后保留');await saved();await p.route('**/api/config',async r=>{if(r.request().method()!=='POST')return r.continue();await r.fetch();await r.abort()});await p.locator('[data-act="ws-update-preset"]').click();await p.waitForFunction(()=>Mio.sync.runtime.dirty&&!!Mio.sync.runtime.error);
 check('a committed save with lost acknowledgement stays explicitly unconfirmed',(await diskSet(d)).entries.find(e=>e.key==='character').value==='响应丢失后保留'&&await p.locator('.toast').allTextContents().then(a=>a.some(t=>t.includes('更新尚未确认'))));await p.unroute('**/api/config');await update();check('ordinary Update retry after lost acknowledgement is idempotent',!await p.evaluate(()=>Mio.sync.runtime.dirty));
 // A real external edit between draft persistence and reopening must not be overwritten.
 await p.locator(edit('[data-art-setting="character"]')).fill('仍未提交的个人草稿');await saved();const nativeFile=Object.keys(presetFiles()).find(f=>JSON.parse(presetFiles()[f]).id===d),external=JSON.parse(presetFiles()[nativeFile]);external.entries.find(e=>e.key==='character').value='外部页面的新内容';writeFileSync(path.join(temp,'data/presets/characters',nativeFile),JSON.stringify(external));await load();await select(d);
 check('reopening preserves both the disk edit and the independent pending draft',await p.locator(edit('[data-art-setting="character"]')).inputValue()==='仍未提交的个人草稿'&&(await diskSet(d)).entries.find(e=>e.key==='character').value==='外部页面的新内容');await p.locator('[data-act="ws-update-preset"]').click();await p.locator('.toast').filter({hasText:'原预设已有其他修改'}).waitFor();check('stale draft is rejected before overwriting a newer preset',(await diskSet(d)).entries.find(e=>e.key==='character').value==='外部页面的新内容');await named('art-save-preset','冲突草稿的独立副本');const e=await p.evaluate(()=>settingPresetSelection());await saved();check('Save As recovers the stale draft without replacing either original',(await diskSet(e)).entries.find(e=>e.key==='character').value==='仍未提交的个人草稿'&&(await diskSet(d)).entries.find(e=>e.key==='character').value==='外部页面的新内容');
 // A removed/recreated image key is not the original upload target.
 await add('晚到的图片','image');let releaseLate,readyLate;const late=new Promise(r=>readyLate=r);await p.route('**/api/store-image',async r=>{await new Promise(resolve=>{releaseLate=resolve;readyLate()});await r.continue()});await p.locator(edit('[data-image-key="晚到的图片"] input')).setInputFiles(path.join(root,'examples/afterglow/cover.webp'));await late;
 await p.locator(edit('[data-act="art-setting-remove"][data-key="晚到的图片"]')).click();await p.locator('#confirm-yes').click();await add('晚到的图片','image');releaseLate();await p.locator('.toast').filter({hasText:'属性已被删除或更改'}).waitFor();await p.unroute('**/api/store-image');check('late upload cannot bind to a removed-and-recreated property with the same key',await p.locator(edit('[data-image-key="晚到的图片"] img')).count()===0);
 // Draft-only removals and typed values stay isolated; export uses the displayed draft.
 await add('启用','boolean');await p.locator(edit('[data-art-setting="启用"]')).selectOption('true');await add('数值','number');await p.locator(edit('[data-art-setting="数值"]')).fill('7');await add('结构','json');await p.locator(edit('[data-art-setting="结构"]')).fill('{"模式":"柔和"}');await p.locator(edit('[data-act="art-setting-remove"][data-key="自定义变量"]')).click();await p.locator('#confirm-yes').click();await select(c);check('removing a draft field leaves the same field in C intact',await p.locator(edit('[data-art-setting="自定义变量"]')).inputValue()==='111');await select(e);check('boolean, number and JSON fields stay with the selected preset draft',await p.locator(edit('[data-art-setting="启用"]')).inputValue()==='true'&&await p.locator(edit('[data-art-setting="数值"]')).inputValue()==='7'&&await p.locator(edit('[data-art-setting="结构"]')).inputValue()==='{"模式":"柔和"}');
 let exported;await p.route('**/api/library/export-document',r=>{exported=r.request().postDataJSON();return r.continue()});const download=p.waitForEvent('download');await p.locator(edit('[data-act="native-export-settings"]')).click();const zip=path.join(temp,'visible-draft.mio.zip');await(await download).saveAs(zip);await p.unroute('**/api/library/export-document');const inspected=await(await fetch(base+'/api/library/inspect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({zip:readFileSync(zip).toString('base64'),expectedKind:'variables'})})).json();check('actual draft export ZIP passes inspection and carries its owned image bytes',readFileSync(zip).subarray(0,2).toString()==='PK'&&inspected.images===1);check('export takes the visible preset draft rather than the album or source preset',exported.document.entries.some(x=>x.key==='启用'&&x.value===true)&&!exported.document.entries.some(x=>x.key==='自定义变量')&&exported.document.entries.find(x=>x.key==='character').value==='仍未提交的个人草稿');
 // Updating a legacy live reference preserves every currently effective plan/scene value.
 const legacy=await p.evaluate(id=>{const set=setBy(id),plan=selectedPlan();plan.variableSetIds=[id];plan.variables=[variableEntry('本地覆盖','保留')];plan.sceneOverrides={frame:{variableSetIds:[id],variables:[variableEntry('character','单幕优先')]}};save();return {global:JSON.stringify(effectivePlanScope(plan).values),scene:JSON.stringify(plan.sceneOverrides.frame.variables),id}},initial.id);await select(initial.id);await p.locator(edit('[data-art-setting="character"]')).fill('仅保存到原预设');await update();check('updating a legacy referenced preset preserves the album’s effective values and local precedence',await p.evaluate(l=>JSON.stringify(effectivePlanScope(selectedPlan()).values)===l.global&&selectedPlan().sceneOverrides.frame.variables.some(e=>e.key==='character'&&e.value==='单幕优先')&&!selectedPlan().variableSetIds.includes(l.id),legacy));
 const cancelState=await p.evaluate(()=>({count:state.creation.variableSets.length,selected:settingPresetSelection()}));await p.locator(edit('[data-act="art-save-preset"]')).click();await p.locator('#modal .modal-footer [data-act="close-modal"]').click();check('canceling Save As neither creates a file nor changes the selected target',await p.evaluate(s=>state.creation.variableSets.length===s.count&&settingPresetSelection()===s.selected,cancelState));
 for(const [action,label,status]of[['art-save-preset','另存',500],['ws-new-preset','新建',409]]){
   await saved();const count=await p.evaluate(()=>state.creation.variableSets.length),beforePlan=await p.evaluate(()=>JSON.stringify(selectedPlan()));await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status,contentType:'application/json',body:JSON.stringify({error:'受控创建失败'})}):r.continue());await named(action,label+'保存失败');await p.waitForFunction(()=>Mio.sync.runtime.dirty&&!!Mio.sync.runtime.error);const id=await p.evaluate(()=>settingPresetSelection());check(label+' failure retains an independent unconfirmed copy without changing the album',!await diskSet(id)&&await p.evaluate(b=>JSON.stringify(selectedPlan())===b,beforePlan)&&await p.locator('.toast').allTextContents().then(a=>a.some(t=>t.includes(label+'尚未确认'))));await p.unroute('**/api/config');await update();check(label+' retry persists the same ID without creating duplicates',!!await diskSet(id)&&await p.evaluate(n=>state.creation.variableSets.length===n+1,count));
 }
 const removed=await p.evaluate(()=>settingPresetSelection());await add('删除中上传','image');let releaseDeleted,readyDeleted;const waitingDelete=new Promise(r=>readyDeleted=r);await p.route('**/api/store-image',async r=>{await new Promise(resolve=>{releaseDeleted=resolve;readyDeleted()});await r.continue()});await p.locator(edit('[data-image-key="删除中上传"] input')).setInputFiles(path.join(root,'examples/afterglow/cover.webp'));await waitingDelete;await p.locator('[data-act="ws-delete-preset"]').click();await p.locator('#confirm-yes').click();await p.waitForFunction(id=>!setBy(id)&&!Mio.sync.runtime.dirty,removed);releaseDeleted();await p.locator('.toast').filter({hasText:'属性已被删除或更改'}).waitFor();await p.unroute('**/api/store-image');check('deleting a preset during upload does not resurrect it or attach its image to another editor',await p.evaluate(id=>!setBy(id)&&!state.drafts.presetEdits[id]&&!mergedSettingEntries(selectedPlan()).some(e=>e.key==='删除中上传'),removed));await select(initial.id);
 check('the requested concise Save As label is used',await p.locator(edit('[data-act="art-save-preset"]')).innerText()==='另存为');
 for(const [width,theme]of[[1440,'light'],[390,'dark']]){await p.setViewportSize({width,height:900});await p.evaluate(theme=>{state.settings.studio.appearance.theme=theme;render()},theme);check(`editor ownership and controls fit ${width}px ${theme}`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>{document.querySelectorAll('.toast').forEach(e=>e.remove());window.scrollTo(0,0)});await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,`preset-editor-${width}-${theme}.png`)});await p.locator('.preset-library-index').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(evidence,`preset-editor-controls-${width}-${theme}.png`)})}
 check('no browser exceptions or paid generation submissions',errors.length===0&&paid===0);console.log(n+' preset isolation checks PASS');
 }
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
