// Genuine portrait/landscape/small artwork, complete-frame geometry and offline parity.
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-reading-stage-')),base='http://127.0.0.1:8883',evidence=path.join(process.cwd(),'docs/acceptance-2.3.0');mkdirSync(evidence,{recursive:true});
const server=spawn('python',['-u',path.join(root,'server.py')],{cwd:root,env:{...process.env,MIO_PORT:'8883',MIO_DATA_DIR:path.join(temp,'data')},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});
let browser,p,n=0;const errors=[],check=(name,v)=>{assert.ok(v,name);console.log('PASS '+name);n++};
async function wait(){for(let i=0;i<200;i++){try{if((await fetch(base+'/api/config')).ok)return}catch{}await new Promise(r=>setTimeout(r,40))}throw Error('server timeout')}
async function settle(){await p.waitForTimeout(300);await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))))}
async function shot(name){await settle();await p.screenshot({path:path.join(evidence,name)})}
try{
 await wait();browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));
 const images=['cover','dense-portrait','coast','dense-portrait','postcard'].map(name=>'data:image/webp;base64,'+readFileSync(path.join(root,'examples/afterglow/'+name+'.webp')).toString('base64'));
 await p.evaluate(async images=>{await Mio.fileLibrary.hydrateAll();const book=state.books[0],sizes=[[928,1152],[1024,1408],[1376,768],[1024,1408],[240,180]];book.title='夏日之间 · 完整画面';book.curatedDemo=false;delete book.pictureEdits;delete book.nativeReaderMode;delete book.presentationTemplateId;book.totalSteps=5;book.generatedSteps=5;book.status='complete';book.steps=images.map((image,i)=>({stepIndex:i,name:['窗边的信','雨后的书页','沿海公路','夏日来信','一枚明信片'][i],caption:i===0?'故事从一封没有寄出的信开始。':'',prompt:'',image,width:sizes[i][0],height:sizes[i][1]}));openArtReader(book.id);window.keptImages=$$('#reader-canvas img')},images);
 await p.waitForFunction(()=>artUI.readingStage?.active&&$$('.mio-reading-stage').length===4);await settle();
 const geometry=await p.evaluate(()=>{const canvas=$('#reader-canvas').getBoundingClientRect(),g=$$('.mio-reading-stage');return {counts:g.map(e=>e.dataset.count),top:g[0].getBoundingClientRect().top,bottom:g[1].getBoundingClientRect().top,canvas:canvas.toJSON(),images:[...g[0].querySelectorAll('img')].map(i=>({rect:i.getBoundingClientRect().toJSON(),w:i.naturalWidth,h:i.naturalHeight,fit:getComputedStyle(i).objectFit}))}});
 check('adjacent portraits pair automatically; landscape and small artwork remain independent',geometry.counts.join(',')==='2,1,1,1');
 check('both portraits are complete, proportional and inside the viewport',geometry.images.every(i=>i.rect.top>=geometry.canvas.top&&i.rect.bottom<=geometry.canvas.bottom&&Math.abs(i.rect.width/i.rect.height-i.w/i.h)<.01&&i.fit==='contain'));
 check('the next composition does not peek into a settled desktop page',Math.abs(geometry.top-geometry.canvas.top)<1&&geometry.bottom>=geometry.canvas.bottom-1);
 check('paired portraits use the widescreen substantially, without stretching originals',geometry.images.reduce((sum,i)=>sum+i.rect.width,0)>geometry.canvas.width*.65&&geometry.images.every(i=>i.rect.width<=i.w));await shot('reading-paired-dark.png');
 await p.locator('[data-act="page-next"]').click();await settle();check('next-page navigation advances a whole spread, not the second half of the same spread',await p.evaluate(()=>ui.step===2));await shot('reading-landscape-dark.png');
 await p.locator('[data-act="page-next"]').click();await settle();check('an unpaired portrait has a local soft backdrop instead of empty black sidebars',await p.locator('.mio-reading-stage').nth(2).evaluate(e=>getComputedStyle(e).getPropertyValue('--mio-stage-backdrop').includes('url(')&&getComputedStyle(e,'::before').filter.includes('blur')));await shot('reading-single-portrait-dark.png');
 await p.locator('[data-act="page-next"]').click();await settle();check('small artwork never exceeds its native pixel dimensions',await p.locator('#reader-canvas img').last().evaluate(i=>i.getBoundingClientRect().width<=240.1&&i.getBoundingClientRect().height<=180.1));
 await p.locator('[data-act="reading-mode"][data-mode="single"]').click();await settle();check('single-page mode deliberately disables automatic pairing',await p.locator('.mio-reading-stage').count()===5);
 await p.locator('[data-act="reading-mode"][data-mode="continuous"]').click();await settle();check('continuous mode restores natural scrolling without replacing image nodes',await p.evaluate(()=>!artUI.readingStage.active&&window.keptImages.every((img,i)=>img===$$('#reader-canvas img')[i])));
 await p.locator('[data-act="reading-mode"][data-mode="auto"]').click();await p.evaluate(()=>artUI.readingStage.go(0));await p.setViewportSize({width:390,height:844});await settle();check('phone reading remains continuous and does not overflow horizontally',await p.evaluate(()=>!artUI.readingStage.active&&$('#reader-canvas').scrollWidth<=$('#reader-canvas').clientWidth+1));await shot('reading-mobile-continuous.png');
 await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>{state.settings.studio.appearance.theme='light';applyStudioPreferences();artUI.readingStage.go(0)});await settle();check('rotation back to desktop restores pairing and original node identity',await p.evaluate(()=>artUI.readingStage.active&&$$('.mio-reading-stage')[0].dataset.count==='2'&&window.keptImages.every((img,i)=>img===$$('#reader-canvas img')[i])));check('first paired composition keeps correct page numbering after resizing',await p.locator('#page-position').innerText()==='01–02 / 05');await shot('reading-paired-light.png');
 for(const id of ['mio-fit','export-seamless']){
  const html=await p.evaluate(async id=>{bookBy(ui.bookId).readingMode='auto';const b=clone(bookBy(ui.bookId));for(const frame of b.steps)frame.image=await imageData(frame.image);return compileTemplateDocument(exportTemplateBy(id),[b],{showCaptions:true,showPrompts:false})},id),file=path.join(temp,id+'.html');writeFileSync(file,html);
  const offline=await browser.newPage({viewport:{width:1440,height:900}});offline.on('pageerror',e=>errors.push(e.message));await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+file);await offline.waitForSelector('.mio-reading-stage');await offline.locator('[data-cc-frame] img').evaluateAll(images=>Promise.all(images.map(i=>{i.loading='eager';return i.decode()})));check(id+' standalone export contains five successfully decoded embedded originals',await offline.locator('[data-cc-frame] img').evaluateAll(images=>images.length===5&&images.every(i=>i.naturalWidth>0&&i.src.startsWith('data:image/'))));await offline.waitForTimeout(300);
  const measure=()=>{const g=[...document.querySelectorAll('.mio-reading-stage')];return {counts:g.map(e=>e.dataset.count),dims:[...g[0].querySelectorAll('img')].map(i=>[i.getBoundingClientRect().width,i.getBoundingClientRect().height]),gap:g[1].getBoundingClientRect().top-g[0].getBoundingClientRect().bottom}};
  const a=await offline.evaluate(measure);check(id+' actual standalone HTML preserves pairing and complete image geometry',a.counts.join(',')==='2,1,1,1'&&Math.abs(a.gap)<1&&a.dims.every(d=>d[1]<=900));
  const preview=await browser.newPage({viewport:{width:1440,height:900}});await preview.setContent('<iframe sandbox="allow-scripts" style="position:fixed;inset:0;width:100%;height:100%;border:0"></iframe>');await preview.locator('iframe').evaluate((el,html)=>el.srcdoc=html,html);const frame=preview.frameLocator('iframe');await frame.locator('.mio-reading-stage').first().waitFor();await frame.locator('[data-cc-frame] img').evaluateAll(images=>Promise.all(images.map(i=>{i.loading='eager';return i.decode()})));await preview.waitForTimeout(300);const b=await frame.locator('body').evaluate(measure);
  check(id+' sandbox preview and offline export use identical geometry at the same viewport',JSON.stringify(a)===JSON.stringify(b));
  if(id==='export-seamless'){check('seamless pages still contain only imagery, no caption blocks or page numbers',await offline.locator('[data-cc-pages]').innerText()===''&&await offline.locator('[data-cc-caption],.room-page-number,[data-mio-colophon]').count()===0);await offline.screenshot({path:path.join(evidence,'seamless-desktop.png')});await offline.setViewportSize({width:390,height:844});await offline.waitForTimeout(300);check('seamless phone mode retains genuine zero-gap original-ratio images',await offline.locator('[data-cc-frame]').evaluateAll(frames=>Math.abs(frames[1].getBoundingClientRect().top-frames[0].getBoundingClientRect().bottom)<1));await offline.screenshot({path:path.join(evidence,'seamless-mobile.png')})}
  await preview.close();await offline.close();
 }
 check('serialized reading preferences cannot close the script element',await p.evaluate(()=>{const b=clone(bookBy(ui.bookId));b.readingMode='</script><img id="reading-injected" src="x">';const html=compileTemplateDocument(exportTemplateBy('mio-fit'),[b]);return !new DOMParser().parseFromString(html,'text/html').querySelector('#reading-injected')&&html.includes('\\u003c/script>')}));
 await p.evaluate(()=>{presentationUI.templateId='export-seamless';bookBy(ui.bookId).presentationTemplateId='export-seamless';renderArtReader()});await p.frameLocator('#presentation-preview').locator('[data-reading-mode="continuous"]').click();await p.waitForFunction(()=>bookBy(ui.bookId).readingMode==='continuous');
 check('changing mode in the real sandbox reader persists to the album and subsequent export',await p.evaluate(()=>compileTemplateDocument(exportTemplateBy('export-seamless'),[bookBy(ui.bookId)]).includes('"mode":"continuous"')));
 await p.evaluate(async()=>{const b=bookBy(ui.bookId);for(const [i,w,h] of [[0,768,1152],[1,900,1200]]){const original=new Image();original.src=b.steps[i].image;await original.decode();const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.fillStyle='#e8e5db';ctx.fillRect(0,0,w,h);const scale=Math.min((w-8)/original.naturalWidth,(h-8)/original.naturalHeight);ctx.drawImage(original,(w-original.naturalWidth*scale)/2,(h-original.naturalHeight*scale)/2,original.naturalWidth*scale,original.naturalHeight*scale);b.steps[i]={...b.steps[i],image:canvas.toDataURL(),width:w,height:h,caption:''}}b.readingMode='auto';b.presentationTemplateId='mio-fit';presentationUI.templateId='mio-fit';artUI.readerMode='webtoon';ui.step=0;renderArtReader()});
 for(const [width,height] of [[1366,768],[1280,720],[1920,1080]]){await p.setViewportSize({width,height});await p.waitForFunction(()=>artUI.readingStage?.active);await settle();check(width+'×'+height+' shows exact 2:3 and 3:4 portraits completely, with balanced pairing and no next-frame edge',await p.evaluate(()=>{const canvas=$('#reader-canvas').getBoundingClientRect(),groups=$$('.mio-reading-stage'),images=[...groups[0].querySelectorAll('img')],r=images.map(i=>i.getBoundingClientRect());return images.length===2&&Math.abs(images[0].naturalWidth/images[0].naturalHeight-2/3)<.001&&Math.abs(images[1].naturalWidth/images[1].naturalHeight-3/4)<.001&&r.every((b,i)=>b.top>=canvas.top-.5&&b.bottom<=canvas.bottom+.5&&b.left>=canvas.left&&b.right<=canvas.right&&Math.abs(b.width/b.height-images[i].naturalWidth/images[i].naturalHeight)<.001)&&r.reduce((n,b)=>n+b.width,0)>canvas.width*.55&&groups[1].getBoundingClientRect().top>=canvas.bottom-1}));if(width===1366)await shot('reading-1366x768-ratios.png')}
 check('no browser script errors',errors.length===0);console.log(n+' adaptive reading checks PASS');
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
