// Explicit original 2.2.2 ZIP required; never touch a real user's workspace.
import {chromium} from 'playwright';import {spawn,spawnSync} from 'node:child_process';import {mkdtempSync,readFileSync,readdirSync,rmSync} from 'node:fs';import {createHash} from 'node:crypto';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.cwd(),archive=process.argv[2];assert.ok(archive,'Usage: node tests/rename_upgrade.mjs /path/to/original-mio-2.2.2-source.zip');
const temp=mkdtempSync(path.join(tmpdir(),'mio-preset-upgrade-')),data=path.join(temp,'data'),base='http://127.0.0.1:8868';let server,browser;const errors=[];
async function stop(){if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}server=null}
async function boot(project){server=spawn('python',['-u',path.join(project,'server.py')],{cwd:project,env:{...process.env,MIO_PORT:'8868',MIO_DATA_DIR:data},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)return}catch{}await new Promise(r=>setTimeout(r,40))}throw Error('startup failed')}
function entities(){const result={};for(const dir of ['albums','presets','layouts','storyboards','plans','records','collections','settings','workflows']){const folder=path.join(data,dir);for(const file of readdirSync(folder,{recursive:true}))if(file.endsWith('.json')){const relative=dir+'/'+file;result[relative]=createHash('sha256').update(readFileSync(path.join(data,relative))).digest('hex')}}return result}
async function page(){const p=await browser.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{guidePreferences().seen=true;state.settings.identity.onboarded=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close())});return p}
try{
 const unpack=spawnSync('python',['-c',`import sys,zipfile,json
with zipfile.ZipFile(sys.argv[1]) as z:
 root=z.namelist()[0].split('/')[0]
 assert json.loads(z.read(root+'/PACKAGE_MANIFEST.json'))['version']=='2.2.2'
 z.extractall(sys.argv[2]);print(sys.argv[2]+'/'+root)`,archive,temp],{encoding:'utf8'});assert.equal(unpack.status,0,unpack.stderr);console.log('Baseline SHA256',createHash('sha256').update(readFileSync(archive)).digest('hex'));
 browser=await chromium.launch({args:['--no-sandbox']});await boot(unpack.stdout.trim());let p=await page();const id=await p.evaluate(async()=>{const set=state.creation.variableSets[0];set.title='我的修改不得覆盖';set.entries.push({id:uid('var'),key:'私人变量',type:'text',value:'用户编辑的内容'});await Mio.fileLibrary.hydrateAll();state.books[0].title='升级前的真实画册标题';save();if(!await savePythonWorkspace())throw Error(Mio.sync.runtime.error);return set.id});const oldJob=await p.evaluate(async()=>{await foundationRequest('jobs/scheduler',{action:'policy',policy:{mode:'retry',maxRetries:7,delaySeconds:30,onExhausted:'pause'}});return foundationRequest('jobs',{idempotencyKey:'upgrade-held-job',input:{hold:true,frames:[{config:{provider:'openai',keyMode:'none'},prompt:'must not submit',images:[]}]}})});const before=entities();await p.close();await stop();
 await boot(root);p=await page();assert.deepEqual(entities(),before);console.log('PASS 2.2.2 to 2.2.3 preserves every saved native entity and settings file byte-for-byte');
 assert.ok(await p.evaluate(id=>setBy(id).title==='我的修改不得覆盖'&&setBy(id).entries.some(e=>e.key==='私人变量'&&e.value==='用户编辑的内容')&&state.books[0].title==='升级前的真实画册标题',id));console.log('PASS existing edited preset and album remain visible after upgrade');
 await p.evaluate(()=>{createUI.tab='settings';navigate(1)});await p.locator('#art-setting-preset').selectOption(id);assert.ok(await p.locator('[data-act="ws-delete-preset"]').isEnabled());assert.equal(await p.locator('[data-art-setting="私人变量"]').inputValue(),'用户编辑的内容');assert.equal(await p.locator('[data-act="art-save-preset"]').innerText(),'另存为');console.log('PASS upgraded workspace shows the selected existing preset and Save As/Delete controls without reinstalling data');await p.evaluate(()=>navigate(0));await p.locator('[data-act="book-menu"]').first().click();await p.locator('[data-act="org-context-edit"]').click();assert.equal(await p.locator('[data-book-rename]').inputValue(),'升级前的真实画册标题');console.log('PASS existing album opens directly in the new rename editor');const jobs=await p.evaluate(()=>foundationRequest('jobs'));const held=jobs.jobs.find(j=>j.id===oldJob.id);assert.equal(held.attempts,0);assert.equal(held.state,'paused');assert.equal(held.consecutive_failures,0);assert.equal(held.failure_limit_reached,0);assert.equal(jobs.failurePolicy.maxRetries,7);assert.equal(jobs.failurePolicy.maxConsecutiveFailures,5);console.log('PASS actual 2.2.2 task database gains guard columns without replaying the held job or replacing prior retry settings');assert.deepEqual(errors,[]);console.log('5 upgrade checks PASS; no generation submitted');
}finally{await browser?.close();await stop();rmSync(temp,{recursive:true,force:true})}
