// Actual album rename UI and browser -> Python -> controlled HTTP failure guard.
import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {createServer} from 'node:http';import {mkdtempSync,mkdirSync,readFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const root=process.env.MIO_TEST_PROJECT||process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-rename-guard-')),base='http://127.0.0.1:8871',evidence=path.join(process.cwd(),'docs/acceptance-2.2.3'),token='r'.repeat(40);mkdirSync(evidence,{recursive:true});
const calls=[],png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
const upstream=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const body=JSON.parse(raw);calls.push(body.prompt);res.setHeader('Content-Type','application/json');if(body.prompt.includes('guard-fail')){res.statusCode=503;res.end(JSON.stringify({error:{message:'controlled persistent service failure'}}))}else res.end(JSON.stringify({data:[{b64_json:png}]}))});await new Promise(r=>upstream.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+upstream.address().port+'/v1';
const server=spawn('python',['-u',path.join(root,'server.py')],{cwd:root,env:{...process.env,MIO_PORT:'8871',MIO_DATA_DIR:path.join(temp,'data'),MIO_API_TOKEN:token},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});
let browser,p,n=0;const errors=[],check=(name,value)=>{assert.ok(value,name);n++;console.log('PASS '+name)};
async function api(route,body){const r=await fetch(base+'/api/v1/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();assert.ok(r.ok,JSON.stringify(data));return data.data}
async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{guidePreferences().seen=true;state.settings.identity.onboarded=true;createUI.welcomePending=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(0)})}
async function saved(){assert.ok(await p.evaluate(()=>savePythonWorkspace()))}
async function open(ids){await p.evaluate(ids=>{ui.selected=new Set(ids);openBookContext(ids[0],80,120)},ids);await p.locator('[data-act="org-context-edit"]').click();await p.locator('[data-book-rename]').first().waitFor()}
async function confirm(){await p.locator('[data-act="org-book-edit-confirm"]').click();await p.waitForFunction(()=>!Mio.sync.runtime.dirty&&!Mio.sync.runtime.saving)}
async function diskBooks(){return (await(await fetch(base+'/api/config')).json()).savedGalleries}
async function waitJob(id,predicate){for(let i=0;i<160;i++){const j=await api('jobs/'+id);if(predicate(j))return j;await new Promise(r=>setTimeout(r,50))}throw Error('job condition timeout '+id)}
async function shot(name){await p.evaluate(()=>{document.querySelectorAll('.toast').forEach(e=>e.remove())});await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,name)})}
try{
 for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)break}catch{}await new Promise(r=>setTimeout(r,40))}
 browser=await chromium.launch({args:['--no-sandbox']});p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.route(/^https:\/\//,r=>r.abort());await load();
 if(process.argv.includes('--baseline')){
   const title=await p.evaluate(()=>state.books[0].title);await p.locator('[data-act="book-menu"]').first().click();await p.locator('[data-act="org-context-edit"]').click();check('2.2.2 reproduced: existing name cannot be edited, only blank prefix and tag fields are offered',await p.locator('#org-book-prefix').count()===1&&await p.locator('#org-book-tags').count()===1&&!(await p.locator('#modal input').evaluateAll(nodes=>nodes.map(n=>n.value))).includes(title));console.log('Original title:',title);console.log('Policy:',JSON.stringify((await api('jobs')).failurePolicy));
 }else{
 const ids=await p.evaluate(async()=>{await Mio.fileLibrary.hydrateAll();const source=state.books[0];source.tags=['保留搜索标签'];const ids=[source.id];for(let i=1;i<=2;i++){const b={...clone(source),id:uid('book'),title:'现有名称 '+i};state.books.push(b);ids.push(b.id)}save();await savePythonWorkspace();render();return ids});const before=await diskBooks();await load();check('fixture opens with lazy native album summaries',await p.evaluate(()=>state.books.every(b=>b._lazy)));
 await p.evaluate(()=>{state.settings.studio.appearance.theme='light';render()});await open([ids[0]]);check('single rename is prefilled with the existing full title',await p.locator('[data-book-rename]').inputValue()===before.find(b=>b.id===ids[0]).title);check('rename dialog has no prefix or appended-tag controls',await p.locator('#org-book-prefix,#org-book-tags').count()===0&&await p.locator('#modal').innerText().then(t=>t.includes('重命名')));await p.locator('[data-book-rename]').fill('取消的名称');await p.locator('#modal .modal-footer [data-act="close-modal"]').click();check('cancel leaves every native album unchanged',JSON.stringify(await diskBooks())===JSON.stringify(before));
 await open([ids[0]]);await p.locator('[data-book-rename]').fill('完全替换原名');await confirm();const renamed=await diskBooks();check('rename replaces rather than prefixes the original name',renamed.find(b=>b.id===ids[0]).title==='完全替换原名');const strip=b=>Object.fromEntries(Object.entries(b).filter(([k])=>!['title','updatedAt'].includes(k)));check('rename preserves all content, tags, image ownership and unselected albums',JSON.stringify(strip(renamed.find(b=>b.id===ids[0])))===JSON.stringify(strip(before.find(b=>b.id===ids[0])))&&ids.slice(1).every(id=>JSON.stringify(renamed.find(b=>b.id===id))===JSON.stringify(before.find(b=>b.id===id))));
 await open(ids.slice(0,2));check('batch rename gives each selected album its own existing-name input',await p.locator('[data-book-rename]').count()===2&&await p.locator('[data-book-rename]').nth(1).inputValue()==='现有名称 1');await p.locator('[data-book-rename]').nth(0).fill('第一本新名');await p.locator('[data-book-rename]').nth(1).fill('   ');await p.locator('[data-act="org-book-edit-confirm"]').click();await p.locator('.toast').filter({hasText:'1–150'}).waitFor();check('one invalid name blocks the entire batch without partial edits',JSON.stringify(await diskBooks())===JSON.stringify(renamed));await p.locator('[data-book-rename]').nth(1).fill('第二本独立新名');await shot('rename-desktop-light.png');await confirm();await load();check('distinct batch names persist after a normal reload',await p.evaluate(ids=>bookBy(ids[0]).title==='第一本新名'&&bookBy(ids[1]).title==='第二本独立新名'&&bookBy(ids[2]).title==='现有名称 2',ids));
 await p.evaluate(()=>{ui.search='保留搜索标签';refreshGallery()});check('existing album tags have a real search use and remain searchable',await p.evaluate(()=>getShelfBooks().length===3));await p.evaluate(()=>{ui.search='';refreshGallery()});
 await open(ids.slice(0,2));await p.locator('[data-book-rename]').nth(0).fill('不覆盖并发修改');await p.evaluate(id=>bookBy(id).title='另一操作已修改',ids[0]);await p.locator('[data-act="org-book-edit-confirm"]').click();await p.locator('.toast').filter({hasText:'其他操作中改变'}).waitFor();check('a changed rename target is rejected before editing the other selected album',await p.evaluate(id=>bookBy(id).title==='第二本独立新名',ids[1]));await p.locator('#modal .modal-footer [data-act="close-modal"]').click();await saved();
 for(const status of [409,500]){await open([ids[0]]);await p.locator('[data-book-rename]').fill('待确认 '+status);const old=(await diskBooks()).find(b=>b.id===ids[0]).title;await p.route('**/api/config',r=>r.request().method()==='POST'?r.fulfill({status,contentType:'application/json',body:JSON.stringify({error:'controlled rename failure'})}):r.continue());await p.locator('[data-act="org-book-edit-confirm"]').click();await p.waitForFunction(()=>Mio.sync.runtime.dirty&&!!Mio.sync.runtime.error);check(status+' rename is explicitly unconfirmed and does not change the disk name',(await diskBooks()).find(b=>b.id===ids[0]).title===old&&await p.locator('.toast').allTextContents().then(a=>a.some(t=>t.includes('重命名尚未确认'))));await p.unroute('**/api/config');await saved();check(status+' ordinary save retry persists the replacement, not a repeated prefix',(await diskBooks()).find(b=>b.id===ids[0]).title==='待确认 '+status)}
 await open([ids[0]]);await p.locator('[data-book-rename]').fill('响应丢失的重命名');await p.route('**/api/config',async r=>{if(r.request().method()!=='POST')return r.continue();await r.fetch();await r.abort()});await p.locator('[data-act="org-book-edit-confirm"]').click();await p.waitForFunction(()=>Mio.sync.runtime.dirty&&!!Mio.sync.runtime.error);check('lost rename acknowledgement retains an unconfirmed local name even after server commit',(await diskBooks()).find(b=>b.id===ids[0]).title==='响应丢失的重命名');await p.unroute('**/api/config');await saved();check('retry after a lost rename acknowledgement is idempotent',(await diskBooks()).find(b=>b.id===ids[0]).title==='响应丢失的重命名');
 await p.setViewportSize({width:390,height:900});await p.evaluate(()=>{state.settings.studio.appearance.theme='dark';render()});await open(ids);check('mobile rename fields and actions fit the viewport',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('rename-mobile-dark.png');await p.locator('#modal .modal-footer [data-act="close-modal"]').click();
 await p.evaluate(()=>{createUI.tab='queue';navigate(1)});await p.waitForFunction(()=>foundationRuntime.runtimeLoaded);await p.locator('#queue-policy').evaluate(el=>el.open=true);check('consecutive failure limit is configurable alongside per-frame retries',await p.locator('#queue-policy-consecutive').inputValue()==='5');await p.locator('#queue-policy-consecutive').fill('101');await p.locator('[data-act="queue-policy-save"]').click();await p.locator('.toast').filter({hasText:'0–100'}).waitFor();check('invalid failure limit never reaches the server',(await api('jobs')).failurePolicy.maxConsecutiveFailures===5);
 await p.locator('#queue-policy-consecutive').fill('3');await p.locator('[data-act="queue-policy-save"]').click();await p.locator('#confirm-no').click();check('canceling policy confirmation preserves the service limit',(await api('jobs')).failurePolicy.maxConsecutiveFailures===5);
 await p.route('**/api/foundation/jobs/scheduler',r=>r.request().method()==='POST'?r.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'controlled policy failure'})}):r.continue());await p.locator('[data-act="queue-policy-save"]').click();await p.locator('#confirm-yes').click();await p.locator('#queue-policy-feedback').filter({hasText:'保存未确认'}).waitFor();check('failed policy save retains the old service limit and does not display saved',(await api('jobs')).failurePolicy.maxConsecutiveFailures===5);await p.unroute('**/api/foundation/jobs/scheduler');
 await p.locator('#queue-policy-consecutive').fill('2');await p.locator('#queue-policy-count').fill('1');await p.locator('#queue-policy-delay').fill('5');await p.locator('[data-act="queue-policy-save"]').click();check('billing confirmation discloses both per-frame retry and consecutive-failure limits',await p.locator('#confirm-dialog').innerText().then(t=>t.includes('连续失败 2 次')&&t.includes('额外请求 1 次')));await p.locator('#confirm-yes').click();await p.waitForFunction(()=>foundationRuntime.failurePolicy.maxConsecutiveFailures===2);check('configured failure guard is persisted in the real service',(await api('jobs')).failurePolicy.maxConsecutiveFailures===2);
 await p.locator('#queue-policy').evaluate(el=>el.open=true);await p.locator('#queue-policy').scrollIntoViewIfNeeded();await shot('failure-policy-mobile-dark.png');
 async function enqueue(prefix,n){return p.evaluate(async({prefix,n,url})=>{state.settings.comfy.mode='real';const g=ensureImageProviders();if(!g.profiles.some(x=>x.id==='guard-fixture'))g.profiles.push({id:'guard-fixture',title:'Controlled guard fixture',provider:'openai',protocol:'images',model:'test',baseUrl:url,keyMode:'none',sendSize:false,sendQuality:false});g.active='guard-fixture';const plan=selectedPlan(),t=templateBy(plan.templateId),f=clone(t.frames[0]);plan.storyVersionId='';t.frames=Array.from({length:n},(_,i)=>({...clone(f),id:uid('frame'),name:'第 '+(i+1)+' 幕',prompt:prefix+'-'+i,negative:'',caption:''}));const b=enqueuePlanSnapshot(plan);b.title=prefix;save();await savePythonWorkspace();await runQueue();const q=state.queue.find(q=>q.bookId===b.id);return {id:q.serverId,qid:q.id,book:b.id}},{prefix,n,url})}
 const a=await enqueue('guard-fail',6);const stopped=await waitJob(a.id,j=>j.failure_limit_reached===2&&!j.running_count);check('real HTTP failures stop the album after two attempts, before all six scenes',stopped.attempts===2&&stopped.blocked&&stopped.ready_at===0&&calls.filter(x=>x.includes('guard-fail')).length===2);await p.evaluate(()=>pollFoundationJobs());check('the queue card explains the automatic stop and manual continuation',await p.locator(`[data-sort-task="${a.qid}"] .task-error-summary`).innerText().then(t=>t.includes('连续失败 2 次')&&t.includes('手动继续')));await new Promise(r=>setTimeout(r,5300));check('no retry leaks after the original retry deadline',calls.filter(x=>x.includes('guard-fail')).length===2);
 const b=await enqueue('guard-ok',1);await waitJob(b.id,j=>j.state==='complete');check('another album still executes while the failing album stays stopped',(await api('jobs/'+a.id)).attempts===2&&(await api('jobs/'+b.id)).cursor===1);await load();await p.evaluate(()=>{createUI.tab='queue';navigate(1)});await p.waitForFunction(()=>foundationRuntime.failurePolicy.maxConsecutiveFailures===2);check('refresh retains policy and does not resume the stopped task',(await api('jobs/'+a.id)).failure_limit_reached===2&&calls.filter(x=>x.includes('guard-fail')).length===2);
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{state.settings.studio.appearance.theme='light';render()});await p.locator('#queue-policy').evaluate(el=>el.open=true);await p.locator('#queue-policy').scrollIntoViewIfNeeded();check('desktop failure policy fits without horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('failure-policy-desktop-light.png');check('no uncaught browser exceptions',errors.length===0);console.log(n+' rename / failure-limit browser checks PASS');
 }
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}await new Promise(r=>upstream.close(r));rmSync(temp,{recursive:true,force:true})}
