import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn}from'node:child_process';import{chromium}from'playwright';
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'mio-review-')),base='http://127.0.0.1:18814',evidence='docs/acceptance-review';fs.cpSync('data',temp,{recursive:true});fs.mkdirSync(evidence,{recursive:true});const log=fs.openSync('/tmp/mio-review-server.log','w'),server=spawn('python',['server.py'],{env:{...process.env,MIO_DATA_DIR:temp,MIO_PORT:'18814',MIO_HOST:'127.0.0.1'},stdio:['ignore',log,log]});let browser,count=0;const check=(value,label)=>{assert.ok(value,label);console.log('PASS',label);count++};
try{
 for(let i=0;i<100;i++){try{if((await fetch(base+'/api/content')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(async()=>{await connectPythonBackend();document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(1)});
 check(await p.evaluate(()=>{const t={id:'review_story',frames:[{id:'review_a',caption:'甲',prompt:''},{id:'review_b',caption:'乙',prompt:''}]},r={id:'review_actor',storyVersions:{},activeStoryVersionIds:{},character:'角色'};const v=ensureManual(r,t);v.captions.review_a='甲的专属台词';t.frames.reverse();if(captionFor(r,t,1)!=='甲的专属台词')return false;t.frames.splice(0,1);if(captionFor(r,t,0)!=='甲的专属台词')return false;v.captions.review_a='';return captionFor(r,t,0)===''&&!Array.isArray(v.captions)}),'caption IDs survive reorder/delete and preserve intentionally blank overrides');
 await p.locator('[data-workshop-frame="prompt"]').focus();
 check(await p.evaluate(()=>{const el=document.activeElement;el.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true,data:'zhong'}));el.value='中文输入中的提示词';el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertCompositionText',data:'中文',isComposing:true}));el.setSelectionRange(2,5);for(let i=0;i<5;i++)render();const good=el.isConnected&&document.activeElement===el&&el.selectionStart===2&&el.selectionEnd===5&&el.value==='中文输入中的提示词';el.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true,data:'中文'}));return good}),'background renders preserve the exact active textarea, IME session and selection');
 await p.locator('[data-workshop-frame="name"]').focus();check(await p.evaluate(()=>{const el=document.activeElement;el.value='标题输入不中断';el.dispatchEvent(new Event('input',{bubbles:true}));render();return el===document.activeElement&&el.value==='标题输入不中断'}),'title editing survives synchronization without detachment');await p.locator('[data-workshop-frame="name"]').blur();
 check(await p.evaluate(()=>{const root=document.createElement('section');root.innerHTML='<div class="editor"><textarea id="review-focus">原稿</textarea></div>';document.body.append(root);const field=root.querySelector('textarea');field.focus();patchDOM(root,'<div class="notice">后台同步完成</div><div class="editor"><textarea id="review-focus">服务器回显</textarea></div>');const good=document.activeElement===field&&field.value==='原稿'&&root.firstChild.className==='notice';root.remove();return good}),'inserting an unkeyed background notice does not reuse and destroy the focused editor container');
 check(await p.evaluate(()=>{const value=clone(state);value.templates[0].frames=[{id:'duplicate'},{id:'duplicate'}];try{ComfyComic.stateContract.normalize(value);return false}catch(error){return error.message.includes('ID 重复')}}),'duplicate imported frame IDs are rejected instead of aliasing caption dictionaries');
 check(await p.evaluate(()=>{const prior=workshop.frame;workshop.frame=0;render();const field=document.querySelector('[data-workshop-frame="name"]');field.focus();workshop.frame=1;render();const good=!field.isConnected&&document.querySelector('[data-workshop-frame="name"]').value===workshopStory().frames[1].name;workshop.frame=prior;render();return good}),'explicit scene switches replace the scoped editor rather than retaining a stale focused value');
 check(await p.evaluate(()=>{const first=document.createElement('dialog'),second=document.createElement('dialog');first.id='review-first';second.id='review-second';document.body.append(first,second);second.showModal();first.showModal();toast('动态模态错误','error');const good=document.querySelector('#toasts').parentElement===first;first.close();second.close();first.remove();second.remove();return good}),'toast follows actual dialog opening order rather than hard-coded IDs or DOM order');
 const id=await p.evaluate(async()=>{const b=state.books[0];await Mio.fileLibrary.hydrate(b.id);await ComfyComic.pictures.open(b.id,0);return b.id});await p.waitForFunction(()=>ComfyComic.pictures.runtime.editor?.image&&document.querySelector('#image-studio [role=status]').textContent.includes('px'));
 await p.evaluate(()=>toast('修图保存失败的可见反馈','error'));check(await p.locator('#image-studio #toasts .toast.error').isVisible(),'errors remain visible in the image studio top layer');
 await p.locator('[data-pic="bubble"]').click();await p.locator('#pic-text').fill('竖排对白测试\n第二列');await p.locator('#pic-text').blur();await p.locator('[data-layer="writingMode"]').selectOption('vertical-rl');check(await p.evaluate(()=>ComfyComic.pictures.runtime.editor.recipe.layers[0].writingMode==='vertical-rl'),'vertical right-to-left writing mode is in the saved layer recipe');
 const hit=p.locator('[data-layer-hit="0"]'),box=await hit.boundingBox();await p.mouse.move(box.x+15,box.y+15);await p.mouse.down();const before=await p.locator('#pic-canvas').evaluate(c=>c.toDataURL());await p.mouse.move(box.x+65,box.y+35,{steps:8});await p.waitForTimeout(100);check(await p.locator('#pic-canvas').evaluate((c,b)=>c.toDataURL()!==b,before),'canvas redraws during drag before pointer release');await p.mouse.up();
 const selected=await p.evaluate(()=>{const e=ComfyComic.pictures.runtime.editor;return e.recipe.layers[e.selected].id});await p.locator('[data-pic="undo"]').click();check(await p.evaluate(id=>{const e=ComfyComic.pictures.runtime.editor;return e.recipe.layers[e.selected]?.id===id},selected),'undo keeps the original selected layer and its properties');
 await p.locator('[data-layer-hit="0"]').dblclick({position:{x:25,y:25}});await p.locator('.pic-inline-text').waitFor();await p.locator('.pic-inline-text').fill('原位双击输入');await p.locator('.pic-inline-text').press('Control+Enter');check(await p.locator('#pic-text').inputValue()==='原位双击输入','double-click edits the bubble text in place');
 const tail=p.locator('[data-tail-handle]'),tb=await tail.boundingBox(),oldTail=await p.evaluate(()=>ComfyComic.pictures.runtime.editor.recipe.layers[0].tailX);await p.mouse.move(tb.x+tb.width/2,tb.y+tb.height/2);await p.mouse.down();await p.mouse.move(tb.x+50,tb.y+20,{steps:7});await p.mouse.up();check(await p.evaluate(x=>ComfyComic.pictures.runtime.editor.recipe.layers[0].tailX!==x,oldTail),'tail handle drags independently toward a character');
 await p.screenshot({path:evidence+'/image-studio.png',animations:'disabled'});
 await p.locator('[data-pic="save"]').click();await p.waitForSelector('#image-studio',{state:'detached'});check(await p.evaluate(id=>bookBy(id).pictureEdits[0].recipe.layers[0].text==='原位双击输入',id),'new layer properties persist through the real backend validator');
 const image=await p.evaluate(id=>bookBy(id).steps[0].image,id);const response=await fetch(base+image+'?thumb=300x200');check(response.ok&&response.headers.get('content-type')==='image/webp','thumbnail HTTP route returns WebP, not the original raster');const size=(await response.arrayBuffer()).byteLength;check(size<200000,'thumbnail response stays small');
 await p.evaluate(async id=>{await openArtReader(id);artUI.filmstrip=true;renderArtReader()},id);check(await p.locator('#room-filmstrip img').first().getAttribute('src').then(s=>s.includes('?thumb=')),'reader filmstrip requests thumbnail URLs');await p.evaluate(()=>closeReader());
 await p.evaluate(id=>showExportHub([id]),id);for(const format of ['zip','pdf']){const download=p.waitForEvent('download').then(file=>({file}),error=>({error}));await p.locator(`[data-act="portable-export"][data-format="${format}"]`).click();const out=path.join(temp,'review.'+format);const result=await download;if(result.error)throw result.error;await result.file.saveAs(out);check(fs.readFileSync(out).subarray(0,format==='zip'?2:4).toString()=== (format==='zip'?'PK':'%PDF'),format.toUpperCase()+' downloads from the real export UI');}
 await p.screenshot({path:evidence+'/export.png',animations:'disabled'});check(errors.length===0,'no uncaught browser exceptions: '+errors.join(';'));console.log(`REVIEW: ${count} checks PASS`);
}finally{await browser?.close();if(server.exitCode===null){const closed=new Promise(r=>server.once('exit',r));server.kill('SIGTERM');await closed}fs.closeSync(log);fs.rmSync(temp,{recursive:true,force:true})}
