// Image-only reader: actual previous release, native storage, real UI and offline HTML.
import {chromium} from 'playwright';
import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync,mkdirSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {isDeepStrictEqual} from 'node:util';
const root=process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-seamless-')),data=path.join(temp,'library'),base='http://127.0.0.1:8854';
const evidence=path.join(root,'docs/acceptance-2.1');mkdirSync(evidence,{recursive:true});
let browser,server,count=0,baseline;const errors=[],paid=[];const check=(label,value)=>{assert.ok(value,label);console.log('PASS '+label);count++};
async function stop(){const child=server;server=null;if(child&&child.exitCode===null&&child.signalCode===null){const done=new Promise(r=>child.once('exit',r));child.kill();await done}}
async function boot(project){server=spawn('python',['-u',path.join(project,'server.py')],{cwd:temp,env:{...process.env,MIO_DATA_DIR:data,MIO_PORT:'8854'},stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});server.stderr.on('data',()=>{});for(let i=0;i<250;i++){try{if((await fetch(base+'/api/config')).ok)return}catch{}if(server.exitCode!==null)throw Error('server failed');await new Promise(r=>setTimeout(r,40))}throw Error('startup timeout')}
async function page(){const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.method()==='POST'&&/\/(?:chat|generate-image|provider\/generate|foundation\/jobs)$/.test(new URL(r.url()).pathname))paid.push(r.url())});await p.route(/^https:\/\//,r=>r.abort());await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{createUI.welcomePending=false;state.settings.identity.onboarded=true;guidePreferences().seen=true;document.querySelectorAll('dialog[open]').forEach(d=>d.close())});return p}
async function geometry(p,selector='.sf-image'){return p.locator(selector).evaluateAll(images=>{const r=images.map(i=>i.getBoundingClientRect());return {count:images.length,noGaps:r.slice(1).every((b,i)=>Math.abs(b.top-r[i].bottom)<.6),ratio:images.every((im,i)=>Math.abs(r[i].width/r[i].height-im.naturalWidth/im.naturalHeight)<.003),noOverflow:document.documentElement.scrollWidth<=innerWidth+1,top:r[0]?.top+scrollY,small:images.every((im,i)=>r[i].width<=im.naturalWidth+.5),text:(document.querySelector('.sf-pages')||document.body).innerText.trim()}})}
try{
 browser=await chromium.launch({args:['--no-sandbox']});
 if(process.env.MIO_SEAMLESS_BASELINE){
  const zip=path.resolve(process.env.MIO_SEAMLESS_BASELINE),result=spawnSync('python',['-c',`import zipfile,sys,json,hashlib
from pathlib import Path
z=zipfile.ZipFile(sys.argv[1]);marker=next(n for n in z.namelist() if n.endswith('/PACKAGE_MANIFEST.json'));m=json.loads(z.read(marker));assert m['version']=='2.0.0';prefix=marker.rsplit('/',1)[0]
assert hashlib.sha256(Path(sys.argv[1]).read_bytes()).hexdigest()=='58d5367146aca6fa6e928d9d5d5ce0a7e5037fb781b65f357dd2025319888f80'
z.extractall(sys.argv[2]);print(str(Path(sys.argv[2])/prefix))`,zip,path.join(temp,'old')],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);await boot(result.stdout.trim());const old=await page();
  baseline=await old.evaluate(async()=>{state.settings.studio.export.templateId='export-ink';state.books[0].presentationTemplateId='export-afterglow';const custom=exportTemplateCopy(exportTemplateBy('export-paper'));custom.title='我的旧版模板';state.exportTemplates.push(custom);save();if(!await savePythonWorkspace())throw Error('baseline save');return {templates:clone(state.exportTemplates),book:state.books[0].id,defaultId:state.settings.studio.export.templateId}});check('actual 2.0.0 archive supplies all six original presets and a custom copy',baseline.templates.length===7);await old.close();await stop();
 }
 await boot(root);const p=await page();
 check('new built-in appears once and validates',await p.evaluate(()=>{ensureStudioState();ensureStudioState();return state.exportTemplates.filter(t=>t.id==='export-seamless').length===1&&validateExportTemplate(seamlessTemplate())}));
 if(baseline){const upgraded=await p.evaluate(()=>({templates:state.exportTemplates,defaultId:state.settings.studio.export.templateId}));for(const old of baseline.templates){const now=upgraded.templates.find(t=>t.id===old.id);if(!isDeepStrictEqual(now,old))console.log('TEMPLATE_DIFFERENCE',old.id,Object.keys({...old,...now}).filter(k=>!isDeepStrictEqual(old[k],now?.[k])))}check('upgrade preserves every old template, custom copy, default and album choice',baseline.templates.every(old=>isDeepStrictEqual(upgraded.templates.find(t=>t.id===old.id),old))&&upgraded.defaultId===baseline.defaultId&&((await(await fetch(base+'/api/config')).json()).savedGalleries.find(b=>b.id===baseline.book).presentationTemplateId==='export-afterglow'))}
 check('registration does not replace user-owned data with the same identity',await p.evaluate(()=>{const s=clone(state),t=s.exportTemplates.find(t=>t.id==='export-seamless');t.builtin=false;t.title='用户自己的版本';const old=JSON.stringify(t);ensureStudioState(s);return JSON.stringify(s.exportTemplates.find(x=>x.id==='export-seamless'))===old}));
 const assets=['coast','cover','station','postcard'].map(n=>'data:image/webp;base64,'+readFileSync(path.join(root,'examples/afterglow',n+'.webp')).toString('base64'));
 const id=await p.evaluate(async assets=>{await Mio.fileLibrary.hydrateAll();const b=state.books[0];b.title='沿着海岸，一直走';b.curatedDemo=false;delete b.pictureEdits;b.steps=[];for(let i=0;i<assets.length;i++){const im=new Image();im.src=assets[i];await im.decode();b.steps.push({stepIndex:i,name:'外置幕标题_'+i,caption:'外置配文不应显示_'+i,prompt:'提示词不应显示_'+i,image:assets[i],width:im.naturalWidth,height:im.naturalHeight})}b.totalSteps=4;b.generatedSteps=4;state.queue=[];save();if(!await savePythonWorkspace())throw Error('seed failed');return b.id},assets);
 check('out-of-order source frames compile in storyboard order',await p.evaluate(assets=>{const b={title:'顺序',steps:[2,0,1].map(i=>({stepIndex:i,image:assets[i]}))};const doc=new DOMParser().parseFromString(compileTemplateDocument(seamlessTemplate(),[b]),'text/html');return [...doc.querySelectorAll('.sf-image')].every((im,i)=>im.src===assets[i])},assets));
 await p.evaluate(id=>bookBy(id).readingMode='continuous',id);
 const source=await p.evaluate(id=>JSON.stringify(bookBy(id).steps),id);await p.evaluate(id=>openArtReader(id),id);await p.locator('.presentation-trigger').click();await p.locator('[data-act="presentation-select"][data-id="export-seamless"]').click();
 const frame=p.frameLocator('#presentation-preview');await frame.locator('.sf-image').last().waitFor();await frame.locator('.sf-image').evaluateAll(images=>Promise.all(images.map(i=>{i.loading='eager';return i.decode()})));
 const g=await geometry(frame);check('real reader has four images, no visible text and zero vertical gaps',g.count===4&&g.noGaps&&g.text==='');check('reader retains complete ratios and does not enlarge small originals',g.ratio&&g.small&&g.noOverflow);check('there is no cover duplicate, caption slot, title block or ending',await frame.locator('figcaption,[data-cc-caption],[data-cc-prompt],h1,h2,footer,[data-mio-colophon]').count()===0&&g.top===0);
 check('opaque preview sandbox and offline CSP stay intact',await p.locator('#presentation-preview').getAttribute('sandbox')==='allow-scripts'&&(await frame.locator('meta[http-equiv="Content-Security-Policy"]').getAttribute('content')).includes("connect-src 'none'"));
 check('selecting a style leaves original captions, prompts and images untouched',await p.evaluate(({id,source})=>JSON.stringify(bookBy(id).steps)===source,{id,source}));
 await p.locator('#presentation-drawer [data-act="presentation-panel"]').click();await p.screenshot({path:path.join(evidence,'reader-desktop.png')});
 const html=await p.evaluate(async id=>{const b=clone(bookBy(id));for(const s of b.steps)s.image=await imageData(s.image);return compileTemplateDocument(seamlessTemplate(),[b],{showCaptions:true,showPrompts:true,border:8,signature:'不应显示的签名'})},id);
 const example=path.join(root,'examples/seamless/无缝_纯图阅读_演示画册.html');mkdirSync(path.dirname(example),{recursive:true});writeFileSync(example,html);
 const offline=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'});offline.on('pageerror',e=>errors.push(e.message));await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+example);await offline.locator('.sf-image').evaluateAll(images=>Promise.all(images.map(i=>{i.loading='eager';return i.decode()})));
 check('caption/prompt/signature/border options cannot reintroduce text or frame gaps',!html.includes('外置配文不应显示')&&!html.includes('提示词不应显示')&&!html.includes('不应显示的签名')&&(await geometry(offline)).noGaps&&await offline.locator('.sf-image').evaluateAll(a=>a.every(i=>getComputedStyle(i).borderTopWidth==='0px'&&getComputedStyle(i).borderRadius==='0px')));
 for(const [width,theme] of [[1440,'light'],[390,'light'],[390,'dark'],[320,'dark']]){await offline.setViewportSize({width,height:900});await offline.emulateMedia({colorScheme:theme});const metrics=await geometry(offline);check(width+'px '+theme+' offline view is seamless, uncropped and inside the viewport',metrics.noGaps&&metrics.ratio&&metrics.noOverflow);if(width!==320)await offline.screenshot({path:path.join(evidence,`offline-${width}-${theme}.png`)})}
 const nojs=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await nojs.goto('file://'+example);check('zero-gap layout works with JavaScript disabled',(await geometry(nojs)).noGaps&&await nojs.locator('.sf-image').count()===4);await nojs.close();
 // Native-sized small images and edited raster content are not cropped or rewritten.
 const extra=await p.evaluate(async()=>{const c=document.createElement('canvas');c.width=240;c.height=160;const x=c.getContext('2d');x.fillStyle='#e4c18a';x.fillRect(0,0,240,160);x.fillStyle='#17292e';x.font='18px sans-serif';x.fillText('图内对白保留',18,86);const im=c.toDataURL();const b={title:'尺寸与图内对白',readingMode:'continuous',steps:[{stepIndex:2,image:im},{stepIndex:0,image:im},{stepIndex:1,image:im}]};return {im,html:compileTemplateDocument(seamlessTemplate(),[b])}});const small=await browser.newPage({viewport:{width:1440,height:900}});await small.setContent(extra.html);await small.locator('.sf-image').evaluateAll(a=>Promise.all(a.map(i=>i.decode())));check('small edited raster stays 240px wide and its bytes are unchanged',await small.locator('.sf-image').evaluateAll((a,im)=>a.every(i=>i.src===im&&i.getBoundingClientRect().width===240),extra.im)&&(await geometry(small)).noGaps);await small.close();
 await p.locator('.presentation-trigger').click();const download=p.waitForEvent('download');await p.locator('[data-act="presentation-export"]').click();const dl=await download,downloaded=path.join(temp,'actual-download.html');await dl.saveAs(downloaded);await offline.goto('file://'+downloaded);await offline.locator('.sf-image').evaluateAll(a=>Promise.all(a.map(i=>{i.loading='eager';return i.decode()})));check('actual UI download includes every original image at native resolution',await offline.locator('.sf-image').evaluateAll((a,assets)=>a.length===assets.length&&a.every((im,i)=>im.src===assets[i]),assets)&&(await geometry(offline)).noGaps);
 await p.evaluate(async()=>{await closeReader();if(!await savePythonWorkspace())throw Error('save after selection')});await p.reload();await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(id=>openArtReader(id),id);await p.frameLocator('#presentation-preview').locator('.sf-image').last().waitFor();check('chosen style and original text survive native save/reload',await p.evaluate(id=>presentationUI.templateId==='export-seamless'&&bookBy(id).steps[0].caption==='外置配文不应显示_0',id));
 check('there were no provider submissions or browser errors',paid.length===0&&errors.length===0);console.log(count+' seamless checks passed. No model calls.');
}finally{await browser?.close();await stop();rmSync(temp,{recursive:true,force:true})}
