import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdirSync,readFileSync,mkdtempSync,rmSync} from 'node:fs';import {spawn} from 'node:child_process';import {tmpdir} from 'node:os';import path from 'node:path';
const base=process.env.MIO_TEST_URL||'http://127.0.0.1:8883',artifacts=process.env.MIO_EVIDENCE||path.join(process.cwd(),'docs/acceptance-round2');mkdirSync(artifacts,{recursive:true});
const temp=mkdtempSync(path.join(tmpdir(),'mio-workbench-'));let server;
if(!process.env.MIO_TEST_URL){server=spawn('python',['server.py'],{env:{...process.env,MIO_HOST:'127.0.0.1',MIO_PORT:'8883',MIO_DATA_DIR:path.join(temp,'data')},stdio:'ignore'});let ready=false;for(let i=0;i<150;i++){try{if((await fetch(base+'/api/content')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}if(!ready){server.kill();throw Error('Isolated test service did not start')}}
const browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1560,height:1050}});const errors=[];p.on('pageerror',e=>errors.push(e.message));let n=0;const check=(label,v)=>{assert.ok(v,label);console.log('PASS '+label);n++};
async function shot(name){await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:artifacts+'/'+name+'.png',fullPage:true})}
async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());state.settings.identity.onboarded=true;guidePreferences().seen=true;createUI.tab='settings';navigate(1)});}
async function save(){const ok=await p.evaluate(()=>savePythonWorkspace());if(!ok)console.log('SAVE ERROR',await p.evaluate(()=>Mio.sync.runtime.error));check('backend acknowledges save',ok)}
async function expand(scope='#main'){while(await p.locator(scope+' .group-toggle[aria-expanded="false"]').count())await p.locator(scope+' .group-toggle[aria-expanded="false"]').first().click()}
try{
 await load();await p.evaluate(async()=>{state.creation.variableSets=state.creation.variableSets.filter(s=>!s.title.startsWith('第二轮'));const plan=selectedPlan();state.drafts.creationTargets??={};state.drafts.creationTargets[plan.id]='';plan.settingsGroups=[{id:'test-character',title:'主角与服装'},{id:'test-visual',title:'画风与场景'}];plan.variables=mergedSettingEntries(plan).filter(e=>e.key!=='round2_light').map(e=>({...e,groupId:['character_display_name','character','outfit'].includes(e.key)?'test-character':'test-visual'}));plan.variableSetIds=[];settingsGroupUI.open.clear();settingsGroupUI.editing.clear();save();await savePythonWorkspace();render()});
 check('groups start collapsed',await p.locator('#main .group-content:visible').count()===0);
 check('only one album selector, in title',await p.locator('#art-book-draft').count()===1&&await p.locator('.title-owner-select #art-book-draft').count()===1);
 check('footer and English decorations removed',await p.locator('.settings-book-footer').count()===0&&!/YOUR CREATIVE TOOLKIT|BOOK SETTINGS/.test(await p.locator('#main').innerText()));
 check('toolbar includes import / export / asset save',await p.locator('.settings-toolbar-actions [data-act="native-import"]').count()===1&&await p.locator('.settings-toolbar-actions [data-act="native-export-settings"]').count()===1);
 await shot('01-collapsed-desktop');
 await p.locator('[data-act="settings-group-new"]').click();await p.locator('#text-value').fill('镜头与光影');await p.locator('[data-act="text-submit"]').click();await p.waitForSelector('.group-title:text-is("镜头与光影")');
 const gid=await p.evaluate(()=>settingsGroups(currentBookSettings()).find(g=>g.title==='镜头与光影').id);
 await p.locator('[data-act="settings-group-edit"]').click();await p.locator(`[data-group-name="${gid}"]`).fill('镜头语言');await p.locator('[data-act="settings-group-edit"]').click();await save();
 check('group renamed',await p.locator('.group-title:text-is("镜头语言")').count()===1);
 await p.locator('.settings-toolbar-actions [data-act="art-setting-add"]').click();await p.locator('#art-new-setting-label').fill('光线');await p.locator('#art-new-setting-key').fill('round2_light');await p.locator('#art-new-setting-group').selectOption(gid);await p.locator('[data-act="art-setting-confirm"]').click();await p.locator(`.group-title[data-id="${gid}"]`).click();await p.locator('[data-art-setting="round2_light"]').fill('soft backlighting, blue hour');
 await p.locator('[data-act="settings-meta-edit"][data-key="round2_light"]').click();await p.locator('#setting-meta-group').selectOption('test-visual');await p.locator('[data-act="settings-meta-save"]').click();await save();
 check('move preserves typed value',await p.evaluate(()=>currentBookSettings().variables.find(e=>e.key==='round2_light').value==='soft backlighting, blue hour'));
 await p.reload();await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await p.evaluate(()=>{createUI.tab='settings';navigate(1)});
 check('groups and membership persist across reload',await p.evaluate(()=>settingsGroups(currentBookSettings()).some(g=>g.title==='镜头语言')&&currentBookSettings().variables.find(e=>e.key==='round2_light').groupId==='test-visual'));
 check('reload resets expansion',await p.locator('.group-content:visible').count()===0);
 await expand();await shot('02-expanded-desktop');
 await p.locator('[data-act="settings-group-edit"]').click();await shot('03-edit-groups');await p.locator('[data-act="settings-group-delete"][data-id="test-visual"]').click();await p.locator('#confirm-yes').click();
 check('delete group preserves all attribute values',await p.evaluate(()=>currentBookSettings().variables.some(e=>e.key==='round2_light'&&!e.groupId&&e.value==='soft backlighting, blue hour')));
 await p.locator('[data-act="settings-group-edit"]').click();await save();
 await p.locator('.settings-toolbar-actions [data-act="art-save-preset"]').click();await p.locator('#text-value').fill('第二轮 · 分组验证');await p.locator('[data-act="text-submit"]').click();await p.waitForFunction(()=>projectVariableSets().some(s=>s.title==='第二轮 · 分组验证'));
 const presetId=await p.evaluate(()=>projectVariableSets().find(s=>s.title==='第二轮 · 分组验证').id);
 check('save as preset copies groups',await p.evaluate(id=>JSON.stringify(setBy(id).settingsGroups)===JSON.stringify(currentBookSettings().settingsGroups),presetId));
 await p.locator('[data-act="preset-library-open"]').click();await p.locator('#art-setting-preset').selectOption(presetId);await expand('#preset-library');await p.locator('#preset-library [data-art-setting="character"]').fill('isolated-preset-draft');
 check('preset draft does not mutate album',await p.evaluate(()=>currentBookSettings().variables.find(e=>e.key==='character').value!=='isolated-preset-draft'));
 await p.locator('#preset-library [data-act="ws-update-preset"]').click();await save();check('update preserves preset groups',await p.evaluate(id=>setBy(id).settingsGroups.length===currentBookSettings().settingsGroups.length,presetId));
 const downloadPromise=p.waitForEvent('download');await p.locator('#preset-library [data-act="native-export-settings"]').click();const download=await downloadPromise;await download.saveAs(artifacts+'/grouped-settings.mio.zip');check('real ZIP export succeeds',readFileSync(artifacts+'/grouped-settings.mio.zip').subarray(0,2).toString()==='PK');
 await shot('04-preset-library');
 await p.locator('#preset-library [data-act="art-apply-preset"]').click();await p.locator('#confirm-yes').click();await p.waitForFunction(()=>currentBookSettings().variables.some(e=>e.key==='character'&&e.value==='isolated-preset-draft'));await save();
 check('apply copies groups without shared object identity',await p.evaluate(id=>JSON.stringify(currentBookSettings().settingsGroups)===JSON.stringify(setBy(id).settingsGroups)&&currentBookSettings().settingsGroups!==setBy(id).settingsGroups,presetId));
 const first=await p.evaluate(()=>selectedPlan().id);const second=await p.evaluate(()=>{const old=selectedPlan();const other={...clone(old),id:uid('plan'),title:'另一册 · 雨后',variables:[variableEntry('character','second-album')],settingsGroups:[],variableSetIds:[]};state.creation.plans.push(other);save();render();return other.id});await p.locator('#art-book-draft').selectOption(second);check('title selector switches editor owner',await p.evaluate(()=>currentBookSettings().variables[0].value==='second-album'));await p.locator('#art-book-draft').selectOption(first);
 // Import the exported ZIP via the real picker/inspection/confirmation pipeline.
 const chooserPromise=p.waitForEvent('filechooser');await p.locator('#main .settings-toolbar-actions [data-act="native-import"]').click();const chooser=await chooserPromise;await chooser.setFiles(artifacts+'/grouped-settings.mio.zip');await p.locator('#resource-import-confirm').click();await p.waitForFunction(()=>projectVariableSets().filter(s=>s.entries?.some(e=>e.key==='round2_light')).length>=2);
 check('import retains group definitions',await p.evaluate(()=>projectVariableSets().filter(s=>s.entries?.some(e=>e.key==='round2_light')).every(s=>s.settingsGroups?.length)));
 await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());settingsGroupUI.open.clear();render()});await p.setViewportSize({width:390,height:844});await shot('05-mobile');check('mobile has no horizontal overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('.preset-independence summary').click();check('help is available on touch',await p.locator('.preset-independence[open]').count()===1);await expand();await shot('06-mobile-expanded');
 check('no uncaught JS errors',errors.length===0);console.log(n+' workbench assertions PASS');
}finally{await browser.close();if(server&&server.exitCode===null){const stopped=new Promise(r=>server.once('exit',r));server.kill();await stopped}rmSync(temp,{recursive:true,force:true})}
