// Current studio UI regression suite. Runs against an isolated data directory.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,cpSync,readFileSync,writeFileSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const temp=mkdtempSync(path.join(tmpdir(),'ccs-studio-'));
for(const name of ['server.py','mio_api.py','mio_credentials.py','mio_docs.py','index.html','styles.css','favicon.svg','vendor','js','docs','examples','README.md','README.en.md','SECURITY.md'])cpSync(path.join(ROOT,name),path.join(temp,name),{recursive:true});
const port=Number(process.env.SMOKE_PORT||8791),base=`http://127.0.0.1:${port}`;
const server=spawn('python3',['-u','server.py'],{cwd:temp,env:{...process.env,COMFY_COMIC_PORT:String(port)},stdio:['ignore','pipe','pipe']});
let browser,checks=0;const check=(name,value)=>{assert.ok(value,name);console.log('PASS '+name);checks++};
try{
  await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Server startup timeout')),15000);server.stdout.on('data',d=>{if(d.toString().includes('物理落盘')){clearTimeout(timeout);resolve()}});server.on('error',reject)});
  browser=await chromium.launch({args:['--no-sandbox'],...(process.env.CCS_CHROMIUM?{executablePath:process.env.CCS_CHROMIUM}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await context.route(/^https:\/\//,route=>route.abort());
  await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);
  check('Mio workspace identity and runtime are available',await page.evaluate(()=>document.title.includes('Mio')&&document.querySelector('.brand-name').textContent==='Mio'&&!!globalThis.Mio));
  check('offline documentation hub is served', (await page.request.get(base+'/docs/index.html')).status()===200);
  check('fresh installation accepts the native backend contract',await page.evaluate(()=>ComfyComic.sync.runtime.loaded));
  if(await page.locator('[data-act="v3-welcome-default"]').isVisible())await page.locator('[data-act="v3-welcome-default"]').click();
  await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close())});
  // Marketplace scrolling, selective rendering and scoped localization.
  await page.evaluate(()=>{ui.marketTab='all';ui.marketSearch='';marketModal()});
  await page.waitForTimeout(150);
  check('market uses a single scroll surface without live backdrop blur',await page.evaluate(()=>getComputedStyle($('#modal'),'::backdrop').backdropFilter==='none'&&getComputedStyle($('#modal-body')).overscrollBehavior==='contain'&&getComputedStyle($('.market-item')).contentVisibility==='auto'));
  const marketId=await page.evaluate(()=>exportMarketCatalog.find(c=>!state.installedPackages.some(p=>p.id===c.id)).id);
  await page.locator('#raw-url').fill('https://example.invalid/my-template.json');
  await page.evaluate(()=>{window.marketInputBefore=$('#market-search');window.marketRawBefore=$('#raw-url');window.marketScrollCard=$('.market-item');$('#modal-body').scrollTop=400});
  await page.waitForTimeout(100);
  check('scrolling preserves card and input DOM nodes',await page.evaluate(()=>window.marketScrollCard===$('.market-item')&&window.marketInputBefore===$('#market-search')));
  await page.locator('#market-search').fill('no-such-market-entry-90872');await page.waitForTimeout(200);
  check('market search renders empty results without replacing controls',await page.evaluate(()=>!$('.market-item')&&window.marketInputBefore===$('#market-search')&&window.marketRawBefore===$('#raw-url')&&$('#raw-url').value==='https://example.invalid/my-template.json'&&document.activeElement===$('#market-search')));
  await page.locator('#market-search').fill('');await page.waitForTimeout(200);
  await page.locator('[data-act="market-tab"][data-tab="exports"]').click();
  check('market tabs filter cards and retain import drafts',await page.evaluate(()=>$$('.market-item').length===exportMarketCatalog.length&&$('#raw-url').value==='https://example.invalid/my-template.json'));
  await page.locator(`[data-act="market-install"][data-id="${marketId}"]`).click();
  check('market installation still works after result-only rendering',await page.evaluate(id=>state.installedPackages.some(p=>p.id===id),marketId));
  await page.locator(`[data-act="market-install"][data-id="${marketId}"]`).click();await page.locator('#confirm-yes').click();
  check('market uninstall retains its confirmation flow',await page.evaluate(id=>!state.installedPackages.some(p=>p.id===id),marketId));
  await page.evaluate(()=>{displayUI.locale.setLanguage('en');localizeWorkspace();const probe=document.createElement('div');probe.id='market-locale-probe';probe.innerHTML='<span>安装</span><span data-user-content>设置</span><input placeholder="新建画册">';$('#market-content').append(probe)});
  await page.waitForTimeout(100);
  check('mutation localization translates interface text but not authored content',await page.evaluate(()=>$('#market-locale-probe span').textContent==='Install'&&$('#market-locale-probe [data-user-content]').textContent==='设置'));
  await page.evaluate(()=>{$('#market-locale-probe input').setAttribute('placeholder','搜索画册')});await page.waitForTimeout(100);
  check('scoped localization includes attributes on the changed input itself',await page.locator('#market-locale-probe input').getAttribute('placeholder')==='Search books');
  await page.evaluate(()=>{displayUI.locale.setLanguage('zh-CN');localizeWorkspace()});
  check('language switching restores interface copy',await page.locator('#market-locale-probe span').first().innerText()==='安装');
  await page.locator(`[data-act="et-market-preview"][data-id="${marketId}"]`).first().click();
  check('template preview retains its sandbox and clears market-only styling',await page.locator('#market-template-preview').getAttribute('sandbox')==='allow-scripts'&&!await page.locator('#modal').evaluate(e=>e.classList.contains('market-dialog')));
  await page.evaluate(()=>{$('#modal').close()});await page.waitForTimeout(100);
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{ui.marketTab='all';ui.marketSearch='';marketModal()});
  check('market fits a narrow viewport without horizontal overflow',await page.evaluate(()=>$('#modal-body').scrollWidth<=$('#modal-body').clientWidth+2&&$('#modal').getBoundingClientRect().right<=innerWidth));
  await page.evaluate(()=>{$('#modal').close()});await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(100);
  check('all services default to real mode without fallback',await page.evaluate(()=>state.settings.comfy.mode==='real'&&state.settings.llm.mode==='real'&&state.settings.critic.mode==='real'&&state.settings.comfy.autoFallback===false&&!llmMock()));
  check('original girl cover is embedded and survives offline loading',await page.evaluate(()=>{const b=state.books.find(b=>b.id==='edition_letter');return b.steps[0].image===defaultCuratedCover()&&b.steps[0].image.startsWith('data:image/webp;base64,')&&readerSequence(b)[0].pending===false}));
  check('restoring the demo cover never fills other missing pages or replaces custom artwork',await page.evaluate(()=>{const sample={books:[{id:'edition_letter',curatedDemo:true,steps:[{stepIndex:0,image:'https://images.alphacoders.com/819/thumbbig-819506.webp'},{stepIndex:1,image:''}]},{id:'edition_letter_demo_custom',curatedDemo:true,steps:[{stepIndex:0,image:'my-custom-image'}]},{id:'new-book',steps:[{stepIndex:0,image:''}]}]};return restoreCuratedCover(sample)===1&&sample.books[0].steps[0].image===defaultCuratedCover()&&sample.books[0].steps[1].image===''&&sample.books[1].steps[0].image==='my-custom-image'&&sample.books[2].steps[0].image===''}));
  check('showcase is the default gallery',await page.evaluate(()=>state.settings.presentation.homeLayout==='showcase'));
  check('extensions are hidden by default',await page.locator('[data-act="art-nav"][data-route="7"]').count()===0);
  check('activity log is last when enabled',await page.evaluate(()=>{const n=createWorkspaceChromePolicy().navigation({logs:true});return n.at(-1)[0]===6}));
  await page.locator('[data-act="art-nav"][data-route="3"]').click();
  check('workflow has an independent module',await page.locator('.workflow-library').count()===1&&await page.evaluate(()=>ui.workspace===3));
  // Real multi-file file picker, with one invalid import to exercise partial success.
  const wf=await page.evaluate(()=>clone(state.settings.comfy.workflow));
  const chooser=page.waitForEvent('filechooser');await page.locator('[data-act="ws-import"]').click();
  await (await chooser).setFiles([
    {name:'A.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({title:'A workflow',workflow:wf}))},
    {name:'B.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({title:'B workflow',workflow:wf}))},
    {name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{broken')}
  ]);
  await page.waitForSelector('#modal[open]');check('batch import reports invalid files without losing valid imports',(await page.locator('#modal-body').innerText()).includes('成功导入 2'));
  await page.locator('#modal [data-act="close-modal"]').first().click();
  const ids=await page.evaluate(()=>state.settings.comfy.presets.filter(p=>/^[AB] workflow/.test(p.title)).map(p=>p.id));
  await page.locator('[data-setting="comfy.workflowTitle"]').fill('A edited');await page.locator('#ws-library-select').selectOption(ids[1]);await page.locator('#ws-library-select').selectOption(ids[0]);
  check('workflow switching retains unsaved-looking field edits',await page.locator('[data-setting="comfy.workflowTitle"]').inputValue()==='A edited');
  await page.locator('[data-act="art-nav"][data-route="1"]').click();
  check('storyboard provides preset and workflow selectors before preview',await page.locator('#ws-scene-preset').count()===1&&await page.locator('#ws-scene-workflow').count()===1);
  await page.locator('[data-act="art-create-tab"][data-tab="settings"]').click();
  const old=await page.evaluate(()=>JSON.stringify(state.creation.variableSets));
  await page.locator('[data-act="ws-new-preset"]').click();
  await page.locator('#modal input').first().fill('New preset');
  await page.locator('#modal .modal-footer .primary').click();
  check('blank preset starts empty without clearing existing presets',await page.evaluate(old=>{const prior=JSON.parse(old);return prior.every(p=>JSON.stringify(setBy(p.id))===JSON.stringify(p))&&mergedSettingEntries(selectedPlan()).every(e=>e.value==='')},old));
  await page.locator('[data-art-setting="character"]').fill('new_character');await page.locator('[data-act="ws-update-preset"]').click();
  check('new preset can be saved directly',await page.evaluate(()=>setBy(selectedPlan().editingPresetId).entries.some(e=>e.key==='character'&&e.value==='new_character')));
  // Stable fixture: full scope priority and per-frame workflow choices.
  await page.evaluate(ids=>{
    const p=selectedPlan(),t=templateBy(p.templateId),set={id:uid('set'),projectId:state.activeProjectId,title:'Scene preset',entries:[variableEntry('character','scene_character')]};state.creation.variableSets.push(set);
    p.variables=[variableEntry('character','book_character')];p.sceneOverrides[t.frames[0].id]={variableSetIds:[set.id],workflowId:ids[0]};p.sceneOverrides[t.frames[1].id]={workflowId:ids[1]};p.workflowId=ids[0];state.settings.comfy.mode='mock';createUI.tab='story';render();
  },ids);
  check('scene preset overrides full-book values',await page.evaluate(()=>effectivePlanFrame(selectedPlan(),currentTemplate().frames[0])._scope.character==='scene_character'));
  await page.evaluate(()=>{const p=selectedPlan(),f=currentTemplate().frames[0];p.sceneOverrides[f.id].variables=[variableEntry('character','frame_character')]});
  check('scene custom override has highest priority',await page.evaluate(()=>effectivePlanFrame(selectedPlan(),currentTemplate().frames[0])._scope.character==='frame_character'));
  await page.locator('[data-act="art-create-tab"][data-tab="queue"]').click();
  check('queue can add a task and choose a workflow in-place',await page.locator('#ws-plan-workflow').count()===1&&await page.locator('#ws-queue-range').count()===1);
  await page.locator('#ws-queue-range').selectOption('0');await page.locator('[data-act="ws-enqueue-range"]').click();
  await page.waitForFunction(()=>rt.running);
  await page.locator('#ws-queue-range').selectOption('1');await page.locator('[data-act="ws-enqueue-range"]').click();
  check('a second scene can queue while the first runs',await page.evaluate(()=>state.queue.length>=2));
  check('A and B tasks keep separate workflow snapshots',await page.evaluate(ids=>{const [a,b]=state.queue.slice(-2);return a.frames[0]._execution.workflowId===ids[0]&&b.frames[1]._execution.workflowId===ids[1]},ids));
  await page.waitForFunction(()=>!rt.running,null,{timeout:20000});
  check('both mock tasks finish successfully',await page.evaluate(()=>state.queue.slice(-2).every(q=>q.status==='complete')));
  check('single-scene task does not claim the entire album is complete',await page.evaluate(()=>state.books.slice(-2).every(b=>b.status==='partial'&&b.generatedSteps===1)));
  // In-place edits are allowed only for a pending scene, not a running one.
  await page.evaluate(()=>{rt.paused=true;return enqueueWorkspaceRange([0,1])});
  const qid=await page.evaluate(()=>state.queue.at(-1).id);
  await page.locator('.queue-workflow-detail').last().locator('summary').click();
  await page.locator(`[data-ws-task="${qid}"][data-ws-index="1"]`).selectOption(ids[0]);
  check('pending task workflow can be adjusted inline',await page.evaluate(id=>state.queue.at(-1).frames[1]._execution.workflowId===id,ids[0]));
  check('changing pending task does not mutate another task',await page.evaluate(id=>state.queue.at(-2).frames[1]._execution.workflowId===id,ids[1]));
  // Exercise the actual /prompt -> /history -> /view client against a stub GPU,
  // then the real Python image endpoint. No real GPU is claimed by this test.
  const pixel='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1x8AAAAASUVORK5CYII=';
  const submissions=[];
  await context.route('http://127.0.0.1:8188/**',async route=>{
    const req=route.request(),url=new URL(req.url());let json={};
    if(url.pathname==='/prompt'){submissions.push(req.postDataJSON());json={prompt_id:'stub-prompt'}}
    if(url.pathname.startsWith('/history/'))json={'stub-prompt':{status:{completed:true},outputs:{'9':{images:[{filename:'pixel.png',type:'output'}]}}}};
    await route.fulfill({status:200,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'*'},contentType:url.pathname==='/view'?'image/png':'application/json',body:url.pathname==='/view'?Buffer.from(pixel,'base64'):JSON.stringify(json)});
  });
  const asset=await page.evaluate(async()=>{const p=selectedPlan(),f=effectivePlanFrame(p,currentTemplate().frames[0]);f._execution.mode='real';f._execution.autoFallback=false;f._assetBookId='integration-album';return (await generateMappedFrame(f,planRuntimeRow(p),new AbortController().signal)).image});
  check('GPU protocol path persists raster output under the album directory',asset.startsWith('/images/albums/integration-album/')&&submissions.length===1);
  const image=await fetch(base+asset);check('stored relative image URL is served by the same Python backend',image.ok&&(await image.arrayBuffer()).byteLength>0);
  const preview=await page.evaluate(()=>{const copyState=clone(state);copyState.books[0].steps[0].image='/images/albums/integration-album/example.png';validateState(copyState);return true});
  check('state validator accepts portable local image URLs',preview);
  await context.route('http://127.0.0.1:8188/prompt',route=>route.fulfill({status:400,headers:{'Access-Control-Allow-Origin':'*'},contentType:'application/json',body:JSON.stringify({error:'test GPU rejection'})}));
  check('real GPU failures never create sample artwork even with legacy fallback enabled',await page.evaluate(async()=>{const p=selectedPlan(),f=effectivePlanFrame(p,currentTemplate().frames[0]);f._execution.mode='real';f._execution.autoFallback=true;try{await generateMappedFrame(f,planRuntimeRow(p),new AbortController().signal);return false}catch(e){return e.message.includes('400')}}));

  const saved=await page.evaluate(()=>ComfyComic.sync.save());if(!saved)console.log('SYNC ERROR',await page.evaluate(()=>ComfyComic.sync.runtime.error));check('native POST save is confirmed',saved);
  const persisted=await (await fetch(base+'/api/config')).json();
  check('API preserves per-scene workflow and preset assignments',persisted.uiConfig.comfyStudio.creation.plans.some(p=>Object.values(p.sceneOverrides).some(o=>o.workflowId===ids[0])));
  check('structured workflow and queue files exist',existsSync(path.join(temp,'data/workflows/library.json'))&&existsSync(path.join(temp,'data/queue/tasks.json')));
  // Queue organization: queue is explicitly paused while arranging pending work.
  await page.evaluate(async()=>{rt.paused=true;await enqueueWorkspaceRange([1]);await enqueueWorkspaceRange([2])});
  const pendingBefore=await page.evaluate(()=>state.queue.filter(q=>q.status==='pending').map(q=>q.id));
  const firstPending=pendingBefore[0],lastPending=pendingBefore.at(-1);
  await page.locator(`[data-sort-task="${lastPending}"] .task-drag-handle`).dragTo(page.locator(`[data-sort-task="${firstPending}"]`),{targetPosition:{x:40,y:4}});
  check('dragging a pending task updates actual execution order',await page.evaluate(id=>state.queue.filter(q=>q.status==='pending')[0].id===id,lastPending));
  check('queue rows use the same forward order as stored tasks',await page.evaluate(()=>[...document.querySelectorAll('[data-sort-task]')].map(e=>e.dataset.sortTask).join('|')===state.queue.filter(q=>bookBy(q.bookId)).map(q=>q.id).join('|')));
  const removed=await page.evaluate(()=>{const q=state.queue.filter(q=>q.status==='pending')[1];return {id:q.id,book:q.bookId}});
  await page.locator(`[data-act="org-task-delete"][data-id="${removed.id}"]`).click();await page.locator('#confirm-yes').click();
  await page.waitForFunction(id=>!state.queue.some(q=>q.id===id),removed.id);
  check('deleting a queued task keeps its album',await page.evaluate(id=>!!bookBy(id),removed.book));
  check('only Generate album has primary emphasis on the queue page',await page.evaluate(()=>[...document.querySelectorAll('#main .primary')].every(e=>e.dataset.act==='v3-generate-plan')&&document.querySelectorAll('#main .primary').length===1));
  check('unfinished queue thumbnails contain no fabricated image',await page.evaluate(()=>[...document.querySelectorAll('[data-sort-task]')].filter(e=>state.queue.find(q=>q.id===e.dataset.sortTask)?.status==='pending').every(e=>e.querySelector('.ordered-queue-thumb .artwork-missing')&&!e.querySelector('.ordered-queue-thumb img'))));
  await page.evaluate(()=>{window.startedBooks=[];window.originalTestGenerator=generateFrame;generateFrame=async function(f,...rest){window.startedBooks.push(f._assetBookId);return window.originalTestGenerator(f,...rest)}});
  const expectedBooks=await page.evaluate(()=>state.queue.filter(q=>q.status==='pending').map(q=>q.bookId));
  await page.locator('[data-act="org-queue-pause"]').click();await page.waitForFunction(()=>rt.running);
  check('running task cannot be dragged or deleted',await page.evaluate(()=>{const q=state.queue.find(q=>q.status==='running'),el=document.querySelector(`[data-sort-task="${q.id}"]`);return el.draggable===false&&el.querySelector('[data-act="org-task-delete"]').disabled}));
  check('enqueue while paused does not implicitly resume an active queue',await page.evaluate(async()=>{rt.paused=true;await enqueueWorkspaceRange([3]);return rt.paused===true}));
  const appended=await page.evaluate(()=>state.queue.at(-1).bookId);expectedBooks.push(appended);
  await page.locator('[data-act="org-queue-pause"]').click();await page.waitForFunction(()=>!rt.running,null,{timeout:25000});
  const started=await page.evaluate(()=>[...new Set(window.startedBooks)]);
  check('scheduler executes the reordered queue FIFO including new tasks',JSON.stringify(started)===JSON.stringify(expectedBooks));
  await page.evaluate(()=>{generateFrame=window.originalTestGenerator});
  // Errors must preserve the source URL and show a neutral placeholder.
  const failureSafe=await page.evaluate(()=>{const b=state.books[0],before=b.steps[0].image,img=document.createElement('img');img.dataset.book=b.id;img.dataset.step='0';img.alt='unavailable';document.body.append(img);img.dispatchEvent(new Event('error'));const placeholder=document.querySelector('.artwork-missing[aria-label="unavailable · 暂无画面"]');const ok=!!placeholder&&b.steps[0].image===before;placeholder?.remove();return ok});
  check('image errors do not rewrite stored URLs to sample artwork',failureSafe);
  check('missing reader pages stay empty even with an old offline preview',await page.evaluate(()=>{const seq=readerSequence({theme:0,totalSteps:2,steps:[{stepIndex:0,image:'',offlineImage:'data:image/png;base64,AAAA'}]});return seq.every(s=>s.image===''&&s.pending)}));
  // Existing explicit real configs without keys must not invoke mock language generation.
  check('missing API keys do not silently enable mock mode',await page.evaluate(()=>llmMock({mode:'real',key:'',baseUrl:'https://example.invalid'})===false));
  // Collection drag sorting and right-click multi-selection.
  await page.evaluate(()=>{navigate(0);setShelfLayout('grid');ui.filter='all';ui.search='';ui.selected.clear();ui.bulk=false;render()});
  const books=await page.evaluate(()=>getShelfBooks().map(b=>b.id));
  await page.locator(`.shelf-item[data-sort-book="${books.at(-1)}"]`).dragTo(page.locator(`.shelf-item[data-sort-book="${books[0]}"]`),{targetPosition:{x:30,y:4}});
  check('dragging an album persists manual collection order',await page.evaluate(id=>ui.sort==='manual'&&getShelfBooks()[0].id===id,books.at(-1)));
  const chosen=await page.evaluate(()=>getShelfBooks().filter(b=>!b.curatedDemo).slice(0,2).map(b=>b.id));
  await page.locator(`.shelf-item[data-sort-book="${chosen[0]}"] .shelf-cover`).click({modifiers:['Control']});
  await page.locator(`.shelf-item[data-sort-book="${chosen[1]}"] .shelf-cover`).click({modifiers:['Control']});
  await page.locator(`.shelf-item[data-sort-book="${chosen[1]}"]`).click({button:'right'});
  check('right-click retains multiple selected albums',await page.locator('#book-context-menu').isVisible()&&await page.evaluate(()=>ui.selected.size===2));
  await page.locator('[data-act="org-context-edit"]').click();await page.locator('#org-book-prefix').fill('Edited · ');await page.locator('#org-book-tags').fill('test-tag');await page.locator('[data-act="org-book-edit-confirm"]').click();
  check('context batch editing affects exactly the selected albums',await page.evaluate(ids=>state.books.filter(b=>b.title.startsWith('Edited · ')).length===ids.length&&ids.every(id=>bookBy(id).tags.includes('test-tag')),chosen));
  await page.locator(`.shelf-item[data-sort-book="${chosen[0]}"]`).click({button:'right'});await page.locator('[data-act="org-context-export"]').click();
  check('context batch export opens the multi-book export dialog',await page.locator('#modal[open]').count()===1);
  await page.evaluate(()=>document.addEventListener('click',e=>{if(e.target.tagName==='A')window.testDownloadName=e.target.download},true));
  const exportDownload=page.waitForEvent('download');await page.locator('[data-act="compile-export"]').click();const exported=await exportDownload;const exportedHTML=readFileSync(await exported.path(),'utf8');check('batch export downloads an HTML album with neutral missing-page notes',exportedHTML.startsWith('<!DOCTYPE html>')&&exportedHTML.includes('尚未生成')&&await page.evaluate(()=>window.testDownloadName.endsWith('.html')));

  await page.locator('#modal [data-act="close-modal"]').first().click();
  await page.locator(`.shelf-item[data-sort-book="${chosen[0]}"]`).click({button:'right'});await page.keyboard.press('Escape');
  check('context menu supports Escape and returns focus',await page.locator('#book-context-menu').count()===0&&await page.evaluate(()=>document.activeElement.hasAttribute('data-sort-book')));
  const orderSaved=await page.evaluate(()=>manualBookIds());check('organized state saves successfully',await page.evaluate(()=>ComfyComic.sync.save()));
  await page.reload();await page.waitForFunction(()=>!rt.booting);await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(0)});
  check('manual album order survives a backend reload',JSON.stringify(await page.evaluate(()=>manualBookIds()))===JSON.stringify(orderSaved));
  await page.evaluate(ids=>{ui.selected=new Set(ids);ui.bulk=true;render()},chosen);
  await page.locator(`.shelf-item[data-sort-book="${chosen[0]}"]`).click({button:'right'});await page.locator('[data-act="org-context-delete"]').click();
  check('context batch delete requires confirmation',await page.locator('#confirm-dialog[open]').count()===1&&await page.evaluate(ids=>ids.every(id=>!!bookBy(id)),chosen));
  await page.locator('#confirm-yes').click();await page.waitForFunction(ids=>ids.every(id=>!bookBy(id)),chosen);
  check('context batch delete removes only chosen albums',await page.evaluate(count=>state.books.length===count,books.length-chosen.length));
  await page.reload();await page.waitForFunction(()=>!rt.booting);check('workflow library survives reload',await page.evaluate(id=>state.settings.comfy.presets.some(p=>p.id===id&&p.title==='A edited'),ids[0]));
  await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(3)});await page.waitForTimeout(500);
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(300);
  check('mobile workflow view has no document overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
  await page.locator('#image-provider-select').selectOption('novelai');
  check('NovelAI hides workflow library and exposes native model configuration',await page.locator('.workflow-library').count()===0&&await page.locator('[data-image-config="model"]').inputValue()==='nai-diffusion-4-5-full');
  await page.locator('[data-act="image-provider-keys"]').click();await page.waitForSelector('#modal[open]');
  await page.locator('#image-key-label').fill('Primary');await page.locator('#image-provider-key').fill('local-test-secret');
  check('key entry does not request a generated login password',await page.locator('#image-provider-key').getAttribute('autocomplete')==='off');
  await page.locator('[data-act="image-key-save"]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);
  check('saved key is hidden and only a reference enters configuration',await page.evaluate(()=>activeImageProfile().keyMode==='stored'&&!!activeImageProfile().keyId&&(!document.querySelector('#image-provider-key')||document.querySelector('#image-provider-key').value==='')&&!JSON.stringify(state).includes('local-test-secret')));
  check('provider snapshots freeze configuration without secrets or workflow',await page.evaluate(()=>{const ex=workflowExecutionFor(selectedPlan(),currentTemplate().frames[0]);window.providerTestSnapshot=ex;activeImageProfile().model='changed-model';return ex.config.model==='nai-diffusion-4-5-full'&&!ex.workflow&&!JSON.stringify(ex).includes('local-test-secret')&&ex.config.keyMode==='stored'&&!!ex.config.keyId}));
  check('API frame preflight does not require a valid ComfyUI workflow',await page.evaluate(()=>{const f=effectivePlanFrame(selectedPlan(),currentTemplate().frames[0]),old=state.settings.comfy.workflow;state.settings.comfy.workflow={};try{return Object.keys(buildMappedWorkflow(f,planRuntimeRow(selectedPlan()),{preview:true}).workflow).length===0}finally{state.settings.comfy.workflow=old}}));
  await page.route('**/api/image/generate',async route=>{const p=route.request().postDataJSON();await route.fulfill({json:{image:'/images/provider-contract.png',offlineFallback:false,seenModel:p.config.model}})});
  check('generation uses frozen provider even after switching active channel',await page.evaluate(async()=>{const f=effectivePlanFrame(selectedPlan(),currentTemplate().frames[0]);f._execution=window.providerTestSnapshot;ensureImageProviders().active='comfyui';const r=await generateFrame(f,planRuntimeRow(selectedPlan()),new AbortController().signal);return r.image==='/images/provider-contract.png'&&r.seenModel==='nai-diffusion-4-5-full'}));
  await page.unroute('**/api/image/generate');
  await page.evaluate(()=>{ensureImageProviders().active='openai';render()});
  await page.locator('[data-act="image-provider-copy"]').click();
  check('multiple OpenAI-compatible channels can be configured independently',await page.evaluate(()=>ensureImageProviders().profiles.length===4&&activeImageProfile().id!=='openai'&&activeImageProfile().protocol==='images'));
  check('provider layout fits mobile',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
  const providerId=await page.evaluate(()=>activeImageProfile().id);
  await page.evaluate(()=>ComfyComic.sync.save());await page.reload();await page.waitForFunction(()=>!rt.booting);
  check('provider settings and key references persist without plaintext',await page.evaluate(id=>activeImageProfile().id===id&&ensureImageProviders().profiles.find(p=>p.id==='novelai').keyMode==='stored'&&!JSON.stringify(ComfyComic.convertStudioStateToApiPayload()).includes('local-test-secret'),providerId));
  await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(3)});
  check('copied channels do not share saved credentials',await page.evaluate(()=>activeImageProfile().keyMode==='none'&&!activeImageProfile().keyId));
  await page.locator('[data-image-config="sendSize"]').check();await page.locator('[data-image-config="size"]').fill('1024x1536');await page.locator('[data-image-config="sendQuality"]').check();
  await page.locator('[data-image-config="sendSize"]').uncheck();await page.locator('[data-image-config="sendQuality"]').uncheck();
  check('size and quality can be disabled while their draft values remain',await page.locator('[data-image-config="size"]').isDisabled()&&await page.locator('[data-image-config="quality"]').isDisabled()&&await page.evaluate(()=>activeImageProfile().sendSize===false&&activeImageProfile().size==='1024x1536'));
  await page.route('**/api/image/models',route=>route.fulfill({json:{models:['model-a','model-b','<unsafe>']}}));
  await page.locator('[data-act="image-provider-models"]').click();await page.waitForFunction(()=>document.querySelector('#image-provider-model-select').options.length===4);
  await page.locator('#image-provider-model-select').selectOption('model-b');
  check('model discovery populates a safe picker and updates editable model ID',await page.locator('[data-image-config="model"]').inputValue()==='model-b'&&await page.locator('unsafe').count()===0);
  await page.unroute('**/api/image/models');await page.route('**/api/image/models',route=>route.fulfill({status:404,json:{error:'Models not supported'}}));
  await page.locator('[data-act="image-provider-models"]').click();await page.waitForFunction(()=>document.querySelector('#provider-model-status').textContent.includes('获取失败'));
  await page.locator('[data-image-config="model"]').fill('manual-model');await page.locator('[data-image-config="title"]').click();
  check('unsupported model discovery preserves manual configuration',await page.evaluate(()=>activeImageProfile().model==='manual-model'));
  await page.unroute('**/api/image/models');
  for(const [label,key] of [['Account A','secret-a'],['Account B','secret-b']]){
    await page.locator('[data-act="image-provider-keys"]').click();await page.waitForSelector('#modal[open]');await page.locator('#image-key-label').fill(label);await page.locator('#image-provider-key').fill(key);await page.locator('[data-act="image-key-save"]').click();await page.waitForFunction(()=>!document.querySelector('#modal').open);
  }
  const savedKey=await page.evaluate(()=>activeImageProfile().keyId);
  await page.locator('[data-act="image-provider-keys"]').click();await page.waitForSelector('#modal[open]');
  check('multiple keys are listed as metadata without secret values',await page.locator('.provider-key-row').count()===2&&!(await page.locator('#modal-body').innerText()).includes('secret-a'));
  await page.locator('[data-act="image-key-use"]').first().click();
  check('user can select a saved key explicitly',await page.evaluate(()=>activeImageProfile().keyLabel==='Account A'));
  await page.evaluate(()=>ComfyComic.sync.save());await page.reload();await page.waitForFunction(()=>!rt.booting);await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());navigate(3)});
  await page.locator('[data-act="image-provider-keys"]').click();await page.waitForSelector('#modal[open]');
  check('local key metadata survives page reload',await page.locator('.provider-key-row').count()===2&&await page.evaluate(()=>activeImageProfile().keyLabel==='Account A'));
  await page.locator('[data-act="image-key-delete"]').first().click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>document.querySelectorAll('.provider-key-row').length===1);
  check('deleting the selected key clears authentication instead of switching keys',await page.evaluate(()=>activeImageProfile().keyMode==='none'&&!activeImageProfile().keyId));
  await page.locator('[data-act="image-key-use"]').click();
  check('remaining key can still be selected',await page.evaluate(id=>activeImageProfile().keyId===id,savedKey));
  await page.locator('#image-provider-auth').selectOption('none');
  check('empty authentication is explicit and persists',await page.evaluate(()=>activeImageProfile().keyMode==='none'));
  check('channels in pending tasks cannot be deleted',await page.evaluate(async()=>{const p=activeImageProfile(),q={id:'provider-delete-guard',status:'pending',execution:{profileId:p.id}};state.queue.push(q);try{await handleImageProviderAction('image-provider-delete');return false}catch(e){return e.message.includes('未完成任务')}finally{state.queue=state.queue.filter(x=>x.id!==q.id)}}));
  await page.locator('[data-act="image-provider-delete"]').click();await page.locator('#confirm-no').click();
  check('channel deletion requires confirmation',await page.evaluate(id=>!!ensureImageProviders().profiles.find(p=>p.id===id),providerId));
  const removedProfile=await page.evaluate(()=>imageConfigSnapshot());
  await page.locator('[data-act="image-provider-delete"]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(id=>!ensureImageProviders().profiles.some(p=>p.id===id),providerId);
  const emptyKeys=await page.request.post(base+'/api/image/credentials',{data:{action:'list',config:removedProfile}});
  check('channel deletion also removes its saved local keys',(await emptyKeys.json()).keys.length===0);
  await page.locator('[data-act="image-provider-new"]').click();await page.locator('#image-new-title').fill('New channel');await page.locator('[data-act="image-provider-create"]').click();
  check('new API channels can be created after deletion with optional parameters off',await page.evaluate(()=>activeImageProfile().title==='New channel'&&activeImageProfile().sendSize===false&&activeImageProfile().sendQuality===false&&activeImageProfile().keyMode==='none'));

  // Documentation must render correctly, not merely return HTTP 200.
  const docsPage=await context.newPage();docsPage.on('pageerror',e=>errors.push(e.message));
  await docsPage.setViewportSize({width:1440,height:1000});
  const docResponse=await docsPage.goto(base+'/docs/WORKFLOW_UPDATE.md');await docsPage.waitForSelector('#document h1');
  check('Markdown URLs render readable Chinese headings with explicit UTF-8',docResponse.headers()['content-type']==='text/html; charset=utf-8'&&(await docsPage.locator('#document h1').innerText()).includes('第一阶段'));
  check('reader creates a working table of contents',await docsPage.locator('#toc a').count()>0);
  check('reader rewrites relative Markdown links to offline HTML pages',(await docsPage.locator('#document a').first().getAttribute('href')).endsWith('.html'));
  await docsPage.locator('#document a').first().click();await docsPage.waitForSelector('#document h1');
  check('linked guide navigation keeps Chinese text intact',(await docsPage.locator('#document').innerText()).includes('队列')&&docsPage.url().endsWith('QUEUE_AND_COLLECTION_UPDATE.html'));
  await docsPage.goto(base+'/docs/guide/QUICKSTART.html');await docsPage.waitForSelector('.copy-code');
  await docsPage.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copiedDocCode=text}}})});
  await docsPage.locator('.copy-code').first().click();
  check('reader code-copy button copies the code without UI labels',await docsPage.evaluate(()=>window.copiedDocCode.includes('{character}')&&!window.copiedDocCode.includes('复制代码')));
  writeFileSync(path.join(temp,'docs','security-probe.md'),'# 安全测试\n\n<script>window.docsInjected=true</script>\n<img src="bad" onerror="window.docsInjected=true">\n[unsafe](javascript:alert(1))');
  await docsPage.goto(base+'/docs/security-probe.md');await docsPage.waitForSelector('#document h1');
  check('reader sanitizes embedded script handlers and javascript links',await docsPage.evaluate(()=>!window.docsInjected&&!document.querySelector('#document script')&&!document.querySelector('#document [onerror]')&&![...document.querySelectorAll('#document a')].some(a=>a.href.startsWith('javascript:'))));
  await docsPage.goto(base+'/docs/index.html');await docsPage.waitForSelector('.hero h1');
  check('new homepage renders its illustration without external requests',await docsPage.evaluate(()=>[...document.querySelectorAll('.art-img')].every(img=>img.src.startsWith('data:image/webp;'))));
  await docsPage.locator('#guide-search').fill('密钥');
  check('homepage search filters tutorial entries',await docsPage.locator('.guide-link:visible').count()===1);
  await docsPage.locator('#guide-search').fill('');await docsPage.locator('#language').click();
  check('homepage language switch updates copy and tutorial destinations',await docsPage.locator('html').getAttribute('lang')==='en'&&(await docsPage.locator('.hero-actions .pill').getAttribute('href')).includes('en/GUIDE.html'));
  await docsPage.setViewportSize({width:390,height:844});
  check('new homepage fits mobile without horizontal overflow',await docsPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
  await docsPage.goto(base+'/docs/en/API.html');await docsPage.waitForSelector('#document h1');
  check('reader keeps code and tables inside the mobile viewport',await docsPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
  await docsPage.goto('file://'+path.join(temp,'docs','guide','CHANNELS_AND_KEYS.html'));await docsPage.waitForSelector('#document h1');
  check('prebuilt handbook works from file URLs without a Python server',(await docsPage.locator('#document h1').innerText()).includes('本地密钥'));
  await docsPage.close();
  check('no uncaught browser errors',errors.length===0);
  console.log(`${checks} browser checks passed.`);
}catch(e){console.error(e);process.exitCode=1}finally{await browser?.close();server.kill();await new Promise(resolve=>server.once('exit',resolve));rmSync(temp,{recursive:true,force:true})}
