// Standalone storyboard import: ownership, exact prompt preservation, one image variable.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,cpSync,readdirSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),file=process.argv[2]||path.join(root,'examples/storyboards/晴天借阅室_分镜导入.json'),temp=mkdtempSync(path.join(tmpdir(),'mio-story-import-'));
for(const n of [...readdirSync(root).filter(n=>n.endsWith('.py')),'data','backend','index.html','styles.css','favicon.svg','vendor','js','docs'])cpSync(path.join(root,n),path.join(temp,n),{recursive:true,filter:src=>!['runtime','.cache','.write.lock','secrets.json'].includes(path.basename(src))});
let server,browser,count=0;const check=(label,ok)=>{assert.ok(ok,label);console.log('PASS '+label);count++};
try{
 const data=JSON.parse(readFileSync(file));check('twelve nonempty frames, only one Chinese image variable, Chinese positive and negative prompts',data.frames.length===12&&data.frames.every(f=>f.prompt.includes('{主角参考图}')&&[...f.prompt.matchAll(/\{([^{}]+)\}/g)].map(m=>m[1]).join()==='主角参考图'&&!/[A-Za-z]/.test(f.prompt+f.negative)&&!f.renderOverride));
 server=spawn('python',['-u','server.py'],{cwd:temp,env:{...process.env,MIO_PORT:'8808'},stdio:['ignore','pipe','pipe']});const base='http://127.0.0.1:8808';let ready=false;for(let i=0;i<200;i++){try{if((await fetch(base+'/api/config')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,50))}assert.ok(ready);
 browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1000}});const paid=[],errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&(/\/api\/image\/generate|\/api\/foundation\/jobs$|\/v1\/images\//.test(r.url())))paid.push(r.url())});await page.route(/^https:\/\//,r=>r.abort());await page.goto(base);await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));await page.evaluate(()=>Mio.fileLibrary.hydrateAll());
 await page.evaluate(()=>{createUI.tab='story';navigate(1)});assert.ok(await page.evaluate(()=>savePythonWorkspace(true)));
 const before=await page.evaluate(()=>({templates:JSON.stringify(state.templates),books:JSON.stringify(state.books),plans:state.creation.plans.map(p=>({id:p.id,templateId:p.templateId})),queue:JSON.stringify(state.queue)}));
 const planId=await page.evaluate(()=>{const p=createBookPlan();p.title='晴天借阅室 · 独立导入检查';createUI.tab='story';render();return p.id});
 const chooser=page.waitForEvent('filechooser');await page.locator('[data-act="native-import"][data-kind="storyboards"]').first().click();await chooser;await page.locator('#file-input').setInputFiles({name:'晴天借阅室_分镜导入.json',mimeType:'application/json',buffer:readFileSync(file)});await page.locator('#resource-import-confirm').click();await page.waitForFunction(()=>state.templates.some(t=>t.title==='晴天借阅室｜十二幕中文分镜'));
await page.waitForFunction(id=>selectedPlan()?.id===id,planId);await page.evaluate(()=>Mio.fileLibrary.hydrateAll());
const templateId=await page.evaluate(()=>state.templates.find(t=>t.title==='晴天借阅室｜十二幕中文分镜').id);
 check('normal UI file import creates a new template ID and twelve distinct frame IDs',await page.evaluate(({id,source})=>{const t=templateBy(id);return t.id!==source&&t.frames.length===12&&new Set(t.frames.map(f=>f.id)).size===12},{id:templateId,source:data.id}));
 check('all twelve imported names, prompts, captions and negatives exactly match the file',await page.evaluate(({id,frames})=>templateBy(id).frames.every((f,i)=>['name','prompt','caption','negative'].every(k=>f[k]===frames[i][k])),{id:templateId,frames:data.frames}));
 check('existing templates and generated albums remain byte-for-byte unchanged in state',await page.evaluate(({before,id})=>JSON.parse(before.templates).every(old=>JSON.stringify(templateBy(old.id))===JSON.stringify(old))&&JSON.stringify(state.books)===before.books,{before,id:templateId}));
 check('only the new blank plan selects the imported template; old plan choices and queue remain unchanged',await page.evaluate(({before,planId,templateId})=>state.creation.plans.find(p=>p.id===planId).templateId===templateId&&before.plans.every(p=>state.creation.plans.find(x=>x.id===p.id).templateId===p.templateId)&&JSON.stringify(state.queue)===before.queue,{before,planId,templateId}));
 await page.locator('[data-act="art-create-tab"][data-tab="settings"]').click();await page.locator('[data-act="art-setting-add"]').click();await page.locator('#art-new-setting-key').fill('主角参考图');await page.locator('#art-new-setting-label').fill('主角参考图');await page.locator('#art-new-setting-type').selectOption('image');await page.locator('[data-act="art-setting-confirm"]').click();await page.locator('[data-image-key="主角参考图"] input').setInputFiles(path.join(root,'examples/afterglow/cover.webp'));await page.waitForFunction(()=>selectedPlan().variables.find(e=>e.key==='主角参考图')?.value?.src?.startsWith('/images/'));
 const ref=await page.evaluate(()=>selectedPlan().variables.find(e=>e.key==='主角参考图').value.src);check('the single reference is uploaded as a real local image asset',Buffer.from(await(await fetch(base+ref)).arrayBuffer()).equals(readFileSync(path.join(root,'examples/afterglow/cover.webp'))));
 check('every frame resolves exactly one ordered image input without relying on previous-frame memory',await page.evaluate(()=>{const p=selectedPlan(),t=templateBy(p.templateId);return t.frames.every(raw=>{const f=effectivePlanFrame(p,raw);return f._imageInputs.length===1&&f._imageInputs[0].key==='主角参考图'&&f._resolvedImagePrompt.includes('@image_1')&&!f._resolvedImagePrompt.includes('{主角参考图}')})}));
 await page.locator('[data-act="art-create-tab"][data-tab="story"]').click();check('actual storyboard preview displays the numbered uploaded reference',await page.locator('.image-binding-preview code').allTextContents().then(a=>a.includes('@image_1')));
 await page.evaluate(()=>savePythonWorkspace(true));await page.reload();await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);check('imported template and reference remain after saving and reloading',await page.evaluate(({planId,templateId,ref})=>{const p=state.creation.plans.find(x=>x.id===planId);return templateBy(templateId).frames.length===12&&p.variables.find(e=>e.key==='主角参考图').value.src.startsWith('/images/library/plans/')},{planId,templateId,ref}));
 await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));
 // A second import must save a not-yet-blurred edit to its old owner, never the new first frame.
 await page.evaluate(planId=>{createUI.planId=planId;createUI.tab='story';navigate(1);document.querySelector('[data-v3-frame="prompt"]').value='这是上一份模板尚未失焦的中文草稿。'},planId);
 const secondChooser=page.waitForEvent('filechooser');await page.locator('[data-act="native-import"][data-kind="storyboards"]').first().click();await secondChooser;await page.locator('#file-input').setInputFiles({name:'同名分镜.json',mimeType:'application/json',buffer:readFileSync(file)});await page.locator('#resource-import-confirm').click();await page.waitForFunction(()=>state.templates.filter(t=>t.title==='晴天借阅室｜十二幕中文分镜').length===2);
 check('reimport creates another independent copy, while flushing the old unblurred draft to its correct owner',await page.evaluate(({oldId,expected})=>{const next=currentTemplate();return next.id!==oldId&&next.frames[0].prompt===expected&&templateBy(oldId).frames[0].prompt==='这是上一份模板尚未失焦的中文草稿。'}, {oldId:templateId,expected:data.frames[0].prompt}));
 const stable=await page.evaluate(()=>({templates:JSON.stringify(state.templates),plan:selectedPlan().templateId}));const invalidChooser=page.waitForEvent('filechooser');await page.locator('[data-act="native-import"][data-kind="storyboards"]').first().click();await invalidChooser;await page.locator('#file-input').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"title":12,"frames":[]}')});await page.waitForFunction(()=>document.querySelector('#toasts').textContent.includes('Resource requires a title'));
 check('invalid input leaves all existing templates and selection intact',await page.evaluate(stable=>JSON.stringify(state.templates)===stable.templates&&selectedPlan().templateId===stable.plan,stable));
 check('no generation job or paid image request was submitted',paid.length===0);check('no uncaught browser errors',errors.length===0);console.log(`${count} checks passed. Linux Chromium; isolated temporary workspace only. No model generation tested.`);
}finally{await browser?.close();if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
