// Regenerate src/api/schema.d.ts from the FastAPI OpenAPI document (no server needs to run).
// Usage: npm run gen:api   (set PYTHON=... if `python` is not on PATH)
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const server = resolve(here, '../../server');
const dump = [
  'import json, tempfile',
  'from mio_server.api import create_app',
  'from mio_server.context import AppContext',
  'with tempfile.TemporaryDirectory() as d:',
  '    ctx = AppContext.create(d, memory=True, autostart=False, seed_instance=False)',
  '    print(json.dumps(create_app(ctx, serve_web=False).openapi(), ensure_ascii=False))',
  '    ctx.close()',
].join('\n');

function run(python) {
  return execFileSync(python, ['-c', dump], { cwd: server, encoding: 'utf8', maxBuffer: 64 << 20 });
}

const candidates = [process.env.PYTHON, 'python', 'python3'].filter(Boolean);
let text = '';
for (const python of candidates) {
  try {
    text = run(python);
    break;
  } catch (error) {
    if (python === candidates.at(-1)) throw error;
  }
}
/**
 * Pydantic versions differ on `dict[str, Any]`: older ones emit a bare `{"type": "object"}`,
 * newer ones add `"additionalProperties": true`. Both mean "any keys"; strip the flag so every
 * environment feeds openapi-typescript the same document and the output is byte-identical.
 */
function normalize(node) {
  if (Array.isArray(node)) return node.forEach(normalize);
  if (!node || typeof node !== 'object') return;
  if (node.type === 'object' && !node.properties && node.additionalProperties === true) {
    delete node.additionalProperties;
  }
  Object.values(node).forEach(normalize);
}

const spec = JSON.parse(text);
normalize(spec);
// Response schemas already list defaulted fields as required (server config); request bodies keep
// defaulted fields optional. Bare objects mean "any keys", not "no keys".
const ast = await openapiTS(spec, { defaultNonNullable: false, emptyObjectsUnknown: true });
const out = resolve(here, '../src/api/schema.d.ts');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, `// Generated by scripts/gen-api.mjs — do not edit.\n${astToString(ast)}`);
console.log(`wrote ${out}`);
