// Compact credential form, real local vault and actual loopback image transport.
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import{spawn}from'node:child_process';import{chromium}from'playwright';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mio-key-pool-')),base='http://127.0.0.1:18872',up='http://127.0.0.1:18972',evidence='build/inline-evidence';fs.mkdirSync(evidence,{recursive:true});const fd=fs.openSync(path.join(dir,'server.log'),'w'),server=spawn('python',['tests/journey_fixture_server.py'],{env:{...process.env,MIO_HOST:'127.0.0.1',MIO_PORT:'18872',MIO_DATA_DIR:path.join(dir,'data'),MIO_JOURNEY_PROVIDER_PORT:'18972',OPENAI_API_KEY:'must-not-use-environment'},stdio:['ignore',fd,fd]});let browser,count=0;const check=(v,name)=>{assert.ok(v,name);console.log('PASS '+name);count++};
try{
 for(let i=0;i<150;i++){try{if((await fetch(base+'/api/content')).ok)break}catch{}await new Promise(r=>setTimeout(r,100))}
 browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1568,height:1004},reducedMotion:'reduce'}),errors=[],configs=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().endsWith('/api/config')&&r.method()==='POST')configs.push(r.postData())});await p.route(/^https?:\/\//,r=>new URL(r.request().url()).origin===base?r.continue():r.abort());await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);
 const nav=async n=>p.locator(`#sidebar [data-act="art-nav"][data-route="${n}"]`).click(),keys=()=>p.locator('[data-image-key]');
 const settled=()=>p.waitForFunction(()=>imageProviderUI.keyWrites.size===0&&!imageKeyDraftChanged()&&rt.saved);
 const save=async()=>{await p.locator('[data-act="image-key-save-inline"]').click();await settled()};
 const add=async key=>{await p.locator('[data-act="image-key-add-row"]').click();await keys().last().fill(key);await save()};
 const wire=()=>fs.existsSync(path.join(dir,'data/journey-wire.json'))?JSON.parse(fs.readFileSync(path.join(dir,'data/journey-wire.json'))):[];
 await nav(3);check(await p.locator('.provider-setup-heading').count()===0,'ComfyUI has no lecture panel');check(await p.locator('#setup-comfy-url').isVisible(),'ComfyUI address and actions remain');await p.screenshot({path:path.join(evidence,'comfy.png'),fullPage:true});
 await p.locator('#image-provider-select').selectOption('openai');await p.locator('[data-image-config="baseUrl"]').fill(up+'/pool/v1');await p.locator('[data-image-config="baseUrl"]').press('Tab');await p.locator('#image-provider-model-input').fill('fixture-image');
 check(await p.locator('#image-provider-auth').count()===0,'authentication selector is removed');check(!(await p.locator('.image-provider-panel').innerText()).includes('环境变量'),'no environment-variable option or explanation');check(await keys().first().getAttribute('type')==='password','API key is masked');

 check(await p.evaluate(()=>{const m=document.querySelector('#image-provider-model-input').getBoundingClientRect(),b=document.querySelector('[data-act="image-provider-models"]').getBoundingClientRect(),k=document.querySelector('[data-image-key]').getBoundingClientRect();return Math.abs(m.y-b.y)<2&&Math.abs(m.y-k.y)<2}),'model input, fetch button and API key align');
 await keys().first().fill('fixture-A');await save();check(await p.evaluate(()=>activeImageProfile().keyIds.length)===1,'first key saves through the inline form');check(await keys().first().inputValue()==='••••••••','saved key displays a mask rather than a misleading empty field');await add('fixture-B');check(await p.evaluate(()=>activeImageProfile().keyIds.length)===2,'second key joins the ordered pool');await p.waitForFunction(()=>!document.querySelector('#toasts .toast'));await p.screenshot({path:path.join(evidence,'openai-multiple.png')});
 check(!await p.evaluate(()=>JSON.stringify(state).includes('fixture-A')||JSON.stringify({...localStorage}).includes('fixture-A')),'secrets never enter state or localStorage');check(configs.every(x=>!x.includes('fixture-A')&&!x.includes('fixture-B')),'normal configuration writes contain only credential references');await p.reload();await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await nav(3);check(await keys().count()===2&&(await keys().allTextContents()).every(x=>!x.includes('fixture-')),'pool persists after reload');
 const generate=()=>p.evaluate(async()=>{const r=await request('/api/image/generate',post({config:imageConfigSnapshot(),prompt:'fixture scene',frame:{width:512,height:512},albumId:'pool-test'}));return r.status});
 for(let i=0;i<4;i++)assert.equal(await generate(),200);
 check(wire().filter(x=>x.method==='POST').map(x=>x.keyTag).join(',')==='A,B,A,B','actual image requests rotate A, B, A, B');
 await p.locator('[data-act="image-provider-models"]').click();await p.getByRole('option',{name:'fixture-image',exact:true}).waitFor();check(wire().filter(x=>x.path.endsWith('/models')).at(-1).keyTag==='A','model discovery uses the same current pool');await p.getByRole('option',{name:'fixture-image',exact:true}).click();
 await keys().first().fill('fixture-fail');await save();const before=wire().filter(x=>x.method==='POST').length;const failure=await p.evaluate(async()=>{try{await request('/api/image/generate',post({config:imageConfigSnapshot(),prompt:'fixture',frame:{},albumId:'pool-test'}));return ''}catch(e){return e.message}});check(failure.includes('401'),'upstream authentication error is surfaced');check(wire().filter(x=>x.method==='POST').length===before+1,'failed request never silently retries with another key');assert.equal(await generate(),200);check(wire().filter(x=>x.method==='POST').at(-1).keyTag==='B','next explicit call advances to the next key');
 while(await keys().count()>1){await p.locator('[data-act="image-key-remove-row"]').last().click();await settled()}
 await keys().first().fill('');await save();check(await p.evaluate(()=>activeImageProfile().keyMode==='none'&&activeImageProfile().keyIds.length===0),'clearing the input clears authentication');await generate();check(wire().filter(x=>x.method==='POST').at(-1).hasAuth===false,'empty input sends no auth even when server environment has a key');
 await p.route('**/api/image/credentials',r=>r.request().postDataJSON()?.action==='apply'?r.fulfill({status:503,json:{error:'Fixture vault unavailable'}}):r.continue());await keys().first().fill('fixture-A');await p.locator('[data-act="first-run-continue"]').click();await p.getByText('HTTP 503: Fixture vault unavailable',{exact:true}).first().waitFor();check(await keys().first().inputValue()==='fixture-A','failed save keeps the draft');check(await p.locator('#image-provider-select').isVisible(),'failed save does not advance to storyboarding');await p.unroute('**/api/image/credentials');await save();
 let release;const gate=new Promise(r=>release=r);await p.route('**/api/image/credentials',async r=>{if(r.request().postDataJSON()?.action==='apply')await gate;await r.continue()});await keys().first().fill('fixture-B');await keys().first().press('Tab');await p.waitForFunction(()=>imageProviderUI.keyWrites.size===1);await p.locator('[data-image-config="baseUrl"]').fill(up+'/other/v1');await p.locator('[data-image-config="baseUrl"]').press('Tab');release();await p.getByText('地址已改变，请重新填写密钥。',{exact:true}).first().waitFor();check(await p.evaluate(()=>activeImageProfile().keyMode==='none'&&!activeImageProfile().keyIds?.length),'late save never binds the old URL pool to a new URL');await p.unroute('**/api/image/credentials');
 await p.locator('[data-image-config="baseUrl"]').fill(up+'/pool/v1');await p.locator('[data-image-config="baseUrl"]').press('Tab');await keys().first().fill('fixture-A');await p.locator('#image-provider-model-input').click();await settled();check(await p.evaluate(()=>activeImageProfile().keyIds.length)===1,'blur auto-saves a changed key');await p.locator('[data-act="first-run-continue"]').click();await p.locator('.assembly-workshop').waitFor();check(await p.locator('.assembly-workshop').isVisible(),'continue opens storyboards with saved input');await nav(3);await p.waitForFunction(()=>!document.querySelector('#toasts .toast'));await p.screenshot({path:path.join(evidence,'openai.png'),fullPage:true});
 await p.locator('#image-provider-select').selectOption('novelai');check(await p.locator('.provider-setup,.setup-warning').count()===0,'NovelAI has no introductory disclaimer panel');await p.screenshot({path:path.join(evidence,'novelai.png'),fullPage:true});
 for(const width of [390,320]){await p.setViewportSize({width,height:844});check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'provider form fits mobile '+width);await p.locator('#image-provider-select').selectOption('openai');check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'OpenAI form fits mobile '+width);check(await p.locator('[data-act="image-provider-models"]').evaluate(e=>e.getBoundingClientRect().height>=44),'fetch-model target is at least 44px');if(width===390){await p.waitForFunction(()=>rt.saved);await p.screenshot({path:path.join(evidence,'mobile.png')})}}
 check(errors.length===0,'no browser exceptions: '+errors.join(';'));console.log('INLINE CREDENTIALS: '+count+' checks PASS');
}finally{await browser?.close();if(server.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}fs.closeSync(fd);fs.rmSync(dir,{recursive:true,force:true})}
