// Verify the actual ZIP, then run its extracted server against its own shipped data.
import {chromium} from 'playwright';
import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,readFileSync,writeFileSync,mkdirSync,readdirSync,rmSync} from 'node:fs';
import path from 'node:path';import {tmpdir} from 'node:os';import assert from 'node:assert/strict';
const source=process.cwd(),version=JSON.parse(readFileSync(path.join(source,'package.json'))).version,archive=path.resolve(process.argv[2]||'releases/mio-'+version+'-source.zip'),temp=mkdtempSync(path.join(tmpdir(),'mio-delivered-')),base='http://127.0.0.1:8865',evidence=path.join(source,'docs/acceptance-assembly/packaged');mkdirSync(evidence,{recursive:true});
let server,browser,count=0;const errors=[],check=(name,value)=>{assert.ok(value,name);console.log('PASS '+name);count++};
try{
 const extraction=spawnSync('python',['-c',`import zipfile,json,hashlib,sys
from pathlib import Path
with zipfile.ZipFile(sys.argv[1]) as z:
 assert z.testzip() is None
 root=z.namelist()[0].split('/')[0]
 m=json.loads(z.read(root+'/PACKAGE_MANIFEST.json'))
 assert m['version']==sys.argv[3] and m['includesShippedData'] and not m['includesUserData']
 for n,h in m['files'].items():assert hashlib.sha256(z.read(root+'/'+n)).hexdigest()==h,n
 assert not any(any(x in n.split('/') for x in ('secrets.json','runtime','.cache','node_modules','.work')) for n in z.namelist())
 assert not any(n.startswith(root+'/presets/') for n in z.namelist())
 d=json.loads(z.read(root+'/data/distribution.json'))
 assert len(d['files'])==59
 for n,h in d['files'].items():assert hashlib.sha256(z.read(root+'/data/'+n)).hexdigest()==h,n
 z.extractall(sys.argv[2]);print(Path(sys.argv[2])/root)`,archive,temp,version],{encoding:'utf8'});assert.equal(extraction.status,0,extraction.stderr);const project=extraction.stdout.trim();check('actual ZIP CRC, every manifest hash and all 59 content files match; no private/runtime paths',true);
 const env={...process.env,MIO_PORT:'8865',MIO_HOST:'127.0.0.1'};delete env.MIO_DATA_DIR;server=spawn('python',['-u','server.py'],{cwd:project,env,stdio:['ignore','pipe','pipe']});server.stdout.on('data',()=>{});let logs='';server.stderr.on('data',x=>logs+=x);
 let ready=false;for(let i=0;i<250;i++){try{if((await fetch(base+'/api/content')).ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,40))}check('unpacked package starts with Python and its own included data, no source-tree fallback',ready);
 browser=await chromium.launch({args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:1440,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.route(/^https:\/\//,r=>r.abort());
 async function load(){await p.goto(base);await p.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);assert.ok(await p.locator('#mio-home').isVisible(),'unpacked package defaults to the independent home');await p.locator('#sidebar [data-route="0"]').click();await p.evaluate(()=>{guidePreferences().seen=true;state.settings.identity.onboarded=true;createUI.welcomePending=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close())})}
 async function shot(name){await p.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:path.join(evidence,name)})}
 await load();check('shipped native album, 12-frame storyboard, preset and seven layouts are visible',await p.evaluate(()=>state.books.length===1&&state.templates[0].frames.length===12&&state.creation.variableSets.length===1&&state.exportTemplates.length===7));await p.locator('#collection-home img').first().evaluate(i=>i.decode());check('real cover is served from this unpacked album’s owned assets',await p.locator('#collection-home img').first().getAttribute('src').then(s=>s.startsWith('/images/library/')));
 for(const [width,theme]of[[1440,'light'],[390,'dark']]){await p.setViewportSize({width,height:900});await p.evaluate(theme=>{state.settings.studio.appearance.theme=theme;render()},theme);check(`packaged gallery ${width} ${theme} has no horizontal overflow`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot(`packaged-gallery-${width}-${theme}.png`)}
 await p.locator('[data-act="book-menu"]').first().click();await p.locator('#book-context-menu [data-act="native-export"]').click();await p.locator('#native-share-download').waitFor();check('actual touch-sized gallery menu opens source sharing with independent default-off choices',!await p.locator('#export-embed-storyboard').isChecked()&&!await p.locator('#export-embed-variables').isChecked());await p.locator('summary').filter({hasText:'分享源素材'}).click();await p.locator('#export-embed-storyboard').check();await p.locator('#export-embed-variables').check();await shot('packaged-source-share-mobile.png');
 const downloaded=p.waitForEvent('download');await p.locator('#native-share-download').click();const file=path.join(temp,'shared.mio.zip');await(await downloaded).saveAs(file);check('actual packaged UI downloads a valid ZIP',readFileSync(file).subarray(0,2).toString()==='PK');
 const old=await p.evaluate(()=>({books:state.books.length,templates:state.templates.length,presets:state.creation.variableSets.length}));const chooser=p.waitForEvent('filechooser');await p.locator('#collection-home [data-act="native-import"]').click();await(await chooser).setFiles(file);await p.locator('#resource-import-confirm').waitFor();check('recipient sees one default-off confirmation and no pre-confirmation import',await p.evaluate(n=>state.books.length===n,old.books)&&!await p.locator('#import-include-storyboards').isChecked()&&!await p.locator('#import-include-variables').isChecked());await p.locator('#import-include-storyboards').check();await p.locator('#import-include-variables').check();await shot('packaged-import-mobile.png');await p.locator('#resource-import-confirm').click();await p.waitForFunction(n=>state.books.length===n+1,old.books);check('confirmed import creates fresh album, storyboard and preset without replacing originals',await p.evaluate(n=>state.templates.length===n.templates+1&&state.creation.variableSets.length===n.presets+1&&new Set(state.books.map(b=>b.id)).size===state.books.length,old));
 const imported=await p.evaluate(()=>state.books.find(b=>b.id!=='edition_letter').id);await p.evaluate(id=>openArtReader(id),imported);await p.locator('#reader-canvas img').first().evaluate(i=>i.decode());check('imported image immediately reads from the new album’s own folder',await p.evaluate(id=>bookBy(id).steps[0].image.includes('/albums/'+id+'/images/'),imported));await p.evaluate(()=>closeReader());
 const layouts=path.join(project,'data/layouts'),layoutFile=readdirSync(layouts).find(n=>JSON.parse(readFileSync(path.join(layouts,n))).id==='export-ink'),raw=JSON.parse(readFileSync(path.join(layouts,layoutFile)));raw.title='直接编辑交付包中的文件';writeFileSync(path.join(layouts,layoutFile),JSON.stringify(raw));await load();check('editing a shipped JSON affects the unpacked application on reload',await p.evaluate(()=>exportTemplateBy('export-ink').title==='直接编辑交付包中的文件'));
 for(const name of readdirSync(layouts))if(name.endsWith('.json'))rmSync(path.join(layouts,name));await load();check('deleting all layouts does not resurrect them or prevent gallery startup',await p.evaluate(()=>state.exportTemplates.length===0));await p.locator('[data-act="read"]').first().click();await p.locator('#reader').waitFor();await p.locator('.presentation-trigger').click();check('empty layout library offers an explicit import rather than a broken dialog',await p.locator('#presentation-drawer [data-act="et-import"]').isVisible());
 await p.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close())});
 const prepared=await p.evaluate(async()=>{const {id}=await ecoRequest('preparations',{owner:'packaged-node-check',seed:42,trusted:true,entries:[{key:'value',type:'text',compute:{script:'return "package-ready";'}}]});for(let i=0;i<100;i++){const j=await ecoRequest('preparations/'+id);if(!['pending','running'].includes(j.status))return j;await new Promise(r=>setTimeout(r,50))}throw Error('Packaged Node timeout')});check('unpacked package runs its own Node worker and vendored AST parser',prepared.status==='complete'&&prepared.values.value==='package-ready');
 function exampleZip(relative){const r=spawnSync('python',['-c',`import io,zipfile,pathlib,base64,sys\nb=io.BytesIO()\nwith zipfile.ZipFile(b,'w') as z:\n for p in pathlib.Path(sys.argv[1]).rglob('*'):\n  if p.is_file():z.write(p,p.relative_to(sys.argv[1]))\nprint(base64.b64encode(b.getvalue()).decode())`,path.join(project,relative)],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);return r.stdout.trim()}
 const paper=await p.evaluate(async data=>{const t=await ecoRequest('themes/install',{data,filename:'paper.zip',trusted:true});return ecoRequest('themes/css/'+t.id)},exampleZip('examples/themes/paper-atelier'));check('unpacked theme example inlines its actual texture',paper.css.includes('data:image/png;base64,'));
 await p.evaluate(async zip=>{await ecoRequest('extensions/install',{zip,trusted:true});await refreshEcosystem();await ecoContext('scene-notebook').api('/notes',{title:'package-test',text:'persisted'})},exampleZip('examples/extensions/scene-notebook'));
 check('unpacked extension executes backend and separates code from persisted notes',JSON.parse(readFileSync(path.join(project,'data/extensions/scene-notebook/notes.json')))[0].text==='persisted'&&readFileSync(path.join(project,'extensions/scene-notebook/index.js'),'utf8').includes('export default'));
 check('no browser exceptions, provider calls or server tracebacks',errors.length===0&&!logs.includes('Traceback'));console.log(`${count} actual-package checks PASS`);
}finally{await browser?.close();if(server?.exitCode===null){const done=new Promise(r=>server.once('exit',r));server.kill();await done}rmSync(temp,{recursive:true,force:true})}
