// Regression for opening the template drawer rebuilding an already loaded iframe.
import {chromium} from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtempSync,cpSync,readdirSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),temp=mkdtempSync(path.join(tmpdir(),'mio-preview-')),evidence=process.env.MIO_PREVIEW_EVIDENCE||path.join(root,'docs/acceptance-2.2/reader'),base='http://127.0.0.1:8805';mkdirSync(evidence,{recursive:true});
for(const n of [...readdirSync(root).filter(n=>n.endsWith('.py')),'data','backend','index.html','styles.css','favicon.svg','vendor','js','docs'])cpSync(path.join(root,n),path.join(temp,n),{recursive:true,filter:src=>!['runtime','.cache','.write.lock','secrets.json'].includes(path.basename(src))});
let server,browser,checks=0;const errors=[],check=(name,ok)=>{assert.ok(ok,name);checks++;console.log('PASS '+name)};
async function until(fn){for(let i=0;i<200;i++){if(await fn())return;await new Promise(r=>setTimeout(r,50))}throw Error('condition timeout')}
try{
server=spawn('python',['-u','server.py'],{cwd:temp,env:{...process.env,MIO_PORT:'8805'},stdio:['ignore','pipe','pipe']});await until(async()=>{try{return (await fetch(base+'/api/config')).ok}catch{return false}});
browser=await chromium.launch({args:['--no-sandbox'],ignoreDefaultArgs:['--disable-popup-blocking']});const page=await browser.newPage({viewport:{width:1440,height:960}});page.on('pageerror',e=>errors.push(e.message));await page.route(/^https:\/\//,r=>r.abort());await page.goto(base);await page.waitForFunction(()=>typeof rt!=='undefined'&&!rt.booting);await page.evaluate(()=>document.querySelectorAll('dialog[open]').forEach(d=>d.close()));await page.evaluate(()=>Mio.fileLibrary.hydrateAll());
await page.evaluate(async()=>{const b=state.books[0];b.totalSteps=8;b.steps=[];b.curatedDemo=false;delete b.presentationTemplateId;delete b.nativeReaderMode;delete b.pictureEdits;state.settings.presentation.readerModeExplicit=false;for(let i=0;i<8;i++){const c=document.createElement('canvas');c.width=i%2?400:720;c.height=i%2?520:320;const x=c.getContext('2d');x.fillStyle=['#557f82','#ab9271','#728d70','#797b9d'][i%4];x.fillRect(0,0,c.width,c.height);x.fillStyle='#f7efda';x.font='28px sans-serif';x.fillText('SCENE '+(i+1),30,65);const image=(await foundationRequest('assets/upload',{dataUrl:c.toDataURL(),name:i+'.png'})).url;b.steps.push({stepIndex:i,name:'第 '+(i+1)+' 幕',prompt:'test',caption:'把故事留在画面里。',image,width:c.width,height:c.height})}b.generatedSteps=8;b.status='complete';await openArtReader(b.id)});
check('default mounts the entire album in a native continuous reader',await page.evaluate(()=>artUI.readerMode==='webtoon'&&$('#reader-canvas [data-scroll-step="7"]')&&!$('#presentation-preview')));
check('lazy images retain full aspect ratios without eager template compilation',await page.locator('#reader-canvas img').evaluateAll(a=>a.length===8&&a.every(i=>i.loading==='lazy'&&getComputedStyle(i).objectFit==='contain')));
await page.evaluate(()=>{const c=$('#reader-canvas');c.scrollTop=700;window.nativeImages=[...c.querySelectorAll('img')];window.nativeScroll=c.scrollTop;window.previewBuilds=0;window.previewReads=0;const compile=compileTemplateDocument,read=presentationImage;compileTemplateDocument=function(...args){window.previewBuilds++;return compile(...args)};presentationImage=async function(...args){window.previewReads++;return read(...args)}});
await page.locator('.presentation-trigger').click();await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();
check('native panel open/close preserves image nodes, no compile or preparation',await page.evaluate(()=>window.nativeImages.every((img,i)=>img===$$('#reader-canvas img')[i])&&window.previewBuilds===0&&window.previewReads===0));
await page.locator('#reader-canvas img').evaluateAll(images=>Promise.all(images.map(i=>{i.loading='eager';return i.decode()})));await page.evaluate(()=>$('#reader-canvas').scrollTo({top:$('#reader-canvas').scrollHeight,behavior:'instant'}));await page.waitForFunction(()=>ui.step===7);await page.locator('[data-mio-colophon]').waitFor();await page.screenshot({path:path.join(evidence,'default-scroll-ending.png')});
check('native ending has one quiet poem and the real project URL',await page.locator('#reader-canvas [data-mio-colophon]').count()===1&&await page.locator('[data-mio-colophon] a').getAttribute('href')==='https://github.com/lumingya/comfy-comic-studio');
// In-flight picture preparation must not be canceled by opening/closing the drawer.
await page.locator('.presentation-trigger').click();await page.route('**/images/**',async r=>{await new Promise(resolve=>setTimeout(resolve,160));await r.continue()});await page.locator('[data-act="presentation-select"][data-id="export-paper"]').click();await page.evaluate(()=>{window.heldFrame=$('#presentation-preview');window.heldController=presentationUI.loadController});await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();await page.locator('.presentation-trigger').click();
check('toggling during preparation neither replaces iframe nor aborts controller',await page.evaluate(()=>window.heldFrame===$('#presentation-preview')&&window.heldController===presentationUI.loadController&&!window.heldController.signal.aborted));await page.frameLocator('#presentation-preview').locator('[data-cc-frame]').last().waitFor();await page.unroute('**/images/**');
const frame=page.frameLocator('#presentation-preview');await frame.locator('body').evaluate(()=>{window.drawerSentinel='kept';window.scrollTo(0,850)});await page.evaluate(()=>{window.keptFrame=$('#presentation-preview');window.keptRevision=presentationUI.revision;window.startBuilds=window.previewBuilds;window.startReads=window.previewReads;window.iframeMutations=0;window.ifObserver=new MutationObserver(rs=>window.iframeMutations+=rs.length);window.ifObserver.observe(window.keptFrame,{attributes:true,attributeFilter:['srcdoc','src']})});
for(let i=0;i<3;i++){await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();await page.locator('.presentation-trigger').click();await page.locator('#presentation-search').fill(i?'':'海风');await page.locator('#presentation-search').fill('')}
await page.locator('[data-act="presentation-select"][data-id="export-paper"]').click();
check('drawer toggles/search/current selection never remount loaded iframe',await page.evaluate(()=>window.keptFrame===$('#presentation-preview')&&window.keptRevision===presentationUI.revision&&window.iframeMutations===0));
check('drawer interactions do not compile or reread any image',await page.evaluate(()=>window.startBuilds===window.previewBuilds&&window.startReads===window.previewReads));
check('iframe script state and reading position survive drawer interactions',await frame.locator('body').evaluate(()=>window.drawerSentinel==='kept'&&window.scrollY>0));
check('drawer trigger reports expanded state accessibly',await page.locator('.presentation-trigger').getAttribute('aria-expanded')==='true');
await page.screenshot({path:path.join(evidence,'template-drawer-stable.png')});
// Every shipped template gets exactly one footer; custom copies are untouched.
for(const id of ['mio-fit','export-paper','export-ink','export-gallery','export-flip']){
 const result=await page.evaluate(id=>{const t=exportTemplateBy(id),b=bookBy(ui.bookId),doc=new DOMParser().parseFromString(compileTemplateDocument(t,[b],{showCaptions:true,showPrompts:false}),'text/html');return{count:doc.querySelectorAll('[data-mio-colophon]').length,url:doc.querySelector('[data-mio-colophon] a')?.href,poem:doc.querySelector('[data-mio-colophon]')?.textContent,html:'<!DOCTYPE html>'+doc.documentElement.outerHTML}},id);
 check(id+' compiled preview/export has one small colophon',result.count===1&&result.url==='https://github.com/lumingya/comfy-comic-studio'&&result.poem.includes('一念成画'));
 const dest=path.join(evidence,id+'-offline.html');writeFileSync(dest,result.html);const offline=await browser.newPage();await offline.route(/^https?:/,r=>r.abort());await offline.goto('file://'+dest);if(id==='export-flip'){check('flip poem is hidden until final spread',!await offline.locator('[data-mio-colophon]').isVisible());while(!await offline.locator('.cc-controls button:last-child').isDisabled())await offline.locator('.cc-controls button:last-child').click()}
 check(id+' reopened offline keeps poem and project address',await offline.locator('[data-mio-colophon]').isVisible()&&await offline.locator('[data-mio-colophon] a').getAttribute('href')===result.url);await offline.close();
}
check('user-created template copies are not branded or rewritten',await page.evaluate(()=>{const t=exportTemplateCopy(exportTemplateBy('export-paper'));return !compileTemplateDocument(t,[bookBy(ui.bookId)]).includes('data-mio-colophon')}));
// Real UI export + reopen, not just compilation.
await page.locator('[data-act="presentation-select"][data-id="export-paper"]').click();const event=page.waitForEvent('download');await page.locator('[data-act="presentation-export"]').click();const dl=await event,file=path.join(evidence,'downloaded-album.html');await dl.saveAs(file);const exported=await browser.newPage();await exported.route(/^https?:/,r=>r.abort());await exported.goto('file://'+file);check('actual downloaded album contains all eight scenes and footer',await exported.locator('[data-cc-frame]').count()===8&&await exported.locator('[data-mio-colophon]').count()===1);await exported.close();
// Sandbox remains unchanged; project link opens only the hardcoded address on user click.
await frame.locator('[data-mio-colophon] a').scrollIntoViewIfNeeded();const popupEvent=page.waitForEvent('popup');await frame.locator('[data-mio-colophon] a').click();const popup=await popupEvent;await popup.close();check('preview project link opens without loosening iframe sandbox',await page.locator('#presentation-preview').getAttribute('sandbox')==='allow-scripts');
// Mobile drawer and native footer.
await page.locator('[data-act="presentation-select"][data-id="mio-fit"]').click();await page.setViewportSize({width:390,height:844});await page.locator('#presentation-drawer [data-act="presentation-panel"]').click();await page.locator('#reader-canvas img').evaluateAll(images=>Promise.all(images.map(i=>{i.loading='eager';return i.decode()})));await page.evaluate(()=>$('#reader-canvas').scrollTo({top:$('#reader-canvas').scrollHeight,behavior:'instant'}));await page.waitForTimeout(350);await page.screenshot({path:path.join(evidence,'mobile-scroll-ending.png')});check('mobile default scroll footer fits without horizontal overflow',await page.locator('#reader-canvas').evaluate(c=>c.scrollWidth<=c.clientWidth+1));
check('no uncaught browser errors',errors.length===0);console.log(`${checks} reader preview checks passed`);
}finally{await browser?.close();if(server?.exitCode===null){const exit=new Promise(r=>server.once('exit',r));server.kill();await exit}rmSync(temp,{recursive:true,force:true})}
