import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const artifacts=process.env.MIO_ARTIFACT_DIR||fs.mkdtempSync(path.join(os.tmpdir(),'mio-selection-'));
fs.mkdirSync(artifacts,{recursive:true});
const browser=await chromium.launch({args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
let checks=0;const check=(value,label)=>{assert.ok(value,label);console.log('PASS',label);checks++};
try{
await page.goto(process.env.MIO_TEST_URL||'http://127.0.0.1:8777');
await page.waitForFunction(()=>typeof state!=='undefined'&&state.templates.length);
await page.evaluate(()=>{navigate(1);workshop.view='stories';render()});
const rows=()=>page.locator('.workshop-frames-list button[data-index]');
await rows().nth(2).click();check(await page.evaluate(()=>workshop.frame===2&&workshop.pickedFrames.size===0),'one click switches frame without selection');
await rows().nth(4).click({modifiers:['Shift']});check(await page.evaluate(()=>workshop.pickedFrames.size===3),'Shift extends from last opened frame');
check(await page.locator('.workshop-frames input[type=checkbox],.workshop-frames-selbar,[data-act="workshop-frame-sel-toggle"]:not(.ctx-menu *)').count()===0,'no frame checkbox, toolbar, or mode entry');
await rows().nth(3).click({button:'right'});
check((await page.locator('.ctx-menu').innerText()).includes('删除选中的 3 幕'),'selected frame opens bulk menu');
check(!(await page.locator('.ctx-menu').innerText()).includes('复制这一幕'),'bulk menu does not mix single-item actions');
check(await page.locator('.ctx-menu [data-act=workshop-frame-sel-toggle]').isVisible(),'exit selection is visible inside context menu');
await page.keyboard.press('Escape');
await rows().nth(1).click();check(await page.evaluate(()=>workshop.frame===1&&!workshop.pickedFrames.size),'single click still switches during selection');
await rows().nth(1).click({button:'right'});check((await page.locator('.ctx-menu').innerText()).includes('复制这一幕'),'unselected frame has individual menu');
await page.keyboard.press('Escape');
async function drag(a,b,modifier){if(modifier)await page.keyboard.down(modifier);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:15});await page.mouse.up();if(modifier)await page.keyboard.up(modifier)}
const a=await rows().nth(0).boundingBox(),b=await rows().nth(2).boundingBox();
await drag({x:a.x+8,y:a.y+8},{x:b.x+b.width-8,y:b.y+b.height-8});
check(await page.evaluate(()=>workshop.pickedFrames.size===3),'drag from row selects a rectangle');
check(await page.evaluate(()=>workshop.frame===1),'drag release does not open a frame');
await page.screenshot({path:path.join(artifacts,'frames-selection.png')});
await rows().nth(0).click({modifiers:['Control']});
check(await page.evaluate(()=>workshop.pickedFrames.size===2&&!workshop.pickedFrames.has(0)),'Ctrl click deselects one frame');
const c=await rows().nth(0).boundingBox();
await drag({x:c.x+8,y:c.y+8},{x:c.x+c.width-8,y:c.y+c.height-8},'Control');
check(await page.evaluate(()=>workshop.pickedFrames.size===3),'Ctrl marquee adds to existing selection');
await page.mouse.move(c.x+8,c.y+8);await page.mouse.down();await page.mouse.move(c.x+c.width-8,c.y+c.height+30,{steps:8});
await page.evaluate(()=>window.dispatchEvent(new PointerEvent('pointercancel')));await page.mouse.up();
check(await page.evaluate(()=>workshop.pickedFrames.size===3),'cancelled drag restores original selection');
await page.keyboard.press('Control+a');check(await page.evaluate(()=>workshop.pickedFrames.size===workshopStory().frames.length),'Ctrl+A selects frame list');
await page.keyboard.press('Escape');check(await page.evaluate(()=>!workshop.pickedFrames.size),'Escape clears selection');
await page.evaluate(()=>{navigate(0);const base=projectBooks()[0];if(base)for(let i=0;i<3;i++)state.books.push({...clone(base),id:'selection-test-'+i,title:'测试画册 '+i});state.settings.presentation.homeLayout='grid';refreshGallery()});
const books=()=>page.locator('#gallery-results [data-sort-book]');
check(await books().count()>=3,'album fixtures available');
await books().first().click();await page.waitForFunction(()=>document.querySelector('#reader').open);check(true,'one click opens album');await page.evaluate(()=>closeReader());
await books().nth(0).click({modifiers:['Control']});await books().nth(1).click({modifiers:['Control']});
check(await page.evaluate(()=>ui.selected.size===2),'Ctrl click toggles albums');
check(await page.locator('#gallery-results input[type=checkbox],.shelf-bulk,[data-act="toggle-bulk"]').count()===0,'no album checkboxes, selection bar, or toggle');
await books().first().click({button:'right'});check((await page.locator('.ctx-menu').innerText()).includes('批量删除'),'album right click uses bulk menu');await page.keyboard.press('Escape');
await books().first().click();await page.waitForFunction(()=>document.querySelector('#reader').open);check(await page.evaluate(()=>!ui.selected.size),'one click opens album even after multi-selection');await page.evaluate(()=>closeReader());
const x=await books().nth(0).boundingBox(),y=await books().nth(1).boundingBox();
await drag({x:x.x+10,y:x.y+10},{x:y.x+y.width-10,y:y.y+Math.min(y.height-10,220)});
check(await page.evaluate(()=>ui.selected.size>=2),'drag on album selects instead of reordering');check(await page.locator('#reader[open]').count()===0,'marquee release never opens reader');
await page.screenshot({path:path.join(artifacts,'albums-selection.png')});
await page.locator('#gallery-results').click({button:'right',position:{x:2,y:2}});
check((await page.locator('.ctx-menu').innerText()).includes('批量删除'),'right click on blank shelf preserves bulk context');await page.keyboard.press('Escape');
await page.locator('#gallery-results').click({position:{x:2,y:2}});check(await page.evaluate(()=>!ui.selected.size),'click blank shelf clears selection');
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{navigate(1);workshop.view='stories';render()});
await page.locator('.wm-card').nth(1).click();check(await page.evaluate(()=>workshop.mobileEditor&&workshop.frame===1),'mobile frame still opens with one tap');
check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has no horizontal overflow');
check(errors.length===0,'no browser errors: '+errors.join(';'));
console.log(`${checks} selection checks passed`);
}finally{await browser.close()}
