import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'slots-v3-ui-')),port=18834,url=`http://127.0.0.1:${port}`;
fs.cpSync('data',dir,{recursive:true});
const log=fs.openSync(path.join(dir,'server.log'),'w');
const server=spawn('python',['server.py'],{env:{...process.env,MIO_DATA_DIR:dir,MIO_PORT:String(port),MIO_HOST:'127.0.0.1',MIO_NO_BROWSER:'1'},stdio:['ignore',log,log]});
let browser;
const fixture=JSON.parse(fs.readFileSync('tests/fixtures/workflow_slots_contract.json','utf8')).cases.find(x=>x.name==='paired');
const check=(ok,msg)=>{assert.ok(ok,msg);console.log('PASS',msg);};
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/content')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>globalThis.Mio&&state.templates.length);
 await page.evaluate(async f=>{
   await connectPythonBackend();
   const c=state.settings.comfy; c.workflow=f.workflow;c.slots={};c.objectInfo={};c.bindings=[];c.workflowTitle='V3 paired test';
   storeActiveWorkflow();await ensureWorkflowSlotPlan(c,{force:true});
   const providers=ensureImageProviders();providers.active=providers.profiles.find(p=>p.provider==='comfyui').id;
   state.settings.productionAssembly={channelId:providers.active,workflowId:c.activeWorkflowId};openAssemblyDesigner();
 },fixture);
 await page.locator('.designer-advanced > summary').click();
 await page.waitForSelector('[data-designer-paired-model]');
 check(await page.locator('[data-designer-paired-model]').count()===2,'paired model selectors');
 check(await page.locator('.designer-lora-chip.is-pinned').count()===2,'blueprint LoRAs are locked, not editable defaults');
 check(await page.evaluate(()=>assemblyDesign.overrides.loras.length===0),'no remembered LoRA replacements');
 const key=await page.locator('[data-designer-paired-model]').first().getAttribute('data-designer-paired-model');
 await page.locator('[data-designer-paired-model]').first().fill('new-high.safetensors');await page.locator('[data-designer-paired-model]').first().press('Tab');
 check(await page.evaluate(key=>designerOverrides().model[key]==='new-high.safetensors',key),'paired key override preserved');
 await page.locator('[data-act="designer-lora-unpin"]').first().click();
 check(await page.locator('.designer-lora-chip.is-pinned').count()===1,'unpin removes only the selected blueprint pin');
 await page.evaluate(()=>{designerAddLora('user.safetensors');refreshDesignerOverrides('lora');});
 await page.locator('[data-designer-lora-strength]').fill('-2');
 check(await page.evaluate(()=>designerOverrides().loras[0].strength===-2),'negative strengths are not clamped');
 check((await page.locator('.designer-slots').innerText()).includes('LoRA 追加到'),'plan summary displayed');
 const payload=await page.evaluate(async()=>{const w=designerWorkflow();return productionRequest('apply-slots',{workflow:w.workflow,slots:w.slots,overrides:designerOverrides()});});
 check(payload.workflow['1'].inputs.ckpt_name==='new-high.safetensors','backend dry-run receives keyed models');
 check(payload.notices.some(n=>n.includes('写入 LoRA')),'actual write notices returned');
 await page.evaluate(()=>{closeModal();ui.workspace=3;mapperUI.selected='__slot_lora__';render();});
 await page.waitForSelector('[data-slot-plan-kind="lora"]');
 check((await page.locator('[data-slot-plan-kind="lora"]').count())===2,'read-only plan groups rendered with checkboxes');
 await page.locator('[data-slot-plan-kind="lora"]').first().uncheck();
 check(await page.evaluate(()=>state.settings.comfy.slots.plan.lora.groups[0].enabled===false),'group selection persisted');
 await page.locator('[data-act="wf-slots-manual"]').click();
 await page.locator('#slot-manual-field').selectOption({label:'#2 · lora_name'});
 await page.locator('[data-act="wf-slots-manual-save"]').click();
 await page.waitForFunction(()=>!document.querySelector('#modal').open);
 check(await page.evaluate(()=>state.settings.comfy.slots.plan.manual.some(x=>x.nodeId==='2'&&x.path==='lora_name')),'manual field registered by Python analyzer');
 await page.locator('[data-act="wf-slots-analyze"]').click();
 await page.waitForFunction(()=>state.settings.comfy.slots.plan.version===3);
 await page.setViewportSize({width:390,height:844});
 check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile plan has no horizontal overflow');
 const saved=await page.evaluate(async()=>({ok:await savePythonWorkspace(),error:backendRuntime.error}));
 check(saved.ok,'v3 plan persists through native credential guards: '+(saved.error||''));
 await page.reload();await page.waitForFunction(()=>globalThis.Mio&&state.templates.length&&backendRuntime.connected);
 check(await page.evaluate(()=>state.settings.comfy.slots?.plan?.version===3&&state.settings.comfy.slots.plan.model.targets.every(t=>!!t.key)),'plan identifiers survive save and reload');
 check(errors.length===0,'no browser runtime errors: '+errors.join(';'));
 console.log('Workflow slots v3 browser acceptance PASS');
}finally{await browser?.close();server.kill();fs.rmSync(dir,{recursive:true,force:true});}
