import type { Episode, Job, Panel, Series, Take } from '../api/types';

const T = '2026-09-01T10:00:00';

export const series: Series = {
  id: 'ser_1',
  title: '雨夜便利店',
  subtitle: '第一季',
  status: 'active',
  bible: {
    characters: [
      {
        id: 'char_a',
        name: '林夏',
        gender: 'female',
        age: 26,
        appearance: ['short black hair', 'round eyewear'],
        description: '插画师',
        tag_description: [],
        signature: ['round eyewear'],
        outfits: { 通勤: ['beige trench coat'] },
        references: [],
        loras: [],
        trigger: '',
      },
    ],
    locations: [
      {
        id: 'loc_1',
        name: '便利店',
        description: '',
        tags: ['convenience store'],
        time: 'night',
        references: [],
      },
    ],
    props: [],
    styles: [
      {
        id: 'style_1',
        name: '水彩',
        description: '',
        tag_description: ['watercolor'],
        negative: [],
        references: [],
        loras: [],
      },
    ],
  },
  variants: [{ id: 'var_1', name: '冬装', characters: {}, style_id: null, profile_id: null }],
  variables: {},
  default_profile_id: null,
  created_at: T,
  updated_at: T,
  deleted_at: null,
};

function panel(i: number, extra: Partial<Panel> = {}): Panel {
  return {
    id: `p${i}`,
    order: i,
    shot: 'medium',
    angle: 'eye',
    characters: [
      {
        character_id: 'char_a',
        outfit: '',
        expression: 'smile',
        action: '',
        tags: [],
        position: 'unspecified',
      },
    ],
    location_id: 'loc_1',
    props: [],
    time: 'night',
    lighting: '',
    description: `第 ${i + 1} 格`,
    tags: [],
    dialogues: [{ speaker_id: 'char_a', text: '欢迎光临', kind: 'speech' }],
    width_mode: 'full',
    aspect_ratio: '3:4',
    gap_after: 40,
    transition_background: '',
    reference_mode: 'auto',
    references: [],
    locked: false,
    overrides: {
      raw_prompt: null,
      raw_negative: null,
      append_prompt: '',
      negative_prompt: '',
      seed: null,
      width: null,
      height: null,
      values: {},
      node_overrides: {},
      profile_id: null,
    },
    ...extra,
  };
}

export function take(id: string, panelId: string, status: Take['status']): Take {
  return {
    id,
    panel_id: panelId,
    asset_id: `asset_${id}`,
    status,
    score: null,
    stage: 'draft',
    variant_id: null,
    job_id: null,
    parent_take_id: null,
    width: 832,
    height: 1109,
    seed: 1,
    parameter_snapshot: {},
    qa: null,
    faces: [],
    edits: [],
    created_at: T,
  };
}

export const episode: Episode = {
  id: 'ep_1',
  series_id: 'ser_1',
  title: '第一话',
  order: 0,
  synopsis: '深夜的便利店',
  panels: [panel(0), panel(1, { locked: true, dialogues: [] })],
  takes: [take('t1', 'p0', 'adopted'), take('t2', 'p0', 'candidate'), take('t3', 'p1', 'rejected')],
  strip: {
    width: 800,
    background: '#ffffff',
    margin: 24,
    panel_boxes: { p0: [0, 170, 800, 1237] },
    crops: {},
    lettering: [
      {
        id: 'letter_1',
        panel_id: 'p0',
        kind: 'speech',
        text: '欢迎光临',
        speaker_id: 'char_a',
        box: [500, 220, 740, 320],
        tail_to: null,
        vertical: false,
        font_size: null,
        locked: false,
      },
    ],
    height: 1500,
    manual: false,
  },
  created_at: T,
  updated_at: T,
  deleted_at: null,
  revision: 3,
};

export const job: Job = {
  id: 'job_1',
  kind: 'render',
  title: '第一话 · 草稿',
  state: 'running',
  paused: false,
  blocked: false,
  canceled: false,
  owner: 'ep_1',
  error: null,
  created: 1_790_000_000,
  updated: 1_790_000_100,
  items: [
    {
      idx: 0,
      state: 'running',
      label: '第 1 格 · 候选 1',
      attempts: 1,
      instance_id: 'comfy_1',
      error: null,
      result: null,
      started: 1_790_000_050,
      finished: null,
      input: { meta: { panel_id: 'p0', variant_id: null } },
    },
    {
      idx: 1,
      state: 'uncertain',
      label: '第 2 格 · 候选 1',
      attempts: 1,
      instance_id: 'comfy_1',
      error: { kind: 'result_unconfirmed', message: '服务重启，结果未确认' },
      result: null,
      started: 1_790_000_050,
      finished: null,
      input: { meta: { panel_id: 'p1', variant_id: null } },
    },
  ],
};
