import fs from 'node:fs';import vm from 'node:vm';import * as acorn from 'acorn';
const names=['renderSettingCards','renderSettingsGroups','renderUnifiedSettings','presetLibraryHTML'];let funcs='';for(const file of ['js/ui-settings.js','js/creative-context.js']){let s=fs.readFileSync(file,'utf8');for(const n of acorn.parse(s,{ecmaVersion:'latest'}).body)if(n.type==='FunctionDeclaration'&&names.includes(n.id.name))funcs+=s.slice(n.start,n.end)+'\n';}
const css=fs.readFileSync('styles.css','utf8');
const setup=`const labels={character_display_name:'角色展示名 / 旁白',character:'角色名 / 提示词',outfit:'服装',style:'画风',scene:'场景与环境',mood:'情绪'};
const entries=Object.entries({character_display_name:'七海',character:'nanami',outfit:'white shirt, navy skirt, small canvas bag',style:'cinematic anime illustration, delicate cel shading, soft film texture',scene:'quiet seaside town, late summer, golden hour',mood:'gentle, nostalgic, hopeful'}).map(([key,value],i)=>({id:'e'+i,key,value,type:'text'}));
let book={id:'demo-book',title:'海风与未寄出的信',variables:structuredClone(entries)},presets=[{id:'p1',title:'海风与未寄出的信',entries:structuredClone(entries)},{id:'p2',title:'雨天的旧书店',entries:entries.map(e=>({...e,value:e.key==='scene'?'old bookshop, rainy afternoon':e.key==='style'?'watercolor illustration, soft muted colors':e.value}))},{id:'p3',title:'夏日出游 · 清透动画',entries:entries.filter(e=>['style','mood','outfit'].includes(e.key))}],selected='p1',drafts={};
const state={drafts:{presetEdits:{}}};const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');const icon=(name)=>'<span aria-hidden="true">'+({box:'◇',plus:'＋',arrow:'↗',shield:'♧',copy:'▧',download:'↓',trash:'×',check:'✓',disk:'✓',upload:'↑'}[name]||'◇')+'</span>';
const btn=(label,ic,act,attrs='',cl='')=>'<button type="button" class="btn '+cl+'" data-act="'+act+'" '+attrs+'>'+ (ic?icon(ic):'')+esc(label)+'</button>';
const ibtn=(ic,act,title,attrs)=>'<button type="button" class="icon-btn" title="'+esc(title)+'" aria-label="'+esc(title)+'" data-act="'+act+'" '+attrs+'>'+icon(ic)+'</button>';
const opt=(id,title,sel)=>'<option value="'+esc(id)+'" '+(id===sel?'selected':'')+'>'+esc(title)+'</option>';
const mergedSettingEntries=p=>p.variables||p.entries;const currentBookSettings=()=>book;const creationTask=()=>null;const currentSettingsLabel=()=>book.title;const projectVariableSets=()=>presets;const settingPresetSelection=()=>selected;const settingPresetDraft=id=>drafts[id]??=( {...structuredClone(presets.find(x=>x.id===id)),_presetEditorId:id});const settingLabel=e=>labels[e.key]||e.key;
const characterSettingHelp=key=>key==='character_display_name'?'用于旁白和画册展示，不加入出图提示词。':key==='character'?'用于出图提示词，填写模型识别的角色名或触发词。':'';
const input=(n,v,type,attrs)=>'<input type="'+type+'" value="'+esc(v)+'" '+attrs+'>';`;
const behavior=`let library=false;const main=document.querySelector('#demo-main'),dialog=document.querySelector('#demo-dialog');function render(){main.innerHTML=renderUnifiedSettings()}function open(id){if(id)selected=id;library=true;dialog.innerHTML='<div class="demo-modal-head"><div><span class="context-kicker">PRESET LIBRARY</span><h2>预设库</h2></div><button class="btn ghost" data-act="close-modal" aria-label="关闭">✕</button></div>'+presetLibraryHTML();if(!dialog.open)dialog.showModal()}function notify(s){const n=document.querySelector('#demo-toast');n.textContent=s;n.hidden=false;setTimeout(()=>n.hidden=true,2800)}
document.addEventListener('input',e=>{if(e.target.id==='preset-search'){for(const el of dialog.querySelectorAll('.preset-library-item'))el.hidden=!el.textContent.toLowerCase().includes(e.target.value.toLowerCase());return}if(e.target.dataset.artSetting){const owner=library?settingPresetDraft(selected):book;mergedSettingEntries(owner).find(x=>x.key===e.target.dataset.artSetting).value=e.target.value;document.querySelectorAll('[data-settings-save-status]').forEach(x=>x.textContent='演示中已保存');}});
document.addEventListener('change',e=>{if(e.target.id==='art-setting-preset'){selected=e.target.value;open()}});dialog.addEventListener('close',()=>{library=false});
document.addEventListener('click',e=>{const el=e.target.closest('[data-act]');if(!el)return;const a=el.dataset.act;if(a==='preset-library-open')open();else if(a==='preset-library-preview'||a==='preset-library-select')open(el.dataset.id);else if(a==='close-modal'){dialog.close();library=false;render()}else if(a==='art-apply-preset'){if(!confirm('将预设中的同名属性复制到本册？未同名的本册属性会保留。'))return;const map=new Map(book.variables.map(v=>[v.key,v]));for(const v of settingPresetDraft(selected).entries)map.set(v.key,structuredClone(v));book.variables=[...map.values()];dialog.close();library=false;render();notify('已复制到本册，公共预设不受影响')}else if(a==='ws-update-preset'){presets[presets.findIndex(v=>v.id===selected)].entries=structuredClone(settingPresetDraft(selected).entries);notify('演示预设已更新');open()}else if(a==='art-setting-add'){const key=prompt('输入属性标识，例如 lighting');if(!key)return;const p=library?settingPresetDraft(selected):book;const list=mergedSettingEntries(p);if(list.some(v=>v.key===key))return notify('该属性已存在');list.push({id:'e'+Date.now(),key,type:'text',value:''});library?open():render()}else if(a==='art-setting-remove'){if(!confirm('移除此属性？'))return;const p=library?settingPresetDraft(selected):book;const list=mergedSettingEntries(p);list.splice(list.findIndex(v=>v.key===el.dataset.key),1);library?open():render()}else if(a==='art-save-preset'||a==='ws-new-preset'){const title=prompt('预设名称');if(!title)return;const id='p'+Date.now();presets.push({id,title,entries:a==='ws-new-preset'?[]:structuredClone(mergedSettingEntries(library?settingPresetDraft(selected):book))});open(id)}else if(a==='ws-delete-preset'){if(!confirm('删除此演示预设？本册属性不受影响。'))return;presets=presets.filter(x=>x.id!==selected);selected=presets[0]?.id||'';open()}else if(a==='native-export-settings'){const blob=new Blob([JSON.stringify(library?settingPresetDraft(selected):book,null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='demo-settings.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}else notify('此入口需要完整项目运行；当前为 UI 交互演示。')});render();`;
fs.writeFileSync('/home/user/ui-preview/index.html',`<!doctype html><html lang="zh-CN" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mio · 设定工作台 UI 演示</title><style>${css}\n:root{--bg:#111514;--panel:#171c1a;--panel2:#1e2521;--text:#e4eae2;--soft:#b4beb4;--muted:#87978d;--line:#2b3530;--accent:#b4dfb6;--accent2:#b4dfb6}body{display:block;background:var(--bg);color:var(--text);overflow:auto;height:auto}.demo-top{display:flex;justify-content:space-between;padding:20px 4vw;border-bottom:1px solid var(--line);font-size:12px}.demo-top strong{font-family:Georgia;font-size:22px;letter-spacing:2px}.demo-wrap{max-width:1440px;margin:38px auto;padding:0 36px 40px}.demo-pagehead{display:flex;align-items:center;justify-content:space-between;margin-bottom:26px}.demo-pagehead h1{font-size:30px;margin:0 0 9px}.demo-pagehead p{color:var(--muted);font-size:12px}.demo-tabs{display:flex;gap:30px;border-bottom:1px solid var(--line);margin-bottom:30px;font-size:13px;color:var(--muted)}.demo-tabs span{padding:15px 0}.demo-tabs .active{color:var(--accent);border-bottom:2px solid var(--accent)}#demo-dialog{width:min(1120px,calc(100vw - 30px));max-width:1120px;max-height:88vh;overflow:auto;border:1px solid var(--line);border-radius:16px;background:var(--bg);color:var(--text);padding:28px}#demo-dialog::backdrop{background:#0009;backdrop-filter:blur(5px)}.demo-modal-head{display:flex;justify-content:space-between;margin-bottom:25px}.demo-modal-head h2{font-size:25px;margin:8px 0}.demo-note{font-size:11px;color:var(--muted)}#demo-toast{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:var(--accent);color:#15251b;padding:14px 22px;border-radius:10px;z-index:9999}.preset-library-footer{bottom:-28px;background:var(--bg);padding-bottom:15px!important}.icon-btn{font-size:18px}.rail-safety>span:first-child{font-size:18px}.demo-tools{display:flex;gap:15px;align-items:center}@media(max-width:760px){.demo-wrap{padding:0 16px}.demo-pagehead{align-items:start;gap:15px}.demo-tools{display:none}.demo-top{gap:20px}.demo-top span{max-width:240px}#demo-dialog{padding:18px}.demo-tabs{gap:20px}}
</style></head><body><header class="demo-top"><strong>Mio<span style="color:var(--accent)">.</span></strong><span class="demo-note">UI 交互演示 · 示例数据仅保留在当前页面，不连接生成服务</span></header><div class="demo-wrap"><header class="demo-pagehead"><div><h1>创作画册</h1><p>画面由你定义，故事自由发生。</p></div><div class="demo-tools"><span class="demo-note">当前画册</span><select aria-label="当前画册"><option>海风与未寄出的信 · 草稿</option></select></div></header><nav class="demo-tabs"><span>分镜故事</span><span class="active">角色与画面设定</span><span>生成队列</span></nav><main id="demo-main"></main></div><dialog id="demo-dialog"></dialog><div id="demo-toast" hidden role="status"></div><script>${setup}\n${funcs}\n${behavior}</script></body></html>`);
