"""Mio API v2.0 client — generated by clients/python/generate.py, do not edit.

Usage::

    from mio_client import MioClient
    mio = MioClient("http://127.0.0.1:8788", token="mio_tok_…")
    series = mio.create_series({"title": "雨夜"})
    ep = mio.generate_episode(series["id"], {"sentence": "雨夜的便利店"})
    job = mio.render_episode(ep["id"], {"candidates": 1})
    mio.wait_job(job["id"])
"""

from __future__ import annotations

import json
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

__all__ = ["MioClient", "MioError"]

TERMINAL = {"completed", "failed", "canceled"}


class MioError(Exception):
    """HTTP error from the Mio API; ``kind`` is not_found / invalid / unauthorized / …"""

    def __init__(self, status: int, kind: str, detail: str):
        super().__init__(f"{status} {kind}: {detail}")
        self.status, self.kind, self.detail = status, kind, detail


def _q(value: Any) -> str:
    return urllib.parse.quote(str(value), safe="")


class _Base:
    def __init__(self, base_url: str = "http://127.0.0.1:8788", token: str = "", timeout=120.0):
        self.base = base_url.rstrip("/") + "/api/v2"
        self.token = token
        self.timeout = timeout

    def _request(self, method: str, path: str, *, params=None, json=None, content=None) -> Any:
        url = self.base + path
        query = {k: v for k, v in (params or {}).items() if v is not None}
        if query:
            url += "?" + urllib.parse.urlencode(
                {k: str(v).lower() if isinstance(v, bool) else v for k, v in query.items()}
            )
        headers = {"Accept": "application/json", "User-Agent": "mio-client"}
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        data = None
        if json is not None:
            data = _json.dumps(json, ensure_ascii=False).encode("utf-8")
            headers["Content-Type"] = "application/json"
        elif content is not None:
            data = content
            headers["Content-Type"] = "application/octet-stream"
        req = urllib.request.Request(url, data=data, method=method, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                raw, ctype = resp.read(), resp.headers.get("Content-Type", "")
        except urllib.error.HTTPError as exc:
            raw = exc.read()
            try:
                err = _json.loads(raw)
                raise MioError(exc.code, err.get("kind", "error"), str(err.get("detail"))) from None
            except ValueError:
                raise MioError(exc.code, "error", raw[:300].decode("utf-8", "replace")) from None
        if not raw:
            return None
        return _json.loads(raw) if "json" in ctype else raw

    # ---------------------------------------------------------------- helpers
    def wait_job(self, job_id: str, timeout: float = 1800, poll: float = 2.0) -> dict:
        """Poll until the job reaches completed / failed / canceled; returns the job."""
        deadline = time.monotonic() + timeout
        while True:
            job = self._request("GET", f"/jobs/{_q(job_id)}")
            if job["state"] in TERMINAL:
                return job
            if time.monotonic() > deadline:
                raise TimeoutError(f"job {job_id} still {job['state']} after {timeout:.0f}s")
            time.sleep(poll)


_json = json


class MioClient(_Base):
    """One method per ``/api/v2`` operation.  Binary endpoints return ``bytes``."""

    def meta(self) -> Any:
        """GET /meta — Meta.

        Unauthenticated: API and server version (connectivity check).
        """
        return self._request("GET", "/meta")

    def whoami(self) -> Any:
        """GET /whoami — Whoami."""
        return self._request("GET", "/whoami")

    def list_series(self, *, deleted: bool | None = None) -> Any:
        """GET /series — List Series."""
        return self._request("GET", "/series", params={"deleted": deleted})

    def create_series(self, body: dict | list | None = None) -> Any:
        """POST /series — Create Series."""
        return self._request("POST", "/series", json=body)

    def get_series(self, series_id: str) -> Any:
        """GET /series/{series_id} — Get Series."""
        return self._request("GET", f"/series/{_q(series_id)}")

    def patch_series(self, series_id: str, body: dict | list | None = None) -> Any:
        """PATCH /series/{series_id} — Patch Series."""
        return self._request("PATCH", f"/series/{_q(series_id)}", json=body)

    def trash_series(self, series_id: str) -> Any:
        """DELETE /series/{series_id} — Trash Series."""
        return self._request("DELETE", f"/series/{_q(series_id)}")

    def restore_series(self, series_id: str) -> Any:
        """POST /series/{series_id}/restore — Restore Series."""
        return self._request("POST", f"/series/{_q(series_id)}/restore")

    def list_episodes(
        self,
        series_id: str,
        *,
        offset: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """GET /series/{series_id}/episodes — List Episodes."""
        return self._request(
            "GET",
            f"/series/{_q(series_id)}/episodes",
            params={"offset": offset, "limit": limit},
        )

    def create_episode(self, series_id: str, body: dict | list | None = None) -> Any:
        """POST /series/{series_id}/episodes — Create Episode."""
        return self._request("POST", f"/series/{_q(series_id)}/episodes", json=body)

    def generate_episode(self, series_id: str, body: dict | list | None = None) -> Any:
        """POST /series/{series_id}/episodes/generate — Generate Episode.

        One sentence → script via the LLM.  New characters / scenes are added to the bible.
        """
        return self._request("POST", f"/series/{_q(series_id)}/episodes/generate", json=body)

    def get_episode(self, episode_id: str) -> Any:
        """GET /episodes/{episode_id} — Get Episode."""
        return self._request("GET", f"/episodes/{_q(episode_id)}")

    def patch_episode(self, episode_id: str, body: dict | list | None = None) -> Any:
        """PATCH /episodes/{episode_id} — Patch Episode."""
        return self._request("PATCH", f"/episodes/{_q(episode_id)}", json=body)

    def trash_episode(self, episode_id: str) -> Any:
        """DELETE /episodes/{episode_id} — Trash Episode."""
        return self._request("DELETE", f"/episodes/{_q(episode_id)}")

    def restore_episode(self, episode_id: str) -> Any:
        """POST /episodes/{episode_id}/restore — Restore Episode."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/restore")

    def add_panel(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/panels — Add Panel."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/panels", json=body)

    def patch_panel(self, episode_id: str, panel_id: str, body: dict | list | None = None) -> Any:
        """PATCH /episodes/{episode_id}/panels/{panel_id} — Patch Panel."""
        return self._request(
            "PATCH",
            f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}",
            json=body,
        )

    def delete_panel(self, episode_id: str, panel_id: str) -> Any:
        """DELETE /episodes/{episode_id}/panels/{panel_id} — Delete Panel.

        Removes the panel; its takes stay in the episode (orphaned takes are hidden, not lost).
        """
        return self._request("DELETE", f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}")

    def patch_panels(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/panels/batch — Patch Panels.

        Batch edit: one revision, every listed panel gets the same changes.
        """
        return self._request("POST", f"/episodes/{_q(episode_id)}/panels/batch", json=body)

    def delete_panels(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/panels/batch-delete — Delete Panels."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/panels/batch-delete", json=body)

    def import_panels(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/panels/import — Import Panels."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/panels/import", json=body)

    def panel_history(self, episode_id: str, panel_id: str) -> Any:
        """GET /episodes/{episode_id}/panels/{panel_id}/history — Panel History.

        Earlier saved versions of one panel (newest first, unchanged saves collapsed).
        """
        return self._request("GET", f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}/history")

    def restore_panel(self, episode_id: str, panel_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/panels/{panel_id}/restore — Restore Panel.

        Put the panel back to how it was at ``revision`` (position and id stay).
        """
        return self._request(
            "POST",
            f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}/restore",
            json=body,
        )

    def reorder_panels(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/panels/reorder — Reorder Panels."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/panels/reorder", json=body)

    def duplicate_panel(self, episode_id: str, panel_id: str) -> Any:
        """POST /episodes/{episode_id}/panels/{panel_id}/duplicate — Duplicate Panel."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}/duplicate")

    def panel_prompt(self, episode_id: str, panel_id: str, *, variant_id: Any | None = None) -> Any:
        """GET /episodes/{episode_id}/panels/{panel_id}/prompt — Panel Prompt.

        Compiled prompt in both dialects plus the automatically chosen reference images.
        """
        return self._request(
            "GET",
            f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}/prompt",
            params={"variant_id": variant_id},
        )

    def adopt_take(self, episode_id: str, take_id: str) -> Any:
        """POST /episodes/{episode_id}/takes/{take_id}/adopt — Adopt Take."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/takes/{_q(take_id)}/adopt")

    def reject_take(self, episode_id: str, take_id: str) -> Any:
        """POST /episodes/{episode_id}/takes/{take_id}/reject — Reject Take."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/takes/{_q(take_id)}/reject")

    def restore_take(self, episode_id: str, take_id: str) -> Any:
        """POST /episodes/{episode_id}/takes/{take_id}/restore — Restore Take."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/takes/{_q(take_id)}/restore")

    def render_episode(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/render — Render."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/render", json=body)

    def finalize_episode(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/finalize — Finalize."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/finalize", json=body)

    def edit_take(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/edit — Edit."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/edit", json=body)

    def qa_episode(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/qa — Qa."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/qa", json=body)

    def layout_strip(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/strip/layout — Layout Strip."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/strip/layout", json=body)

    def save_strip(self, episode_id: str, body: dict | list | None = None) -> Any:
        """PUT /episodes/{episode_id}/strip — Save Strip.

        Hand edits from the canvas (moved / resized lettering, crops, boxes).
        """
        return self._request("PUT", f"/episodes/{_q(episode_id)}/strip", json=body)

    def strip_png(
        self,
        episode_id: str,
        *,
        variant_id: Any | None = None,
        width: int | None = None,
    ) -> Any:
        """GET /episodes/{episode_id}/strip.png — Strip Png."""
        return self._request(
            "GET",
            f"/episodes/{_q(episode_id)}/strip.png",
            params={"variant_id": variant_id, "width": width},
        )

    def export_episode(
        self,
        episode_id: str,
        *,
        fmt: str | None = None,
        preset: str | None = None,
        variant_id: Any | None = None,
    ) -> Any:
        """GET /episodes/{episode_id}/export — Export."""
        return self._request(
            "GET",
            f"/episodes/{_q(episode_id)}/export",
            params={"fmt": fmt, "preset": preset, "variant_id": variant_id},
        )

    def export_presets(self) -> Any:
        """GET /export/presets — Export Presets."""
        return self._request("GET", "/export/presets")

    def assistant_propose(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/assistant/propose — Propose."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/assistant/propose", json=body)

    def assistant_apply(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/assistant/apply — Apply."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/assistant/apply", json=body)

    def take_image(self, episode_id: str, take_id: str) -> Any:
        """GET /episodes/{episode_id}/takes/{take_id}/image — Take Image."""
        return self._request("GET", f"/episodes/{_q(episode_id)}/takes/{_q(take_id)}/image")

    def sfx_presets(self) -> Any:
        """GET /lettering/sfx-presets — Sfx Presets.

        Built-in presets plus those contributed by extensions (registry point ``sfx_preset``).
        """
        return self._request("GET", "/lettering/sfx-presets")

    def pacing_suggest(self, episode_id: str) -> Any:
        """POST /episodes/{episode_id}/pacing/suggest — Pacing Suggest."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/pacing/suggest")

    def pacing_apply(self, episode_id: str, body: dict | list | None = None) -> Any:
        """POST /episodes/{episode_id}/pacing/apply — Pacing Apply."""
        return self._request("POST", f"/episodes/{_q(episode_id)}/pacing/apply", json=body)

    def strip_report(self, episode_id: str, *, variant_id: Any | None = None) -> Any:
        """GET /episodes/{episode_id}/strip/report — Strip Report.

        Readability check of the saved strip (missing lines, faces covered, overlaps …).
        """
        return self._request(
            "GET",
            f"/episodes/{_q(episode_id)}/strip/report",
            params={"variant_id": variant_id},
        )

    def composition_preview(
        self,
        episode_id: str,
        panel_id: str,
        *,
        dialect: str | None = None,
    ) -> Any:
        """POST /episodes/{episode_id}/panels/{panel_id}/composition — Composition Preview.

        Regions, regional prompts and the auto pose skeleton exactly as a render would use them.
        """
        return self._request(
            "POST",
            f"/episodes/{_q(episode_id)}/panels/{_q(panel_id)}/composition",
            params={"dialect": dialect},
        )

    def list_workflows(self) -> Any:
        """GET /workflows — List Workflows."""
        return self._request("GET", "/workflows")

    def import_workflow(self, body: dict | list | None = None) -> Any:
        """POST /workflows — Import Workflow."""
        return self._request("POST", "/workflows", json=body)

    def get_workflow(self, workflow_id: str) -> Any:
        """GET /workflows/{workflow_id} — Get Workflow."""
        return self._request("GET", f"/workflows/{_q(workflow_id)}")

    def patch_workflow(self, workflow_id: str, body: dict | list | None = None) -> Any:
        """PATCH /workflows/{workflow_id} — Patch Workflow."""
        return self._request("PATCH", f"/workflows/{_q(workflow_id)}", json=body)

    def delete_workflow(self, workflow_id: str) -> Any:
        """DELETE /workflows/{workflow_id} — Delete Workflow."""
        return self._request("DELETE", f"/workflows/{_q(workflow_id)}")

    def copy_workflow(self, workflow_id: str) -> Any:
        """POST /workflows/{workflow_id}/copy — Copy Workflow."""
        return self._request("POST", f"/workflows/{_q(workflow_id)}/copy")

    def compile_preview(self, workflow_id: str, body: dict | list | None = None) -> Any:
        """POST /workflows/{workflow_id}/compile — Compile Preview.

        Dry run: the exact graph Mio would queue for these values (编译结果可见).
        """
        return self._request("POST", f"/workflows/{_q(workflow_id)}/compile", json=body)

    def diagnose_workflow(self, workflow_id: str, *, instance_id: str | None = None) -> Any:
        """POST /workflows/{workflow_id}/diagnose — Diagnose Workflow."""
        return self._request(
            "POST",
            f"/workflows/{_q(workflow_id)}/diagnose",
            params={"instance_id": instance_id},
        )

    def list_profiles(self) -> Any:
        """GET /profiles — List Profiles."""
        return self._request("GET", "/profiles")

    def create_profile(self, body: dict | list | None = None) -> Any:
        """POST /profiles — Create Profile."""
        return self._request("POST", "/profiles", json=body)

    def get_profile(self, profile_id: str) -> Any:
        """GET /profiles/{profile_id} — Get Profile."""
        return self._request("GET", f"/profiles/{_q(profile_id)}")

    def put_profile(self, profile_id: str, body: dict | list | None = None) -> Any:
        """PUT /profiles/{profile_id} — Put Profile."""
        return self._request("PUT", f"/profiles/{_q(profile_id)}", json=body)

    def delete_profile(self, profile_id: str) -> Any:
        """DELETE /profiles/{profile_id} — Delete Profile."""
        return self._request("DELETE", f"/profiles/{_q(profile_id)}")

    def list_instances(self) -> Any:
        """GET /instances — List Instances."""
        return self._request("GET", "/instances")

    def create_instance(self, body: dict | list | None = None) -> Any:
        """POST /instances — Create Instance."""
        return self._request("POST", "/instances", json=body)

    def put_instance(self, instance_id: str, body: dict | list | None = None) -> Any:
        """PUT /instances/{instance_id} — Put Instance."""
        return self._request("PUT", f"/instances/{_q(instance_id)}", json=body)

    def delete_instance(self, instance_id: str) -> Any:
        """DELETE /instances/{instance_id} — Delete Instance."""
        return self._request("DELETE", f"/instances/{_q(instance_id)}")

    def instance_health(self, instance_id: str) -> Any:
        """GET /instances/{instance_id}/health — Instance Health."""
        return self._request("GET", f"/instances/{_q(instance_id)}/health")

    def upload_asset(self, body: bytes, *, filename: str | None = None) -> Any:
        """POST /assets — Upload Asset.

        Raw request body = file bytes (``Content-Type`` is ignored; the type is sniffed).
        """
        return self._request("POST", "/assets", params={"filename": filename}, content=body)

    def get_asset(self, asset_id: str, *, thumb: int | None = None) -> Any:
        """GET /assets/{asset_id} — Get Asset."""
        return self._request("GET", f"/assets/{_q(asset_id)}", params={"thumb": thumb})

    def list_jobs(
        self,
        *,
        owner: Any | None = None,
        active: bool | None = None,
        limit: int | None = None,
    ) -> Any:
        """GET /jobs — List Jobs."""
        return self._request(
            "GET",
            "/jobs",
            params={"owner": owner, "active": active, "limit": limit},
        )

    def get_job(self, job_id: str) -> Any:
        """GET /jobs/{job_id} — Get Job."""
        return self._request("GET", f"/jobs/{_q(job_id)}")

    def delete_job(self, job_id: str) -> Any:
        """DELETE /jobs/{job_id} — Delete Job."""
        return self._request("DELETE", f"/jobs/{_q(job_id)}")

    def job_events(self, job_id: str, *, after: int | None = None, limit: int | None = None) -> Any:
        """GET /jobs/{job_id}/events — Job Events."""
        return self._request(
            "GET",
            f"/jobs/{_q(job_id)}/events",
            params={"after": after, "limit": limit},
        )

    def pause_job(self, job_id: str) -> Any:
        """POST /jobs/{job_id}/pause — Pause."""
        return self._request("POST", f"/jobs/{_q(job_id)}/pause")

    def resume_job(self, job_id: str) -> Any:
        """POST /jobs/{job_id}/resume — Resume."""
        return self._request("POST", f"/jobs/{_q(job_id)}/resume")

    def cancel_job(self, job_id: str) -> Any:
        """POST /jobs/{job_id}/cancel — Cancel."""
        return self._request("POST", f"/jobs/{_q(job_id)}/cancel")

    def retry_job(self, job_id: str, body: dict | list | None = None) -> Any:
        """POST /jobs/{job_id}/retry — Retry.

        Per-panel (``indexes``) or suffix (``from_index``) rerun; never implicit.
        """
        return self._request("POST", f"/jobs/{_q(job_id)}/retry", json=body)

    def resolve_job_item(self, job_id: str, idx: int, body: dict | list | None = None) -> Any:
        """POST /jobs/{job_id}/items/{idx}/resolve — Resolve.

        Settle an ``uncertain`` item: reconcile from upstream records, mark failed, or resubmit.
        """
        return self._request("POST", f"/jobs/{_q(job_id)}/items/{_q(idx)}/resolve", json=body)

    def list_album_templates(self) -> Any:
        """GET /album-templates — List Templates."""
        return self._request("GET", "/album-templates")

    def import_album_template(self, body: dict | list | None = None) -> Any:
        """POST /album-templates — Import Template.

        Import a template file (the legacy ``formatVersion: 1`` format works unchanged).
        """
        return self._request("POST", "/album-templates", json=body)

    def get_album_template(self, template_id: str) -> Any:
        """GET /album-templates/{template_id} — Get Template."""
        return self._request("GET", f"/album-templates/{_q(template_id)}")

    def delete_album_template(self, template_id: str) -> Any:
        """DELETE /album-templates/{template_id} — Delete Template."""
        return self._request("DELETE", f"/album-templates/{_q(template_id)}")

    def export_album(self, body: dict | list | None = None) -> Any:
        """POST /export/album — Export Album.

        Self-contained offline HTML album; one book per episode.
        """
        return self._request("POST", "/export/album", json=body)

    def motion_plan(self, episode_id: str, *, variant_id: Any | None = None) -> Any:
        """GET /episodes/{episode_id}/motion-plan — Motion Plan.

        Resolved move and hold for every panel (``Panel.motion`` overrides, else automatic).
        """
        return self._request(
            "GET",
            f"/episodes/{_q(episode_id)}/motion-plan",
            params={"variant_id": variant_id},
        )

    def export_motion(self, body: dict | list | None = None) -> Any:
        """POST /export/motion — Export Motion.

        Self-contained offline motion-comic player (one HTML file, no network needed).
        """
        return self._request("POST", "/export/motion", json=body)

    def get_settings(self) -> Any:
        """GET /settings — Get Settings."""
        return self._request("GET", "/settings")

    def patch_settings(self, body: dict | list | None = None) -> Any:
        """PATCH /settings — Patch Settings.

        Deep-merges one level; sending the masked api key back keeps the stored one.
        """
        return self._request("PATCH", "/settings", json=body)

    def get_registry(self) -> Any:
        """GET /registry — Registry."""
        return self._request("GET", "/registry")

    def list_trash(self) -> Any:
        """GET /trash — List Trash."""
        return self._request("GET", "/trash")

    def purge_trash(self, kind: str, item_id: str) -> Any:
        """DELETE /trash/{kind}/{item_id} — Purge.

        Permanent delete (only for items already in the recycle bin).
        """
        return self._request("DELETE", f"/trash/{_q(kind)}/{_q(item_id)}")

    def expire_trash(self) -> Any:
        """POST /trash/expire — Expire."""
        return self._request("POST", "/trash/expire")

    def export_bundle(self, series_id: str) -> Any:
        """GET /series/{series_id}/bundle — Export Bundle."""
        return self._request("GET", f"/series/{_q(series_id)}/bundle")

    def import_bundle(self, body: bytes) -> Any:
        """POST /bundles — Import Bundle.

        Raw request body = the ``.mio.zip`` file.
        """
        return self._request("POST", "/bundles", content=body)

    def legacy_scan(self, *, root: Any | None = None) -> Any:
        """GET /legacy/scan — Legacy Scan."""
        return self._request("GET", "/legacy/scan", params={"root": root})

    def legacy_import(self, body: dict | list | None = None) -> Any:
        """POST /legacy/import — Legacy Import.

        One-time import of old storyboards / presets / workflows; idempotent unless overwrite.
        """
        return self._request("POST", "/legacy/import", json=body)

    def update_status(self) -> Any:
        """GET /update — Update Status."""
        return self._request("GET", "/update")

    def check_update(self) -> Any:
        """POST /update/check — Check Update."""
        return self._request("POST", "/update/check")

    def download_update(self) -> Any:
        """POST /update/download — Download Update.

        Download and verify, then stage; the launcher installs it on the next start.
        """
        return self._request("POST", "/update/download")

    def list_webhooks(self) -> Any:
        """GET /webhooks — List Webhooks."""
        return self._request("GET", "/webhooks")

    def create_webhook(self, body: dict | list | None = None) -> Any:
        """POST /webhooks — Create Webhook.

        The signing ``secret`` is shown in full only here and after ``rotate_secret``.
        """
        return self._request("POST", "/webhooks", json=body)

    def update_webhook(self, hook_id: str, body: dict | list | None = None) -> Any:
        """PATCH /webhooks/{hook_id} — Update Webhook."""
        return self._request("PATCH", f"/webhooks/{_q(hook_id)}", json=body)

    def delete_webhook(self, hook_id: str) -> Any:
        """DELETE /webhooks/{hook_id} — Delete Webhook."""
        return self._request("DELETE", f"/webhooks/{_q(hook_id)}")

    def test_webhook(self, hook_id: str) -> Any:
        """POST /webhooks/{hook_id}/test — Test Webhook.

        Send a ``ping`` right away (synchronously, no retries) and return the delivery record.
        """
        return self._request("POST", f"/webhooks/{_q(hook_id)}/test")

    def webhook_deliveries(self, hook_id: str) -> Any:
        """GET /webhooks/{hook_id}/deliveries — Webhook Deliveries."""
        return self._request("GET", f"/webhooks/{_q(hook_id)}/deliveries")
